# -*- coding: utf-8 -*-
"""Bangla for the rest of Kent's rubric vocabulary.

kent_bn.SEG holds the core vocabulary — the terms that recur across the whole
book and were worth hand-checking one at a time. This file is the long tail:
the ~15,000 segments that appear once or twice each, together only about a
tenth of all segment occurrences but the difference between a rubric that
reads as Bangla and one that trails off into English halfway through.

Same rule as SEG: a term whose Bangla is not certain stays in English, because
a wrong Bangla rubric name sends the practitioner to the wrong rubric. Keys are
matched case-insensitively by kent_bn.bn_segment().
"""

SEG_EXT = {}

SEG_EXT.update({
    "Abrupt": "রুক্ষ, আকস্মিক",
    "periodical attacks of": "পর্যায়ক্রমিক আক্রমণ",
    "short lasting": "স্বল্পস্থায়ী",
    "starts when spoken to": "কথা বললে চমকে ওঠে",
    "buried in thought": "চিন্তায় ডুবে থাকা",
    "alternating with frivolity": "চপলতার সঙ্গে পর্যায়ক্রমে",
    "as to what would become of him": "তার কী হবে সেই ভেবে",
    "Abstraction of mind": "মনের অন্যমনস্কতা",
    "Abusive": "গালিগালাজপ্রবণ",
    "angry": "ক্রুদ্ধ",
    "without being": "না হয়েও",
    "scolds until the lips are blue and eyes stare and she falls down fainting": "গালাগাল করতে করতে ঠোঁট নীল হয়, চোখ স্থির হয়ে যায় ও মূর্ছা গিয়ে পড়ে যায়",
    "Activity": "কর্মচঞ্চলতা",
    "fruitless": "নিষ্ফল",
    "Admonition agg.": "উপদেশ বা তিরস্কারে বৃদ্ধি",
    "Affectation": "ভান করা",
    "Affectionate": "স্নেহপ্রবণ",
    "Amusement": "আমোদ-প্রমোদ",
    "irascibility": "খিটখিটে মেজাজ",
    "absent persons": "অনুপস্থিত ব্যক্তি",
    "ailments after anger": "রাগের পর অসুস্থতা",
    "ailments after anger with anxiety": "উদ্বেগসহ রাগের পর অসুস্থতা",
    "with fright": "ভয় পাওয়া সহ",
    "silent grief": "নীরব শোক",
    "quick repentance": "দ্রুত অনুতাপ",
    "answer": "উত্তর",
    "when obliged to": "বাধ্য হলে",
    "caressing": "আদর করা",
    "consoled": "সান্ত্বনা দেওয়া হলে",
    "from the": "-এর কারণে",
    "former vexations": "পুরনো বিরক্তি",
    "interruption": "বাধা দেওয়া",
    "mistakes": "ভুল",
    "over his": "নিজের",
    "misunderstood": "ভুল বোঝা হলে",
    "past events": "অতীত ঘটনা",
    "stabbed": "ছুরিকাঘাত করা",
    "so that he could have": "এমন যে সে করে ফেলতে পারত",
    "any one": "যে কাউকে",
    "thinking of his ailments": "নিজের অসুখের কথা ভাবা",
    "throws things away": "জিনিসপত্র ছুড়ে ফেলে",
    "voices of people": "মানুষের কণ্ঠস্বর",
    "driving from place to place": "এক জায়গা থেকে আরেক জায়গায় ছোটা",
    "abruptly": "আকস্মিকভাবে",
    "shortly": "সংক্ষেপে",
    "curtly": "রূঢ়ভাবে সংক্ষিপ্ত",
    "loquacious at other times": "অন্য সময়ে বাচাল",
    "sings": "গান গায়",
    "talks": "কথা বলে",
    "but will not answer questions": "কিন্তু প্রশ্নের উত্তর দেয় না",
    "confusedly as though thinking of something else": "এলোমেলোভাবে, যেন অন্য কিছু ভাবছে",
    "disconnected": "অসংলগ্ন",
    "foolish": "বোকার মতো",
    "hastily": "তাড়াহুড়ো করে",
    "imaginary questions": "কাল্পনিক প্রশ্ন",
    "incoherently": "অসংলগ্নভাবে",
    "incorrectly": "ভুলভাবে",
    "irrelevantly": "অপ্রাসঙ্গিকভাবে",
    "monosyllable": "এক শব্দে",
    "\"no\" to all questions": "সব প্রশ্নেই \"না\"",
    "reflects long": "দীর্ঘক্ষণ ভাবে",
    "refuses to": "অস্বীকার করে",
    "repeats the question first": "আগে প্রশ্নটি আবার বলে",
    "yet knows no one": "তবু কাউকে চেনে না",
    "stupor returns quickly after": "পরেই দ্রুত আচ্ছন্নতা ফিরে আসে",
    "unintelligibly": "দুর্বোধ্যভাবে",
    "Antagonism with herself": "নিজের সঙ্গেই বিরোধ",
    "Anticipation": "আগাম আশঙ্কা",
    "complaints from": "-জনিত উপসর্গ",
    "Antics": "ভাঁড়ামি",
    "plays": "খেলা করে",
    "uneasiness and anxiety": "অস্বস্তি ও উদ্বেগ",
    "must uncover": "গা খুলে ফেলতেই হয়",
    "violent exercise": "প্রচণ্ড পরিশ্রম",
    "alternating with indifference": "উদাসীনতার সঙ্গে পর্যায়ক্রমে",
    "anticipating an engagement": "কোনো কাজের কথা ভেবে আগাম উদ্বেগ",
    "apparition": "প্রেতমূর্তি",
    "from horrible": "ভয়ানক কিছু থেকে",
    "while awake": "জেগে থাকা অবস্থায়",
    "bathing the feet": "পা ধোয়া",
    "about his": "নিজের সম্পর্কে",
    "when lifted from the cradle": "দোলনা থেকে তুললে",
    "church bells": "গির্জার ঘণ্টা",
    "from hearing": "শুনে",
    "thought of (in a woman)": "-এর কথা ভাবলে (নারীর ক্ষেত্রে)",
    "conscience": "বিবেক",
    "of (as if guilty of a crime)": "-এর (যেন কোনো অপরাধ করেছে)",
    "continence prolonged": "দীর্ঘ যৌনসংযম",
    "before attack of whooping cough": "হুপিং কাশির আক্রমণের আগে",
    "crowd": "ভিড়",
    "cruelties": "নিষ্ঠুরতা",
    "after hearing of": "-এর কথা শোনার পর",
    "on waking from frightful": "ভয়ানক স্বপ্ন থেকে জেগে উঠলে",
    "exertion of eyes": "চোখের পরিশ্রম",
    "expected of him": "তার কাছ থেকে প্রত্যাশিত",
    "when anything is": "যখন কিছু প্রত্যাশা করা হয়",
    "prodrome": "পূর্বলক্ষণ",
    "fits": "আক্ষেপের আক্রমণ",
    "emission of": "-এর নিঃসরণ",
    "flushes of heat": "উত্তাপের ঝলক",
    "foot bath": "পা ধোয়ার স্নান",
    "friends at home": "বাড়ির স্বজন",
    "future": "ভবিষ্যৎ",
    "health": "স্বাস্থ্য",
    "especially during climacteric period": "বিশেষত রজোনিবৃত্তিকালে",
    "hot air": "গরম বাতাস",
    "hungry": "ক্ষুধার্ত",
    "hypochondriacal": "রোগভীতিগ্রস্ত",
    "ineffectual desire for stool": "মলত্যাগের নিষ্ফল ইচ্ছা",
    "must lie down with anguish": "যন্ত্রণায় শুয়ে পড়তেই হয়",
    "from flatulence": "বায়ু জমা থেকে",
    "which prevents sleep": "যা ঘুম আসতে দেয় না",
    "night watching": "রাত জাগা",
    "of rushing water": "বেগে বয়ে যাওয়া জলের",
    "pressure on the chest": "বুকে চাপ",
    "pursued when walking": "হাঁটার সময় কেউ পিছু নিয়েছে",
    "railroad": "রেলগাড়ি",
    "when about to journey by": "-এ যাত্রা করার আগে",
    "while in train": "ট্রেনে থাকা অবস্থায়",
    "down hill": "ঢাল বেয়ে নামা",
    "salvation": "পরিত্রাণ",
    "sedentary employment": "বসে করার কাজ",
    "shaving": "দাড়ি কামানো",
    "loss of sleep": "নিদ্রাহীনতা",
    "on starting from": "-এ চমকে উঠলে",
    "partial slumbering in the morning": "সকালে আধা-তন্দ্রা",
    "in company": "লোকজনের মধ্যে",
    "while straining at": "-এ কোঁথ দেওয়ার সময়",
    "during a thunder": "বজ্রপাতের সময়",
    "strangers": "অপরিচিত লোক",
    "in the presence of": "-এর সামনে",
    "suicidal": "আত্মহত্যাপ্রবণ",
    "thinking about it": "তা নিয়ে ভাবলে",
    "thoughts": "চিন্তা",
    "time is set": "সময় বেঁধে দেওয়া হলে",
    "if a": "যদি",
    "from smoking": "ধূমপান থেকে",
    "on raising the": "-টি তুললে",
    "which makes him walk faster": "যা তাকে দ্রুত হাঁটায়",
    "warm bed yet limbs cold if uncovered": "বিছানা গরম, তবু গা খুললে হাত-পা ঠান্ডা",
    "during manual": "হাতের কাজের সময়",
    "Aphasia": "বাকশক্তি লোপ",
    "Ardent": "উদ্দীপ্ত",
    "Asks for nothing": "কিছুই চায় না",
    "Attitudes": "ভঙ্গি",
    "assumes strange": "অদ্ভুত ভঙ্গি নেয়",
    "Audacity": "দুঃসাহস",
    "Avarice": "কৃপণতা",
    "approached to being": "কাছে আসা",
    "friends": "বন্ধুবান্ধব",
    "during pregnancy": "গর্ভাবস্থায়",
    "husband": "স্বামী",
    "members of family": "পরিবারের সদস্য",
    "to certain": "নির্দিষ্ট কারও প্রতি",
    "religious": "ধর্মীয়",
    "to the opposite sex": "বিপরীত লিঙ্গের প্রতি",
    "those": "যারা",
    "ailments from": "-জনিত অসুস্থতা",
    "Battles": "যুদ্ধ",
    "talks about": "-এর কথা বলে",
    "aversion to (shuns)": "-এ বিতৃষ্ণা (এড়িয়ে চলে)",
    "desires to remain in": "-এ থাকতে চায়",
    "jumps out of": "-থেকে লাফিয়ে নামে",
    "wants to destroy himself but lacks courage": "আত্মহত্যা করতে চায় কিন্তু সাহস পায় না",
    "and runs recklessly about": "এবং বেপরোয়াভাবে ছোটাছুটি করে",
    "Begging": "ভিক্ষা করা",
    "entreating": "মিনতি করা",
    "Bellowing": "চিৎকার করে ডাকা",
    "Benevolence": "পরোপকারিতা",
    "himself": "নিজেকে",
    "pillow": "বালিশ",
    "spoons": "চামচ",
    "tumblers": "গ্লাস",
    "Black and sombre": "কালো ও বিষণ্ন",
    "everything that is": "যা কিছু -তা-ই",
    "Blindness": "অন্ধত্ব",
    "pretended": "ভান করা",
    "cannot look at": "-এর দিকে তাকাতে পারে না",
    "or a knife": "বা ছুরি",
    "Break things": "জিনিস ভাঙা",
    "Brooding": "গুমরে থাকা",
    "incapacity for": "-এর অক্ষমতা",
    "talks of": "-এর কথা বলে",
    "Busy": "ব্যস্ত",
    "fruitlessly": "নিষ্ফলভাবে",
    "Capriciousness": "খেয়ালিপনা",
    "Carefulness": "অতি সতর্কতা",
    "Cares": "দুশ্চিন্তা",
    "full of": "-এ পরিপূর্ণ",
    "domestic affairs": "সংসারের ব্যাপার",
    "Carried": "কোলে নেওয়া",
    "desires to be": "-হতে চায়",
    "in croup": "ক্রুপ রোগে",
    "Cautious": "সতর্ক",
    "anxiously": "উদ্বিগ্নভাবে",
    "Censorious": "দোষ ধরা স্বভাব",
    "critical": "সমালোচনাপ্রবণ",
    "dearest friends": "প্রিয়তম বন্ধুদের",
    "disposed to find fault or is silent": "দোষ ধরে অথবা চুপ করে থাকে",
    "Chaotic": "বিশৃঙ্খল",
    "Chases imaginary objects": "কাল্পনিক জিনিসের পিছনে ছোটে",
    "gay": "প্রফুল্ল",
    "happy": "সুখী",
    "alternating with aversion to work": "কাজে অনীহার সঙ্গে পর্যায়ক্রমে",
    "passion": "আবেগ",
    "with burst of": "-এর প্রবল বেগসহ",
    "physical sufferings": "শারীরিক কষ্ট",
    "violence": "প্রচণ্ডতা",
    "want of sympathy": "সহানুভূতির অভাব",
    "constipated": "কোষ্ঠবদ্ধ",
    "followed by irritability": "এরপর খিটখিটে ভাব",
    "melancholy": "বিষণ্নতা",
    "prostration": "অবসাদ",
    "with all": "সব ক্ষেত্রেই",
    "thinking of death": "মৃত্যুর কথা ভাবা",
    "thunders and lightnings": "বজ্র ও বিদ্যুৎ",
    "when it": "যখন তা হয়",
    "Childish behavior": "শিশুসুলভ আচরণ",
    "desires to beat": "মারতে চায়",
    "to have": "পেতে চায়",
    "to beget": "সন্তান জন্ম দিতে",
    "dislikes her own": "নিজের সন্তানকেই অপছন্দ করে",
    "especially little girls (a woman)": "বিশেষত ছোট মেয়েদের (নারীর ক্ষেত্রে)",
    "flies from his own": "নিজের সন্তানের কাছ থেকে পালায়",
    "Clairvoyance": "অতীন্দ্রিয় দৃষ্টি",
    "Clinging to persons or furniture": "মানুষ বা আসবাব আঁকড়ে ধরা",
    "child awakens terrified": "শিশু আতঙ্কিত হয়ে জেগে ওঠে",
    "knows no one": "কাউকে চেনে না",
    "screams": "চিৎকার করে",
    "clings to those near": "কাছের লোকদের আঁকড়ে ধরে",
    "aversion to red": "লাল রঙে বিতৃষ্ণা",
    "green and black": "সবুজ ও কালো",
    "alternating with bursts of pleasantry and sarcasm": "হঠাৎ রসিকতা ও শ্লেষের সঙ্গে পর্যায়ক্রমে",
    "when alone": "একা থাকলে",
    "avoids the sight of people": "মানুষের চোখের সামনে পড়া এড়ায়",
    "and lies with closed eyes": "এবং চোখ বন্ধ করে শুয়ে থাকে",
    "and shuts herself up": "এবং নিজেকে ঘরে বন্ধ করে রাখে",
    "country away from people": "লোকালয় থেকে দূরে গ্রামে",
    "wants to get into the": "-এ চলে যেতে চায়",
    "desires solitude to practice masturbation": "হস্তমৈথুনের জন্য নির্জনতা চায়",
    "to indulge her fancy": "নিজের কল্পনায় ডুবে থাকার জন্য",
    "lie with closed eyes": "চোখ বন্ধ করে শুয়ে থাকা",
    "dreads being alone": "একা থাকতে ভয় পায়",
    "yet": "তবুও",
    "of intimate": "ঘনিষ্ঠ লোকদের",
    "meeting of friends": "বন্ধুদের সঙ্গে দেখা",
    "whom he imagines he has offended": "যাদের সে ভাবে সে আঘাত দিয়েছে",
    "desires to be let alone": "একা থাকতে দেওয়া হোক তা চায়",
    "pregnant": "গর্ভবতী",
    "presence of strangers": "অপরিচিতদের উপস্থিতি",
    "people intolerable to her during stool": "মলত্যাগের সময় লোকজন অসহ্য লাগে",
    "during urination": "প্রস্রাবের সময়",
    "smiling faces": "হাসিমুখ",
    "walk alone": "একা হাঁটা",
    "want to": "-করতে চায়",
    "while agg.": "-এর সময় বৃদ্ধি",
    "friend": "বন্ধু",
    "of a": "একজনের",
    "yet treats them outrageously": "তবু তাদের সঙ্গে দুর্ব্যবহার করে",
    "Complaining": "অভিযোগ করা",
    "offenses": "অপমান",
    "long past": "বহু আগেকার",
    "supposed injury": "কল্পিত অপমান",
    "alternating with uterine pains": "জরায়ুর ব্যথার সঙ্গে পর্যায়ক্রমে",
    "calculating while": "হিসাব করার সময়",
    "crazy feeling on top of head": "মাথার চাঁদিতে পাগল-পাগল অনুভূতি",
    "wild feeling in head": "মাথায় উন্মাদ-সদৃশ অনুভূতি",
    "with confusion of ideas": "ভাবনার গোলমালসহ",
    "it becomes dark before the eyes": "চোখের সামনে অন্ধকার হয়ে আসে",
    "has a vacant feeling": "শূন্য-শূন্য অনুভূতি হয়",
    "studying": "পড়াশোনা করা",
    "Confidence": "আত্মবিশ্বাস",
    "want of self": "আত্মবিশ্বাসের অভাব",
    "and thinks others have none which makes her unhappy": "এবং ভাবে অন্যদেরও তা নেই, যা তাকে অসুখী করে",
    "Confiding": "বিশ্বাস করে সব বলে ফেলা",
    "Confounding objects and ideas": "বস্তু ও ভাবনা গুলিয়ে ফেলা",
    "arouse himself": "নিজেকে জাগিয়ে তোলা",
    "ascending agg.": "উপরে উঠলে বৃদ্ধি",
    "bread agg.": "রুটিতে বৃদ্ধি",
    "calculating": "হিসাব করা",
    "carousal": "মদ্যপানের আসর",
    "cold bath": "ঠান্ডা জলে স্নান",
    "concentrate the mind": "মন একাগ্র করা",
    "conversation agg.": "কথাবার্তায় বৃদ্ধি",
    "before paroxysm of": "-এর আক্রমণের আগে",
    "epistaxis amel.": "নাক দিয়ে রক্ত পড়ায় উপশম",
    "putting on": "পরার সময়",
    "identity": "নিজের পরিচয়",
    "as to his": "নিজের সম্পর্কে",
    "injury to head": "মাথায় আঘাত",
    "as after being": "যেন আঘাত পাওয়ার পর",
    "laughing agg.": "হাসলে বৃদ্ধি",
    "loses his way in well-known streets": "চেনা রাস্তায় পথ হারায়",
    "paroxysms of pain": "ব্যথার আক্রমণ",
    "if he attempts to understand it": "বোঝার চেষ্টা করলে",
    "after a siesta": "দুপুরের ঘুমের পর",
    "spirituous liquors": "কড়া মদ",
    "washing the face amel.": "মুখ ধুলে উপশম",
    "weeping amel.": "কাঁদলে উপশম",
    "strong effort of": "-এর প্রবল চেষ্টা",
    "wrapping up head amel.": "মাথা ঢেকে রাখলে উপশম",
    "Conscientious about trifles": "তুচ্ছ বিষয়ে অতি বিবেকবান",
    "Consolation agg.": "সান্ত্বনায় বৃদ্ধি",
    "Contemptuous": "অবজ্ঞাপূর্ণ",
    "in open air or when sun shines into room": "খোলা বাতাসে বা ঘরে রোদ এলে",
    "paroxysms against her will": "ইচ্ছার বিরুদ্ধে আক্রমণ",
    "of everything": "সবকিছুর প্রতি",
    "self": "নিজের প্রতি",
    "Contradict": "প্রতিবাদ করা",
    "disposition to": "-এর প্রবণতা",
    "is intolerant of": "-সহ্য করতে পারে না",
    "has to restrain himself to keep from violence": "সহিংসতা ঠেকাতে নিজেকে সামলাতে হয়",
    "Contrary": "বিপরীতধর্মী, বিরোধিতাপ্রবণ",
    "Conversation agg.": "কথাবার্তায় বৃদ্ধি",
    "Counting continually": "অনবরত গোনা",
    "Courageous": "সাহসী",
    "Cowardice": "কাপুরুষতা",
    "Crawling on floor": "মেঝেতে হামাগুড়ি দেওয়া",
    "Croaking": "ব্যাঙের মতো ডাকা",
    "Cruelty": "নিষ্ঠুরতা",
    "Cursing": "অভিশাপ দেওয়া",
    "all night": "সারা রাত",
    "and complains of stupid feeling": "এবং ভোঁতা-ভোঁতা অনুভূতির অভিযোগ করে",
    "Cut others": "অন্যকে কাটা",
    "desires to": "-করতে চায়",
    "alternating with sighing": "দীর্ঘশ্বাসের সঙ্গে পর্যায়ক্রমে",
    "grotesque": "উদ্ভট",
    "unconscious": "অচেতন",
    "Darkness agg.": "অন্ধকারে বৃদ্ধি",
    "Deafness": "বধিরতা",
    "convalescence": "রোগমুক্তির সময়",
    "walking in open air while": "খোলা বাতাসে হাঁটার সময়",
    "presentiment of": "-এর পূর্বাভাস",
    "believes that she will die soon": "বিশ্বাস করে সে শীঘ্রই মারা যাবে",
    "and that she cannot be helped": "এবং তাকে বাঁচানো যাবে না",
    "predicts the time": "সময় আগেই বলে দেয়",
    "thinks of death calmly": "শান্তভাবে মৃত্যুর কথা ভাবে",
    "thoughts of": "-এর চিন্তা",
    "Deceitful": "প্রতারক",
    "Deeds": "কীর্তি",
    "feels as if he could do great": "মনে হয় সে মহৎ কাজ করতে পারবে",
    "Defiant": "অবাধ্য",
    "at daybreak": "ভোরবেলা",
    "nap": "ভাতঘুম",
    "abandons her relatives": "আত্মীয়দের ছেড়ে যায়",
    "absurd things": "উদ্ভট কাজ",
    "does": "করে",
    "coma": "গভীর অচেতনতা",
    "also with somnolency": "সেই সঙ্গে ঝিমুনিও",
    "sopor": "গভীর আচ্ছন্নতা",
    "tetanic convulsions": "ধনুষ্টঙ্কার-সদৃশ আক্ষেপ",
    "lies on his back": "চিত হয়ে শুয়ে থাকে",
    "knees and thighs flexed": "হাঁটু ও ঊরু গোটানো",
    "hands joined": "হাত জোড় করা",
    "antics": "ভাঁড়ামি",
    "apathetic": "নিস্পৃহ",
    "throws about": "ছোড়াছুড়ি করে",
    "aroused": "জাগানো",
    "on being": "-হলে",
    "attacks people with knife": "ছুরি নিয়ে মানুষের উপর চড়াও হয়",
    "attempts to leave": "চলে যাওয়ার চেষ্টা করে",
    "creeps about in": "-এর মধ্যে হামাগুড়ি দিয়ে ঘোরে",
    "bellows like a calf": "বাছুরের মতো ডাকে",
    "blames himself for his folly": "নিজের বোকামির জন্য নিজেকে দোষ দেয়",
    "busy": "ব্যস্ত",
    "changing subjects rapidly": "দ্রুত প্রসঙ্গ বদলানো",
    "comical": "হাস্যকর",
    "for help": "সাহায্যের জন্য",
    "depletion": "রক্ত বা রস ক্ষয়",
    "embraces the stove": "চুলা জড়িয়ে ধরে",
    "erotic": "কামজ",
    "exaltation of strength": "শক্তি বেড়ে গেছে এমন বোধ",
    "fantastic": "উদ্ভট কল্পনাপূর্ণ",
    "fatigue": "ক্লান্তি",
    "study": "পড়াশোনা",
    "fear of men": "মানুষের ভয়",
    "fierce": "উগ্র",
    "silly": "নির্বোধ",
    "foreign countries": "বিদেশ",
    "language": "ভাষা",
    "talks in a": "-ভাষায় কথা বলে",
    "gather objects off the wall": "দেয়াল থেকে জিনিস কুড়ানো",
    "tries to": "-চেষ্টা করে",
    "alternating with laughing": "হাসির সঙ্গে পর্যায়ক্রমে",
    "with melancholy": "বিষণ্নতার সঙ্গে",
    "almost": "প্রায়",
    "look fixed on one point staring": "এক বিন্দুতে স্থির দৃষ্টি",
    "with wrinkled face": "কুঁচকানো মুখসহ",
    "loquacious": "বাচাল",
    "maniacal": "উন্মাদপ্রায়",
    "miscarriage": "গর্ভপাত",
    "moves lips as if talking": "কথা বলার মতো ঠোঁট নাড়ে",
    "puts stones in": "-এ পাথর ভরে",
    "murmuring": "বিড়বিড় করা",
})

SEG_EXT.update({
    "to himself": "নিজের মনে",
    "muttering": "বিড়বিড় করা",
    "noisy": "হইচইপূর্ণ",
    "nonsense": "আজেবাজে কথা",
    "with eyes open": "চোখ খোলা অবস্থায়",
    "picking at nose or lips": "নাক বা ঠোঁট খোঁটা",
    "quiet": "শান্ত",
    "rabid": "ক্ষিপ্ত",
    "raging": "উন্মত্ত ক্রোধ",
    "raving": "প্রলাপ বকা",
    "rambling": "এলোমেলো বকা",
    "recognizes no one": "কাউকে চিনতে পারে না",
    "repeats the same sentence": "একই বাক্য বারবার বলে",
    "reproachful": "তিরস্কারপূর্ণ",
    "rocking to and fro": "সামনে-পিছনে দোলা",
    "rolls on floor": "মেঝেতে গড়াগড়ি দেয়",
    "romping with children": "শিশুদের সঙ্গে হুটোপুটি",
    "same subject all the time": "সবসময় একই প্রসঙ্গ",
    "scolding": "বকাঝকা",
    "silent": "নীরব",
    "sorrowful": "শোকার্ত",
    "urinate on the floor": "মেঝেতে প্রস্রাব করা",
    "urinates outside the pot": "পাত্রের বাইরে প্রস্রাব করে",
    "is restrained and calmed with great difficulty": "বহু কষ্টে সামলানো ও শান্ত করা যায়",
    "jumping into": "-এ ঝাঁপ দেওয়া",
    "wedding": "বিয়ে",
    "prepares for": "-এর জন্য প্রস্তুতি নেয়",
    "well": "সুস্থ",
    "declares she is": "নিজেকে সুস্থ বলে দাবি করে",
    "wraps up in fur during summer": "গ্রীষ্মেও পশমে গা ঢাকে",
    "wrongs": "অন্যায়",
    "of fancied": "কল্পিত",
    "imaginations": "কল্পনা",
    "hallucinations": "মায়াদর্শন",
    "that it is always": "যে তা সবসময়",
    "abdomen is fallen in": "পেট ভিতরে দেবে গেছে",
    "his stomach devoured": "তার পাকস্থলী খেয়ে ফেলা হয়েছে",
    "his scrotum swollen": "তার অণ্ডকোষ ফুলে গেছে",
    "absurd": "উদ্ভট",
    "figures are present": "নানা মূর্তি উপস্থিত",
    "accused": "অভিযুক্ত",
    "thinks she is": "নিজেকে মনে করে",
    "active": "সক্রিয়",
    "affection of friends": "বন্ধুদের স্নেহ",
    "has lost": "হারিয়ে ফেলেছে",
    "that he is hovering in": "যে সে ভেসে বেড়াচ্ছে",
    "like a spirit": "আত্মার মতো",
    "that she is alone in a graveyard": "যে সে কবরস্থানে একা",
    "in a wilderness": "জনহীন প্রান্তরে",
    "she is": "সে যে",
    "in the world": "পৃথিবীতে",
    "are in": "-এর মধ্যে আছে",
    "dancing on the": "-এর উপর নাচছে",
    "beetles": "গুবরে পোকা",
    "on walls and furniture": "দেয়াল ও আসবাবে",
    "creeping of": "-এর হামাগুড়ি দেওয়া",
    "in her": "তার ভিতরে",
    "cup": "পেয়ালা",
    "dark colored": "গাঢ় রঙের",
    "jump out of the ground": "মাটি থেকে লাফিয়ে ওঠে",
    "jumping at her": "তার দিকে লাফিয়ে আসছে",
    "passing before her": "তার সামনে দিয়ে যাচ্ছে",
    "persons are": "মানুষজন যে",
    "rats": "ইঁদুর",
    "mice": "নেংটি ইঁদুর",
    "unclean": "অপরিচ্ছন্ন",
    "annihilation": "সম্পূর্ণ বিলুপ্তি",
    "about to sink into": "-এ তলিয়ে যাওয়ার মুখে",
    "ants": "পিঁপড়া",
    "bed seems full of": "বিছানা যেন ভরা",
    "thought he would have": "ভাবল তার হবে",
    "appreciated": "সমাদৃত",
    "that she is not": "যে সে নয়",
    "argument": "যুক্তিতর্ক",
    "making an eloquent": "বাগ্মিতাপূর্ণ বক্তৃতা দিচ্ছে",
    "arms are bound to her body": "হাত দুটি শরীরের সঙ্গে বাঁধা",
    "do not belong to her": "তার নিজের নয়",
    "reach the clouds when going to sleep": "ঘুমাতে গেলে মেঘ ছুঁয়ে ফেলে",
    "that she has three": "যে তার তিনটি আছে",
    "is about to be": "-হতে চলেছে",
    "assaulted": "আক্রান্ত",
    "is going to be": "-হতে যাচ্ছে",
    "asylum": "পাগলাগারদ",
    "that she will be sent to": "যে তাকে পাঠানো হবে",
    "babies": "শিশু",
    "are two in bed": "বিছানায় দুটি আছে",
    "that he is sitting on a": "যে সে -এর উপর বসে আছে",
    "that he is being": "যে তাকে -করা হচ্ছে",
    "beautiful": "সুন্দর",
    "landscape": "প্রাকৃতিক দৃশ্য",
    "micturition": "প্রস্রাব করা",
    "all things seem": "সবকিছু মনে হয়",
    "rags seem": "ছেঁড়া কাপড় মনে হয়",
    "even": "এমনকি",
    "drawn from under her": "তার নিচ থেকে টেনে নেওয়া",
    "as if some one was in": "যেন কেউ -এর মধ্যে আছে",
    "with him": "তার সঙ্গে",
    "bouncing her up and down": "তাকে উপর-নিচ করে ঝাঁকাচ্ছে",
    "two persons in bed": "বিছানায় দুজন মানুষ",
    "with her": "তার সঙ্গে",
    "naked man is wrapped in the bedclothes with her": "একজন নগ্ন পুরুষ তার সঙ্গে বিছানার চাদরে জড়ানো",
    "someone over it": "তার উপর কেউ",
    "drives him out": "তাকে তাড়িয়ে দেয়",
    "stands at the foot menacing": "পায়ের দিকে ভীতিপ্রদভাবে দাঁড়িয়ে থাকে",
    "tries to take away the bed clothes": "বিছানার চাদর কেড়ে নিতে চায়",
    "under it": "তার নিচে",
    "knocking": "টোকা দেওয়া",
    "bees": "মৌমাছি",
    "bells": "ঘণ্টা",
    "hears ringing of": "-এর বাজনা শোনে",
    "his funeral": "তার নিজের অন্ত্যেষ্টি",
    "numberless sweet toned": "অসংখ্য মধুর সুরের",
    "door bell": "দরজার ঘণ্টা",
    "belong to her own family": "তার নিজের পরিবারের",
    "does not": "নয়",
    "betrothal must be broken": "বাগদান ভাঙতেই হবে",
    "better than others": "অন্যদের চেয়ে ভালো",
    "bewitched": "ভূতে ধরা",
    "thinks he is": "নিজেকে মনে করে",
    "bier": "শবাধার",
    "is lying on a": "-এর উপর শুয়ে আছে",
    "birds": "পাখি",
    "that he is picking feathers from": "যে সে -এর পালক ছাড়াচ্ছে",
    "black objects and people": "কালো জিনিস ও মানুষ",
    "blind": "অন্ধ",
    "blood rushed through like roar of many waters": "বহু জলধারার গর্জনের মতো রক্ত ছুটে চলে",
    "alive on one side": "একদিকে জীবিত",
    "buried on the other": "অন্যদিকে সমাধিস্থ",
    "as if it were": "যেন তা ছিল",
    "brittle": "ভঙ্গুর",
    "covered the whole earth": "সারা পৃথিবী ঢেকে ফেলেছে",
    "the whole bed": "সমস্ত বিছানা",
    "delicate": "কোমল, ভঙ্গুর",
    "divided": "বিভক্ত",
    "erroneous ideas as to the state of his": "নিজের শরীরের অবস্থা নিয়ে ভুল ধারণা",
    "greatness of": "-এর বিশালতা",
    "as to": "-সম্পর্কে",
    "lighter than air": "বাতাসের চেয়েও হালকা",
    "putrefy": "পচে যাওয়া",
    "scattered about bed": "বিছানায় ছড়ানো",
    "tossed about to get the pieces together": "টুকরোগুলো জড়ো করতে ছোটাছুটি",
    "shrunken": "কুঁচকে যাওয়া",
    "like the dead": "মৃতের মতো",
    "spotted brown": "বাদামি ছোপযুক্ত",
    "is made of": "-দিয়ে তৈরি",
    "threefold": "তিনগুণ",
    "has a": "-আছে",
    "would sink down between the thighs": "দুই ঊরুর মাঝে তলিয়ে যাবে",
    "has softening": "নরম হয়ে গেছে",
    "brother fell overboard in her sight": "তার চোখের সামনে ভাই জাহাজ থেকে পড়ে গেল",
    "building stones": "গাঁথনির পাথর",
    "appearance of": "-এর চেহারা",
    "fancies is doing": "কল্পনা করে সে করছে",
    "thought they were pursuing ordinary": "ভাবল তারা সাধারণ কাজেই ব্যস্ত",
    "unfit for": "-এর অযোগ্য",
    "butterflies": "প্রজাপতি",
    "calls": "ডাকে",
    "someone": "কাউকে",
    "for absent persons": "অনুপস্থিত ব্যক্তিদের",
    "castles and palaces": "দুর্গ ও প্রাসাদ",
    "cats": "বিড়াল",
    "caught": "ধরা পড়া",
    "as if he would be": "যেন সে -হবে",
    "chair is rising up": "চেয়ার উপরে উঠে যাচ্ছে",
    "chairs": "চেয়ার",
    "thinks he is repairing old": "ভাবে সে পুরনো চেয়ার সারাচ্ছে",
    "changed": "বদলে গেছে",
    "thinks everything": "ভাবে সবকিছু",
    "changing suddenly": "হঠাৎ বদলে যাওয়া",
    "childish fantasies": "শিশুসুলভ কল্পনা",
    "has": "-আছে",
    "is with companions of his youth": "যৌবনের সঙ্গীদের সঙ্গে আছে",
    "not hers": "তার নিজের নয়",
    "thinks he is again a": "ভাবে সে আবার শিশু হয়ে গেছে",
    "thinks he must drive": "ভাবে তাকে তাড়িয়ে দিতে হবে",
    "out of the house": "ঘর থেকে বাইরে",
    "too long": "অতি দীর্ঘ",
    "choir": "সমবেত সঙ্গীতদল",
    "on hearing music thinks he is in a cathedral": "গান শুনে ভাবে সে গির্জায় আছে",
    "choked": "শ্বাসরোধ",
    "thinks he is about to be": "ভাবে তার -হতে চলেছে",
    "night on waking": "রাতে জেগে উঠলে",
    "by icy-cold hands": "বরফ-ঠান্ডা হাতে",
    "christ": "যিশু",
    "thinks himself to be": "নিজেকে তা-ই মনে করে",
    "churchyard": "গির্জার কবরস্থান",
    "visits a": "-এ যায়",
    "that he is dancing in": "যে সে সেখানে নাচছে",
    "ciphers": "সংখ্যা",
    "clock": "ঘড়ি",
    "hears strike": "ঘণ্টা বাজতে শোনে",
    "clothes": "পোশাক",
    "thinks beautiful": "সুন্দর বলে মনে করে",
    "is clad in rags": "ছেঁড়া কাপড় পরা",
    "would fly away and become wandering stars": "উড়ে গিয়ে ভবঘুরে তারা হয়ে যাবে",
    "on undressing": "কাপড় খোলার সময়",
    "clouds": "মেঘ",
    "settled upon patients": "রোগীর উপর নেমে এল",
    "or danced about the sun": "অথবা সূর্যের চারদিকে নাচল",
    "before the fancy": "কল্পনার সামনে",
    "heavy black enveloped her": "ভারী কালো মেঘ তাকে ঘিরে ফেলল",
    "clouds and rocks as if looking over": "যেন মেঘ ও পাথরের উপর দিয়ে তাকানো",
    "cockroaches swarmed about the room": "ঘরে আরশোলার ঝাঁক",
    "companions seemed half men": "সঙ্গীদের অর্ধেক মানুষ মনে হলো",
    "half plants": "অর্ধেক গাছ",
    "confidence in him": "তার উপর আস্থা",
    "his friends have lost all": "তার বন্ধুরা সব আস্থা হারিয়েছে",
    "confusion": "বিভ্রান্তি",
    "imagines others will observe her": "কল্পনা করে অন্যরা তাকে লক্ষ করবে",
    "consciousness": "চেতনা",
    "belongs to another": "অন্য কারও",
    "conspiracies against her father": "তার বাবার বিরুদ্ধে ষড়যন্ত্র",
    "thought the landlord's bills were": "ভাবল বাড়িওয়ালার বিলগুলোই ষড়যন্ত্র",
    "against him": "তার বিরুদ্ধে",
    "there were": "ছিল",
    "contaminates everything she touches": "যা ছোঁয় তা-ই দূষিত করে",
    "convent": "মঠ",
    "thinks she will have to go to a": "ভাবে তাকে মঠে যেতে হবে",
    "corner": "কোণ",
    "sees something coming out of": "-থেকে কিছু বেরিয়ে আসতে দেখে",
    "corners of houses seem to project so that he fears he will run against them while walking in the street": "রাস্তায় হাঁটার সময় বাড়ির কোণগুলো এমন বেরিয়ে আছে মনে হয় যে ধাক্কা লাগার ভয় পায়",
    "cowards": "কাপুরুষ",
    "thinks persons leaving him to be": "যারা তাকে ছেড়ে যায় তাদের কাপুরুষ মনে করে",
    "crabs": "কাঁকড়া",
    "creative power": "সৃষ্টিক্ষমতা",
    "crime about to commit a": "অপরাধ করতে চলেছে",
    "as if he had committed": "যেন সে অপরাধ করেছে",
    "criminal": "অপরাধী",
    "that he is a": "যে সে একজন",
    "and others know it": "এবং অন্যরা তা জানে",
    "criminals": "অপরাধীরা",
    "criticised": "সমালোচিত",
    "cucumbers": "শসা",
    "sees on the bed": "বিছানায় দেখে",
    "cut through": "কেটে ফেলা",
    "as if he were": "যেন সে",
    "in two": "দুই টুকরো",
    "cylinder": "চোঙ",
    "seemed to be a": "-বলে মনে হলো",
    "dancing satyres and nodding mandarins": "নাচতে থাকা বনদেবতা ও মাথা-নাড়া পুতুল",
    "danger": "বিপদ",
    "impression of": "-এর ধারণা",
    "to his life": "তার জীবনের",
    "from his family": "তার পরিবারের কাছ থেকে",
    "frightened by images of": "-এর ছবি দেখে ভয় পায়",
    "all her friends are dead and she must go to a convent": "তার সব বন্ধু মৃত এবং তাকে মঠে যেতে হবে",
    "corpse on a bier": "শবাধারে মৃতদেহ",
    "mutilated": "বিকৃত",
    "of absent acquaintance on sofa and has dread": "সোফায় অনুপস্থিত পরিচিতের মৃতদেহ, আর তাতে আতঙ্ক",
    "dead brother and child": "মৃত ভাই ও সন্তান",
    "sister": "বোন",
    "tall yellow": "লম্বা হলদে",
    "trying to share bed with him and promptly ejected": "তার সঙ্গে বিছানা ভাগ করতে চায়, সঙ্গে সঙ্গে তাড়িয়ে দেওয়া হয়",
    "that he himself was dead": "যে সে নিজেই মৃত",
    "her child was dead": "তার সন্তান মৃত",
    "his mother is dead": "তার মা মৃত",
    "deaf and dumb": "বধির ও বোবা",
    "debate": "তর্কসভা",
    "of being in": "-এ থাকার",
    "delirious": "প্রলাপগ্রস্ত",
    "expected to become": "হয়ে যাওয়ার আশঙ্কা",
    "imagines he was": "কল্পনা করে সে ছিল",
    "deserted": "পরিত্যক্ত",
    "forsaken": "একেবারে ত্যাজ্য",
    "despised": "ঘৃণিত",
    "that is": "যে তা",
    "devils": "শয়তান",
    "possessed of a": "শয়তানে ভর করেছে",
    "that everyone is": "যে সবাই তা-ই",
    "present": "উপস্থিত",
    "that all persons are": "যে সব মানুষই তা-ই",
    "he is a": "সে একজন",
    "he will be taken by the devil": "শয়তান তাকে নিয়ে যাবে",
    "devoured": "গিলে ফেলা",
    "had been by animals": "জন্তুতে খেয়ে ফেলেছিল",
    "die": "মরা",
    "thought he was about to": "ভাবল সে মরতে চলেছে",
    "time has come to": "মরার সময় এসে গেছে",
    "while walking thinks he will have a fit or die": "হাঁটার সময় ভাবে তার খিঁচুনি হবে বা সে মারা যাবে",
    "would": "-হবে",
    "and soon be dissected": "এবং শীঘ্রই ব্যবচ্ছেদ করা হবে",
    "everything in room": "ঘরের সবকিছু",
    "is while she is tall and elevated": "সে লম্বা ও উঁচু, আর তা ছোট",
    "left side of body is smaller": "শরীরের বাম দিক ছোট",
    "parts are": "অঙ্গগুলি",
    "is too": "অতিরিক্ত",
    "whole body is": "সমস্ত শরীর",
    "eating dirt": "মাটি খাওয়া",
    "that": "যে",
    "disabled": "অক্ষম",
    "that he has every": "যে তার সব রোগ আছে",
    "has incurable": "দুরারোগ্য রোগ আছে",
    "is deaf": "বধির",
    "dumb and has cancer": "বোবা এবং ক্যান্সার আছে",
    "unrecognized": "অচেনা",
    "has an": "-আছে",
    "disgraced": "অপমানিত",
    "dissected": "ব্যবচ্ছেদ করা",
    "that he will be": "যে তাকে -করা হবে",
    "distinguished": "বিশিষ্ট",
    "divided into two parts": "দুই ভাগে বিভক্ত",
    "or cut in two": "অথবা দুই টুকরো করা",
    "and could not tell of which part he had possession on waking": "এবং জেগে উঠে বলতে পারে না কোন অংশটি তার",
    "divine": "ঐশ্বরিক",
    "doctors": "ডাক্তার",
    "thought three were coming": "ভাবল তিনজন আসছে",
    "attack him": "তাকে আক্রমণ করে",
    "biting his chest": "তার বুকে কামড়াচ্ছে",
    "swarm about him": "তাকে ঘিরে ঝাঁক বাঁধে",
    "dolls": "পুতুল",
    "people appeared like": "মানুষকে পুতুলের মতো দেখাল",
    "door": "দরজা",
    "that someone was coming in at the": "যে কেউ দরজা দিয়ে ঢুকছে",
    "one limb is": "একটি অঙ্গ",
    "sensations present themselves in a double form": "অনুভূতি দ্বিগুণ হয়ে দেখা দেয়",
    "dragged from lowest abyss of darkness": "অন্ধকারের গভীরতম গহ্বর থেকে টেনে তোলা",
    "dreaming when awake": "জেগে থেকেও স্বপ্ন দেখা",
    "imagines himself": "নিজেকে কল্পনা করে",
    "driving sheep": "ভেড়া তাড়ানো",
    "peacocks": "ময়ূর",
    "dumb": "বোবা",
    "dying": "মরণাপন্ন",
    "elevated in air": "বাতাসে উঁচুতে",
    "carried to an elevation": "উঁচুতে তুলে নেওয়া",
    "bed were raised": "বিছানা যেন উঁচু হয়ে গেছে",
    "emperor": "সম্রাট",
    "thought himself an": "নিজেকে সম্রাট ভাবল",
    "talked of": "-এর কথা বলল",
    "encaged in wires": "তারের খাঁচায় বন্দী",
    "enemy": "শত্রু",
    "everyone is an": "সবাই শত্রু",
    "surrounded by": "-দ্বারা পরিবেষ্টিত",
    "under the bed": "বিছানার নিচে",
    "engaged in some occupation": "কোনো কাজে ব্যস্ত",
    "in ordinary occupation": "সাধারণ কাজে",
    "body parts of": "শরীরের অঙ্গ",
    "chin is": "চিবুক",
    "distances are": "দূরত্ব",
    "eyes are": "চোখ",
    "eye-lashes are": "চোখের পাপড়ি",
    "head is": "মাথা",
    "objects are": "বস্তুগুলি",
    "one leg is longer": "একটি পা বেশি লম্বা",
    "scrotum is swollen": "অণ্ডকোষ ফোলা",
    "tall": "লম্বা",
    "very": "খুব",
    "fancies he has": "কল্পনা করে তার আছে",
    "eternity": "অনন্তকাল",
    "that he was in": "যে সে তার মধ্যে ছিল",
    "excited": "উত্তেজিত",
    "executioner": "জল্লাদ",
    "visions of an": "জল্লাদের দৃশ্য",
    "existence": "অস্তিত্ব",
    "doubt if anything had": "কোনো কিছুর অস্তিত্ব আছে কি না সন্দেহ",
    "doubted his own": "নিজের অস্তিত্বেই সন্দেহ",
    "expanding": "প্রসারিত হওয়া",
    "thought passers-by were": "পথচারীদের তা-ই ভাবল",
    "experienced before": "আগেই ঘটেছে এমন",
    "thought everything had been": "ভাবল সবকিছুই আগে ঘটেছে",
    "falling out": "খসে পড়া",
    "diabolical": "শয়তানসুলভ",
    "crowd upon him": "তার উপর ভিড় করে",
    "distinguished people of": "বিশিষ্ট লোকজনের",
    "distorted day": "বিকৃত, দিনের বেলা",
    "elongated": "লম্বাটে",
    "it": "তা",
    "grows larger": "বড় হয়ে ওঠে",
    "hideous": "কুৎসিত",
    "ridiculous": "হাস্যকর",
    "ugly faces seem pleasing": "কুৎসিত মুখ মনোরম লাগে",
    "wherever he turns his eyes": "যেদিকেই চোখ ফেরায়",
    "or looking out from corners": "অথবা কোণ থেকে উঁকি দিচ্ছে",
    "fail": "ব্যর্থ হওয়া",
    "everything will": "সবকিছুই ব্যর্থ হবে",
    "as if things would": "যেন সব ব্যর্থ হবে",
    "falling forward": "সামনের দিকে পড়ে যাওয়া",
    "walls of room seem": "ঘরের দেয়াল যেন",
    "before epileptic fit": "মৃগীর আক্রমণের আগে",
    "walls": "দেয়াল",
    "that he is falling": "যে সে পড়ে যাচ্ছে",
    "family": "পরিবার",
    "does not belong to her own": "তার নিজের পরিবারের নয়",
    "fancy": "কল্পনা",
    "fighting": "মারামারি",
    "that people are": "যে লোকজন মারামারি করছে",
    "gigantic": "বিশালকায়",
    "hurled bottle at": "-এর দিকে বোতল ছুড়ল",
    "large black": "বড় কালো",
    "about to spring on him": "তার উপর ঝাঁপিয়ে পড়তে উদ্যত",
    "marching in the air": "বাতাসে সারি বেঁধে চলেছে",
    "evening while half asleep": "সন্ধ্যায় আধা-ঘুমন্ত অবস্থায়",
    "fingers cut off": "আঙুল কেটে ফেলা",
    "finger-nails seem as large a plates during drowsiness": "ঝিমুনির সময় নখগুলো থালার মতো বড় মনে হয়",
    "distant home": "দূরের বাড়ি",
    "every noise is a cry of fire": "প্রতিটি শব্দই আগুন-আগুন চিৎকার মনে হয়",
    "she thinks": "সে ভাবে",
    "and she trembles": "এবং সে কাঁপে",
    "head is surrounded by": "মাথা -দিয়ে ঘেরা",
})

SEG_EXT.update({
    "abdomen has fallen in": "পেট দেবে গেছে",
    "house on": "বাড়িতে আগুন",
    "neighbor's house on": "প্রতিবেশীর বাড়িতে আগুন",
    "waking in a fright": "আতঙ্কে জেগে ওঠা",
    "room is on": "ঘরে আগুন",
    "world is on": "পৃথিবীতে আগুন",
    "fishes": "মাছ",
    "flies": "মাছি",
    "fit": "খিঁচুনির আক্রমণ",
    "thinks she will have a fit and walks faster": "ভাবে তার খিঁচুনি হবে, তাই দ্রুত হাঁটে",
    "floating in air": "বাতাসে ভেসে থাকা",
    "suspended in": "-এ ঝুলে থাকা",
    "is not resting in": "-এ স্থির নয়",
    "ethereal surrounded by": "ঘিরে থাকা সূক্ষ্ম আবহ",
    "resisting passage": "চলাচলে বাধা দিচ্ছে",
    "flying": "উড়ে যাওয়া",
    "from a rock into dark abyss": "পাথর থেকে অন্ধকার গহ্বরে",
    "footsteps": "পায়ের শব্দ",
    "behind him": "তার পিছনে",
    "in next room": "পাশের ঘরে",
    "fortune": "সম্পদ",
    "that he was going to lose his": "যে সে তা হারাতে চলেছে",
    "everything appears": "সবকিছু মনে হয়",
    "fowls": "হাঁস-মুরগি",
    "thinks she is about to lose a": "ভাবে সে একজনকে হারাতে চলেছে",
    "has lost the affection of": "-এর স্নেহ হারিয়েছে",
    "met with an accident": "দুর্ঘটনায় পড়েছে",
    "offended": "মনে আঘাত পেয়েছে",
    "friendless": "বন্ধুহীন",
    "furniture": "আসবাবপত্র",
    "imagines it to be persons": "তাকে মানুষ বলে কল্পনা করে",
    "gallows": "ফাঁসিকাঠ",
    "vision of": "-এর দৃশ্য",
    "with fear of": "-এর ভয়সহ",
    "geese": "রাজহাঁস",
    "threw themselves into water": "জলে ঝাঁপ দিল",
    "thinking themselves to be": "নিজেদের তা-ই ভেবে",
    "general": "সেনাপতি",
    "giants": "দৈত্য",
    "giraffe": "জিরাফ",
    "imagines himself to be a": "নিজেকে তা-ই কল্পনা করে",
    "glass": "কাচ",
    "that she is made of": "যে সে তা দিয়ে তৈরি",
    "god": "ঈশ্বর",
    "is the object of god's vengeance": "ঈশ্বরের প্রতিশোধের লক্ষ্য",
    "that he is in communication with": "যে তার সঙ্গে তার যোগাযোগ আছে",
    "imagines he has a": "কল্পনা করে তার আছে",
    "has one which he cannot see over when sitting down": "এমন একটি আছে যে বসলে তার উপর দিয়ে দেখা যায় না",
    "goose": "রাজহাঁস",
    "grave": "কবর",
    "that he is in his": "যে সে তার নিজের কবরে",
    "great person": "মহান ব্যক্তি",
    "groans": "গোঙানি",
    "fancies he hears": "শুনছে বলে কল্পনা করে",
    "growling": "গরগর শব্দ",
    "as of a bear": "ভালুকের মতো",
    "hall": "বিশাল কক্ষ",
    "illusions of a gigantic hall": "প্রকাণ্ড কক্ষের মায়াদর্শন",
    "halves": "অর্ধাংশ",
    "left half does not belong to her": "বাম অর্ধেক তার নিজের নয়",
    "midnight vision of something taking her": "মধ্যরাতে কিছু একটা তাকে নিয়ে যাচ্ছে এমন দৃশ্য",
    "felt a delicate": "কোমল একটি হাত অনুভব করল",
    "smoothing her head": "তার মাথায় হাত বুলাচ্ছে",
    "of white": "সাদা রঙের",
    "outspread": "ছড়ানো",
    "coming toward face in the darkness": "অন্ধকারে মুখের দিকে এগিয়ে আসছে",
    "hanging": "ঝুলন্ত",
    "sees persons": "মানুষ দেখে",
    "three feet from the ground": "মাটি থেকে তিন ফুট উঁচুতে",
    "or standing high": "অথবা উঁচুতে দাঁড়িয়ে",
    "seems as if": "মনে হয় যেন",
    "happen": "ঘটা",
    "that something terrible is going to": "যে ভয়ানক কিছু ঘটতে চলেছে",
    "that he will never be": "যে সে কখনও হবে না",
    "in his own house": "নিজের বাড়িতে",
    "harlequin": "রঙ্গমঞ্চের ভাঁড়",
    "as if he were a": "যেন সে একজন",
    "hat is a pair of trousers which he tries to put on": "টুপিকে পাজামা ভেবে পরার চেষ্টা করে",
    "can lift it off": "তা তুলে ফেলতে পারে",
    "cold breeze blows on": "-এর উপর ঠান্ডা হাওয়া বইছে",
    "deceased acquaintances": "মৃত পরিচিতজন",
    "without bodies": "দেহহীন",
    "heavy": "ভারী",
    "his own seemed too": "নিজেরটি অতিরিক্ত মনে হলো",
    "seems too": "অতিরিক্ত মনে হয়",
    "heads": "মাথা",
    "make grimaces evening on closing eyes": "সন্ধ্যায় চোখ বুজলে মুখভঙ্গি করে",
    "monstrous": "দানবীয়",
    "on distant wall of room": "ঘরের দূরের দেয়ালে",
    "pendulum": "দোলক",
    "seems an inverted": "উল্টানো দোলকের মতো লাগে",
    "oscillating": "দুলতে থাকা",
    "sees friend's": "বন্ধুর মাথা দেখে",
    "stick out of a bottle": "বোতল থেকে বেরিয়ে আছে",
    "shaking the": "মাথা নাড়া",
    "thinks disease will break out of": "ভাবে রোগ তা ফেটে বেরিয়ে আসবে",
    "transparent and speckled brown": "স্বচ্ছ ও বাদামি ছোপযুক্ত",
    "two": "দুটি",
    "thinks she has": "ভাবে তার আছে",
    "he has ruined his": "সে তার সর্বনাশ করেছে",
    "hear": "শোনা",
    "he thinks he cannot": "ভাবে সে পারে না",
    "heart diseases": "হৃদরোগ",
    "is going to have": "-হতে চলেছে",
    "and die": "এবং মারা যাবে",
    "too large": "অতিরিক্ত বড়",
    "turning around": "ঘুরে যাওয়া",
    "has a furious": "প্রচণ্ড আছে",
    "radiating from epigastrium": "পাকস্থলীর মুখ থেকে ছড়ানো",
    "heaven": "স্বর্গ",
    "is in": "-এ আছে",
    "hell": "নরক",
    "at gate of": "-এর দ্বারে",
    "obliged to confess his sins": "পাপ স্বীকার করতে বাধ্য",
    "in shadows of": "-এর ছায়ায়",
    "suffers the torments of": "-এর যন্ত্রণা ভোগ করে",
    "without being able to explain": "ব্যাখ্যা করতে না পেরে",
    "help": "সাহায্য",
    "calling for": "-এর জন্য ডাকা",
    "herbs": "গাছগাছড়া",
    "gathering": "সংগ্রহ করা",
    "hole": "গর্ত",
    "appears like a frightful chasm": "ভয়ানক খাদের মতো দেখায়",
    "home": "বাড়ি",
    "thinks is at": "ভাবে সে বাড়িতেই আছে",
    "everything at": "বাড়ির সবকিছু",
    "as changed": "বদলে গেছে বলে",
    "think is away from": "ভাবে সে বাড়ি থেকে দূরে",
    "horrible": "ভয়ানক",
    "everything seems": "সবকিছু মনে হয়",
    "is on horseback": "ঘোড়ার পিঠে আছে",
    "house is full of people": "বাড়ি লোকে ভরা",
    "not in right place": "ঠিক জায়গায় নেই",
    "while walking in the street after headache": "মাথাব্যথার পর রাস্তায় হাঁটার সময়",
    "seems movable": "নড়ছে বলে মনে হয়",
    "surrounded": "ঘেরা",
    "houses on each side would approach and crush him": "দুপাশের বাড়ি এগিয়ে এসে তাকে চেপে ধরবে",
    "humility and lowness of others": "অন্যদের নম্রতা ও হীনতা",
    "while he is great": "আর সে নিজে মহান",
    "hunter": "শিকারি",
    "thinks he is a": "নিজেকে তা-ই ভাবে",
    "thinks he is not her": "ভাবে সে তার নয়",
    "errors of personal": "নিজের পরিচয় সম্পর্কে ভুল",
    "thinks she is some one else": "ভাবে সে অন্য কেউ",
    "dwells upon": "-নিয়েই পড়ে থাকে",
    "everchanging": "অনবরত বদলে যাওয়া",
    "past to present": "অতীত থেকে বর্তমানে",
    "while trying to sleep": "ঘুমানোর চেষ্টা করার সময়",
    "pleasant": "মনোরম",
    "rising out of the earth": "মাটি থেকে উঠে আসা",
    "all over": "সর্বত্র",
    "at his": "তার কাছে",
    "wall": "দেয়াল",
    "inanimate objects are persons": "জড়বস্তুকে মানুষ মনে হয়",
    "on entering house after a walk": "হাঁটা শেষে ঘরে ঢুকলে",
    "people seem mentally and physically": "মানুষকে মানসিক ও শারীরিকভাবে তেমন মনে হয়",
    "influence": "প্রভাব",
    "is under a powerful": "প্রবল প্রভাবের অধীনে",
    "is about to receive": "পেতে চলেছে",
    "is being injured": "আঘাত পাচ্ছে",
    "by his surroundings": "চারপাশের দ্বারা",
    "his fingers and toes are being cut off": "তার হাত ও পায়ের আঙুল কেটে ফেলা হচ্ছে",
    "inkstand": "কালির দোয়াত",
    "fancied he saw one on bed": "বিছানায় একটি দেখেছে বলে কল্পনা করল",
    "fancied he was one": "নিজেকে তা-ই কল্পনা করল",
    "insane": "উন্মাদ",
    "that she will become": "যে সে হয়ে যাবে",
    "that people think her": "যে লোকে তাকে তা-ই ভাবে",
    "insulted": "অপমানিত",
    "iodine": "আয়োডিন",
    "illusions of fumes of": "-এর ধোঁয়ার মায়াদর্শন",
    "island": "দ্বীপ",
    "is on a distant": "দূরের একটিতে আছে",
    "journey": "যাত্রা",
    "that he is on a": "যে সে যাত্রায় আছে",
    "juggler": "ভোজবাজিকর",
    "thinks himself a": "নিজেকে তা-ই ভাবে",
    "jumped up on the ground before her": "তার সামনে মাটি থেকে লাফিয়ে উঠল",
    "all sorts of things": "নানারকম জিনিস",
    "that he walks on": "যে সে তার উপর দিয়ে হাঁটছে",
    "knowledge": "জ্ঞান",
    "thought he possessed infinite": "ভাবল তার অসীম জ্ঞান আছে",
    "pretends to be in": "-এ আছে বলে ভান করে",
    "or thinks she has pains": "অথবা ভাবে তার ব্যথা আছে",
    "people seemed too": "লোকজনকে অতিরিক্ত মনে হলো",
    "during vertigo": "মাথা ঘোরার সময়",
    "parts of body seem too": "শরীরের অঙ্গ অতিরিক্ত মনে হয়",
    "self seemed too": "নিজেকে অতিরিক্ত মনে হলো",
    "on entering the house after walking": "হাঁটা শেষে ঘরে ঢোকার সময়",
    "surroundings seemed": "চারপাশ মনে হলো",
    "laughed at": "উপহাসের পাত্র",
    "imagines she is": "কল্পনা করে সে তা-ই",
    "tin case filled with stair rods": "সিঁড়ির শিক ভরা টিনের বাক্স",
    "conversing": "কথোপকথন করছে",
    "cut off": "কেটে ফেলা",
    "don't belong to her": "তার নিজের নয়",
    "three": "তিনটি",
    "lie": "মিথ্যা",
    "thinks all she said is a lie": "ভাবে সে যা বলেছে সবই মিথ্যা",
    "life": "জীবন",
    "symbols of": "-এর প্রতীক",
    "all past events revolve rapidly on wheels": "অতীতের সব ঘটনা চাকার মতো দ্রুত ঘুরতে থাকে",
    "is threatened": "বিপন্ন",
    "on falling to sleep": "ঘুমিয়ে পড়ার সময়",
    "thinks there is too much in room": "ভাবে ঘরে অতিরিক্ত আলো",
    "is swollen": "ফুলে গেছে",
    "living under ordinary relations": "স্বাভাবিক সম্পর্কের মধ্যে বাস করা",
    "thinks is not": "ভাবে তা নয়",
    "locomotive": "রেল-ইঞ্জিন",
    "imagines himself to be": "নিজেকে তা-ই কল্পনা করে",
    "longer": "দীর্ঘতর",
    "things seems": "জিনিসগুলি মনে হয়",
    "chin seems too long": "চিবুক অতিরিক্ত লম্বা মনে হয়",
    "looked down upon": "হেয় করা হচ্ছে",
    "one leg is long": "একটি পা লম্বা",
    "looking at her": "তার দিকে তাকিয়ে আছে",
    "fancies herself": "নিজেকে কল্পনা করে",
    "lying near him": "তার পাশে শুয়ে আছে",
    "fancies some one is": "কল্পনা করে কেউ আছে",
    "crosswise": "আড়াআড়িভাবে",
    "machine": "যন্ত্র",
    "thinks he is working a": "ভাবে সে একটি চালাচ্ছে",
    "maelstrom": "ঘূর্ণিস্রোত",
    "seemed carried down a psychical": "মানসিক ঘূর্ণিস্রোতে ভেসে যাচ্ছে মনে হলো",
    "magician": "জাদুকর",
    "man in the room intending to perforate his throat with a gimlet": "ঘরে একজন লোক তুরপুন দিয়ে তার গলা ফুটো করতে চাইছে",
    "does all the things he does": "সে যা করে সবই করে",
    "old men with long beards and distorted faces": "লম্বা দাড়ি ও বিকৃত মুখের বৃদ্ধরা",
    "muffled": "চাপা",
    "starts from the wall when walking in the streets": "রাস্তায় হাঁটার সময় দেয়াল থেকে বেরিয়ে আসে",
    "naked man in bed": "বিছানায় নগ্ন পুরুষ",
    "thinks men are on the bed at night": "ভাবে রাতে বিছানায় লোক আছে",
    "the same man walking after him that he sees walking before him": "যাকে সামনে হাঁটতে দেখে সে-ই তার পিছনেও হাঁটছে",
    "who hung himself": "যে ফাঁস নিয়েছিল",
    "saw": "দেখল",
    "mandarin": "চীনা রাজকর্মচারী",
    "mistook friend for a": "বন্ধুকে তা-ই ভুল করল",
    "marble statue": "মর্মরমূর্তি",
    "felt as if he were": "নিজেকে তা-ই মনে হলো",
    "marriage": "বিবাহ",
    "must dissolve": "ভেঙে দিতেই হবে",
    "married": "বিবাহিত",
    "masks": "মুখোশ",
    "while half awake at night": "রাতে আধা-জাগ্রত অবস্থায়",
    "melting away": "গলে মিলিয়ে যাওয়া",
    "worse from change": "পরিবর্তনে বৃদ্ধি",
    "better in recumbent position": "শুয়ে থাকলে উপশম",
    "mesmerized": "সম্মোহিত",
    "by her absent pastor": "তার অনুপস্থিত যাজক দ্বারা",
    "mind and body separated": "মন ও দেহ আলাদা হয়ে গেছে",
    "inconsolable over fancied": "কল্পিত ক্ষতিতে অসান্ত্বনীয়",
    "money": "টাকা",
    "as if counting": "যেন গুনছে",
    "sewed up in clothing": "কাপড়ে সেলাই করে রাখা",
    "mountain": "পাহাড়",
    "thought himself to be on the ridge of a": "নিজেকে পাহাড়ের চূড়ায় ভাবল",
    "fancied living things were creeping into": "কল্পনা করল জীবন্ত কিছু ঢুকে পড়ছে",
    "hears things that are high up near him out of sight": "দৃষ্টির বাইরে উঁচুতে থাকা জিনিসের শব্দ শোনে",
    "murder": "খুন",
    "thinks she is about to": "ভাবে সে করতে চলেছে",
    "her husband and child": "তার স্বামী ও সন্তানকে",
    "that she will murder her family with a hatchet": "যে সে কুড়াল দিয়ে পরিবারকে খুন করবে",
    "that he has to": "যে তাকে করতেই হবে",
    "some one": "কাউকে",
    "conspiring to murder him": "তাকে খুনের ষড়যন্ত্র",
    "sees some one": "কাউকে দেখে",
    "that every one around him is a murderer": "যে তার চারপাশের সবাই খুনি",
    "that he was killed": "যে তাকে মেরে ফেলা হয়েছে",
    "roasted and eaten": "পুড়িয়ে খেয়ে ফেলা হয়েছে",
    "thinks persons were bribed to murder him": "ভাবে তাকে খুন করতে লোককে ঘুষ দেওয়া হয়েছে",
    "thought her mother had been": "ভাবল তার মাকে তা-ই করা হয়েছে",
    "mushrooms": "ব্যাঙের ছাতা",
    "fancies he is commanded to fall on his knees and confess his sins and rip up his bowels by a": "কল্পনা করে তাকে হাঁটু গেড়ে পাপ স্বীকার করতে ও পেট চিরে ফেলতে আদেশ করা হয়েছে",
    "hears the music heard in the day": "দিনে শোনা গান আবার শোনে",
    "delightful": "মনোমুগ্ধকর",
    "sweetest and sublimest melody": "মধুরতম ও উদাত্ততম সুর",
    "unearthly": "অলৌকিক",
    "mutilated bodies": "বিকৃত মৃতদেহ",
    "mystery": "রহস্য",
    "everything around seemed a terrifying": "চারপাশের সবকিছু ভয়ানক রহস্য মনে হলো",
    "naked": "নগ্ন",
    "thinks is": "ভাবে সে তা-ই",
    "narrow": "সরু",
    "everything seems too": "সবকিছু অতিরিক্ত মনে হয়",
    "neck is too large": "ঘাড় অতিরিক্ত বড়",
    "neglected his duty": "কর্তব্যে অবহেলা করেছে",
    "that he has": "যে সে করেছে",
    "new": "নতুন",
    "newspapers": "সংবাদপত্র",
    "thinks he sees": "ভাবে সে দেখছে",
    "noble": "অভিজাত",
    "clattering above the bed when falling asleep": "ঘুমিয়ে পড়ার সময় বিছানার উপরে খটখট শব্দ",
    "knocking under bed": "বিছানার নিচে টোকার শব্দ",
    "of shout": "চিৎকারের",
    "vehicles": "গাড়ি",
    "has a transparent": "স্বচ্ছ একটি আছে",
    "has some one else's": "অন্য কারও আছে",
    "takes people by": "মানুষকে নাক ধরে টানে",
    "numeral": "সংখ্যা",
    "appeared nine inches long": "নয় ইঞ্চি লম্বা দেখাল",
    "better lying on other side": "অন্য কাতে শুলে উপশম",
    "nursing her child": "সন্তানকে দুধ খাওয়ানো",
    "that she was": "যে সে ছিল",
    "appear different": "আলাদা দেখায়",
    "bright from": "-এর কারণে উজ্জ্বল",
    "crooked": "বাঁকা",
    "glittering": "ঝলমলে",
    "numerous": "অসংখ্য",
    "in room": "ঘরে",
    "sometimes thick": "কখনও মোটা",
    "sometimes thin": "কখনও সরু",
    "on closing eye": "চোখ বুজলে",
    "in slumber": "তন্দ্রার মধ্যে",
    "obscene": "অশ্লীল",
    "actions of which she has not been guilty": "যে কাজ সে করেনি",
    "accuses herself": "নিজেকেই দোষ দেয়",
    "offended people": "যাদের সে আঘাত দিয়েছে",
    "officer": "সেনাধ্যক্ষ",
    "that he is an": "যে সে একজন",
    "old men": "বৃদ্ধরা",
    "old rags are as fine as silk": "পুরনো ছেঁড়া কাপড় রেশমের মতো মিহি",
    "paradise": "স্বর্গোদ্যান",
    "thought he saw": "ভাবল সে দেখল",
    "past": "অতীত",
    "of events long": "বহু আগেকার ঘটনার",
    "as if chasing": "যেন তাড়া করছে",
    "some one is": "কেউ একজন",
    "when walking in the dark": "অন্ধকারে হাঁটার সময়",
    "beside him": "তার পাশে",
    "doing as he does": "সে যা করে তা-ই করছে",
    "converses": "কথা বলে",
    "with absent": "অনুপস্থিতদের সঙ্গে",
    "entering the house at night": "রাতে ঘরে ঢুকছে",
    "persons are looking at him": "লোকজন তার দিকে তাকিয়ে আছে",
    "persecuted": "নির্যাতিত",
    "person": "ব্যক্তি",
    "that something hanging over chair is a": "চেয়ারে ঝোলানো কিছুকে মানুষ মনে হয়",
    "sitting there": "সেখানে বসে আছে",
    "thinks she is some other": "ভাবে সে অন্য কেউ",
    "another person in the room": "ঘরে আরেকজন মানুষ",
    "pins": "পিন",
    "place": "জায়গা",
    "that he cannot pass a certain": "যে সে একটি নির্দিষ্ট জায়গা পার হতে পারে না",
    "at night on waking thought to find himself in strange and solitary": "রাতে জেগে নিজেকে অচেনা নির্জন জায়গায় ভাবল",
    "of being in two": "দুই জায়গায় থাকার",
    "at the same time": "একই সময়ে",
    "wrong": "ভুল",
    "pleasing": "মনোরম",
    "after sleep": "ঘুমের পর",
    "poisoned": "বিষ প্রয়োগ করা",
    "thought he had been": "ভাবল তাকে তা করা হয়েছে",
    "that he was about to be": "যে তাকে করা হতে চলেছে",
    "medicine being": "ওষুধে বিষ",
    "policeman come into house": "পুলিশ বাড়িতে এসেছে",
    "that physician is a": "যে চিকিৎসক একজন পুলিশ",
    "poor": "দরিদ্র",
    "possessed": "ভর করা",
    "thought herself": "নিজেকে তা-ই ভাবল",
    "prince": "রাজপুত্র",
    "proud": "গর্বিত",
    "murderers": "খুনি",
    "police": "পুলিশ",
    "soldiers": "সৈন্য",
    "some horrid thing": "ভয়ানক কিছু",
    "queen": "রানি",
    "rabbits": "খরগোশ",
    "railway train": "রেলগাড়ি",
    "thought he was obliged to go off by": "ভাবল তাকে তাতে চলে যেতে হবে",
    "rain": "বৃষ্টি",
    "from having wet cloth on head": "মাথায় ভেজা কাপড় থাকায়",
    "thought he had been out in": "ভাবল সে বৃষ্টিতে বাইরে ছিল",
    "rank": "উচ্চপদ",
    "thinks himself a person of": "নিজেকে উচ্চপদস্থ ভাবে",
    "of all colors": "সব রঙের",
    "running across the room": "ঘরের এপাশ-ওপাশ ছুটছে",
    "reading after her": "তার পিছু পিছু পড়ছে",
    "someone is": "কেউ একজন",
    "which makes her read the faster": "যা তাকে আরও দ্রুত পড়ায়",
    "reproach": "তিরস্কার",
    "has neglected duty and deserves": "কর্তব্যে অবহেলা করেছে ও তিরস্কার প্রাপ্য",
    "repudiated by relatives": "আত্মীয়দের দ্বারা প্রত্যাখ্যাত",
    "repulsive fantastic imaginations": "বীভৎস উদ্ভট কল্পনা",
    "riding on an ox": "বলদের পিঠে চড়া",
    "a horse": "একটি ঘোড়া",
    "does nothing": "কিছুই করে না",
    "roaming in the fields": "মাঠে ঘুরে বেড়ানো",
    "garden": "বাগান",
    "like the foam of a troubled sea": "উত্তাল সমুদ্রের ফেনার মতো",
    "sees people in": "-এ মানুষ দেখে",
    "at bedside": "বিছানার পাশে",
    "that the walls will crush him": "যে দেয়াল তাকে চেপে মারবে",
    "walls of": "-এর দেয়াল",
    "seem gliding together": "একসঙ্গে সরে আসছে মনে হয়",
    "sees horrible things on the": "-এর উপর ভয়ানক জিনিস দেখে",
    "thought he was a huge": "নিজেকে বিশাল একটি ভাবল",
    "darting up and down": "উপর-নিচ ছুটে বেড়াচ্ছে",
    "scorpions": "বিছা",
    "scratching on linen or similar substance": "কাপড় বা তেমন কিছুতে আঁচড়ের শব্দ",
    "thought some one was": "ভাবল কেউ একজন",
    "thinks his": "ভাবে তার",
})

SEG_EXT.update({
    "seasick": "সমুদ্রপীড়িত",
    "thinks some one else sees for him": "ভাবে অন্য কেউ তার হয়ে দেখছে",
    "seized": "চেপে ধরা হয়েছে",
    "sensations": "অনুভূতি",
    "misrepresents his": "নিজের অনুভূতি ভুলভাবে বলে",
    "separated from the world": "পৃথিবী থেকে বিচ্ছিন্ন",
    "serpent": "সাপ",
    "a crimson": "একটি টকটকে লাল",
    "fastening on his neck": "তার গলা জড়িয়ে ধরছে",
    "servants": "চাকরবাকর",
    "thinks he must get rid of": "ভাবে তাদের বিদায় করতেই হবে",
    "imagines herself to be": "নিজেকে তা-ই কল্পনা করে",
    "sheep": "ভেড়া",
    "ship": "জাহাজ",
    "thinks they are on board of": "ভাবে তারা জাহাজে আছে",
    "in a storm": "ঝড়ের মধ্যে",
    "shoot": "গুলি করা",
    "with a cane": "লাঠি দিয়ে",
    "shopping with her sister": "বোনের সঙ্গে কেনাকাটা",
    "thinks people are looking over his": "ভাবে লোকে তার কাঁধের উপর দিয়ে দেখছে",
    "shouting": "চিৎকার",
    "fancies himself to be": "নিজেকে তা-ই কল্পনা করে",
    "sick": "অসুস্থ",
    "that he was going to be": "যে সে হতে চলেছে",
    "a beloved friend is sick and dying": "প্রিয় বন্ধু অসুস্থ ও মরণাপন্ন",
    "members of the family are": "পরিবারের সদস্যরা অসুস্থ",
    "two sick people were in bed": "বিছানায় দুজন অসুস্থ লোক ছিল",
    "one of whom got well and the other did not": "যাদের একজন সুস্থ হলো, অন্যজন হলো না",
    "imagined himself alive on one side and buried on the other": "কল্পনা করল একদিকে সে জীবিত, অন্যদিকে সমাধিস্থ",
    "that she did not own her left": "যে বাম দিকটি তার নিজের নয়",
    "sight and hearing": "দৃষ্টি ও শ্রবণ",
    "fancied himself to be": "নিজেকে তা-ই কল্পনা করল",
    "skeletons": "কঙ্কাল",
    "insists that he was": "জোর দিয়ে বলে সে তা-ই ছিল",
    "things appear": "জিনিসগুলি দেখায়",
    "sensation of being smaller": "ছোট হয়ে যাওয়ার অনুভূতি",
    "things grow smaller": "জিনিস ছোট হয়ে যায়",
    "snakes in and around her": "তার ভিতরে ও চারপাশে সাপ",
    "soda water": "সোডার জল",
    "thinks he is a bottle of": "নিজেকে তার একটি বোতল ভাবে",
    "sold": "বিক্রি করা",
    "as if would be": "যেন হয়ে যাবে",
    "his bed": "তার বিছানা",
    "some one has": "কেউ একজন করেছে",
    "cutting him down": "তাকে কেটে ফেলছে",
    "better on getting cool": "ঠান্ডা হলে উপশম",
    "march silently past": "নিঃশব্দে সারি বেঁধে পাশ দিয়ে যায়",
    "on his bed": "তার বিছানায়",
    "something else": "অন্য কিছু",
    "appeared as if": "মনে হলো যেন",
    "soot": "কালি, ঝুল",
    "shower of": "-এর বর্ষণ",
    "fell on him": "তার উপর পড়ল",
    "sorrow": "দুঃখ",
    "thinks everyone he meets has a secret": "ভাবে যার সঙ্গে দেখা হয় তারই গোপন দুঃখ আছে",
    "soul": "আত্মা",
    "fancied body was too small for": "কল্পনা করল দেহটি আত্মার জন্য বড্ড ছোট",
    "or that it was separated from": "অথবা তা বিচ্ছিন্ন হয়ে গেছে",
    "sounds": "শব্দ",
    "listens to imaginary": "কাল্পনিক শব্দ শোনে",
    "space": "শূন্যস্থান",
    "fancied he was carried into": "কল্পনা করল তাকে শূন্যে নিয়ে যাওয়া হয়েছে",
    "expansion of": "-এর প্রসারণ",
    "that there is empty": "যে ফাঁকা জায়গা আছে",
    "between brain and skull": "মস্তিষ্ক ও খুলির মাঝে",
    "continues to enlarge until it disappears": "বড় হতে হতে মিলিয়ে যায়",
    "feels as if spectre would appear": "মনে হয় যেন প্রেতমূর্তি দেখা দেবে",
    "black forms when dreaming": "স্বপ্নে কালো অবয়ব",
    "clutches": "খামচে ধরে",
    "death of": "-এর মৃত্যু",
    "as a gigantic black skeleton": "বিশাল কালো কঙ্কালের রূপে",
    "hovering in the air": "বাতাসে ভেসে থাকা",
    "pursued by": "-দ্বারা তাড়িত",
    "sphere": "গোলক",
    "thought himself a": "নিজেকে তা-ই ভাবল",
    "spiders": "মাকড়সা",
    "spinal column a barometer": "মেরুদণ্ড যেন ব্যারোমিটার",
    "spirit": "আত্মা",
    "his body is": "তার দেহটাই",
    "squares": "চতুষ্কোণ চত্বর",
    "fancies of a colossal surrounded by houses a hundred stories high": "শততলা বাড়িঘেরা প্রকাণ্ড চত্বরের কল্পনা",
    "that he had": "যে তার ছিল",
    "a person who passed him on the street": "রাস্তায় পাশ কাটিয়ে যাওয়া একজন",
    "saw in his plate": "নিজের থালায় দেখল",
    "starve": "অনাহারে থাকা",
    "family will": "পরিবার অনাহারে মরবে",
    "he must": "তাকে তা করতেই হবে",
    "thinks has corrosion of": "ভাবে তা ক্ষয়ে যাচ্ছে",
    "stove for a tree": "চুলাকে গাছ ভাবা",
    "familiar things seem": "চেনা জিনিস মনে হয়",
    "places seemed": "জায়গাগুলি মনে হলো",
    "headache after": "-এর পর মাথাব্যথা",
    "land": "দেশ",
    "as if in a": "যেন একটির মধ্যে",
    "notions": "ধারণা",
    "her own seemed": "তার নিজেরটাই মনে হলো",
    "strangers seemed to be in the room": "ঘরে অপরিচিত লোক আছে মনে হলো",
    "about her while knitting": "বোনার সময় তার চারপাশে",
    "control of": "-এর নিয়ন্ত্রণ",
    "friends appear as": "বন্ধুদের তেমন দেখায়",
    "looking over shoulder": "কাঁধের উপর দিয়ে তাকাচ্ছে",
    "succeed": "সফল হওয়া",
    "that he cannot": "যে সে পারে না",
    "does everything wrong": "সবকিছুই ভুল করে",
    "superhuman": "অতিমানবীয়",
    "control": "নিয়ন্ত্রণ",
    "superiority": "শ্রেষ্ঠত্ব",
    "surrounded by friends": "বন্ধুদের দ্বারা পরিবেষ্টিত",
    "surroundings": "চারপাশ",
    "capacious": "প্রশস্ত",
    "swimming": "সাঁতার কাটা",
    "swine": "শূকর",
    "thinks men are": "ভাবে মানুষগুলি তা-ই",
    "sword hanging over head": "মাথার উপর ঝোলানো তলোয়ার",
    "as with dead people": "যেন মৃত মানুষের সঙ্গে",
    "of persons as though near": "যেন কাছেই মানুষ আছে",
    "about midnight": "মধ্যরাতের দিকে",
    "with spirits": "আত্মাদের সঙ্গে",
    "fancies herself very": "নিজেকে খুবই তা-ই কল্পনা করে",
    "had grown while walking": "হাঁটতে হাঁটতে বেড়ে গেছে",
    "things grow taller": "জিনিস লম্বা হয়ে যায়",
    "thieves": "চোর",
    "after a dream": "স্বপ্নের পর",
    "and will not believe the contrary until search is made": "খুঁজে না দেখা পর্যন্ত উল্টোটা বিশ্বাস করে না",
    "dream of robbers is frightened on waking and thinks dream is true": "ডাকাতের স্বপ্ন দেখে জেগে ভয় পায় ও স্বপ্নকে সত্য ভাবে",
    "that he has been accused of robbing": "যে তার বিরুদ্ধে চুরির অভিযোগ উঠেছে",
    "that house and space under bed are full of": "যে বাড়ি ও বিছানার নিচ চোরে ভরা",
    "is getting": "হয়ে যাচ্ছে",
    "body is": "শরীর",
    "three persons": "তিনজন মানুষ",
    "someone with ice cold hands took her by the": "বরফ-ঠান্ডা হাতে কেউ তাকে ধরল",
    "exaggeration of": "-এর অতিরঞ্জন",
    "seems earlier": "আগের মনে হয়",
    "toes cut off": "পায়ের আঙুল কেটে ফেলা",
    "tongue made of wood": "জিহ্বা কাঠের তৈরি",
    "pulling out": "টেনে বের করা",
    "seems to reach the clouds when going to sleep": "ঘুমাতে গেলে মেঘ ছুঁয়ে ফেলে বলে মনে হয়",
    "tormented": "যন্ত্রণাগ্রস্ত",
    "touching everything": "সবকিছু ছুঁয়ে দেখা",
    "toys": "খেলনা",
    "fancied himself playing with": "নিজেকে তা নিয়ে খেলতে দেখল",
    "object seemed as attractive as": "বস্তুটিকে খেলনার মতো আকর্ষণীয় মনে হলো",
    "transferred to another room": "অন্য ঘরে সরিয়ে নেওয়া",
    "to another world": "অন্য জগতে",
    "seemed to be": "-বলে মনে হলো",
    "head and nose are": "মাথা ও নাক",
    "travelling": "ভ্রমণ",
    "through worlds": "নানা জগতের মধ্য দিয়ে",
    "trees seem to be people in fantastic costume": "গাছগুলিকে উদ্ভট পোশাকে মানুষ মনে হয়",
    "while riding": "গাড়িতে চড়ার সময়",
    "of everything on him": "তার গায়ের সবকিছুর",
    "when only half awake": "আধা-জাগ্রত অবস্থায়",
    "troubles": "দুর্ভোগ",
    "broods over imaginary": "কল্পিত দুর্ভোগ নিয়ে গুমরায়",
    "turtles": "কচ্ছপ",
    "sees large": "বড় দেখে",
    "typhoid fever": "টাইফয়েড জ্বর",
    "thought": "ভাবল",
    "he would have": "তার হবে",
    "unfortunate": "দুর্ভাগা",
    "unpleasant": "অপ্রীতিকর",
    "distinct from surrounding objects": "চারপাশের জিনিস থেকে আলাদা",
    "unreal": "অবাস্তব",
    "unseen": "অদৃশ্য",
    "thing": "জিনিস",
    "living things creep into at night": "রাতে জীবন্ত কিছু ঢুকে পড়ে",
    "vanish": "মিলিয়ে যাওয়া",
    "seems as if everything would": "মনে হয় যেন সবকিছু মিলিয়ে যাবে",
    "vegetable existence": "উদ্ভিদের মতো জীবন",
    "thinks he is leading a": "ভাবে সে তেমন জীবন কাটাচ্ছে",
    "thinks he is selling green": "ভাবে সে সবুজ শাকসবজি বেচছে",
    "vengeance": "প্রতিশোধ",
    "thinks he is singled out for divine": "ভাবে ঈশ্বরের প্রতিশোধের জন্য তাকেই বেছে নেওয়া হয়েছে",
    "vermin": "পোকামাকড়",
    "sees crawl about": "হামাগুড়ি দিতে দেখে",
    "his bed is covered with": "তার বিছানা তাতে ভরা",
    "vexations": "বিরক্তি",
    "and offences": "ও অপমান",
    "virgin Mary": "কুমারী মেরি",
    "clouds of colors": "রঙের মেঘ",
    "grandeur": "জাঁকজমক",
    "of magnificent": "মহিমান্বিত",
    "in the dark": "অন্ধকারে",
    "imaginary power": "কাল্পনিক ক্ষমতা",
    "monsters": "দানব",
    "on falling asleep and on waking": "ঘুমিয়ে পড়ার সময় ও জেগে ওঠার সময়",
    "rats and strange objects": "ইঁদুর ও অদ্ভুত জিনিস",
    "wonderful": "বিস্ময়কর",
    "ceases when listening intently": "মন দিয়ে শুনলে থেমে যায়",
    "calling his name": "তার নাম ধরে ডাকছে",
    "confused": "অস্পষ্ট, গোলমেলে",
    "swallowing or walking in open air": "গিলতে গেলে বা খোলা বাতাসে হাঁটলে",
    "dead people": "মৃত মানুষ",
    "that he must follow": "যে তাকে অনুসরণ করতেই হবে",
    "his own": "তার নিজের",
    "sounds strange and seems to reverberate like thunder": "অদ্ভুত শোনায় ও বজ্রের মতো প্রতিধ্বনিত হয়",
    "in his abdomen": "তার পেটে",
    "vow": "ব্রত",
    "that she is breaking her": "যে সে তা ভাঙছে",
    "some one walks beside him": "কেউ তার পাশে হাঁটে",
    "he sees the same one walking after him that he sees walking before him": "যাকে সামনে হাঁটতে দেখে সে-ই তার পিছনেও হাঁটে",
    "is surrounded by high": "উঁচু দেয়ালে ঘেরা",
    "want": "অভাব",
    "fancied that he would come to": "কল্পনা করল সে অভাবে পড়বে",
    "that they had come to": "যে তারা অভাবে পড়েছে",
    "thinks he has": "ভাবে তার আছে",
    "watched": "নজরে রাখা হচ্ছে",
    "that she is being": "যে তাকে -করা হচ্ছে",
    "of disasters by": "-জনিত বিপর্যয়ের",
    "sees flowing": "বয়ে যেতে দেখে",
    "spoonful": "চামচভর্তি",
    "a": "একটি",
    "seems like a lake": "হ্রদের মতো মনে হয়",
    "when drinking": "পান করার সময়",
    "thought it delicious nectar": "তাকে সুস্বাদু অমৃত মনে করল",
    "wealth": "ঐশ্বর্য",
    "imaginations of": "-এর কল্পনা",
    "has no": "-নেই",
    "wife is faithless": "স্ত্রী অবিশ্বস্ত",
    "will run away from him": "তাকে ছেড়ে পালাবে",
    "wind sighing in chimney sounded like the hum of a vast wheel": "চিমনিতে হাওয়ার শব্দ বিশাল চাকার গুঞ্জনের মতো শোনাল",
    "and reverberated like a peal of thunder on a grand organ": "এবং বিশাল অর্গানে বজ্রনাদের মতো প্রতিধ্বনিত হলো",
    "wires": "তার",
    "is caught in": "-এ আটকে গেছে",
    "wolves": "নেকড়ে",
    "fancies his mother's house is invaded by lewd": "কল্পনা করে তার মায়ের বাড়িতে লম্পটরা ঢুকে পড়েছে",
    "evil": "অশুভ",
    "and will injure his soul": "এবং তার আত্মার ক্ষতি করবে",
    "illusions of old and wrinkled": "বৃদ্ধ ও কুঁচকানো মুখের মায়াদর্শন",
    "wood": "কাঠ",
    "is hard at": "কঠোর পরিশ্রমে ব্যস্ত",
    "is hindered at": "কাজে বাধা পাচ্ছে",
    "will do him harm": "তার ক্ষতি করবে",
    "imagined vomitus to be a bunch of": "বমিকে একগুচ্ছ কীট বলে কল্পনা করল",
    "imagines he is covered with": "কল্পনা করে সে তাতে ঢাকা",
    "wretched": "হতভাগ্য",
    "thinks she looks": "ভাবে তাকে তেমন দেখাচ্ছে",
    "when looking in a mirror": "আয়নায় তাকালে",
    "fancies he has done": "কল্পনা করে সে করেছে",
    "has suffered": "ভোগ করেছে",
    "more than she needs": "প্রয়োজনের চেয়ে বেশি",
    "itching of the skin": "ত্বকের চুলকানি",
    "in the stomach": "পাকস্থলীতে",
    "recovery": "আরোগ্য",
    "religious (of salvation etc.)": "ধর্মীয় (পরিত্রাণ ইত্যাদি নিয়ে)",
    "alternating with sexual excitement": "যৌন উত্তেজনার সঙ্গে পর্যায়ক্রমে",
    "suppressed menses": "রুদ্ধ ঋতুস্রাব",
    "social position": "সামাজিক অবস্থান",
    "Destructiveness": "ধ্বংসপ্রবণতা",
    "of clothes": "কাপড়ের",
    "cuts them up": "সেগুলি কেটে ফেলে",
    "cunning": "ধূর্ত",
    "Dictatorial": "হুকুমবাজ",
    "Dipsomania": "মদ্যপানের দুর্নিবার নেশা",
    "drinking on the sly": "লুকিয়ে মদ খাওয়া",
    "Disconcerted": "হতভম্ব",
    "displeased": "অসন্তুষ্ট",
    "dissatisfied": "অতৃপ্ত",
    "inanimate objects": "জড়বস্তু",
    "rainy weather": "বৃষ্টির আবহাওয়া",
    "alternating with haughtiness": "অহংকারের সঙ্গে পর্যায়ক্রমে",
    "Disgust": "ঘৃণা",
    "Disobedience": "অবাধ্যতা",
    "Distance": "দূরত্ব",
    "inaccurate judge of": "-এর ভুল আন্দাজ",
    "exaggerated": "অতিরঞ্জিত",
    "averse to being": "-হতে অনিচ্ছুক",
    "Doubtful": "সংশয়পূর্ণ",
    "soul's welfare": "আত্মার মঙ্গল",
    "about the poetical": "কাব্যিক বিষয়ে",
    "sluggishness": "মন্থরতা",
    "difficulty of thinking and comprehending": "ভাবতে ও বুঝতে অসুবিধা",
    "alternating with hilarity": "প্রফুল্লতার সঙ্গে পর্যায়ক্রমে",
    "copious flow of urine amel.": "প্রচুর প্রস্রাবে উপশম",
    "could not think of her condition": "নিজের অবস্থার কথা ভাবতে পারল না",
    "damp air": "স্যাঁতসেঁতে বাতাস",
    "gas light": "গ্যাসের আলো",
    "after injurious effects of": "-এর ক্ষতিকর প্রভাবের পর",
    "injuries of head": "মাথার আঘাত",
    "news": "খবর",
    "from disagreeable": "অপ্রীতিকর খবরে",
    "after sound": "শব্দের পর",
    "think long": "দীর্ঘক্ষণ ভাবা",
    "understands questions only after repetition": "বারবার বললে তবেই প্রশ্ন বোঝে",
    "Dwells on past disagreeable occurrences": "অতীতের অপ্রীতিকর ঘটনা নিয়ে পড়ে থাকা",
    "recalls old grievances": "পুরনো ক্ষোভ মনে করে",
    "Eat": "খাওয়া",
    "Eccentricity": "খামখেয়ালিপনা",
    "walking in moonlight": "জ্যোৎস্নায় হাঁটা",
    "alternating with sadness": "বিষণ্নতার সঙ্গে পর্যায়ক্রমে",
    "amorous": "কামাসক্ত",
    "Egotism": "আত্মম্ভরিতা",
    "Embarrassed": "অপ্রস্তুত",
    "Embraces": "আলিঙ্গন করে",
    "companions": "সঙ্গীদের",
    "anything": "যেকোনো কিছু",
    "in morning worse in open air": "সকালে, খোলা বাতাসে বৃদ্ধি",
    "Ennui": "একঘেয়েমি",
    "entertainment amel.": "আমোদে উপশম",
    "Envy": "ঈর্ষা",
    "Escape": "পালানো",
    "attempts to": "-চেষ্টা করে",
    "from her family": "তার পরিবারের কাছ থেকে",
    "is restrained with difficulty": "কষ্টে সামলানো যায়",
    "spring up suddenly from bed": "হঠাৎ বিছানা থেকে লাফিয়ে ওঠা",
    "to run away": "পালিয়ে যেতে",
    "change beds": "বিছানা বদলানো",
    "wants to visit his daughter": "মেয়ের কাছে যেতে চায়",
    "Estranged": "সম্পর্কচ্ছেদ",
    "from her": "তার কাছ থেকে",
    "flies from her own children": "নিজের সন্তানদের কাছ থেকে পালায়",
    "wife": "স্ত্রী",
    "from his": "তার কাছ থেকে",
    "excitable": "সহজে উত্তেজিত",
    "thinking of the things others have done to displease her": "অন্যরা যা করে তাকে অসন্তুষ্ট করেছে তা ভেবে",
    "alternates with convulsions": "আক্ষেপের সঙ্গে পর্যায়ক্রমে",
    "ameliorates": "উপশম হয়",
    "anticipating events": "আসন্ন ঘটনার আশঙ্কায়",
    "emotional": "আবেগজনিত",
    "horrible things": "ভয়ানক কিছু",
    "after hearing": "শোনার পর",
    "hurried": "তাড়াহুড়ো",
    "mental work": "মানসিক পরিশ্রম",
    "stammers when talking to strangers": "অপরিচিতদের সঙ্গে কথা বলতে তোতলায়",
    "swallows continually while talking": "কথা বলার সময় বারবার ঢোঁক গেলে",
    "water poured out": "জল ঢালা হলে",
    "working": "কাজ করা",
    "mental symptoms amel.": "মানসিক লক্ষণে উপশম",
    "by physical": "শারীরিক লক্ষণে",
    "agg. from mental": "মানসিক কারণে বৃদ্ধি",
    "physical amel.": "শারীরিক দিকে উপশম",
    "can recall things long forgotten": "বহুদিন ভুলে যাওয়া কথা মনে করতে পারে",
    "Extravagance": "অমিতব্যয়িতা",
    "Fanaticism": "গোঁড়ামি",
    "absorbed in": "-এ নিমগ্ন",
    "in twilight": "গোধূলিতে",
    "closing the eyes in bed": "বিছানায় চোখ বুজলে",
    "going to bed": "শুতে যাওয়ার সময়",
    "lascivious": "কামুক",
    "lively": "প্রাণবন্ত",
    "periodically returning": "পর্যায়ক্রমে ফিরে আসা",
    "repulsive": "বীভৎস",
    "followed by heat": "এরপর উত্তাপ",
    "Fastidious": "খুঁতখুঁতে",
    "arising from": "-থেকে উদ্ভূত",
    "accidents": "দুর্ঘটনা",
    "lest he die": "পাছে সে মারা যায়",
    "injure himself": "নিজের ক্ষতি করে",
    "alternating with mania": "উন্মত্ততার সঙ্গে পর্যায়ক্রমে",
    "night at": "রাতে",
    "with feelings as if head would burst": "মাথা ফেটে যাবে এমন অনুভূতিসহ",
    "approaching him": "তার দিকে এগিয়ে আসছে",
    "of others": "অন্যদের",
    "children cannot bear to have anyone come near them": "শিশু কাউকে কাছে আসতে দিতে পারে না",
    "lest he be touched": "পাছে তাকে কেউ ছোঁয়",
    "of vehicles": "গাড়ির",
    "of hearing": "শোনার",
    "that someone is": "যে কেউ একজন",
    "betrayed": "বিশ্বাসঘাতকতার শিকার",
    "being": "-হওয়া",
    "bitten": "কামড়ানো",
    "of softening of": "-এর নরম হয়ে যাওয়ার",
    "brilliant objects": "চকচকে জিনিস",
    "looking-glass": "আয়না",
    "or cannot endure": "অথবা সহ্য করতে পারে না",
    "burden": "বোঝা",
    "of becoming a": "-হয়ে ওঠার",
    "censured": "নিন্দিত",
    "church or opera": "গির্জা বা নাট্যশালা",
    "when ready to go": "যাওয়ার জন্য প্রস্তুত হলে",
    "coal-scuttle of the": "কয়লার বালতির",
    "at thought of in a woman": "-এর কথা ভাবলে (নারীর ক্ষেত্রে)",
    "of taking": "গ্রহণ করার",
    "that people would observe her": "যে লোকে তাকে লক্ষ করবে",
    "consumption": "যক্ষ্মা",
    "to walk past certain": "নির্দিষ্ট জায়গা পেরিয়ে হাঁটতে",
    "creeping out of every corner": "প্রতিটি কোণ থেকে বেরিয়ে আসছে",
    "of something": "কোনো কিছুর",
    "public places": "জনবহুল জায়গা",
    "report of": "-এর শব্দ",
    "excite": "উত্তেজিত করা",
    "cutting himself when shaving": "দাড়ি কামাতে গিয়ে নিজেকে কেটে ফেলা",
    "impending": "আসন্ন",
    "dawn": "ঊষা",
    "of the return of": "-এর ফিরে আসার",
    "fear he will": "ভয় পায় সে -করবে",
    "if he goes to sleep": "ঘুমিয়ে পড়লে",
    "after night-mare": "দুঃস্বপ্নের পর",
    "heart symptoms": "হৃদযন্ত্রের লক্ষণ",
    "soon": "শীঘ্রই",
    "that she will die": "যে সে মারা যাবে",
    "destination": "গন্তব্য",
    "of being unable to reach his": "সেখানে পৌঁছাতে না পারার",
    "devil": "শয়তান",
    "being taken by the": "শয়তানের হাতে পড়ার",
    "devoured by animals": "জন্তুতে খেয়ে ফেলার",
    "disaster": "বিপর্যয়",
    "of impending": "আসন্ন",
    "worse walking in open air": "খোলা বাতাসে হাঁটলে বৃদ্ধি",
    "downward motion": "নিচের দিকে নড়াচড়া",
})

SEG_EXT.update({
    "drawn upward": "উপরের দিকে টানা",
    "driving him from place to place": "তাকে এক জায়গা থেকে আরেক জায়গায় তাড়িয়ে বেড়ায়",
    "drowned": "ডুবে যাওয়া",
    "when hungry": "ক্ষুধার্ত অবস্থায়",
    "after an": "একটির পর",
    "in the morning": "সকালে",
    "evil of": "-এর অমঙ্গল",
    "exposure night in bed": "রাতে বিছানায় গা খোলা",
    "failure": "ব্যর্থতা",
    "in business": "ব্যবসায়",
    "fall upon him": "তার উপর পড়বে",
    "high walls and building": "উঁচু দেয়াল ও বাড়ি",
    "letting things fall": "হাত থেকে জিনিস পড়ে যাওয়া",
    "while chilly": "শীত-শীত লাগার সময়",
    "typhus": "টাইফাস",
    "things will catch": "জিনিসে আগুন ধরে যাবে",
    "of having a": "-হওয়ার",
    "friend has met with accident": "বন্ধু দুর্ঘটনায় পড়েছে",
    "that a": "যে একজন",
    "grieving": "শোক করা",
    "when alone relieved by conversation": "একা থাকলে হয়, কথা বললে উপশম",
    "that she has ruined": "যে সে সর্বনাশ করেছে",
    "disease of": "-এর রোগ",
    "will cease to beat unless constantly on the move": "অনবরত না নড়লে স্পন্দন থেমে যাবে",
    "high places": "উঁচু জায়গা",
    "that he would not return": "যে সে ফিরবে না",
    "that something would happen to him": "যে তার কিছু একটা হবে",
    "imaginary things": "কাল্পনিক জিনিস",
    "imbecile": "নির্বোধ",
    "that he would become": "যে সে হয়ে যাবে",
    "infection": "সংক্রমণ",
    "injured": "আহত",
    "joints are weak": "গাঁট দুর্বল",
    "jumps out of bed from": "-এ বিছানা থেকে লাফিয়ে নামে",
    "on touch": "স্পর্শে",
    "out of the window": "জানালা দিয়ে বাইরে",
    "killing": "হত্যা করা",
    "with a knife": "ছুরি দিয়ে",
    "looking before her": "সামনে তাকানো",
    "losing senses": "জ্ঞান হারানো",
    "medicine": "ওষুধ",
    "of taking too much": "অতিরিক্ত খেয়ে ফেলার",
    "men": "পুরুষ",
    "menstrual colic": "ঋতুকালীন পেটব্যথা",
    "mirrors in room": "ঘরের আয়না",
    "mischief": "অনিষ্ট",
    "he might do": "সে করে ফেলতে পারে",
    "moral obliquity alternating with sexual excitement": "যৌন উত্তেজনার সঙ্গে পর্যায়ক্রমে নৈতিক বিকৃতি",
    "narrow place": "সংকীর্ণ জায়গা",
    "of those standing": "যারা দাঁড়িয়ে আছে তাদের",
    "at door": "দরজায়",
    "rushing water": "বেগে বয়ে যাওয়া জল",
    "street": "রাস্তা",
    "observed": "লক্ষ করা হচ্ছে",
    "of her condition being": "তার অবস্থা -হওয়ার",
    "occupation": "কাজকর্ম",
    "out of doors": "বাইরে",
    "to go": "যেতে",
    "physician": "চিকিৎসক",
    "will not see him he seems to terrify her": "তার কাছে যেতে চায় না, তাকে ভয় পায়",
    "piano": "পিয়ানো",
    "when at": "-এ থাকলে",
    "pneumonia": "নিউমোনিয়া",
    "has been": "-হয়েছে",
    "poverty": "দারিদ্র্য",
    "body will": "শরীর -হবে",
    "rain of": "বৃষ্টির",
    "when in a carriage": "গাড়িতে থাকলে",
    "midnight on waking": "মধ্যরাতে জেগে উঠলে",
    "run over of being": "চাপা পড়ার",
    "on going out": "বাইরে বেরোলে",
    "say something wrong": "ভুল কিছু বলে ফেলা",
    "lest he should": "পাছে সে করে ফেলে",
    "self-control": "আত্মসংযম",
    "losing": "হারানো",
    "serious thoughts": "গুরুগম্ভীর চিন্তা",
    "he will never sleep again": "সে আর কখনও ঘুমাতে পারবে না",
    "to close the eyes lest he should never wake": "চোখ বুজতে ভয়, পাছে আর না জাগে",
    "to go to": "-যেতে",
    "of his position in": "-এ তার অবস্থান নিয়ে",
    "speak": "কথা বলা",
    "starving": "অনাহার",
    "of ulcer in": "-এ ক্ষতের",
    "suffering": "কষ্ট",
    "suicide": "আত্মহত্যা",
    "superstitious": "কুসংস্কারাচ্ছন্ন",
    "surprises": "চমক",
    "from pleasant": "আনন্দদায়ক চমকে",
    "syphilis": "উপদংশ",
    "talking loud": "জোরে কথা বলা",
    "as if would kill her": "যেন তাকে মেরে ফেলবে",
    "thinking of disagreeable things": "অপ্রীতিকর কথা ভাবা",
    "sad things": "দুঃখের কথা",
    "of his own": "নিজের",
    "from sensation of swelling of": "-এর ফোলা অনুভূতি থেকে",
    "tread lightly": "পা টিপে হাঁটা",
    "or will injure himself": "অথবা নিজের ক্ষতি করবে",
    "of imaginary": "কাল্পনিক",
    "unaccountable": "অকারণ",
    "undertaking anything": "কোনো কাজে হাত দেওয়া",
    "of being drawn": "টেনে নেওয়ার",
    "of using": "ব্যবহার করার",
    "from a dream": "স্বপ্ন থেকে",
    "of something under the bed": "বিছানার নিচে কিছু আছে এমন",
    "across busy street": "ব্যস্ত রাস্তা পেরোনো",
    "wet his bed": "বিছানায় প্রস্রাব করা",
    "fears he will": "ভয় পায় সে -করবে",
    "literary": "সাহিত্যিক",
    "Feces passed on the floor": "মেঝেতে মলত্যাগ",
    "swallows his own": "নিজের মল গিলে ফেলে",
    "licks up cow-dung": "গোবর চেটে খায়",
    "mud": "কাদা",
    "Feigning sick": "অসুস্থতার ভান",
    "Fight": "মারামারি",
    "wants to": "-করতে চায়",
    "wants to set things on": "জিনিসে আগুন ধরাতে চায়",
    "a flame of": "আগুনের শিখা",
    "seemed passing through him": "তার ভিতর দিয়ে বয়ে যাচ্ছে মনে হলো",
    "throws things into": "-এ জিনিস ছুড়ে ফেলে",
    "Flattery": "তোষামোদ",
    "Foolish behavior": "বোকার মতো আচরণ",
    "happiness and pride": "সুখ ও গর্ব",
    "everything that had occurred for six years": "ছয় বছরে যা ঘটেছে সব",
    "name": "নাম",
    "purchases": "কেনাকাটা",
    "goes off and leaves them": "ফেলে রেখে চলে যায়",
    "shaving or dressing": "দাড়ি কামানো বা পোশাক পরা",
    "he remembers all he had forgotten": "যা ভুলেছিল সব মনে পড়ে যায়",
    "streets": "রাস্তাঘাট",
    "of well-known": "সুপরিচিত",
    "watch": "ঘড়ি",
    "to wind": "দম দিতে",
    "which side of the street his house was on": "রাস্তার কোন পাশে তার বাড়ি",
    "while speaking": "কথা বলার সময়",
    "Forgotten": "ভুলে যাওয়া",
    "feels constantly as if he had": "সবসময় মনে হয় সে কিছু ভুলে গেছে",
    "things": "জিনিস",
    "come to mind in sleep": "ঘুমের মধ্যে মনে পড়ে",
    "Forsaken feeling": "পরিত্যক্ত বোধ",
    "sensation of isolation": "একাকিত্বের অনুভূতি",
    "Forsakes his own children": "নিজের সন্তানদের ত্যাগ করে",
    "relations": "আত্মীয়স্বজন",
    "Frightened easily": "সহজেই ভয় পায়",
    "wakens at 3 a.m.": "ভোর ৩টায় জেগে ওঠে",
    "nocturnal emissions": "রাতে বীর্যপাত",
    "roused": "জাগানো হলে",
    "form": "অবয়ব",
    "day before menses": "ঋতুস্রাবের আগের দিন",
    "wakens in a fright from least noise": "সামান্য শব্দে আতঙ্কে জেগে ওঠে",
    "terrified": "আতঙ্কিত",
    "Frivolous": "চপল",
    "Frown": "ভ্রুকুটি",
    "disposed to": "-এর প্রবণতা",
    "Fur": "পশম",
    "wraps up in": "-এ গা ঢাকে",
    "makes": "করে তোলে",
    "at sight of drink": "পানীয় দেখলে",
    "furious": "উন্মত্ত ক্রুদ্ধ",
    "clapping of the": "হাততালি",
    "crossing the hands": "হাত আড়াআড়ি রাখা",
    "bystanders": "পাশে দাঁড়ানো লোকজন",
    "chewing and swallowing": "চিবানো ও গেলা",
    "at during spasms": "খিঁচুনির সময়",
    "sides of the bed": "বিছানার কিনারা",
    "folding hands": "হাত জড়ো করা",
    "and unfolding coverings": "এবং ঢাকা খোলা",
    "hasty": "তাড়াহুড়ো",
    "lifting up hands": "হাত তোলা",
    "rubbing together": "একসঙ্গে ঘষা",
    "spinning and weaving": "সুতা কাটা ও বোনা",
    "throwing about": "ছোড়াছুড়ি",
    "over head": "মাথার উপরে",
    "waving in the air": "বাতাসে নাড়া",
    "winding a ball": "সুতার গোলা পাকানো",
    "indicates his desires by": "-দিয়ে নিজের ইচ্ছা বোঝায়",
    "picks at bedclothes": "বিছানার চাদর খোঁটে",
    "plays with his fingers": "আঙুল নিয়ে খেলা করে",
    "pouring from hand to hand": "এক হাত থেকে আরেক হাতে ঢালা",
    "pulls hair of bystanders": "পাশের লোকের চুল টানে",
    "standing on the street": "রাস্তায় দাঁড়িয়ে",
    "imitates": "নকল করে",
    "around on the foot": "পায়ের উপর ঘুরপাক",
    "stamps the feet": "পা ঠোকে",
    "usual vocation": "স্বাভাবিক পেশা",
    "of his": "তার",
    "wringing the hands": "হাত মোচড়ানো",
    "Giggling": "খিলখিল হাসি",
    "Godless": "ঈশ্বরবিমুখ",
    "want of religious feeling": "ধর্মবোধের অভাব",
    "Going out": "বাইরে যাওয়া",
    "Gossiping": "পরনিন্দা",
    "cannot cry": "কাঁদতে পারে না",
    "condition": "অবস্থা",
    "for the": "-এর জন্য",
    "hunting for something to grieve one": "শোক করার মতো কিছু খুঁজে বেড়ানো",
    "undemonstrative": "প্রকাশহীন",
    "Grimaces": "মুখভঙ্গি",
    "Groping as if in the dark": "যেন অন্ধকারে হাতড়ানো",
    "Growling like a dog": "কুকুরের মতো গরগর করা",
    "Grunting": "ঘোঁৎ ঘোঁৎ শব্দ",
    "Hatred": "ঘৃণা",
    "better on seeing them": "তাদের দেখলে উপশম",
    "bitter feelings for slight offenses": "সামান্য অপরাধেও তীব্র বিদ্বেষ",
    "who had offended": "যে আঘাত দিয়েছিল",
    "unmoved by apologies": "ক্ষমা চাইলেও গলে না",
    "who do not agree with him": "যারা তার সঙ্গে একমত নয়",
    "Haughty": "উদ্ধত",
    "Heedless": "বেপরোয়া",
    "Helplessness": "অসহায়ত্ব",
    "feeling of": "-এর অনুভূতি",
    "Hide": "লুকানো",
    "on account of fear": "ভয়ের কারণে",
    "child thinks all visitors laugh at it and hides behind furniture": "শিশু ভাবে সব অতিথি তাকে নিয়ে হাসছে, তাই আসবাবের পিছনে লুকায়",
    "Hides things": "জিনিস লুকিয়ে রাখে",
    "High places": "উঁচু জায়গা",
    "High-spirited": "উৎফুল্ল",
    "desires to go": "যেতে চায়",
    "desire to leave home": "বাড়ি ছাড়ার ইচ্ছা",
    "Home-sickness": "বাড়ির জন্য মন কেমন",
    "red cheeks": "লাল গাল",
    "silent ill humour": "নীরব বিরক্তি",
    "Honor": "সম্মান",
    "effects of wounded": "আহত সম্মানের প্রভাব",
    "Hopeful": "আশাবাদী",
    "sad stories": "দুঃখের কাহিনি",
    "affect her profoundly": "তাকে গভীরভাবে নাড়া দেয়",
    "everybody must hurry": "সবাইকে তাড়াহুড়ো করতেই হবে",
    "movements": "নড়াচড়া",
    "cannot do things fast enough": "যথেষ্ট দ্রুত কাজ করতে পারে না",
    "desires to do several things at once": "একসঙ্গে অনেক কাজ করতে চায়",
    "for the appointed": "নির্ধারিত সময়ের জন্য",
    "to arrive": "পৌঁছানোর",
    "Hydrophobia": "জলাতঙ্ক",
    "Hypocrisy": "কপটতা",
    "first day of": "প্রথম দিনে",
    "morning agg.": "সকালে বৃদ্ধি",
    "sighing amel.": "দীর্ঘশ্বাসে উপশম",
    "music amel.": "গানে উপশম",
    "suppression of discharges": "ক্ষরণ বন্ধ হয়ে যাওয়া",
    "deficiency of": "-এর ঘাটতি",
    "extra exertion": "বাড়তি পরিশ্রম",
    "from any": "যেকোনো কারণে",
    "vomiting amel.": "বমিতে উপশম",
    "Idiocy": "জড়বুদ্ধি",
    "idiotic actions": "নির্বোধ আচরণ",
    "Imbecility": "বুদ্ধিহীনতা",
    "playing of children": "শিশুদের খেলা",
    "talk of others": "অন্যদের কথাবার্তা",
    "Impertinence": "ধৃষ্টতা",
    "Impetuous": "উদ্ধত অস্থির",
    "Impulse to destroy himself": "নিজেকে ধ্বংস করার তাড়না",
    "to run": "ছুটে যাওয়ার",
    "to stab his flesh with the knife he holds": "হাতের ছুরি নিজের গায়ে বসানোর",
    "Impulsive": "আবেগতাড়িত",
    "Inciting others": "অন্যদের উসকে দেওয়া",
    "Inconsolable": "অসান্ত্বনীয়",
    "alone and darkness agg.": "একা থাকা ও অন্ধকারে বৃদ্ধি",
    "over fancied misfortune": "কল্পিত দুর্ভাগ্যে",
    "Inconstancy": "অস্থিরচিত্ততা",
    "apathy": "নিস্পৃহতা",
    "agreeable things to": "প্রীতিকর বিষয়েও",
    "alternating with anxiety and restlessness": "উদ্বেগ ও অস্থিরতার সঙ্গে পর্যায়ক্রমে",
    "cheerfulness": "প্রফুল্লতা",
    "business affairs": "ব্যবসার কাজ",
    "caresses": "আদর",
    "complain": "অভিযোগ করা",
    "unless questioned": "জিজ্ঞেস না করলে",
    "then say nothing of his condition": "তারপরও নিজের অবস্থার কথা বলে না",
    "to the dictates of": "-এর নির্দেশে",
    "desire": "ইচ্ছা",
    "no action of the will": "ইচ্ছাশক্তির কোনো সাড়া নেই",
    "exposure of her person": "নিজের শরীর অনাবৃত করা",
    "external things": "বাইরের জিনিস",
    "important things": "গুরুত্বপূর্ণ বিষয়",
    "irritating": "বিরক্তিকর",
    "disagreeable things": "অপ্রীতিকর বিষয়",
    "lies with eyes closed": "চোখ বুজে শুয়ে থাকে",
    "loved ones": "প্রিয়জন",
    "which he loves": "যা সে ভালোবাসে",
    "opposite sex": "বিপরীত লিঙ্গ",
    "personal appearance": "নিজের চেহারা",
    "pleasure": "আনন্দ",
    "her children": "তার সন্তানরা",
    "religion": "ধর্ম",
    "to his": "তার প্রতি",
    "welfare of others": "অন্যের মঙ্গল",
    "bad effects following": "-এর পর খারাপ প্রভাব",
    "discomfort": "অস্বস্তি",
    "from general": "সাধারণভাবে",
    "at unpleasant": "অপ্রীতিকর কিছুতে",
    "Indiscretion": "অবিবেচনা",
    "aversion to work": "কাজে অনীহা",
    "aversion to her usual housework": "নিজের নিত্য ঘরকন্নায় অনীহা",
    "Industrious": "পরিশ্রমী",
    "Injure fears to be left alone": "একা থাকতে ভয়, পাছে ক্ষতি করে ফেলে",
    "lest he should himself": "পাছে নিজেরই ক্ষতি করে",
    "feels as if she could easily injure herself": "মনে হয় সে সহজেই নিজের ক্ষতি করে ফেলতে পারে",
    "frenzy": "উন্মত্ততা",
    "causing him to": "যা তাকে -করায়",
    "satiety": "তৃপ্তি, বিতৃষ্ণা",
    "must use self control to prevent shooting himself": "নিজেকে গুলি করা ঠেকাতে আত্মসংযম লাগে",
    "Inquisitive": "অতি কৌতূহলী",
    "madness": "উন্মাদনা",
    "alternating with metrorrhagia": "জরায়ু-রক্তস্রাবের সঙ্গে পর্যায়ক্রমে",
    "with stupor": "আচ্ছন্নতার সঙ্গে",
    "other mental symptoms": "অন্যান্য মানসিক লক্ষণ",
    "mental with physical symptoms": "শারীরিক লক্ষণের সঙ্গে মানসিক",
    "behaves like a crazy person": "পাগলের মতো আচরণ করে",
    "break pins": "পিন ভাঙে",
    "she will sit and": "সে বসে বসে -করে",
    "coldness of skin": "ত্বকের শীতলতা",
    "climacteric period": "রজোনিবৃত্তিকাল",
    "crawls on the floor": "মেঝেতে হামাগুড়ি দেয়",
    "dresses in his best clothes": "সবচেয়ে ভালো পোশাক পরে",
    "eats only refuse": "শুধু উচ্ছিষ্ট খায়",
    "with a stamping of": "-ঠোকার সঙ্গে",
    "fright or anger": "ভয় বা রাগ",
    "injuries to the head": "মাথার আঘাত",
    "insists upon saying his prayers at the tail of his horse": "ঘোড়ার লেজের কাছে প্রার্থনা করতে জেদ ধরে",
    "makes useless purchases": "অপ্রয়োজনীয় জিনিস কেনে",
    "with profuse": "প্রচুর স্রাবসহ",
    "with suppressed": "রুদ্ধ স্রাবসহ",
    "mental labor": "মানসিক পরিশ্রম",
    "neuralgia": "স্নায়ুশূল",
    "with disappearance of": "-অদৃশ্য হওয়ার সঙ্গে",
    "passes her feces on the floor": "মেঝেতে মলত্যাগ করে",
    "strength increased": "শক্তি বেড়ে যায়",
    "threatens destruction and death": "ধ্বংস ও মৃত্যুর হুমকি দেয়",
    "will not be": "-হবে না",
    "wantonness": "উচ্ছৃঙ্খলতা",
    "Insolent": "ঔদ্ধত্যপূর্ণ",
    "Introspection": "আত্মবিশ্লেষণ",
    "Irresolution": "সিদ্ধান্তহীনতা",
    "acts": "কাজে",
    "ideas": "ভাবনায়",
    "projects": "পরিকল্পনায়",
    "retiring": "শুতে যাওয়া",
    "hypochondriacal mood during day": "দিনে রোগভীতিগ্রস্ত মেজাজ",
    "merry in evening": "সন্ধ্যায় প্রফুল্ল",
    "in an important": "গুরুত্বপূর্ণ কিছুতে",
    "idle": "অলস",
    "during an intermission of": "-এর বিরতির সময়",
    "such as even crackling of newspapers drives him to despair": "এমনকি সংবাদপত্রের খসখস শব্দেও হতাশ হয়ে পড়ে",
    "questioned": "প্রশ্ন করা হলে",
    "rocking fast amel.": "দ্রুত দোলালে উপশম",
    "sends": "পাঠিয়ে দেয়",
    "the doctor home": "ডাক্তারকে বাড়ি",
    "says he is not sick": "বলে সে অসুস্থ নয়",
    "nurse home": "সেবিকাকে বাড়ি",
    "nurse out of the room": "সেবিকাকে ঘরের বাইরে",
    "by noise": "শব্দে",
    "takes everything in bad part": "সবকিছু খারাপভাবে নেয়",
    "hearing or seeing": "শোনা বা দেখা",
    "weather in rainy or cloudy": "বৃষ্টি বা মেঘলা আবহাওয়ায়",
    "Jealousy": "ঈর্ষা",
    "as foolish as it is irresistible": "যতটা অদম্য ততটাই বোকামি",
    "gravity": "গাম্ভীর্য",
    "malicious": "বিদ্বেষপূর্ণ",
    "puns": "শ্লেষোক্তি",
    "from excessive": "অতিরিক্ত কারণে",
    "at the misfortune of others": "অন্যের দুর্ভাগ্যে",
    "out of": "-এর বাইরে",
    "during fever": "জ্বরের সময়",
    "height": "উচ্চতা",
    "impulse to jump": "লাফ দেওয়ার তাড়না",
    "impulse to jump into the river": "নদীতে ঝাঁপ দেওয়ার তাড়না",
    "Kicks": "লাথি মারে",
    "and becomes stiff when": "এবং শক্ত হয়ে যায় যখন",
    "child is cross": "শিশু খিটখিটে",
    "kicks and scolds on waking": "জেগে উঠে লাথি মারে ও বকে",
    "barber wants to kill his customer": "নাপিত খদ্দেরকে খুন করতে চায়",
    "desire to kill the person that contradicts her": "যে প্রতিবাদ করে তাকে খুন করার ইচ্ছা",
    "sight of a knife": "ছুরি দেখা",
    "of knife or a gun": "ছুরি বা বন্দুকের",
    "something urges her to": "কিছু একটা তাকে তাড়না দেয়",
    "her husband": "তার স্বামীকে",
    "of whom she is very fond": "যাকে সে খুব ভালোবাসে",
    "impulse to": "-এর তাড়না",
    "herself": "নিজেকে",
    "for a slight offense": "সামান্য অপরাধে",
    "throw child into fire": "শিশুকে আগুনে ছুড়ে ফেলা",
    "thought he ought to kill somebody": "ভাবল তার কাউকে খুন করা উচিত",
    "threatens to": "-করার হুমকি দেয়",
    "Killed": "নিহত",
    "Kisses everyone": "সবাইকে চুমু খায়",
    "his companions' hands": "সঙ্গীদের হাত",
    "Kleptomania": "চুরির দুর্নিবার প্রবৃত্তি",
    "steals dainties": "মুখরোচক খাবার চুরি করে",
    "steals money": "টাকা চুরি করে",
    "Kneeling and praying": "হাঁটু গেড়ে প্রার্থনা",
    "bemoaning": "বিলাপ",
    "wailing etc. (compare weeping)": "কান্নাকাটি ইত্যাদি (কান্নার সঙ্গে তুলনীয়)",
    "alternating with delirium": "প্রলাপের সঙ্গে পর্যায়ক্রমে",
    "because he is not": "কারণ সে নয়",
    "sickness": "অসুস্থতা",
    "Lasciviousness": "কামুকতা",
    "lustful": "লালসাপূর্ণ",
    "actions": "আচরণ",
    "at his own": "নিজের",
})
