# -*- coding: utf-8 -*-
"""Bangla for Kent's rubric vocabulary.

Kent's rubric names are compositional — 'Pain, stitching, forehead, evening,
walking, amel.' is six reusable terms — so the Bangla lives in a glossary of
terms rather than in 77,000 translated strings. The page composes a rubric's
Bangla name from this glossary at load time, which is also why the data file
carries no per-rubric Bangla for the generated rows.

A term that is not in SEG stays in English. That is deliberate: a wrong Bangla
rubric name is worse than an English one, because the practitioner would select
the wrong rubric and repertorise on it. Bengali homeopathic practice already
uses the English rubric words, so an untranslated term still reads naturally.
"""
import re, collections

# ---------------------------------------------------------------- chapter names
CHAPTER_BN = {
    'Mind': 'মন', 'Vertigo': 'মাথা ঘোরা', 'Head': 'মাথা', 'Eye': 'চোখ',
    'Vision': 'দৃষ্টি', 'Ear': 'কান', 'Hearing': 'শ্রবণ', 'Nose': 'নাক',
    'Face': 'মুখমণ্ডল', 'Mouth': 'মুখগহ্বর', 'Teeth': 'দাঁত', 'Throat': 'গলা',
    'External throat': 'বাইরের গলা', 'Stomach': 'পাকস্থলী', 'Abdomen': 'উদর',
    'Rectum': 'মলদ্বার', 'Stool': 'মল', 'Urinary organs': 'মূত্রতন্ত্র',
    'Bladder': 'মূত্রথলি', 'Kidneys': 'কিডনি', 'Prostate gland': 'প্রস্টেট',
    'Urethra': 'মূত্রনালি', 'Urine': 'প্রস্রাব', 'Genitalia male': 'পুরুষ জননাঙ্গ',
    'Genitalia female': 'নারী জননাঙ্গ', 'Larynx & trachea': 'কণ্ঠনালি',
    'Respiration': 'শ্বাস', 'Cough': 'কাশি', 'Expectoration': 'কফ',
    'Chest': 'বুক', 'Back': 'পিঠ', 'Extremities': 'হাত-পা', 'Sleep': 'ঘুম',
    'Chill': 'শীত', 'Fever': 'জ্বর', 'Perspiration': 'ঘাম', 'Skin': 'ত্বক',
    'Generalities': 'সাধারণ',
}

# ---------------------------------------------------------------- the glossary
# Ordered by theme so it stays auditable. Keys are matched case-insensitively.
SEG = {
    # ---- pain and sensation types
    'Pain': 'ব্যথা',
    'Pain (aching': 'ব্যথা (ভোঁতা',
    'Pain appear gradually': 'ব্যথা ধীরে ধীরে আসে',
    'pain': 'ব্যথা',
    'stitching': 'সূচিবিদ্ধ',
    'stitching (sticking': 'সূচিবিদ্ধ (খোঁচা',
    'stitching in': 'সূচিবিদ্ধ ব্যথা',
    'tearing': 'ছেঁড়া',
    'tearing in': 'ছেঁড়া ব্যথা',
    'drawing': 'টানা',
    'pressing': 'চাপা',
    'burning': 'জ্বালা',
    'sore': 'ঘা-ব্যথা',
    'sore bruised': 'ঘা-থেঁতলানো ব্যথা',
    'bruised': 'থেঁতলানো',
    'aching': 'ভোঁতা ব্যথা',
    'cutting': 'কাটা',
    'cutting (sudden sharp pain)': 'কাটা (হঠাৎ তীক্ষ্ণ ব্যথা)',
    'shooting': 'ছুটে যাওয়া',
    'boring': 'বিদ্ধকারী',
    'digging': 'খোঁড়া',
    'rending': 'ছিন্নকারী',
    'griping': 'মোচড়ানো',
    'cramping': 'খিঁচুনি-সদৃশ',
    'cramp-like': 'খিঁচুনি-সদৃশ',
    'gnawing': 'কুরে খাওয়া',
    'stinging': 'হুল ফোটানো',
    'biting': 'কাটাকাটা জ্বালা',
    'smarting': 'চিড়িক দেওয়া',
    'lancinating': 'তীক্ষ্ণ বিদ্ধকারী',
    'darting': 'ঝিলিক দেওয়া',
    'stabbing': 'ছুরিকাঘাতের মতো',
    'screwing': 'পাক দেওয়া',
    'pinching': 'চিমটি কাটা',
    'dragging': 'ভারী টান',
    'bursting': 'ফেটে যাওয়ার মতো',
    'beaten': 'পিটুনির মতো',
    'broken': 'ভেঙে যাওয়ার মতো',
    'sprained': 'মোচড় লাগার মতো',
    'rheumatic': 'বাতজনিত',
    'paralytic': 'পক্ষাঘাতসদৃশ',
    'constricting': 'সংকোচক',
    'jerking': 'ঝাঁকি দেওয়া',
    'Jerking': 'ঝাঁকি',
    'pulsating': 'স্পন্দনশীল',
    'Pulsating': 'স্পন্দনশীল',
    'Pulsation': 'স্পন্দন',
    'wandering': 'স্থান পরিবর্তনকারী',
    'paroxysmal': 'থেমে থেমে আসা',
    'sudden': 'হঠাৎ',
    'painful': 'ব্যথাযুক্ত',
    'tenderness': 'স্পর্শকাতরতা',
    'itching': 'চুলকানি',
    'Itching': 'চুলকানি',
    'sensation of': '-এর অনুভূতি',
    'as if': 'যেন',
    'as from': 'যেন কিছু থেকে',
    'like': '-এর মতো',

    # ---- complaints and states
    'Eruptions': 'উদ্ভেদ',
    'Eruption': 'উদ্ভেদ',
    'Discoloration': 'বিবর্ণতা',
    'Delusions': 'ভ্রান্ত ধারণা',
    'Delirium': 'প্রলাপ',
    'Weakness': 'দুর্বলতা',
    'Heat': 'উত্তাপ',
    'Coldness': 'শীতলতা',
    'Coldness (including Chill)': 'শীতলতা (কম্প সহ)',
    'Chilliness': 'শীত শীত ভাব',
    'Swelling': 'ফোলা',
    'Numbness': 'অবশতা',
    'Heaviness': 'ভারী বোধ',
    'Twitching': 'পেশির লাফানো',
    'Tension': 'টান',
    'Ulcers': 'ক্ষত',
    'Constriction': 'সংকোচন',
    'Eructations': 'ঢেঁকুর',
    'Vomiting': 'বমি',
    'Nausea': 'বমিবমি ভাব',
    'Dreams': 'স্বপ্ন',
    'Diarrhœa': 'উদরাময়',
    'Paralysis': 'পক্ষাঘাত',
    'Cramps': 'খিঁচুনি',
    'Convulsions': 'আক্ষেপ',
    'Perspiration': 'ঘাম',
    'perspiration': 'ঘাম',
    'Inflammation': 'প্রদাহ',
    'Congestion': 'রক্তসঞ্চয়',
    'Fear': 'ভয়',
    'Anxiety': 'উদ্বেগ',
    'Restlessness': 'অস্থিরতা',
    'Sadness': 'বিষণ্নতা',
    'Weeping': 'কান্না',
    'Excitement': 'উত্তেজনা',
    'Confusion of mind': 'মনের বিভ্রান্তি',
    'Unconsciousness': 'অচেতনতা',
    'Faintness': 'মূর্ছাভাব',
    'Dryness': 'শুষ্কতা',
    'Dry': 'শুষ্ক',
    'Sleepiness': 'তন্দ্রা',
    'Sleeplessness': 'অনিদ্রা',
    'Coryza': 'সর্দি',
    'Palpitation heart': 'হৃদস্পন্দন বেড়ে যাওয়া',
    'Oppression': 'চাপবোধ',
    'Fullness': 'পূর্ণতা বোধ',
    'Emptiness': 'খালি বোধ',
    'Distension': 'ফুলে ওঠা',
    'Formication': 'পিঁপড়ে হাঁটার অনুভূতি',
    'Tingling': 'ঝিনঝিন',
    'Shocks': 'ধাক্কা',
    'Stiffness': 'শক্ত হওয়া',
    'Trembling': 'কম্পন',
    'Lameness': 'খোঁড়ানো',
    'Tumors': 'টিউমার',
    'Sensitive': 'সংবেদনশীল',
    'sensitive to pressure': 'চাপে সংবেদনশীল',
    'Difficult': 'কষ্টকর',
    'difficult': 'কষ্টকর',
    'Discharge': 'স্রাব',
    'Sediment': 'তলানি',
    'Urination': 'মূত্রত্যাগ',
    'Urging to urinate (morbid desire)': 'মূত্রত্যাগের বেগ',
    'Menses': 'ঋতুস্রাব',
    'Metrorrhagia': 'অনিয়মিত রক্তস্রাব',
    'Epistaxis': 'নাক দিয়ে রক্ত পড়া',
    'Erections': 'লিঙ্গোত্থান',
    'Appetite': 'ক্ষুধা',
    'Taste': 'স্বাদ',
    'Voice': 'কণ্ঠস্বর',
    'Noises in': '-এ শব্দ',
    'Colors before the eyes': 'চোখের সামনে রঙ',
    'Contraction of muscles and tendons': 'পেশি ও রগের সংকোচন',
    'Asthmatic': 'হাঁপানিজনিত',
    'Desires alcoholic drinks': 'মদ্যপানের ইচ্ছা',
    'Aversion to acids': 'অম্লজাতীয় খাবারে অরুচি',
    'Dim': 'ঝাপসা',
    'headache': 'মাথাব্যথা',
    'sciatica': 'সায়াটিকা',
    'rash': 'র‍্যাশ',
    'pimples': 'ছোট ফুসকুড়ি',
    'vesicles': 'জলভরা ফুসকুড়ি',
    'pustules': 'পুঁজভরা ফুসকুড়ি',
    'tubercles': 'শক্ত দানা',
    'blotches': 'ছোপ',
    'spots': 'ছোপ',
    'boils': 'ফোড়া',
    'scabs': 'মামড়ি',
    'redness': 'লালচে ভাব',
    'offensive': 'দুর্গন্ধযুক্ত',
    'involuntary': 'অনিচ্ছাকৃত',
    'suppressed': 'রুদ্ধ',

    # ---- time
    'morning': 'সকাল',
    'Morning': 'সকাল',
    'forenoon': 'পূর্বাহ্ন',
    'Forenoon': 'পূর্বাহ্ন',
    'noon': 'দুপুর',
    'Noon': 'দুপুর',
    'afternoon': 'বিকাল',
    'Afternoon': 'বিকাল',
    'evening': 'সন্ধ্যা',
    'Evening': 'সন্ধ্যা',
    'night': 'রাত',
    'Night': 'রাত',
    'midnight': 'মধ্যরাত',
    'Midnight': 'মধ্যরাত',
    'daytime': 'দিনের বেলা',
    'Daytime': 'দিনের বেলা',
    'first': 'প্রথম',
    'second': 'দ্বিতীয়',
    'third': 'তৃতীয়',
    'fourth': 'চতুর্থ',
    'middle': 'মধ্যভাগ',

    # ---- grammar / connectives
    'after': 'পরে',
    'before': 'আগে',
    'during': 'সময়ে',
    'while': 'অবস্থায়',
    'when': 'যখন',
    'with': 'সহ',
    'from': 'থেকে',
    'in': '-এ',
    'on': '-এ',
    'to': '-এর দিকে',
    'of': '-এর',
    'under': 'নিচে',
    'above': 'উপরে',
    'between': 'মাঝে',
    'inside': 'ভিতরে',
    'externally': 'বাইরে',
    'lower': 'নিচের',
    'upward': 'উপরের দিকে',
    'outward': 'বাইরের দিকে',
    'right': 'ডান',
    'left': 'বাম',
    'side': 'পাশ',
    'sides': 'পাশ',
    'sides of': '-এর পাশ',
    'back of': '-এর পিছনে',
    'region of': '-এর অঞ্চল',
    'joints of': '-এর সন্ধি',
    'hollow of': '-এর গর্ত',
    'anterior part': 'সামনের অংশ',
    'etc.': 'ইত্যাদি',
    'etc.)': 'ইত্যাদি)',
    'amel.': 'উপশম',
    'agg.': 'বৃদ্ধি',

    # ---- modalities
    'motion': 'নড়াচড়া',
    'Motion': 'নড়াচড়া',
    'motion agg.': 'নড়াচড়ায় বৃদ্ধি',
    'motion amel.': 'নড়াচড়ায় উপশম',
    'touch': 'স্পর্শ',
    'pressure': 'চাপ',
    'pressure amel.': 'চাপে উপশম',
    'pressure agg.': 'চাপে বৃদ্ধি',
    'rubbing amel.': 'ঘষায় উপশম',
    'scratching': 'আঁচড়ানো',
    'walking': 'হাঁটা',
    'walking in open air': 'খোলা বাতাসে হাঁটা',
    'sitting': 'বসা',
    'standing': 'দাঁড়ানো',
    'lying': 'শোয়া',
    'lying down': 'শুয়ে পড়া',
    'rising': 'ওঠা',
    'rising from a seat': 'আসন থেকে ওঠা',
    'stooping': 'ঝুঁকা',
    'exertion': 'পরিশ্রম',
    'mental exertion': 'মানসিক পরিশ্রম',
    'eating': 'খাওয়া',
    'drinking': 'পান করা',
    'dinner': 'দুপুরের খাবার',
    'breakfast': 'সকালের নাশতা',
    'supper': 'রাতের খাবার',
    'food': 'খাদ্য',
    'water': 'জল',
    'coughing': 'কাশা',
    'cough': 'কাশি',
    'sneezing': 'হাঁচি',
    'yawning': 'হাই তোলা',
    'writing': 'লেখা',
    'reading': 'পড়া',
    'talking': 'কথা বলা',
    'swallowing': 'গেলা',
    'coition': 'সহবাস',
    'pregnancy': 'গর্ভাবস্থা',
    'urination': 'মূত্রত্যাগ',
    'urinating': 'মূত্রত্যাগ',
    'stool': 'মল',
    'sleep': 'ঘুম',
    'waking': 'জাগা',
    'on waking': 'জাগার পর',
    'on going to': '-এ যাওয়ার সময়',
    'bed': 'বিছানা',
    'in bed': 'বিছানায়',
    'air': 'বাতাস',
    'open': 'খোলা',
    'in open': 'খোলা জায়গায়',
    'in open air': 'খোলা বাতাসে',
    'cold': 'ঠান্ডা',
    'heat': 'উত্তাপ',
    'warm room': 'গরম ঘর',
    'room': 'ঘর',
    'chill': 'কম্প',
    'fever': 'জ্বর',
    'menses': 'ঋতুস্রাব',
    'sour': 'টক',
    'bitter': 'তেতো',

    # ---- colours
    'black': 'কালো',
    'red': 'লাল',
    'yellow': 'হলুদ',
    'white': 'সাদা',
    'brown': 'বাদামি',
    'pale': 'ফ্যাকাশে',
    'bluish': 'নীলচে',
    'green': 'সবুজ',

    # ---- anatomy
    'head': 'মাথা',
    'forehead': 'কপাল',
    'frontal': 'সম্মুখভাগ',
    'occiput': 'মাথার পেছন',
    'occiput and Forehead': 'মাথার পেছন ও কপাল',
    'temples': 'রগ',
    'vertex': 'মাথার চাঁদি',
    'eminence': 'উঁচু অংশ',
    'eyes': 'চোখ',
    'lids': 'চোখের পাতা',
    'canthi': 'চোখের কোণ',
    'nose': 'নাক',
    'lips': 'ঠোঁট',
    'tongue': 'জিহ্বা',
    'palate': 'তালু',
    'gums': 'মাড়ি',
    'neck': 'ঘাড়',
    'throat': 'গলা',
    'larynx': 'কণ্ঠনালি',
    'chest': 'বুক',
    'sternum': 'বক্ষাস্থি',
    'mammæ': 'স্তন',
    'heart': 'হৃদয়',
    'axilla': 'বগল',
    'clavicle': 'কণ্ঠাস্থি',
    'shoulder': 'কাঁধ',
    'scapulæ': 'কাঁধের হাড়',
    'upper arm': 'বাহুর উপরাংশ',
    'elbow': 'কনুই',
    'forearm': 'বাহুর নিচের অংশ',
    'wrist': 'কবজি',
    'hand': 'হাত',
    'hands': 'হাত',
    'palm': 'হাতের তালু',
    'fingers': 'আঙুল',
    'thumb': 'বুড়ো আঙুল',
    'upper limbs': 'ঊর্ধ্বাঙ্গ',
    'lower limbs': 'নিম্নাঙ্গ',
    'hip': 'নিতম্ব',
    'thigh': 'উরু',
    'knee': 'হাঁটু',
    'patella': 'হাঁটুর মালাইচাকি',
    'leg': 'জঙ্ঘা',
    'calf': 'পায়ের গোছা',
    'tibia': 'নলার হাড়',
    'ankle': 'গোড়ালির সন্ধি',
    'heel': 'গোড়ালি',
    'foot': 'পা',
    'sole': 'পায়ের তলা',
    'toes': 'পায়ের আঙুল',
    'joints': 'সন্ধি',
    'bones': 'অস্থি',
    'bone': 'অস্থি',
    'back': 'পিঠ',
    'spine': 'মেরুদণ্ড',
    'cervical region': 'গ্রীবাদেশ',
    'dorsal region': 'পৃষ্ঠদেশ',
    'lumbar region': 'কটিদেশ',
    'sacral region': 'ত্রিকাস্থি অঞ্চল',
    'coccyx': 'পুচ্ছাস্থি',
    'nates': 'পাছা',
    'abdomen': 'উদর',
    'umbilicus': 'নাভি',
    'hypochondria': 'পাঁজরের নিচের পার্শ্বদেশ',
    'hypogastrium': 'তলপেট',
    'inguinal region': 'কুঁচকি',
    'iliac region': 'শ্রোণী অঞ্চল',
    'liver': 'যকৃৎ',
    'uterus': 'জরায়ু',
    'ovaries': 'ডিম্বাশয়',
    'vagina': 'যোনি',
    'penis': 'পুরুষাঙ্গ',
    'testes': 'অণ্ডকোষ',
    'scrotum': 'অণ্ডথলি',
    'spermatic cords': 'শুক্রনালি',
    'meatus': 'মুখছিদ্র',
    'tip': 'ডগা',
    'bearing down': 'নিচের দিকে ঠেলা',
    'extending to abdomen': 'উদর পর্যন্ত বিস্তৃত',
    'extending to back': 'পিঠ পর্যন্ত বিস্তৃত',
    'extending to ear': 'কান পর্যন্ত বিস্তৃত',
    'extending to anus': 'পায়ু পর্যন্ত বিস্তৃত',
    'extending downward': 'নিচের দিকে বিস্তৃত',
    'extending across': 'আড়াআড়ি বিস্তৃত',
    'extending to': '-পর্যন্ত বিস্তৃত',
    'inspiration': 'শ্বাস নেওয়া',
}

# A second pass, authored against a frequency count of the terms the first pass
# left in English — main rubric catchwords first, since those are what a
# practitioner scans for.
SEG.update({
    # ---- main rubric catchwords
    'Vertigo': 'মাথা ঘোরা', 'Time': 'সময়', 'Shaking': 'কাঁপা',
    'Loss of vision (blindness)': 'দৃষ্টিহীনতা (অন্ধত্ব)',
    'Irritability': 'বিরক্তি', 'Membrane': 'ঝিল্লি', 'Speech': 'কথা বলা',
    'Weakness (tired feeling': 'দুর্বলতা (ক্লান্তি বোধ',
    'Urging': 'বেগ', 'Hæmorrhoids': 'অর্শ', 'Pulse abnormal': 'অস্বাভাবিক নাড়ি',
    'Rumbling': 'গড়গড় শব্দ', 'Perspiration scalp': 'মাথার ত্বকে ঘাম',
    'Impaired': 'ক্ষীণ', 'Convulsion': 'আক্ষেপ', 'Warts': 'আঁচিল',
    'Gestures': 'অঙ্গভঙ্গি', 'Profuse': 'প্রচুর',
    'Irritation in air passages': 'শ্বাসনালিতে উত্তেজনা',
    'Mucus': 'শ্লেষ্মা', 'Leucorrhœa': 'শ্বেতপ্রদর', 'Spasmodic': 'আক্ষেপিক',
    'Heartburn': 'বুকজ্বালা', 'Gurgling': 'গড়গড় আওয়াজ',
    'Trembling externally': 'বাইরে কম্পন', 'Indifference': 'উদাসীনতা',
    'Falling asleep morning': 'সকালে ঘুম আসা', 'Obstruction': 'বাধা',
    'Motions': 'নড়াচড়া', 'Emaciation': 'শীর্ণতা', 'Odors': 'গন্ধ', 'Odor': 'গন্ধ',
    'Thirst': 'তৃষ্ণা', 'Bloody': 'রক্তমিশ্রিত', 'Swollen': 'ফোলা',
    'Deep': 'গভীর', 'Abscess': 'ফোড়া', 'Dullness': 'জড়তা',
    'Crawling': 'পোকা হাঁটার অনুভূতি', 'Contraction': 'সংকোচন', 'Lump': 'দলা',
    'Color': 'রঙ', 'Retching': 'বমির চেষ্টা', 'Mucous': 'শ্লেষ্মাযুক্ত',
    'Hiccough': 'হিক্কা', 'Copious (increased)': 'প্রচুর (বর্ধিত)',
    'Itching in': '-এ চুলকানি', 'Suicidal disposition': 'আত্মহত্যার প্রবণতা',
    'Seminal emissions (nightly)': 'রাতে শুক্রক্ষয়', 'Cracks skin': 'ত্বকে ফাটা',
    'Short': 'ছোট', 'Hair baldness': 'টাক', 'Saliva': 'লালা',
    'Choking': 'শ্বাসরোধ', 'Cracking': 'কড়কড় শব্দ', 'Lying agg.': 'শোয়ায় বৃদ্ধি',
    'Weak': 'দুর্বল', 'Shivering': 'শীতে কাঁপা', 'Cancer': 'ক্যান্সার',
    'Erysipelas': 'বিসর্প', 'Condylomata': 'আঁচিল-জাতীয় বৃদ্ধি',
    'Laughing': 'হাসা', 'Stupefaction': 'মূঢ়তা', 'Lachrymation': 'চোখে জল',
    'Hæmorrhage': 'রক্তস্রাব', 'Foggy': 'কুয়াশাচ্ছন্ন',
    'Catarrh': 'প্রদাহজনিত স্রাব', 'Continued fever': 'একটানা জ্বর',
    'Discharges': 'স্রাব', 'Hacking': 'খুকখুক', 'Ulceration': 'ক্ষত হওয়া',
    'Tickling': 'সুড়সুড়ি', 'Stretching': 'টানটান করা', 'Starting': 'চমকে ওঠা',
    'Gangrene': 'পচন', 'Prickling': 'সূচ ফোটার মতো', 'Hard': 'শক্ত',
    'Rattling': 'ঘড়ঘড় শব্দ', 'Flatus': 'বায়ু', 'Cheerful': 'প্রফুল্ল',
    'Violent': 'প্রচণ্ড', 'Sighing': 'দীর্ঘশ্বাস', 'Shuddering': 'শিউরে ওঠা',
    'Roughness': 'খসখসে ভাব', 'Flickering': 'ঝিলমিল',
    'Flatulence': 'পেটে বায়ু', 'Chorea': 'নৃত্যরোগ', 'Wind': 'বাতাস',
    'Shrieking': 'চিৎকার', 'Constipation': 'কোষ্ঠকাঠিন্য', 'Scraping': 'খচখচ',
    'Salivation': 'লালাক্ষরণ', 'Lassitude': 'শ্রান্তি', 'Irritation': 'উত্তেজনা',
    'Chilblains': 'শীতে ফোলা', 'Anger': 'রাগ', 'Insanity': 'উন্মত্ততা',
    'Retention of urine': 'মূত্ররোধ', 'Excrescences': 'অতিরিক্ত বৃদ্ধি',
    'Empty': 'খালি', 'Acute': 'তীব্র', 'Turning': 'ঘোরা',
    'Quarrelsome': 'কলহপ্রিয়', 'Photophobia': 'আলোভীতি', 'Loose': 'আলগা',
    'Excoriation': 'চামড়া ছিলে যাওয়া', 'Distention': 'ফুলে ওঠা',
    'Compression': 'চাপ', 'Stiffness': 'শক্ত হওয়া', 'Chilliness': 'শীত শীত ভাব',
    'Thoughts of death': 'মৃত্যুচিন্তা', 'Nodosities': 'গাঁট',
    'Moisture': 'আর্দ্রতা', 'Frothy': 'ফেনাযুক্ত', 'Cramp': 'খিঁচুনি',
    'Watery': 'জলীয়', 'Viscid': 'আঠালো', 'Thick': 'ঘন', 'Thin': 'পাতলা',
    'Scanty': 'অল্প', 'Dark': 'গাঢ়', 'Grief': 'শোক', 'Frequent': 'ঘন ঘন',
    'Whistling': 'শিস দেওয়া', 'Snoring': 'নাক ডাকা', 'Staring': 'একদৃষ্টে তাকানো',
    'Suppuration': 'পুঁজ হওয়া', 'Freckles': 'তিল-ছোপ', 'Moles': 'তিল',
    'Yellowness': 'হলদে ভাব', 'Insensibility': 'অনুভূতিহীনতা',
    'Suspicious': 'সন্দেহপ্রবণ', 'Sulky': 'গোমড়ামুখো', 'Sensitiveness': 'সংবেদনশীলতা',
    'Hardness': 'কাঠিন্য', 'Quivering': 'থরথর কম্পন', 'Sticky': 'আঠালো',
    'Tough': 'শক্ত-আঠালো', 'Clammy': 'ঠান্ডা-আঠালো', 'Chapped': 'ফাটা',
    'Cracks': 'ফাটা', 'Wrinkled': 'কুঞ্চিত', 'Ascending': 'উপরে ওঠা',
    'Descending': 'নিচে নামা', 'Slow': 'ধীর', 'Loss of fluids': 'তরল ক্ষয়',
    'Twisting': 'মোচড়ানো', 'Splitting': 'ফেটে যাওয়া', 'Spasms of': '-এর আক্ষেপ',
    'Spasm': 'আক্ষেপ', 'Uneasiness': 'অস্বস্তি', 'Thirstless': 'তৃষ্ণাহীন',
    'Rough': 'খসখসে', 'Acrid': 'ঝাঁঝালো', 'Albuminous': 'অ্যালবুমিনযুক্ত',
    'Aphthæ': 'মুখের ঘা', 'Polypus': 'পলিপ', 'Tumor': 'টিউমার',
    'Varicose veins': 'ফোলা শিরা', 'Whooping': 'হুপিং কাশি',
    'Singing': 'গান গাওয়া', 'Dancing': 'নাচা', 'Winking': 'চোখ পিটপিট',
    'Torticollis': 'ঘাড় বেঁকে যাওয়া', 'Vaginismus': 'যোনি-আক্ষেপ',
    'Purpura': 'ত্বকে রক্তছোপ',

    # ---- frequent sub-rubric segments
    'sees': 'দেখে', 'root': 'গোড়া', 'nails': 'নখ', 'nail': 'নখ',
    'extending to arms': 'বাহু পর্যন্ত বিস্তৃত', 'extending to arm': 'বাহু পর্যন্ত বিস্তৃত',
    'œsophagus': 'খাদ্যনালি', 'vexation': 'মনঃক্ষোভ', 'sticking': 'খোঁচা',
    'crusts': 'মামড়ি', 'crusty': 'মামড়িযুক্ত', 'upper': 'উপরের',
    'riding': 'গাড়িতে চড়া', 'riding in a carriage': 'গাড়িতে চড়া',
    'downward': 'নিচের দিকে', 'urticaria': 'আমবাত', 'hard': 'শক্ত',
    'bend of': '-এর ভাঁজ', 'sacrum': 'ত্রিকাস্থি', 'smoking': 'ধূমপান',
    'right side': 'ডান দিক', 'left side': 'বাম দিক', 'wine': 'মদ',
    'herpes': 'হারপিস', 'extending': 'বিস্তৃত', 'over': 'উপরে',
    'moist': 'আর্দ্র', 'brain': 'মস্তিষ্ক', 'tips': 'ডগা', 'tips of': '-এর ডগা',
    'of the': '-এর', 'dark': 'গাঢ়', 'cold air': 'ঠান্ডা বাতাস',
    'trachea': 'শ্বাসনালি', 'noise': 'শব্দ', 'frequent': 'ঘন ঘন',
    'coffee': 'কফি', 'at': '-এ', 'touch agg.': 'স্পর্শে বৃদ্ধি',
    'into': '-এর ভিতরে', 'extending to chest': 'বুক পর্যন্ত বিস্তৃত',
    'deep': 'গভীর', 'periodical': 'পর্যায়ক্রমিক', 'periodic': 'পর্যায়ক্রমিক',
    'lying agg.': 'শোয়ায় বৃদ্ধি', 'lying amel.': 'শোয়ায় উপশম',
    'copious': 'প্রচুর', 'ulcerative': 'ক্ষতকারী', 'stepping': 'পা ফেলা',
    'intermittent': 'থেমে থেমে', 'drawing in': 'টানা ব্যথা',
    'lower jaw': 'নিচের চোয়াল', 'jaw': 'চোয়াল', 'glands': 'গ্রন্থি',
    'feet': 'পা', 'extending backward': 'পিছনের দিকে বিস্তৃত',
    'extending down back': 'পিঠ বেয়ে নিচে বিস্তৃত',
    'walking amel.': 'হাঁটায় উপশম', 'walking agg.': 'হাঁটায় বৃদ্ধি',
    'putrid': 'পচা', 'empty': 'খালি', 'convulsive': 'আক্ষেপিক',
    'as from a': 'যেন কিছু থেকে', 'anger': 'রাগ', 'tenesmus': 'কোঁথ',
    'posterior part': 'পিছনের অংশ', 'forward': 'সামনের দিকে',
    'cracking': 'কড়কড়', 'milk': 'দুধ', 'blowing nose': 'নাক ঝাড়া',
    'sensation as if': 'অনুভূতি যেন', 'retarded': 'বিলম্বিত',
    'one-sided': 'একপাশে', 'ankles': 'গোড়ালি', 'about': '-এর চারপাশে',
    'moving': 'নড়া', 'rumbling': 'গড়গড়', 'rest': 'বিশ্রাম', 'lost': 'হারানো',
    'hoarseness': 'স্বরভঙ্গ', 'wings': 'নাকের পাখা', 'open air': 'খোলা বাতাস',
    'glans': 'শিশ্নমুণ্ড', 'prepuce': 'লিঙ্গত্বক', 'violent': 'প্রচণ্ড',
    'vesicular': 'জলভরা', 'upwards': 'উপরের দিকে', 'dull pain': 'ভোঁতা ব্যথা',
    'children': 'শিশু', 'blue': 'নীল', 'thighs': 'উরু', 'roaring': 'গর্জন',
    'respiration': 'শ্বাস', 'epilepsy': 'মৃগী', 'chin': 'চিবুক',
    'inner side': 'ভিতরের দিক', 'ascending steps': 'সিঁড়ি ওঠা',
    'soreness': 'ঘা-ব্যথা', 'blood': 'রক্ত', 'behind the ear': 'কানের পিছনে',
    'warm': 'গরম', 'warmth agg.': 'উষ্ণতায় বৃদ্ধি', 'tonsils': 'টনসিল',
    'scratching agg.': 'আঁচড়ানোয় বৃদ্ধি', 'ringing': 'ঝনঝন',
    'around': 'চারপাশে', 'spasmodic': 'আক্ষেপিক', 'eczema': 'একজিমা',
    'in the': '-এ', 'fright': 'ভয় পাওয়া', 'flatus': 'বায়ু', 'beer': 'বিয়ার',
    'wrists': 'কবজি', 'washing': 'ধোয়া', 'parotid gland': 'কর্ণমূল গ্রন্থি',
    'mouth': 'মুখ', 'breathing': 'শ্বাস নেওয়া', 'below': 'নিচে',
    'becoming': 'হয়ে যাওয়া', 'lying on back': 'চিৎ হয়ে শোয়া',
    'and region of': 'এবং -এর অঞ্চল', 'painless': 'ব্যথাহীন', 'must': 'অবশ্যই',
    'music': 'সঙ্গীত', 'ilium': 'শ্রোণীচক্রের হাড়', 'by': '-এর দ্বারা',
    'sole of': '-এর তলা', 'hot': 'গরম', 'ball of': '-এর মাংসল অংশ',
    'singing': 'গান গাওয়া', 'sitting agg.': 'বসায় বৃদ্ধি',
    'standing agg.': 'দাঁড়ানোয় বৃদ্ধি', 'drinking agg.': 'পানে বৃদ্ধি',
    'swallowing agg.': 'গেলায় বৃদ্ধি', 'uncovering agg.': 'অনাবৃত করায় বৃদ্ধি',
    'stool, during': 'মলত্যাগের সময়', 'urination, during': 'মূত্রত্যাগের সময়',
    'covered parts': 'আবৃত অংশ', 'affected parts': 'আক্রান্ত অংশ',
    'single parts': 'একক অংশ', 'upper part of body': 'শরীরের উপরের অংশ',
})

# A third pass, authored against a full frequency count of every segment left
# untranslated after the first two passes — anatomy, modalities, qualities and
# connectives that recur across many chapters rather than one.
SEG.update({
    # ---- anatomy
    'stomach': 'পাকস্থলী', 'lungs': 'ফুসফুস', 'spleen': 'প্লীহা',
    'zygoma': 'জাইগোমা (গালের হাড়)', 'throat-pit': 'গলার খাঁজ',
    'tendons': 'রগ', 'molars': 'পেষণ দাঁত', 'perineum': 'পেরিনিয়াম',
    'posterior nares': 'নাকের পিছনের ছিদ্র', 'tendo Achillis': 'গোড়ালির রগ',
    'nipples': 'বৃন্ত', 'legs': 'পা', 'arm': 'বাহু', 'arms': 'বাহু',
    'face': 'মুখমণ্ডল', 'shoulders': 'কাঁধ', 'muscles': 'পেশি',
    'eyebrows': 'ভুরু', 'spermatic cord': 'শুক্রনালি', 'periosteum': 'অস্থিআবরণী',
    'eye': 'চোখ', 'ear': 'কান', 'ureters': 'মূত্রনালি (কিডনি থেকে)',
    'hypochondrium': 'পাঁজরের নিচের পার্শ্বদেশ', 'olecranon': 'কনুইয়ের হাড়',
    'metacarpal': 'হাতের তালুর হাড়', 'uvula': 'গলবিল ঝুলন্ত অংশ',
    'soles': 'পায়ের তলা', 'jaws': 'চোয়াল', 'pharynx': 'গলবিল',
    'septum': 'পর্দা (নাকের)', 'scapula': 'কাঁধের হাড়', 'axilla': 'বগল',
    'eminence frontal': 'কপালের উঁচু অংশ', 'fourth finger': 'অনামিকা',
    'flexor muscles': 'সংকোচক পেশি', 'crest of': '-এর শিরদাঁড়া',
    'canine': 'শ্বদন্ত (কুকুর দাঁত)', 'æsophagus': 'খাদ্যনালি',
    'trachea': 'শ্বাসনালি', 'ilium': 'শ্রোণীচক্রের হাড়',
    'index finger': 'তর্জনী', 'between index finger and thumb': 'তর্জনী ও বুড়ো আঙুলের মাঝে',
    'inner side of': '-এর ভিতরের দিক', 'outer side': 'বাইরের দিক',
    'outer': 'বাইরের', 'inner': 'ভিতরের', 'external': 'বাহ্যিক',
    'internal': 'অভ্যন্তরীণ', 'internally': 'ভিতরে',
    'lower part': 'নিচের অংশ', 'first part of': '-এর প্রথম অংশ',
    'middle of': '-এর মাঝামাঝি', 'centre': 'কেন্দ্র', 'margins': 'প্রান্ত',
    'edges': 'কিনারা', 'tip of': '-এর ডগা', 'tips of': '-এর ডগা',

    # ---- qualities / colours
    'greenish': 'সবুজাভ', 'gray': 'ধূসর', 'purple': 'বেগুনি',
    'light': 'হালকা', 'elevated': 'উঁচু', 'bent': 'বাঁকা',
    'wet': 'ভেজা', 'dry heat': 'শুষ্ক উত্তাপ', 'bile': 'পিত্ত',
    'wanting': 'ঘাটতি', 'raw and smarting': 'কাঁচা ও চিড়িক দেওয়া',
    'herpetic': 'হারপিস-জাতীয়', 'backward': 'পিছনের দিকে',
    'chronic': 'দীর্ঘস্থায়ী', 'weather': 'আবহাওয়া', 'inward': 'ভিতরের দিকে',
    'thunderstorm': 'বজ্রঝড়', 'tender': 'কোমল-সংবেদনশীল',
    'old people': 'বয়স্ক মানুষ', 'in spots': 'ছোপ ছোপ',
    'excessive': 'অতিরিক্ত', 'burnt': 'পোড়া', 'scales': 'আঁশ',
    'loud': 'জোরালো', 'soup': 'স্যুপ', 'eggs': 'ডিম', 'sand': 'বালি',
    'purulent': 'পুঁজযুক্ত', 'fetid': 'দুর্গন্ধযুক্ত', 'erect': 'খাড়া',
    'contracting': 'সংকুচিত হওয়া', 'blackness': 'কালচে ভাব',
    'tobacco': 'তামাক', 'syphilitic': 'সিফিলিসজনিত', 'stunning': 'হতবুদ্ধিকর',
    'inflamed': 'প্রদাহযুক্ত', 'scurfy': 'খুশকির মতো', 'patches': 'ছোপ',
    'mercury': 'পারদ', 'meat': 'মাংস', 'gouty': 'গেঁটেবাত-জনিত',
    'voluptuous': 'কামোত্তেজক', 'rapid': 'দ্রুত', 'erysipelatous': 'বিসর্পসদৃশ',
    'irregular': 'অনিয়মিত', 'measles': 'হাম', 'mortification': 'পচন',
    'winter': 'শীতকাল', 'splinter': 'কাঁটা ফোটার মতো', 'scaly': 'আঁশযুক্ত',
    'scabby': 'মামড়িযুক্ত', 'pork': 'শূকরের মাংস', 'impossible': 'অসম্ভব',
    'every': 'প্রতিটি', 'dysuria': 'কষ্টকর মূত্রত্যাগ', 'death': 'মৃত্যু',
    'milky': 'দুধের মতো', 'heated': 'উত্তপ্ত', 'drinks': 'পানীয়',
    'warmth': 'উষ্ণতা', 'flushes': 'ঝলকানি', 'exercise': 'ব্যায়াম',
    'animals': 'প্রাণী', 'small': 'ছোট', 'sharp': 'তীক্ষ্ণ',
    'only': 'শুধুমাত্র', 'foul': 'দুর্গন্ধযুক্ত', 'excoriating': 'ছিলে-দেওয়া',
    'rawness': 'কাঁচা-ব্যথা', 'stomach (Includes complaints after)': 'পাকস্থলী',
    'sweetish': 'মিষ্টি-স্বাদ', 'chewing': 'চিবানো', 'fruit': 'ফল',
    'bread': 'রুটি', 'cold drinks': 'ঠান্ডা পানীয়', 'warm drinks': 'গরম পানীয়',
    'cold water': 'ঠান্ডা জল', 'coffee': 'কফি', 'wine': 'মদ',
    'people': 'মানুষ', 'children': 'শিশু', 'drunkards': 'মদ্যপায়ী',
    'automatic': 'স্বতঃস্ফূর্ত', 'induration': 'কাঠিন্য (দৃঢ়তা)',
    'expression': 'ভাবপ্রকাশ', 'ghosts': 'ভূত', 'ravenous': 'ক্ষুধার্ত-তীব্র',
    'periodical': 'পর্যায়ক্রমিক', 'periodic': 'পর্যায়ক্রমিক',
    'buzzing': 'গুনগুন শব্দ', 'humming': 'গুনগুন শব্দ', 'hawking': 'গলা পরিষ্কারের চেষ্টা',
    'kneeling': 'হাঁটু গেড়ে বসা', 'diplopia': 'দ্বৈত দৃষ্টি',
    'pupils contracted': 'চোখের মণি সংকুচিত',

    # ---- modality / time connectives
    'to left': 'বাম দিকে', 'to right': 'ডান দিকে', 'behind ear': 'কানের পিছনে',
    'behind ears': 'কানের পিছনে', 'behind': 'পিছনে', 'above the ear': 'কানের উপরে',
    'damp weather': 'স্যাঁতসেঁতে আবহাওয়া', 'cold weather': 'ঠান্ডা আবহাওয়া',
    'wet weather': 'ভেজা আবহাওয়া', 'labor': 'প্রসব', 'labor pains': 'প্রসব ব্যথা',
    'when not': 'না হলে', 'speaking': 'কথা বলা', 'sensation': 'অনুভূতি',
    'sensation of in': '-এর মধ্যে অনুভূতি', 'periodic headache': 'পর্যায়ক্রমিক মাথাব্যথা',
    'turning head': 'মাথা ঘোরানো', 'lifting': 'তোলা',
    'while sitting': 'বসে থাকা অবস্থায়', 'twinging': 'চিড়িক ব্যথা',
    'expiration': 'শ্বাস ছাড়া', 'evening in bed': 'সন্ধ্যায় বিছানায়',
    'after a': '-এর পরে', 'on the back': 'পিঠের উপর', 'of being': 'হওয়ার',
    'fasting': 'উপবাস', 'excessive fasting': 'অতিরিক্ত উপবাস',
    'sewing': 'সেলাই করা', 'on back': 'পিঠের উপর',
    'eructations amel.': 'ঢেঁকুরে উপশম', 'emissions': 'ক্ষরণ',
    'dark in spots anterior portion': 'সামনের অংশে গাঢ় ছোপ',
    'warmth of bed': 'বিছানার উষ্ণতা', 'move': 'নড়া',
    'walk': 'হাঁটা', 'falling asleep': 'ঘুমিয়ে পড়া',
    'while walking': 'হাঁটার সময়', 'then left': 'তারপর বাম দিকে',
    'then right': 'তারপর ডান দিকে', 'suppurating': 'পুঁজ হওয়া',
    'stupefying': 'মূঢ়তাকর', 'siesta': 'দুপুরের ঘুম',
    'on beginning to': 'শুরু করার সময়', 'in a': '-এর মধ্যে',
    'fire': 'আগুন', 'fast': 'দ্রুত', 'emission': 'ক্ষরণ',
    'without': 'ছাড়া', 'on entering': 'প্রবেশ করার সময়',
    'before going to': 'যাওয়ার আগে', 'alone': 'একা', 'after rising': 'ওঠার পরে',
    'after abuse of': '-এর অপব্যবহারের পরে', 'urging to urinate': 'মূত্রত্যাগের বেগ',
    'until': 'পর্যন্ত', 'on becoming': 'হয়ে যাওয়ার সময়',
    'in cold': 'ঠান্ডায়', 'after lying down': 'শুয়ে পড়ার পরে',
    'during the': 'সময়ে', 'stooping agg.': 'ঝুঁকায় বৃদ্ধি',
    'side lain on': 'যে পাশে শোয়া হয়েছিল', 'scratching amel.': 'আঁচড়ানোয় উপশম',
    'on rising': 'ওঠার সময়', 'extending to fingers': 'আঙুল পর্যন্ত বিস্তৃত',
    'down': 'নিচে', 'warm drinks agg.': 'গরম পানীয়ে বৃদ্ধি',
    'undressing': 'কাপড় খোলা', 'lying on left side': 'বাম কাতে শোয়া',
    'increased': 'বর্ধিত', 'extending to eyes': 'চোখ পর্যন্ত বিস্তৃত',
    'extending arm and fingers': 'বাহু ও আঙুল পর্যন্ত বিস্তৃত',
    'eating amel.': 'খাওয়ায় উপশম', 'boring in': '-এ বিদ্ধকারী',
    'rubbing agg.': 'ঘষায় বৃদ্ধি', 'rising from bed': 'বিছানা থেকে ওঠা',
    'raising arm': 'বাহু তোলা', 'extending to elbow': 'কনুই পর্যন্ত বিস্তৃত',
    'cold air agg.': 'ঠান্ডা বাতাসে বৃদ্ধি', 'after taking': 'খাওয়ার পরে',
    'from a': '-থেকে', 'to axilla': 'বগল পর্যন্ত',
    'after scratching': 'আঁচড়ানোর পরে', 'to ear': 'কান পর্যন্ত',
    'on the': '-এর উপর', 'on falling asleep': 'ঘুমিয়ে পড়ার সময়',
    'extending toward arms': 'বাহুর দিকে বিস্তৃত', 'extending to ears': 'কান পর্যন্ত বিস্তৃত',
    'bending head backward': 'মাথা পিছনে হেলানো', 'alternating sides': 'পাশ পরিবর্তন',
    'trifles': 'তুচ্ছ বিষয়', 'pressure in': '-এ চাপ', 'pressing (pressure)': 'চাপ',
    'lying on it': 'তার উপর শুয়ে', 'like a': '-এর মতো', 'lain on': 'শুয়ে থাকা',
    'from becoming': 'হয়ে যাওয়া থেকে', 'extending downwards': 'নিচের দিকে বিস্তৃত',
    'cold applications amel.': 'ঠান্ডা প্রয়োগে উপশম', 'bending forward': 'সামনে ঝোঁকা',
    'at night': 'রাতে', 'sitting amel.': 'বসায় উপশম',
    'from taking': 'নেওয়া থেকে', 'after eating': 'খাওয়ার পরে',
    'weakness of': '-এর দুর্বলতা', 'sleep amel.': 'ঘুমে উপশম',
    'one side': 'একপাশ', 'during menses': 'ঋতুস্রাবের সময়',
    'extending upward': 'উপরের দিকে বিস্তৃত', 'extending to ankle': 'গোড়ালি পর্যন্ত বিস্তৃত',
    'extending into abdomen': 'উদর পর্যন্ত বিস্তৃত', 'up the back': 'পিঠ বেয়ে উপরে',
    'sun': 'রোদ', 'step': 'পা ফেলা', 'sensation of in': '-এ অনুভূতি',
    'on left side': 'বাম দিকে', 'in front of ear': 'কানের সামনে',
    'extending to ankles': 'গোড়ালি পর্যন্ত বিস্তৃত',
    'with (fluent)': 'সহ (প্রবহমান)', 'small': 'ছোট', 'sideways': 'পাশাপাশি',
    'sexual excesses': 'যৌন বাড়াবাড়ি', 'rapidly': 'দ্রুত', 'passing': 'চলে যাওয়া',
    'parturition': 'প্রসব', 'knees': 'হাঁটু',

    # ---- mental / general
    'must wait for urine to start': 'মূত্র শুরু হতে অপেক্ষা করতে হয়',
    'Felon (Onychia': 'নখের গোড়ায় পুঁজ (ওনিকিয়া',
    'Inflammation bronchial tubes (bronchitis)': 'শ্বাসনালির প্রদাহ (ব্রংকাইটিস)',
    'Congestion (hyperæmia of chest)': 'রক্তসঞ্চয় (বুকে অতিরিক্ত রক্তপ্রবাহ)',
    'extending along spine in zig-zags to scapular region': 'মেরুদণ্ড বরাবর আঁকাবাঁকা হয়ে কাঁধের হাড় পর্যন্ত বিস্তৃত',
    'ascending stairs': 'সিঁড়ি ওঠা', 'Chill absent': 'কম্প অনুপস্থিত',
    'Beginning in and extending from abdomen': 'উদর থেকে শুরু হয়ে বিস্তৃত',
    'warmth amel.': 'উষ্ণতায় উপশম', 'Taste of almonds': 'কাঠবাদামের স্বাদ',
    'or as if brushing something away': 'যেন কিছু সরিয়ে দিচ্ছে',
    'as if brushing the face': 'যেন মুখ থেকে কিছু সরাচ্ছে',
    'Itching of scalp': 'মাথার ত্বকে চুলকানি',
    'rawness (includes trachea and bronchia)': 'কাঁচা-ব্যথা (শ্বাসনালি সহ)',
    'extending to left side of abdomen': 'উদরের বাম পাশ পর্যন্ত বিস্তৃত',
    'Twitching of muscles of the head': 'মাথার পেশির লাফানো',
    'Tickling in the air passages': 'শ্বাসনালিতে সুড়সুড়ি',
    'Looseness of brain': 'মস্তিষ্কের আলগা ভাব', 'Eruptions about the eyes': 'চোখের চারপাশে উদ্ভেদ',
    'Burning heat': 'জ্বালাপোড়া উত্তাপ', 'Succession of stages': 'ধাপে ধাপে ঘটা',
    'Stopped sensation': 'থেমে যাওয়ার অনুভূতি', 'warm room agg.': 'গরম ঘরে বৃদ্ধি',
    'Paralysis agitans': 'কম্পন-পক্ষাঘাত (পার্কিনসন্স)', 'Shaking sensation': 'কম্পনের অনুভূতি',
    'Pulsation externally': 'বাইরে স্পন্দন', 'Stretched out hand': 'হাত প্রসারিত করা',
    'Looking with eyes turned': 'চোখ ঘুরিয়ে তাকানো', 'Heat in': '-এ উত্তাপ',
    'Enlarged sensation': 'বড় হয়ে যাওয়ার অনুভূতি', 'Arrested': 'থেমে যাওয়া',
    'Swelling in general': 'সাধারণভাবে ফোলা', 'Odor offensive': 'দুর্গন্ধযুক্ত গন্ধ',
    'Motions of head (shaking': 'মাথার নড়াচড়া (কাঁপানো',
    'Discharges of mucus or pus': 'শ্লেষ্মা বা পুঁজের স্রাব',
    'Mistakes in calculating': 'হিসাবে ভুল', 'Memory active': 'সক্রিয় স্মৃতিশক্তি',
    'Indolence': 'আলস্য', 'Falling backward of head': 'মাথা পিছনে হেলে পড়া',
    'Company aversion to': 'সঙ্গে থাকায় অনীহা', 'Sparks': 'ফুলকি',
    'Mucus in the air passages': 'শ্বাসনালিতে শ্লেষ্মা', 'Movements in': '-এ নড়াচড়া',
    'Involuntary stool': 'অনিচ্ছাকৃত মলত্যাগ', 'Forgetful': 'ভুলে যাওয়া স্বভাব',
    'Dry heat': 'শুষ্ক উত্তাপ', 'Disturbed': 'বিঘ্নিত', 'Caries of bone': 'অস্থিক্ষয়',
    'Twitching and jerking': 'পেশির লাফানো ও ঝাঁকানো', 'Retraction': 'সংকোচন-প্রত্যাহার',
    'Milk absent': 'দুধ না হওয়া', 'Enlargement': 'বৃদ্ধি (আকারে)', 'Colors': 'রঙ',
    'Smell': 'ঘ্রাণ', 'Rage': 'ক্রোধ', 'Mirth': 'হাস্যরস', 'Lochia': 'প্রসবোত্তর স্রাব',
    'Indigestion (Includes Complaints After Substances Not Otherwise Described)': 'বদহজম',
    'Bleeding': 'রক্তক্ষরণ', 'Prolapsus': 'স্খলন (নিচে নেমে আসা)',
    'Prolapsus uterus': 'জরায়ু স্খলন', 'Indurations': 'কাঠিন্য',
    'Glittering objects': 'ঝলমলে বস্তু', 'Fancies': 'কল্পনা', 'Fall': 'পতন',
    'Despair': 'হতাশা', 'Corns': 'পায়ের কড়া', 'Abortion': 'গর্ভপাত',
    'Kill': 'হত্যা করার ইচ্ছা', 'Cicatrices': 'ক্ষতচিহ্ন', 'Catching': 'ধরে ফেলার অনুভূতি',
    'waterbrash': 'টক ঢেঁকুর', 'spectres': 'ভূতুড়ে দৃশ্য',
    'sensation of in': '-এ অনুভূতি', 'phantoms': 'অলীক দৃশ্য',
    'olecranon': 'কনুইয়ের হাড়', 'discharges albuminous': 'অ্যালবুমিনযুক্ত স্রাব',
    'Laryngismus stridulus': 'শ্বাসকষ্টজনিত স্বরযন্ত্র-আক্ষেপ', 'Exhausting': 'ক্লান্তিকর',
    'Bloated': 'ফোলা-ভাব', 'Warts upper limbs': 'হাতে আঁচিল', 'Drawn apart': 'আলাদা টানা',
    'storm': 'ঝড়', 'palpitation': 'হৃদস্পন্দন বৃদ্ধি', 'is': 'হয়',
    'house': 'ঘর', 'hips': 'নিতম্ব', 'heat agg.': 'উত্তাপে বৃদ্ধি',
    'gangrenous': 'পচনশীল', 'fluid': 'তরল', 'faces': 'মুখমণ্ডল',
    'epileptic': 'মৃগীজনিত', 'dirty': 'নোংরা',
    'work': 'কাজ', 'visions': 'দর্শন', 'to the': '-এর দিকে',
    'rawness in air passages': 'শ্বাসনালিতে কাঁচা-ব্যথা', 'images': 'প্রতিচ্ছবি',
    'labor-like': 'প্রসবব্যথার মতো', 'clawing': 'নখর দিয়ে আঁচড়ানোর মতো',
    'between the fingers': 'আঙুলের মাঝে',
})

# A fourth pass, continuing down the frequency tail.
SEG.update({
    # ---- modalities / connectives
    'burrowing': 'গর্ত খোঁড়ার মতো', 'falling': 'পড়ে যাওয়া',
    'increased (hunger in general)': 'বর্ধিত (সাধারণভাবে ক্ষুধা)',
    'constant': 'অবিরাম', 'touched': 'স্পর্শ করা হলে', 'extending brain': 'মস্তিষ্ক পর্যন্ত বিস্তৃত',
    'extending to eye': 'চোখ পর্যন্ত বিস্তৃত', 'fifth': 'পঞ্চম', 'and': 'এবং',
    'Swelling of': '-এর ফোলা', 'Orgasm of blood': 'রক্তের উত্তেজনা', 'Impeded': 'বাধাপ্রাপ্ত',
    'closing eyes': 'চোখ বন্ধ করা', 'Position': 'অবস্থান', 'Odor (breath)': 'গন্ধ (নিঃশ্বাসের)',
    'rubbing': 'ঘষা', 'morning on waking': 'সকালে জাগার পর', 'lying on the back': 'চিৎ হয়ে শোয়া',
    'for': '-এর জন্য', 'feather bed agg.': 'পালকের বিছানায় বৃদ্ধি',
    'dribbling (by drops)': 'ফোঁটা ফোঁটা ঝরা', 'bending backward': 'পিছনে বাঁকা',
    'bending': 'বাঁকা হওয়া', 'aversion to': '-এ অনীহা', 'warm bed': 'গরম বিছানা',
    'cold agg.': 'ঠান্ডায় বৃদ্ধি', 'warmth of bed agg.': 'বিছানার উষ্ণতায় বৃদ্ধি',
    'teeth': 'দাঁত', 'objects seem': 'বস্তু মনে হয়', 'objects': 'বস্তু',
    'everything is': 'সবকিছু মনে হয়', 'brownish': 'বাদামি আভা', 'blueness': 'নীলচে ভাব',
    'beaten (tenderness)': 'পিটুনির মতো (স্পর্শকাতরতা)', 'Spasms': 'আক্ষেপ',
    'shaking head': 'মাথা কাঁপানো', 'food (regurgitation)': 'খাদ্য (উগরে ওঠা)',
    'elevations': 'উঁচু অংশ', 'lying on painful side agg.': 'ব্যথার পাশে শোয়ায় বৃদ্ধি',
    'followed by': '-এর পরে হয়', 'during sleep': 'ঘুমের সময়', 'down back': 'পিঠ বেয়ে নিচে',
    'dead': 'মৃত', 'continued': 'চলমান', 'candlelight': 'মোমবাতির আলো',
    'alternating with headache': 'মাথাব্যথার সাথে পর্যায়ক্রমে', 'above the knee': 'হাঁটুর উপরে',
    'Suffocative': 'শ্বাসরোধকারী', 'Sinking': 'ডুবে যাওয়ার অনুভূতি', 'Restless': 'অস্থির',
    'Fluttering': 'ফরফর কম্পন', 'Desire diminished': 'ইচ্ছা হ্রাস', 'Answers': 'উত্তর দেওয়া',
    'to hip': 'নিতম্ব পর্যন্ত', 'temple': 'রগ', 'rushing': 'তাড়াহুড়ো করা',
    'quickly': 'দ্রুত', 'noise agg.': 'শব্দে বৃদ্ধি', 'night in bed': 'রাতে বিছানায়',
    'moving head': 'মাথা নাড়ানো', 'lower part of': '-এর নিচের অংশ', 'hunger': 'ক্ষুধা',
    'hears': 'শোনে', 'from stooping': 'ঝোঁকা থেকে', 'fossa navicularis': 'নাভিকুলার খাঁজ',
    'feeling': 'অনুভূতি', 'extending to head': 'মাথা পর্যন্ত বিস্তৃত', 'diminished': 'হ্রাসপ্রাপ্ত',
    'coppery': 'তামাটে রঙের', 'conversation': 'কথোপকথন', 'confluent': 'মিলিত-একত্রিত',
    'circles': 'বৃত্ত', 'ascends': 'উপরে ওঠে',
    'alternating with abdominal and uterine symptoms': 'উদর ও জরায়ুর উপসর্গের সাথে পর্যায়ক্রমে',
    'after amel.': '-এর পরে উপশম', 'about the ear': 'কানের চারপাশে', 'Varices': 'শিরা ফুলে যাওয়া',
    'Tension of skin': 'ত্বকের টান', 'Talk': 'কথা বলা', 'Flexed': 'ভাঁজ করা',
    'warmth of bed amel.': 'বিছানার উষ্ণতায় উপশম', 'turning in bed': 'বিছানায় পাশ ফেরা',
    'tremulous': 'কম্পিত', 'tearing away': 'ছিঁড়ে ফেলার মতো', 'summer': 'গ্রীষ্মকাল',
    'spring': 'বসন্তকাল', 'rising up': 'উঠে দাঁড়ানো', 'rising from stooping': 'ঝোঁকা থেকে ওঠা',
    'right to left': 'ডান থেকে বাম', 'reddish': 'লালচে', 'rancid': 'বাসি-গন্ধযুক্ত',
    'pursued': 'তাড়া করা হচ্ছে', 'psoriasis': 'সোরিয়াসিস', 'points': 'বিন্দু',
    'plug': 'বন্ধ হয়ে থাকা', 'paroxysms': 'তীব্র পর্যায়', 'open air amel.': 'খোলা বাতাসে উপশম',
    'on the side': 'পাশে', 'morning in bed': 'সকালে বিছানায়', 'looking': 'তাকানো',
    'innumerable': 'অগণিত', 'indurated margins': 'কঠিন কিনারা', 'horses': 'ঘোড়া',
    'groin': 'কুঁচকি', 'extending to left scapula': 'বাম কাঁধের হাড় পর্যন্ত বিস্তৃত',
    'extending to coccyx while sitting': 'বসে থাকলে পুচ্ছাস্থি পর্যন্ত বিস্তৃত',
    'extending to bladder': 'মূত্রথলি পর্যন্ত বিস্তৃত', 'extending back': 'পিছনে বিস্তৃত',
    'exalted': 'উৎফুল্ল', 'disease': 'রোগ', 'colic': 'উদরশূল', 'blue spots': 'নীল ছোপ',
    'as of': '-এর মতো', 'anxious': 'উদ্বিগ্ন', 'accelerated': 'ত্বরান্বিত',
    'Seminal discharge': 'শুক্রস্রাব', 'Relaxation': 'শিথিলতা',
    'Quiet disposition': 'শান্ত স্বভাব', 'Creeping': 'সরসর করে চলার অনুভূতি',
    'Caries': 'অস্থিক্ষয়', 'Bubbling sensation': 'বুদবুদ ওঠার অনুভূতি',
    'Alternating with chills': 'কম্পের সাথে পর্যায়ক্রমে', 'warm bed agg.': 'গরম বিছানায় বৃদ্ধি',
    'urine': 'প্রস্রাব', 'twilight': 'গোধূলি', 'to back': 'পিঠ পর্যন্ত', 'third finger': 'মধ্যমা',
    'straining at': '-এ কোঁথ দেওয়া', 'sleeping': 'ঘুমানো', 'shining': 'চকচকে',
    'preventing': 'বাধা দেওয়া', 'lying down amel.': 'শুয়ে পড়ায় উপশম', 'large': 'বড়',
    'if': 'যদি', 'grasping anything': 'কিছু ধরে রাখা', 'grasping': 'ধরে রাখা',
    'from a seat': 'আসন থেকে', 'extending into arms': 'বাহুর মধ্যে বিস্তৃত',
    'dislocation': 'স্থানচ্যুতি', 'cutting in': '-এ কাটা ব্যথা', 'cheek': 'গাল',
    'brown spots': 'বাদামি ছোপ', 'before the': '-এর আগে', 'aura': 'পূর্বাভাস',
    'angle of': '-এর কোণ', 'abdomen to head': 'উদর থেকে মাথা পর্যন্ত',
    'Sexual passion diminished': 'যৌন আকাঙ্ক্ষা হ্রাস', 'Predominating': 'প্রধান হওয়া',
    'Induration axillary glands': 'বগলের গ্রন্থির কাঠিন্য', 'Impatience': 'অধৈর্য',
    'Hæmorrhage from anus': 'পায়ু দিয়ে রক্তক্ষরণ', 'Hemiopia': 'অর্ধেক দৃষ্টিক্ষেত্র',
    'Froth': 'ফেনা', 'External heat': 'বাহ্যিক উত্তাপ', 'Emission prostatic fluid': 'প্রস্টেট তরল ক্ষরণ',
    'Disordered': 'বিশৃঙ্খল', 'Croupy': 'ক্রুপ-জাতীয়',
    'without (dry)': 'ছাড়া (শুষ্ক)', 'with the': '-এর সাথে', 'whitish': 'সাদাটে',
    'while half awake': 'অর্ধজাগ্রত অবস্থায়', 'vaccination': 'টিকা', 'submaxillary gland': 'নিচের চোয়ালের গ্রন্থি',
    'persistent': 'অবিরাম', 'night agg.': 'রাতে বৃদ্ধি', 'lying on side': 'কাত হয়ে শোয়া',
    'left side agg.': 'বাম দিকে বৃদ্ধি', 'incomplete': 'অসম্পূর্ণ', 'ice cream': 'আইসক্রিম',
    'extending backward over ears': 'কানের উপর দিয়ে পিছনে বিস্তৃত', 'everything': 'সবকিছু',
    'desire to': '-এর ইচ্ছা', 'desire for': '-এর ইচ্ছা', 'crampy': 'খিঁচুনি-সদৃশ',
    'corrosive': 'ক্ষয়কারী', 'concha': 'কানের খোল', 'body adherent to woollen sack': 'শরীর পশমি থলিতে আটকে আছে',
    'bathing': 'স্নান', 'apyrexia': 'জ্বরহীন অবস্থা', 'aching deep in': '-এর গভীরে ভোঁতা ব্যথা',
    'Prostration of mind': 'মনের অবসাদ', 'Moaning': 'গোঙানো', 'Arthritic nodosities': 'বাতজনিত গাঁট',
    'Anguish': 'তীব্র মনোকষ্ট',
    'walking in open air amel.': 'খোলা বাতাসে হাঁটায় উপশম', 'visions of': '-এর দর্শন',
    'to fingers': 'আঙুল পর্যন্ত', 'that he is': 'যে সে', 'tasting like': '-এর স্বাদ',
    'taciturn': 'স্বল্পভাষী', 'soft': 'নরম', 'rush of': '-এর হঠাৎ প্রবাহ', 'running': 'দৌড়ানো',
    'rhythmical': 'ছন্দময়', 'nipple': 'বৃন্ত', 'long': 'দীর্ঘ', 'left to right': 'বাম থেকে ডান',
    'ineffectual': 'নিষ্ফল', 'indisposed to': '-এ অনিচ্ছুক', 'in open air amel.': 'খোলা বাতাসে উপশম',
    'horny': 'শক্ত-শিংয়ের মতো', 'heat amel.': 'উত্তাপে উপশম', 'foreign body': 'বহিরাগত বস্তু',
    'extending to thigh': 'উরু পর্যন্ত বিস্তৃত', 'extending to clavicle': 'কণ্ঠাস্থি পর্যন্ত বিস্তৃত',
    'expectoration': 'কফ তোলা', 'desquamation': 'ত্বক খসে পড়া', 'desire to be silent': 'চুপ থাকার ইচ্ছা',
    'daytime only': 'শুধু দিনের বেলা', 'compelled to': 'বাধ্য হওয়া', 'busily occupied': 'ব্যস্ত থাকা',
    'blisters': 'ফোস্কা', 'black and painful spots': 'কালো ও ব্যথাযুক্ত ছোপ',
    'at beginning of': '-এর শুরুতে', 'are': 'আছে', 'after dinner': 'দুপুরের খাবারের পরে',
    'across': 'আড়াআড়ি', 'abuse of': '-এর অপব্যবহার', 'Weariness': 'ক্লান্তি',
    'Trembling and shivering': 'কম্পন ও শীতে কাঁপা', 'Protruded': 'বেরিয়ে আসা',
    'Phthisis pulmonalis': 'ফুসফুসের যক্ষ্মা', 'Mucous membrane': 'শ্লেষ্মা ঝিল্লি',
    'Foreign body': 'বহিরাগত বস্তু', 'Exposure': 'উন্মুক্ত হওয়া', 'Eruption about anus': 'পায়ুর চারপাশে উদ্ভেদ',
    'Dazzling': 'ঝলসে দেওয়া', 'Ball': 'বলের মতো', 'Accelerated': 'ত্বরান্বিত',
    'worms': 'কৃমি', 'warm drinks amel.': 'গরম পানীয়ে উপশম', 'upper part': 'উপরের অংশ',
    'to arms': 'বাহু পর্যন্ত', 'tea': 'চা', 'suppressed eruptions': 'রুদ্ধ উদ্ভেদ',
    'splinters': 'কাঁটা ফোটার মতো', 'sound of': '-এর শব্দ', 'potatoes': 'আলু',
    'overheated': 'অতিরিক্ত গরম হওয়া', 'mottled': 'ছিটছিট দাগযুক্ত', 'margin': 'কিনারা',
    'malleolus': 'গোড়ালির হাড়', 'lying in bed': 'বিছানায় শোয়া', 'lobes': 'কানের লতি',
    'letters': 'চিঠি', 'lasting all night': 'সারা রাত স্থায়ী', 'last': 'সর্বশেষ',
    'jarring agg.': 'ঝাঁকুনিতে বৃদ্ধি', 'inspiration agg.': 'শ্বাস নেওয়ায় বৃদ্ধি',
    'fish': 'মাছ', 'extending to axilla (left)': 'বগল পর্যন্ত বিস্তৃত (বাম)', 'enlarged': 'বড় হয়ে যাওয়া',
    'electric-like': 'বিদ্যুতের মতো', 'desquamating': 'খসে পড়া', 'damp': 'স্যাঁতসেঁতে',
    'condyles': 'অস্থিসন্ধির উঁচু অংশ', 'coagulated': 'জমাট বাঁধা', 'cheese': 'পনির',
    'breath': 'নিঃশ্বাস', 'between fingers': 'আঙুলের মাঝে', 'bending backward amel.': 'পিছনে বাঁকায় উপশম',
    'alternating with cheerfulness': 'প্রফুল্লতার সাথে পর্যায়ক্রমে', 'after getting': 'পাওয়ার পরে',
    'acids': 'অম্লজাতীয়', 'acid': 'অম্ল', 'Shocks from injury': 'আঘাত থেকে ধাক্কা',
    'Nodules': 'গাঁট', 'Memory': 'স্মৃতিশক্তি', 'Jerking of the head': 'মাথার ঝাঁকি',
    'Interrupted': 'বাধাপ্রাপ্ত', 'Injuries': 'আঘাত', 'Ideas abundant': 'অতিরিক্ত চিন্তা',
    'Discontented': 'অসন্তুষ্ট', 'Croup': 'ক্রুপ', 'Cold in general agg.': 'সাধারণভাবে ঠান্ডায় বৃদ্ধি',
    'while lying': 'শুয়ে থাকা অবস্থায়', 'ulna': 'কনুইয়ের হাড়', 'transparent': 'স্বচ্ছ',
    'toward': '-এর দিকে', 'to left hand': 'বাম হাত পর্যন্ত', 'to feet': 'পা পর্যন্ত',
    'talking agg.': 'কথা বলায় বৃদ্ধি', 'spot': 'ছোপ', 'smell of': '-এর গন্ধ',
    'rest agg.': 'বিশ্রামে বৃদ্ধি', 'pricking': 'সূচ ফোটানো', 'perspiration amel.': 'ঘামে উপশম',
    'on the cornea': 'কর্নিয়ার উপর', 'nursing': 'স্তন্যদান', 'must run and pass a little urine': 'দৌড়ে গিয়ে সামান্য প্রস্রাব করতে হয়',
    'lying on right side': 'ডান কাতে শোয়া', 'lumbo-sacral region': 'কটি-ত্রিক অঞ্চল',
    'hanging down': 'ঝুলে থাকা', 'gonorrhœa': 'প্রমেহ', 'genitals': 'জননাঙ্গ',
    'frightful': 'ভয়ংকর', 'flat': 'চ্যাপ্টা', 'first finger': 'তর্জনী', 'finger': 'আঙুল',
    'extending to nape of neck': 'ঘাড়ের পিছন পর্যন্ত বিস্তৃত', 'extending down arm': 'বাহু বেয়ে নিচে বিস্তৃত',
    'erection': 'লিঙ্গোত্থান', 'dull': 'ভোঁতা', 'downwards': 'নিচের দিকে',
    'crossing limbs': 'পা-হাত ক্রস করা', 'closing eyes amel.': 'চোখ বন্ধ করায় উপশম',
    'cheeks': 'গাল', 'brilliantly colored': 'উজ্জ্বল রঙের', 'bright': 'উজ্জ্বল',
    'body': 'শরীর', 'alternating with catarrh': 'সর্দির সাথে পর্যায়ক্রমে', 'aged people': 'বয়স্ক মানুষ',
    'a draft of': 'হঠাৎ বাতাসের ঝাপটা', 'Spots specks': 'ছোপ ও বিন্দু',
    'Shrivelled (shrunken)': 'কুঁচকে যাওয়া', 'Roughness upper limbs': 'হাতে খসখসে ভাব',
    'Numbness externally': 'বাইরে অবশতা', 'Extension': 'প্রসারণ', 'Close': 'কাছে',
    'Cataract': 'ছানি', 'Blurred': 'ঝাপসা', 'Bathing': 'স্নান', 'Bandaged': 'ব্যান্ডেজ বাঁধা',
    'Balls': 'বলের মতো বস্তু',
    'women': 'নারী', 'without intervening heat': 'মাঝে উত্তাপ ছাড়াই', 'wine agg.': 'মদে বৃদ্ধি',
    'walking rapidly': 'দ্রুত হাঁটা', 'urinate': 'মূত্রত্যাগ', 'sugar': 'চিনি', 'strong': 'তীব্র',
    'stormy weather': 'ঝড়ো আবহাওয়া', 'sitting up amel.': 'উঠে বসায় উপশম', 'sense of': '-এর অনুভূতি',
    'recurrent': 'পুনরাবৃত্তিমূলক', 'pungent': 'ঝাঁঝালো', 'phagedenic': 'দ্রুত-ক্ষয়কারী',
    'paralyzed parts': 'পক্ষাঘাতগ্রস্ত অংশ', 'pains': 'ব্যথা', 'over eyes': 'চোখের উপরে',
    'on right side': 'ডান দিকে', 'on inspiration': 'শ্বাস নেওয়ার সময়', 'on back amel.': 'পিঠের উপর শোয়ায় উপশম',
    'not lain on': 'যে পাশে শোয়া হয়নি', 'nodules': 'গাঁট', 'lower ribs': 'নিচের পাঁজর',
    'inclination to': '-এর প্রবণতা', 'in the open air': 'খোলা বাতাসে', 'in the open': 'খোলা জায়গায়',
    'in larynx': 'কণ্ঠনালিতে', 'hysterical': 'হিস্টিরিয়াজনিত', 'following': 'অনুসরণ করে',
    'feels as if not lying on': 'মনে হয় যেন শোয়া নেই', 'extending to knee': 'হাঁটু পর্যন্ত বিস্তৃত',
    'extending to face': 'মুখমণ্ডল পর্যন্ত বিস্তৃত', 'extending inward': 'ভিতরের দিকে বিস্তৃত',
    'extending downward from above': 'উপর থেকে নিচের দিকে বিস্তৃত', 'eructation': 'ঢেঁকুর',
    'erectile': 'উত্থানশীল', 'eating agg.': 'খাওয়ায় বৃদ্ধি', 'ears': 'কান', 'dressing': 'কাপড় পরা',
    'descending stairs': 'সিঁড়ি নামা', 'cholera': 'কলেরা', 'chill then sweat': 'কম্প তারপর ঘাম',
    'business': 'ব্যবসা', 'blowing the nose': 'নাক ঝাড়া', 'after walking': 'হাঁটার পরে',
    'acne': 'ব্রণ', 'Wounds': 'ক্ষত', 'Wheezing': 'শোঁ শোঁ শব্দ', 'Turned': 'ঘোরানো',
    'Tumors on lids': 'চোখের পাতায় টিউমার', 'Swallow': 'গেলা', 'Paralysis of lids': 'চোখের পাতার পক্ষাঘাত',
    'Lupus': 'লুপাস', 'Hawk': 'গলা পরিষ্কারের চেষ্টা', 'Fistulous openings': 'নালাযুক্ত ছিদ্র',
    'Enlarged': 'বড় হয়ে যাওয়া', 'Distortion': 'বিকৃতি', 'Alive': 'জীবন্ত',
    'œdematous': 'পানি জমা ফোলা', 'while in': '-এ থাকা অবস্থায়', 'wants to be': 'হতে চায়',
    'until 1 a.m.': 'রাত ১টা পর্যন্ত', 'typhoid': 'টাইফয়েড', 'too': 'অতিরিক্ত',
    'to shoulder': 'কাঁধ পর্যন্ত', 'thyroid gland': 'থাইরয়েড গ্রন্থি', 'thinking of it': 'সে কথা ভাবলে',
    'symptoms': 'উপসর্গ', 'strange': 'অদ্ভুত', 'spirits': 'আত্মা', 'side to side': 'পাশ থেকে পাশে',
    'rising from sitting': 'বসা থেকে ওঠা', 'reports in': '-এ শব্দ', 'region of the': '-এর অঞ্চল',
    'radius': 'ব্যাসার্ধ অস্থি', 'pulsative': 'স্পন্দনশীল', 'paralyzed limb': 'পক্ষাঘাতগ্রস্ত অঙ্গ',
    'one': 'একটি', 'on side': 'পাশে', 'on coughing': 'কাশির সময়', 'on attempting to': 'চেষ্টা করার সময়',
    'neuralgic': 'স্নায়ুশূলজনিত', 'misfortune': 'দুর্ভাগ্য', 'manual labor': 'হাতের কাজ',
    'malar bone': 'গালের হাড়', 'looking downward': 'নিচের দিকে তাকানো', 'lip': 'ঠোঁট',
    'inferior': 'নিম্ন', 'indolent': 'অলস-ধীর', 'in sleep': 'ঘুমের মধ্যে',
    'head belongs to another': 'মাথা যেন অন্য কারো', 'hammering': 'হাতুড়ি পেটানোর মতো',
    'gonorrhœal': 'প্রমেহজনিত', 'gluteal muscles': 'পাছার পেশি', 'from exposure to': '-এর সংস্পর্শ থেকে',
    'food tastes': 'খাদ্যের স্বাদ', 'fluttering sounds': 'ফরফর শব্দ', 'flashes': 'ঝলকানি',
    'extensor muscles': 'প্রসারক পেশি', 'extending to shoulder': 'কাঁধ পর্যন্ত বিস্তৃত',
    'every day': 'প্রতিদিন', 'epithelioma': 'ত্বক-ক্যান্সার', 'diaphragm': 'মধ্যচ্ছদা',
    'deep-seated': 'গভীরে অবস্থিত', 'day and night': 'দিনরাত', 'cornea': 'কর্নিয়া',
    'coccyx after stool': 'মলত্যাগের পর পুচ্ছাস্থি', 'breathing deeply': 'গভীর শ্বাস নেওয়া',
    'bladder': 'মূত্রথলি', 'below the ear': 'কানের নিচে', 'asunder': 'আলাদা হয়ে',
    'as with a': '-এর মতো একটি দিয়ে', 'alternating with heat': 'উত্তাপের সাথে পর্যায়ক্রমে', 'ailments': 'অসুস্থতা',
    'Zigzags': 'আঁকাবাঁকা', 'Wildness': 'বন্যতা', 'Objects seem to be too far off': 'বস্তু বেশি দূরে মনে হয়',
    'Movement': 'নড়াচড়া', 'Loathing of food': 'খাদ্যে ঘৃণা', 'Loathing': 'ঘৃণা',
    'Large field of vision': 'দৃষ্টিক্ষেত্র বড় মনে হওয়া', 'Lamenting': 'বিলাপ করা', 'Jumping': 'লাফানো',
    'Jesting': 'ঠাট্টা করা', 'Hurry': 'তাড়াহুড়ো', 'Hollow': 'ফাঁপা', 'Fiery': 'জ্বলন্ত',
    'Easy': 'সহজ', 'Crackling sensation in': '-এ কড়কড় শব্দের অনুভূতি', 'Concentration active': 'সক্রিয় মনোযোগ',
    'Cloudy': 'মেঘলা', 'Circles': 'বৃত্ত', 'Bleeding from eyes': 'চোখ দিয়ে রক্তক্ষরণ',
    'yellowish': 'হলদেটে', 'walking fast': 'দ্রুত হাঁটা', 'veins': 'শিরা', 'vanishing': 'মিলিয়ে যাওয়া',
    'ulnar side of': '-এর কনুই-হাড়ের দিক', 'turning the head': 'মাথা ঘোরানো', 'to hypochondrium': 'পাঁজরের নিচের অংশ পর্যন্ত',
    'to brain like rays': 'মস্তিষ্ক পর্যন্ত রশ্মির মতো', 'that she is': 'যে সে', 'tenacious': 'আঠালো-দৃঢ়',
    'sweets': 'মিষ্টি খাবার', 'spreading': 'ছড়িয়ে পড়া', 'spongy': 'স্পঞ্জের মতো',
    'spinal irritation': 'মেরুদণ্ডের উত্তেজনা', 'slowly amel.': 'ধীরে হলে উপশম', 'slowly': 'ধীরে',
    'shaking the head': 'মাথা কাঁপানো', 'roots': 'গোড়া', 'reverberating (includes Echoes and Reechoes)': 'প্রতিধ্বনিত হওয়া',
    'rectum': 'মলদ্বার', 'radial side': 'ব্যাসার্ধ-হাড়ের দিক', 'petechiæ': 'ত্বকে রক্তবিন্দু',
    'out': 'বাইরে', 'on lying or coughing': 'শোয়া বা কাশির সময়', 'on going to bed': 'বিছানায় যাওয়ার সময়',
    'of head': 'মাথার', 'nervous': 'স্নায়বিক', 'lying on painful side': 'ব্যথার পাশে শোয়া',
    'livid': 'নীলচে-বিবর্ণ', 'light agg.': 'আলোতে বৃদ্ধি', 'instead of': '-এর পরিবর্তে',
    'injury': 'আঘাত', 'injuries': 'আঘাত', 'hat': 'টুপি', 'hang down': 'ঝুলে থাকা',
    'frænum': 'জিহ্বার নিচের ঝিল্লি', 'figures': 'অবয়ব', 'extending to right': 'ডান দিকে বিস্তৃত',
})

# A fifth pass — the tail below occurrence ~10.
SEG.update({
    'sexual excitement': 'যৌন উত্তেজনা', 'rising from seat': 'আসন থেকে ওঠা',
    'radiating': 'বিকিরণকারী', 'pressing externally': 'বাইরে চাপ',
    'standing amel.': 'দাঁড়ানোয় উপশম', 'jaundice': 'জন্ডিস',
    'extending to knees': 'হাঁটু পর্যন্ত বিস্তৃত',
    'extending from lower incisors to malar bone and temple': 'নিচের সামনের দাঁত থেকে গালের হাড় ও রগ পর্যন্ত বিস্তৃত',
    'electric': 'বিদ্যুতের মতো', 'dogs': 'কুকুর', 'deltoid region': 'কাঁধের পেশি অঞ্চল',
    'day': 'দিন', 'cracked': 'ফাটা', 'compressing': 'চেপে ধরার মতো',
    'coldness of body': 'শরীরের শীতলতা', 'cold water amel.': 'ঠান্ডা জলে উপশম',
    'cold application amel.': 'ঠান্ডা প্রয়োগে উপশম', 'closing the eyes': 'চোখ বন্ধ করা',
    'cannot walk': 'হাঁটতে পারে না', 'break': 'ভেঙে যাওয়া', 'bones of': '-এর অস্থি',
    'boiled': 'সিদ্ধ', 'biceps': 'বাইসেপ পেশি',
    'bending forward with forehead on table agg.': 'কপাল টেবিলে রেখে ঝুঁকলে বৃদ্ধি',
    'bath': 'স্নান', 'bad': 'খারাপ', 'at every': 'প্রতিটির সময়',
    'amel. by standing or sitting': 'দাঁড়ানো বা বসায় উপশম', 'after going to': '-এ যাওয়ার পরে',
    'Morose': 'গোমড়ামুখো', 'Clenching fingers': 'আঙুল মুঠো করা',
    'would appear': 'মনে হয়', 'whooping cough': 'হুপিং কাশি', 'while writing': 'লেখার সময়',
    'weight': 'ওজন-ভার', 'wanting (impotency)': 'ঘাটতি (পুরুষত্বহীনতা)',
    'waking from the cough': 'কাশিতে ঘুম ভাঙা', 'voices': 'কণ্ঠস্বর', 'upper jaw': 'উপরের চোয়াল',
    'ulnar side': 'কনুই-হাড়ের দিক', 'ulcerated': 'ক্ষতযুক্ত', 'to head': 'মাথা পর্যন্ত',
    'to chest': 'বুক পর্যন্ত', 'to cheek': 'গাল পর্যন্ত', 'tensive': 'টানটান',
    'swallowing amel.': 'গেলায় উপশম', 'sunlight': 'রোদ', 'suddenly': 'হঠাৎ',
    'submaxillary glands': 'নিচের চোয়ালের গ্রন্থি', 'stretching out': 'প্রসারিত করা',
    'stretching agg.': 'টানটান করায় বৃদ্ধি', 'streaks': 'দাগ', 'society': 'সঙ্গ',
    'smooth': 'মসৃণ', 'sitting down': 'বসে পড়া', 'sensitive to': '-এ সংবেদনশীল',
    'scarlatina': 'স্কারলেট জ্বর', 'rising amel.': 'ওঠায় উপশম', 'reading aloud': 'জোরে পড়া',
    'raising arms': 'বাহু তোলা', 'quick': 'দ্রুত', 'pressure of hand amel.': 'হাতের চাপে উপশম',
    'playing piano': 'পিয়ানো বাজানো', 'persons': 'ব্যক্তি', 'pepper': 'মরিচ',
    'pain in abdomen': 'উদরে ব্যথা', 'overpowering': 'অপ্রতিরোধ্য', 'onions': 'পেঁয়াজ',
    'odor of': '-এর গন্ধ', 'occipital protuberance': 'মাথার পেছনের উঁচু হাড়', 'musty': 'ভ্যাপসা গন্ধ',
    'must run or hop': 'দৌড়াতে বা লাফাতে হয়', 'miliary': 'ছোট দানাযুক্ত',
    'lying on left side agg.': 'বাম কাতে শোয়ায় বৃদ্ধি', 'liquids': 'তরল', 'jarring': 'ঝাঁকুনি',
    'intermittent fever': 'পর্যায়ক্রমিক জ্বর', 'inspiring': 'শ্বাস নেওয়া', 'incisors': 'সামনের দাঁত',
    'in evening': 'সন্ধ্যায়', 'icy': 'বরফশীতল', 'here and there': 'এখানে-সেখানে',
    'grinding': 'দাঁত কিড়মিড় করা', 'grasping or reaching at something': 'কিছু ধরতে বা নাগাল পেতে চাওয়া',
    'from bed': 'বিছানা থেকে', 'from a draft of': 'হঠাৎ বাতাসের ঝাপটা থেকে',
    'finger joints': 'আঙুলের সন্ধি', 'fainting': 'মূর্ছা যাওয়া', 'extending towards abdomen': 'উদরের দিকে বিস্তৃত',
    'extending to stomach': 'পাকস্থলী পর্যন্ত বিস্তৃত', 'extending to left': 'বাম দিকে বিস্তৃত',
    'extending to hand': 'হাত পর্যন্ত বিস্তৃত', 'extending to calves': 'পায়ের গোছা পর্যন্ত বিস্তৃত',
    'extending into groin': 'কুঁচকির মধ্যে বিস্তৃত', 'extending ear': 'কান পর্যন্ত বিস্তৃত',
    'extending backwards': 'পিছনের দিকে বিস্তৃত', 'expectoration amel.': 'কফ তোলায় উপশম',
    'exertion agg.': 'পরিশ্রমে বৃদ্ধি', 'every three or four days': 'প্রতি তিন-চার দিনে',
    'every other': 'প্রতি বিকল্প', 'draft': 'বাতাসের ঝাপটা', 'dorsum': 'পিঠের উপরিভাগ',
    'discharging': 'স্রাব হওয়া', 'dilated': 'প্রসারিত', 'delayed': 'বিলম্বিত',
    'crackling': 'কড়কড় শব্দ', 'coughing agg.': 'কাশিতে বৃদ্ধি', 'corners of': '-এর কোণ',
    'consisting of few coughs': 'সামান্য কাশি নিয়ে', 'company': 'সঙ্গ', 'chirping': 'ঝিঁঝিঁ পোকার শব্দ',
    'child': 'শিশু', 'cheek bones': 'গালের হাড়', 'changeable': 'পরিবর্তনশীল',
    'brownish-red': 'বাদামি-লাল', 'blows': 'আঘাত', 'bending backward agg.': 'পিছনে বাঁকায় বৃদ্ধি',
    'band': 'বেল্টের মতো বাঁধন', 'backwards': 'পিছনের দিকে', 'at root of': '-এর গোড়ায়',
    'as if a': 'যেন একটি', 'alternating with gastric': 'পাকস্থলীর উপসর্গের সাথে পর্যায়ক্রমে',
    'alternating with anger': 'রাগের সাথে পর্যায়ক্রমে', 'after stool': 'মলত্যাগের পরে',
    'Weary of life': 'জীবনে ক্লান্ত', 'Waving sensation': 'ঢেউয়ের মতো অনুভূতি', 'Stone': 'পাথর',
    'Sensitive to bathing': 'স্নানে সংবেদনশীল', 'Racking': 'তীব্র যন্ত্রণাদায়ক', 'Internal heat': 'অভ্যন্তরীণ উত্তাপ',
    'Indignation': 'ক্ষোভ', 'Hair': 'চুল', 'Granular lids': 'চোখের পাতায় দানাদার ভাব',
    'Exhilaration': 'উল্লাস', 'Electrical current': 'বিদ্যুৎ প্রবাহ', 'Dropsy': 'জলোদর',
    'Discouraged': 'নিরুৎসাহিত', 'Comatose': 'অচেতন-মূর্ছিত', 'Collapse': 'ধস (শারীরিক)',
    'Coldness in': '-এ শীতলতা', 'Casts': 'মলে আবরণ', 'Barking': 'ঘেউ ঘেউ শব্দের মতো', 'Atrophy': 'ক্ষয়প্রাপ্তি',
    'Agglutinated': 'আঠালো হয়ে জোড়া লাগা',
    'would come on': 'শুরু হতো', 'wing': 'নাকের পাখা', 'window': 'জানালা', 'wild': 'উন্মত্ত',
    'washing agg.': 'ধোয়ায় বৃদ্ধি', 'warm application amel.': 'গরম প্রয়োগে উপশম',
    'wanting tastelessness of food': 'খাদ্যে স্বাদহীনতা', 'waking him': 'তাকে জাগানো',
    'velum': 'নরম তালু', 'varicose': 'শিরা ফোলা', 'urging to': '-এর বেগ', 'torn': 'ছেঁড়া',
    'toothache': 'দাঁতের ব্যথা', 'then': 'তারপর', 'stripes': 'ডোরা', 'string': 'সুতার মতো',
    'stretching arm': 'বাহু টানটান করা', 'stepping agg.': 'পা ফেলায় বৃদ্ধি', 'stars': 'তারা',
    'sprain': 'মচকানো', 'slow amel.': 'ধীরে হলে উপশম', 'slimy': 'পিচ্ছিল-আঠালো',
    'sitting bent': 'ঝুঁকে বসা', 'serpiginous': 'সাপের মতো আঁকাবাঁকা ছড়ানো', 'rising on': '-এ ওঠা',
    'puerperal': 'প্রসবোত্তর', 'press': 'চাপ দেওয়া', 'pinching in': '-এ চিমটি কাটা',
    'perspiration alternating with chilliness': 'ঘামের সাথে শীত শীত ভাব পর্যায়ক্রমে',
    'papular': 'ছোট দানাযুক্ত', 'opening mouth': 'মুখ খোলা', 'opening eyes': 'চোখ খোলা',
    'onanism': 'হস্তমৈথুন', 'objects seem to be': 'বস্তু মনে হয়', 'moving arm': 'বাহু নাড়ানো',
    'malleoli': 'গোড়ালির হাড়', 'malignant': 'মারাত্মক', 'lower teeth': 'নিচের দাঁত', 'limbs': 'অঙ্গপ্রত্যঙ্গ',
    'knitting': 'বোনা', 'knife': 'ছুরি', 'joint': 'সন্ধি', 'iris': 'চোখের রঙিন অংশ',
    'indurated': 'শক্ত হয়ে যাওয়া', 'icy cold': 'বরফের মতো ঠান্ডা', 'hemiplegia': 'একপাশের পক্ষাঘাত',
    'going to sleep': 'ঘুমাতে যাওয়া', 'from cold': 'ঠান্ডা থেকে', 'fine': 'সূক্ষ্ম', 'fecal': 'মলজাত',
    'fauces': 'গলার ভিতরের অংশ', 'extending to forehead': 'কপাল পর্যন্ত বিস্তৃত',
    'extending to foot': 'পা পর্যন্ত বিস্তৃত', 'extending into back and chest at noon': 'দুপুরে পিঠ ও বুক পর্যন্ত বিস্তৃত',
    'evening after lying down': 'সন্ধ্যায় শোয়ার পরে', 'dyspnœa': 'শ্বাসকষ্ট',
    'drawing head backward': 'মাথা পিছনে টানা', 'double': 'দ্বিগুণ', 'desires': 'আকাঙ্ক্ষা',
    'crushed': 'চূর্ণ হওয়া', 'corners': 'কোণ', 'cool': 'শীতল', 'contradiction': 'বিরোধিতা',
    'cold air amel.': 'ঠান্ডা বাতাসে উপশম', 'clearness of mind': 'মনের স্বচ্ছতা', 'carbuncle': 'বড় ফোড়া',
    'can only pass urine while': 'শুধু -এ প্রস্রাব করতে পারে', 'bending arm': 'বাহু বাঁকানো',
    'as though the back would': 'যেন পিঠ যেন', 'as if bound up': 'যেন বাঁধা আছে',
    'as from cold': 'ঠান্ডা থেকে যেন', 'areola': 'স্তনবৃন্তের চারপাশ', 'and thighs': 'ও উরু',
    'after sitting': 'বসার পরে', 'a long time before he can begin': 'শুরু করতে অনেক সময় লাগে',
    'Warm agg.': 'গরমে বৃদ্ধি', 'Unsteadiness': 'অস্থিরতা (ভারসাম্যহীনতা)', 'Striking': 'আঘাত করা',
    'Reserved': 'সংযত-চাপা স্বভাব', 'Raised': 'উঁচু করা', 'Pulsation in eyes': 'চোখে স্পন্দন',
    'Mouse': 'ইঁদুর', 'Inflammation (Peritonitis': 'প্রদাহ (পেরিটোনাইটিস', 'Illusions': 'বিভ্রম',
    'Hysteria': 'হিস্টিরিয়া', 'Hernia': 'হার্নিয়া', 'Goose flesh': 'গায়ে কাঁটা দেওয়া', 'Goitre': 'গলগণ্ড',
    'Exostoses': 'অস্থি-বৃদ্ধি', 'Drawn backward': 'পিছনে টানা', 'Awkwardness': 'জড়তা-বেঢপ ভাব',
    'Anxiety in': '-এ উদ্বেগ',
    'wine amel.': 'মদে উপশম', 'whizzing': 'শোঁ শোঁ শব্দ', 'while walking in the open': 'খোলা জায়গায় হাঁটার সময়',
    'when in': '-এ থাকা অবস্থায়', 'wet weather agg.': 'ভেজা আবহাওয়ায় বৃদ্ধি',
    'washing in cold water': 'ঠান্ডা জলে ধোয়া', 'warm bed amel.': 'গরম বিছানায় উপশম', 'urethra': 'মূত্রনালি',
    'up': 'উপরে', 'umbilical region': 'নাভি অঞ্চল', 'transversely': 'আড়াআড়িভাবে', 'transient': 'ক্ষণস্থায়ী',
    'to 3 p.m.': 'বিকাল ৩টা পর্যন্ত', 'thumbs': 'বুড়ো আঙুল', 'thinking of it agg.': 'সে কথা ভাবলে বৃদ্ধি',
    'then to right arm': 'তারপর ডান বাহুতে', 'suppressed gonorrhœa': 'রুদ্ধ প্রমেহ',
    'suppressed discharges': 'রুদ্ধ স্রাব', 'stupor': 'অচেতন-জড়তা', 'straining at stool': 'মলত্যাগে কোঁথ দেওয়া',
    'small of back': 'কোমরের নিচের অংশ', 'side agg.': 'পাশে বৃদ্ধি', 'scurfs': 'খুশকির মতো আঁশ',
    'scabies': 'খোসপাঁচড়া', 'saltish': 'নোনতা', 'root of nose': 'নাকের গোড়া', 'root of': '-এর গোড়া',
    'room agg.': 'ঘরে বৃদ্ধি', 'robbers': 'ডাকাত', 'rising agg.': 'ওঠায় বৃদ্ধি', 'rings': 'বলয়',
    'reading agg.': 'পড়ায় বৃদ্ধি', 'raising the arm': 'বাহু তোলা', 'pressive': 'চাপ দেওয়ার মতো',
    'places': 'স্থান', 'phalanx': 'আঙুলের হাড়', 'oozing': 'চুইয়ে পড়া', 'on abdomen': 'উদরের উপর',
    'of bed agg.': 'বিছানার বৃদ্ধি', 'noises': 'শব্দ', 'night (incontinence in bed)': 'রাতে (বিছানায় অনিচ্ছাকৃত মূত্রত্যাগ)',
    'nauseous': 'বমিভাব-জাগানো', 'moving agg.': 'নড়াচড়ায় বৃদ্ধি', 'month': 'মাস',
    'lying on right side agg.': 'ডান কাতে শোয়ায় বৃদ্ধি', 'larynx in': 'কণ্ঠনালিতে', 'jelly-like': 'জেলির মতো',
    'jar': 'ঝাঁকুনি', 'intoxicated': 'নেশাগ্রস্ত', 'intermitting': 'মাঝে মাঝে থামা', 'in front of': '-এর সামনে',
    'illusion of blue': 'নীল রঙের বিভ্রম', 'hernia': 'হার্নিয়া', 'greasy': 'তৈলাক্ত', 'from being': 'হওয়ার থেকে',
    'forward amel.': 'সামনে ঝুঁকলে উপশম', 'floating': 'ভাসমান', 'feverish': 'জ্বরভাব', 'fat food': 'চর্বিযুক্ত খাবার',
    'fancies he cannot': 'মনে করে সে পারবে না', 'falls': 'পড়ে যাওয়া', 'eyes over': 'চোখের উপরে',
    'extending upwards': 'উপরের দিকে বিস্তৃত', 'extending to occiput': 'মাথার পেছন পর্যন্ত বিস্তৃত',
    'extending to hips': 'নিতম্ব পর্যন্ত বিস্তৃত', 'extending to cervical muscles': 'গ্রীবার পেশি পর্যন্ত বিস্তৃত',
    'extending to back of neck': 'ঘাড়ের পিছন পর্যন্ত বিস্তৃত', 'extending into chest': 'বুকের মধ্যে বিস্তৃত',
    'extending from right to left': 'ডান থেকে বাম পর্যন্ত বিস্তৃত',
    'extending down neck into face and teeth': 'ঘাড় থেকে মুখ ও দাঁত পর্যন্ত বিস্তৃত',
    'exposure to': '-এর সংস্পর্শ', 'exercising': 'ব্যায়াম করা', 'exercise amel.': 'ব্যায়ামে উপশম',
    'excitement agg.': 'উত্তেজনায় বৃদ্ধি', 'exaltation of': '-এর উল্লাস', 'epigastrium': 'পাকস্থলীর উপরিভাগ',
    'emotions': 'আবেগ', 'early': 'সকাল সকাল', 'dysentery': 'আমাশয়', 'dream': 'স্বপ্ন',
    'draft of': 'বাতাসের ঝাপটা', 'diphtheria': 'ডিপথেরিয়া', 'descending steps': 'সিঁড়ি নামা',
    'deep inspiration': 'গভীর শ্বাস নেওয়া', 'debilitating': 'দুর্বলকারী', 'dark red': 'গাঢ় লাল',
    'crying': 'কান্না', 'copper-colored': 'তামাটে রঙের', 'contusion': 'থেঁতলানো ক্ষত',
    'contractive': 'সংকোচনশীল', 'constant motion': 'অবিরাম নড়াচড়া', 'conjunctiva': 'চোখের বাইরের ঝিল্লি',
    'congestive': 'রক্তসঞ্চয়জনিত', 'cold damp weather': 'ঠান্ডা স্যাঁতসেঁতে আবহাওয়া', 'cold amel.': 'ঠান্ডায় উপশম',
    'coffee agg.': 'কফিতে বৃদ্ধি', 'clotted': 'জমাট বাঁধা', 'child cries before urine starts': 'প্রস্রাবের আগে শিশু কাঁদে',
    'cheesy': 'পনিরের মতো', 'cervical glands': 'গ্রীবার গ্রন্থি', 'burning externally': 'বাইরে জ্বালা',
    'boring in Gums': 'মাড়িতে বিদ্ধকারী', 'blowing': 'ফুঁ দেওয়া', 'blackish': 'কালচে', 'bent over': 'সামনে ঝুঁকে',
    'bending head forward amel.': 'মাথা সামনে ঝোঁকালে উপশম', 'bending forward amel.': 'সামনে ঝুঁকলে উপশম',
    'beer tastes': 'বিয়ারের স্বাদ', 'averse to': '-এ অনীহা', 'asleep': 'ঘুমন্ত', 'as if in': 'যেন -এ',
    'as if from': 'যেন -থেকে',
})

# A sixth pass, continuing the tail.
SEG.update({
    'apoplexy': 'মস্তিষ্কে রক্তক্ষরণ (স্ট্রোক)', 'anus': 'পায়ু',
    'alternating with pain in small of back': 'কোমরের ব্যথার সাথে পর্যায়ক্রমে',
    'alternating with chill': 'কম্পের সাথে পর্যায়ক্রমে', 'alternating with': '-এর সাথে পর্যায়ক্রমে',
    'after being': 'হওয়ার পরে', 'Veins distended': 'শিরা ফুলে যাওয়া', 'Thrilling sensation': 'শিহরণ অনুভূতি',
    'Suppression of urine': 'মূত্র বন্ধ হয়ে যাওয়া', 'Sunken': 'বসে যাওয়া (চোখ)', 'Styes': 'চোখের গুটি',
    'Sticky viscid': 'আঠালো-পিচ্ছিল', 'Stertorous': 'ঘড়ঘড় শব্দে শ্বাস', 'Run together': 'একত্রে মিলে যাওয়া',
    'Remittent': 'ক্ষণে ক্ষণে কমা-বাড়া জ্বর', 'Odor of an old catarrh': 'পুরনো সর্দির গন্ধ',
    'Icy coldness of the body': 'শরীরে বরফশীতল ভাব', 'Hair on Palate': 'তালুতে লোম অনুভূতি',
    'Hair falling from brows': 'ভুরুর লোম ঝরে পড়া', 'Glassy appearance': 'কাচের মতো চেহারা',
    'Eye gum': 'চোখের কোণে আঠালো স্রাব', 'Enlarged parotid gland': 'কর্ণমূল গ্রন্থি বড় হওয়া',
    'Cramp in': '-এ খিঁচুনি', 'Chapped hand': 'হাত ফাটা', 'Catalepsy': 'অঙ্গ-স্তব্ধতা (ক্যাটালেপসি)',
    'Cancerous affections': 'ক্যান্সারজনিত সমস্যা', 'Bite': 'কামড়', 'Abscess behind': 'পিছনে ফোড়া',
    '7-30 p.m.': 'সন্ধ্যা ৭:৩০', 'without subsequent': 'পরবর্তী ছাড়া', 'when going to': 'যাওয়ার সময়',
    'when coughing': 'কাশির সময়', 'warm in bed': 'বিছানায় গরম', 'warm food': 'গরম খাবার',
    'warm bath': 'গরম স্নান', 'visible': 'দৃশ্যমান', 'vise': 'সাঁড়াশির মতো চাপ', 'veins of': '-এর শিরা',
    'upper teeth': 'উপরের দাঁত', 'up in bed': 'বিছানায় উঠে বসা', 'until evening': 'সন্ধ্যা পর্যন্ত',
    'under right': 'ডান দিকের নিচে', 'uncovering': 'অনাবৃত করা', 'unable to': '-এ অক্ষম',
    'touching': 'স্পর্শ করা', 'touch amel.': 'স্পর্শে উপশম', 'to 4 p.m.': 'বিকাল ৪টা পর্যন্ত',
    'through': 'মধ্য দিয়ে', 'then sweat': 'তারপর ঘাম', 'the other hot': 'অন্যটি গরম',
    'sunlight agg.': 'রোদে বৃদ্ধি', 'sulphur': 'গন্ধক', 'stretching amel.': 'টানটান করায় উপশম',
    'stool amel.': 'মলত্যাগে উপশম', 'still': 'স্থির', 'steadily': 'অবিরাম-ধারাবাহিকভাবে',
    'stammering': 'তোতলামি', 'snow': 'তুষার', 'snapping': 'কট করে শব্দ', 'smoking agg.': 'ধূমপানে বৃদ্ধি',
    'sensation as of': '-এর মতো অনুভূতি', 'seems to be in': '-এ আছে মনে হয়', 'sacro-iliac junction': 'ত্রিক-শ্রোণী সন্ধি',
    'rasping': 'খসখসে শব্দ', 'pelvis': 'শ্রোণী', 'peg or wedge': 'গোঁজ বা কীলকের মতো', 'peaches': 'পীচ ফল',
    'pasty': 'আঠালো-নরম', 'paralyzed': 'পক্ষাঘাতগ্রস্ত', 'outer side of': '-এর বাইরের দিক', 'others': 'অন্যরা',
    'on lying down': 'শুয়ে পড়ার সময়', 'on deep': 'গভীর -এর সময়', 'nape': 'ঘাড়ের পিছন', 'murdered': 'খুন হওয়া',
    'mental': 'মানসিক', 'lying down agg.': 'শুয়ে পড়ায় বৃদ্ধি', 'looking steadily': 'স্থিরভাবে তাকানো',
    'looking at bright objects': 'উজ্জ্বল বস্তুর দিকে তাকানো', 'long-lasting': 'দীর্ঘস্থায়ী', 'lividity': 'নীলচে-বিবর্ণতা',
    'joy': 'আনন্দ', 'itch-like': 'চুলকানির মতো', 'is a': 'একটি', 'involuntarily': 'অনিচ্ছাকৃতভাবে',
    'interrupted (intermittent)': 'বাধাপ্রাপ্ত (মাঝে মাঝে থামা)', 'insipid': 'স্বাদহীন', 'inguinal': 'কুঁচকির',
    'in region of': '-এর অঞ্চলে', 'illusions of': '-এর বিভ্রম', 'ilio-cæcal region': 'অন্ত্রের সংযোগস্থল অঞ্চল',
    'ice': 'বরফ', 'hot weather': 'গরম আবহাওয়া', 'hissing': 'হিসহিস শব্দ', 'heat of body': 'শরীরের উত্তাপ',
    'gluteal region': 'পাছার অঞ্চল', 'gelatinous': 'জেলির মতো', 'garlic': 'রসুন',
    'from suppressed': 'রুদ্ধ হওয়া থেকে', 'from strong': 'তীব্র -থেকে', 'from eating': 'খাওয়া থেকে',
    'flexors': 'সংকোচক পেশি', 'flank': 'কোমরের পাশ', 'feeble stream (slow)': 'দুর্বল ধারা (ধীর)',
    'extending to wrist': 'কবজি পর্যন্ত বিস্তৃত', 'extending to small of back': 'কোমরের নিচ পর্যন্ত বিস্তৃত',
    'extending to scapula': 'কাঁধের হাড় পর্যন্ত বিস্তৃত', 'extending to body': 'শরীর পর্যন্ত বিস্তৃত',
    'extending to bladder and groins': 'মূত্রথলি ও কুঁচকি পর্যন্ত বিস্তৃত', 'extending over abdomen': 'উদর জুড়ে বিস্তৃত',
    'extending outward': 'বাইরের দিকে বিস্তৃত', 'extending down to sciatic nerve': 'সায়াটিক স্নায়ু পর্যন্ত বিস্তৃত',
    'extending down': 'নিচের দিকে বিস্তৃত', 'enemies': 'শত্রু', 'dropsical': 'জলোদরজনিত',
    'dread of': '-এর ভীতি', 'down the': '-এর নিচ দিয়ে', 'distant': 'দূরবর্তী', 'deltoid': 'কাঁধের পেশি',
    'deep breathing': 'গভীর শ্বাস', 'daily': 'প্রতিদিন', 'cramp in': '-এ খিঁচুনি', 'costal cartilages': 'পাঁজরের তরুণাস্থি',
    'continued amel.': 'চলমান থাকায় উপশম', 'compelling': 'বাধ্যকারী', 'cold bathing amel.': 'ঠান্ডা স্নানে উপশম',
    'clear': 'স্বচ্ছ', 'chagrin': 'অপমানবোধ', 'caused by': '-এর কারণে', 'brandy': 'ব্র্যান্ডি',
    'bitter-sweet': 'তেতো-মিষ্টি', 'bending forward while sitting': 'বসে সামনে ঝোঁকা',
    'before paroxysms': 'তীব্র পর্যায়ের আগে', 'bed in': 'বিছানায়', 'become': 'হয়ে যাওয়া',
    'bad news': 'দুঃসংবাদ', 'autumn': 'শরৎকাল', 'as in a': '-এর মতো একটি অবস্থায়', 'as if would': 'যেন হবে',
    'articulation': 'সন্ধিস্থল', 'amel. in': '-এ উপশম', 'amel. after': '-এর পরে উপশম',
    'alternating with frenzy': 'উন্মত্ততার সাথে পর্যায়ক্রমে', 'alternating with colic': 'উদরশূলের সাথে পর্যায়ক্রমে',
    'after drinking': 'পান করার পরে', 'above root of': '-এর গোড়ার উপরে', 'about the eyes': 'চোখের চারপাশে',
    'Twisting sensation': 'মোচড়ানোর অনুভূতি', 'Timidity': 'ভীরুতা', 'Strabismus': 'টেরা চোখ',
    'Sensation absent': 'অনুভূতিহীনতা', 'SHAKINGsensation': 'কাঁপুনির অনুভূতি', 'Rolling': 'গড়িয়ে যাওয়া',
    'Periodicity': 'পর্যায়ক্রমিকতা', 'Mucus on': '-এ শ্লেষ্মা', 'Motion of the mouth as if talking': 'কথা বলার মতো মুখ নাড়ানো',
    'Looseness of': '-এর আলগা ভাব', 'Hoarse': 'স্বরভঙ্গযুক্ত', 'Gasping': 'হাঁপানো', 'Gagging': 'গলায় ঠেলা লাগা',
    'Fistula': 'নালাক্ষত', 'Enlarged ovaries': 'ডিম্বাশয় বড় হওয়া', 'Ecstasy': 'পরমানন্দ', 'Dust': 'ধুলো',
    'Contractions': 'সংকোচন', 'Constriction externally': 'বাইরে সংকোচন', 'Bubbling': 'বুদবুদ ওঠা',
    'Aversion': 'অনীহা', 'Absorbed': 'নিমগ্ন', 'Absent-minded': 'অন্যমনস্ক',
    'yawning amel.': 'হাই তোলায় উপশম', 'yawning agg.': 'হাই তোলায় বৃদ্ধি', 'words': 'শব্দ',
    'will': 'ইচ্ছাশক্তি', 'white spots': 'সাদা ছোপ', 'whiskers': 'গালপাট্টা',
    'while walking in open air': 'খোলা বাতাসে হাঁটার সময়', 'while eating': 'খাওয়ার সময়', 'when passing': 'যাওয়ার সময়',
    'were': 'ছিল', 'washing amel.': 'ধোয়ায় উপশম', 'warm clothing agg.': 'গরম পোশাকে বৃদ্ধি', 'vivid': 'উজ্জ্বল-স্পষ্ট',
    'urination amel.': 'মূত্রত্যাগে উপশম', 'up and down': 'উপর-নিচ', 'ulcerating': 'ক্ষত সৃষ্টিকারী',
    'turning body': 'শরীর ঘোরানো', 'tragus': 'কানের সামনের অংশ', 'tongue fissured': 'জিহ্বায় ফাটল',
    'to wrist': 'কবজি পর্যন্ত', 'to jaw': 'চোয়াল পর্যন্ত', 'to forehead': 'কপাল পর্যন্ত',
    'to cervical muscles': 'গ্রীবার পেশি পর্যন্ত', 'to 5 a.m.': 'ভোর ৫টা পর্যন্ত',
    'thought he was': 'মনে করত সে', 'that she is always': 'যে সে সবসময়', 'that he would be': 'যে সে হবে',
    'that he walks on his knees': 'যে সে হাঁটুতে ভর দিয়ে হাঁটে', 'sunset to sunrise': 'সূর্যাস্ত থেকে সূর্যোদয়',
    'suffocation': 'শ্বাসরোধ', 'sudden impulse to': '-এর হঠাৎ তাড়না', 'stairs': 'সিঁড়ি',
    'spoken to': 'কথা বলা হলে', 'spoiled like': '-এর মতো নষ্ট', 'spinning': 'ঘোরা (চাকার মতো)', 'something': 'কিছু একটা',
    'solids': 'শক্ত খাবার', 'side on': 'যে পাশে', 'side of': '-এর পাশ', 'short ribs': 'ছোট পাঁজর',
    'sensation of a': '-এর অনুভূতি', 'seashore': 'সমুদ্রতট', 'rushing in': '-এ তাড়াহুড়ো করে ঢোকা',
    'ropy': 'সুতোর মতো টানা', 'right agg.': 'ডান দিকে বৃদ্ধি', 'riding on horseback': 'ঘোড়ায় চড়া',
    'ridiculous or foolish': 'হাস্যকর বা বোকা', 'raw': 'কাঁচা-ব্যথাযুক্ত', 'raising the head': 'মাথা তোলা',
    'plums': 'বরই', 'petechial': 'রক্তবিন্দুযুক্ত', 'paronychia': 'নখের গোড়ায় প্রদাহ', 'oysters': 'ঝিনুক',
    'on abdomen amel.': 'উদরের উপর চাপে উপশম', 'of being in different': 'বিভিন্ন অবস্থায় থাকার',
    'of arms': 'বাহুর', 'nettles': 'বিছুটি গাছ', 'needles': 'সূচ', 'near': 'কাছে',
    'morning on rising': 'সকালে ওঠার সময়', 'metallic': 'ধাতব', 'mercurial': 'পারদজনিত',
    'menses would appear': 'ঋতুস্রাব শুরু হতো', 'mealy': 'ময়দার মতো', 'margins of lids': 'চোখের পাতার কিনারা',
    'mania': 'উন্মত্ততা', 'male': 'পুরুষ', 'lying on left side amel.': 'বাম কাতে শোয়ায় উপশম',
    'ludicrous': 'হাস্যকর', 'lower lip': 'নিচের ঠোঁট', 'looking steadily agg.': 'স্থিরভাবে তাকালে বৃদ্ধি',
    'looking fixedly at anything': 'কোনো কিছুর দিকে একদৃষ্টে তাকানো', 'loins': 'কোমর', 'lack of': '-এর অভাব',
    'insects': 'পোকামাকড়', 'inflammatory': 'প্রদাহজনিত', 'ineffectual and incomplete': 'নিষ্ফল ও অসম্পূর্ণ',
    'indistinct': 'অস্পষ্ট', 'in front': 'সামনে',
    'large quantities': 'প্রচুর পরিমাণ', 'small quantities': 'সামান্য পরিমাণ',
    'quantities': 'পরিমাণ', 'often': 'ঘন ঘন',
})

# The long tail lives in its own module so this one stays the readable core
# vocabulary. SEG wins on a clash — its entries are the hand-checked ones.
from kent_bn_ext import SEG_EXT
for _k, _v in SEG_EXT.items():
    SEG.setdefault(_k, _v)

# ---------------------------------------------------------------- clock times
# Kent's time-of-aggravation rubrics are mechanical and there are hundreds of
# them ('10-30 p.m.', '11 a.m. to 4 p.m.', 'until 2 a.m.', 'noon to 3 p.m.'),
# so they are generated rather than listed. He writes half hours with a hyphen,
# '10-30 p.m.' meaning half past ten, not a range.
BN_DIGITS = str.maketrans('0123456789', '০১২৩৪৫৬৭৮৯')
_CLOCK = re.compile(r'^(\d{1,2})\s*[:\-]\s*(\d{2})\s*([ap])\.?\s*m\.?$', re.I)
_HOUR = re.compile(r'^(\d{1,2})\s*([ap])\.?\s*m\.?$', re.I)
_BARE = re.compile(r'^(\d{1,2})$')
_NAMED = {
    'noon': 'দুপুর ১২টা', 'midnight': 'মধ্যরাত', 'morning': 'সকাল',
    'forenoon': 'সকাল', 'afternoon': 'বিকাল', 'evening': 'সন্ধ্যা',
    'night': 'রাত', 'daybreak': 'ভোর', 'daytime': 'দিনের বেলা',
    'sunrise': 'সূর্যোদয়', 'sunset': 'সূর্যাস্ত', 'bed time': 'শোয়ার সময়',
    'bedtime': 'শোয়ার সময়',
}
_SPLIT_RANGE = re.compile(r'\s+(?:to|till|until)\s+', re.I)
_UNTIL = re.compile(r'^(?:to|till|until|lasting till|lasting until)\s+(.+)$', re.I)
_AFTER = re.compile(r'^after\s+(.+)$', re.I)
_BEFORE = re.compile(r'^before\s+(.+)$', re.I)
_AT = re.compile(r'^at\s+(.+)$', re.I)


def _clock(hour, minute, meridiem):
    h = int(hour)
    # 12 is the one hour whose name does not follow from the number: 12 a.m. is
    # midnight and 12 p.m. is noon, and Kent writes both as plain '12'.
    if h == 12 and not minute:
        return 'মধ্যরাত' if meridiem == 'a' else 'দুপুর ১২টা'
    part = ('ভোর' if h < 6 else 'সকাল') if meridiem == 'a' else \
           ('দুপুর' if h < 3 else ('বিকাল' if h < 6 else 'রাত'))
    if minute:
        return f'{part} {(str(h) + ":" + minute).translate(BN_DIGITS)}'
    return f'{part} {str(h).translate(BN_DIGITS)}টা'


def _gen(a):
    """Genitive: 'রাত ১০টা' -> 'রাত ১০টার', so 'after 10 p.m.' does not come
    out as the ungrammatical 'রাত ১০টা-এর পর'."""
    return a[:-2] + 'টার' if a.endswith('টা') else a + '-এর'


def _loc(a):
    """Locative: 'সকাল ১১টা' -> 'সকাল ১১টায়'."""
    return a[:-2] + 'টায়' if a.endswith('টা') else a + '-এ'


def _atom(s, meridiem=None):
    """One point in time — '4 p.m.', '10-30 a.m.', 'noon' — or None.

    `meridiem` supplies a.m./p.m. for the bare half of a range like
    '7 until 10 a.m.', where Kent states it only once.
    """
    s = s.strip().rstrip('.').strip()
    named = _NAMED.get(s.lower())
    if named:
        return named
    m = _CLOCK.match(s)
    if m:
        return _clock(m.group(1), m.group(2), m.group(3).lower())
    m = _HOUR.match(s)
    if m:
        return _clock(m.group(1), None, m.group(2).lower())
    m = _BARE.match(s)
    if m and meridiem:
        # '9 a.m. to 12' is nine to noon, never nine to midnight
        return 'দুপুর ১২টা' if m.group(1) == '12' else _clock(m.group(1), None, meridiem)
    return None


def _meridiem(s):
    m = _CLOCK.match(s.strip().rstrip('.')) or _HOUR.match(s.strip().rstrip('.'))
    return m.group(3).lower() if m and m.lastindex == 3 else \
        (m.group(2).lower() if m else None)


def bn_time(s):
    """Bangla for a time-of-day expression, or None if it is not one."""
    s = s.strip()
    solo = _atom(s)
    if solo:
        return solo
    parts = _SPLIT_RANGE.split(s)
    if len(parts) == 2:
        mer = _meridiem(parts[0]) or _meridiem(parts[1])
        a, b = _atom(parts[0], mer), _atom(parts[1], mer)
        if a and b:
            return f'{a} থেকে {b} পর্যন্ত'
    parts = re.split(r'\s+or\s+', s, flags=re.I)
    if len(parts) == 2:
        mer = _meridiem(parts[0]) or _meridiem(parts[1])
        a, b = _atom(parts[0], mer), _atom(parts[1], mer)
        if a and b:
            return f'{a} বা {b}'
    for rx, fmt in ((_UNTIL, lambda a: f'{a} পর্যন্ত'),
                    (_AFTER, lambda a: f'{_gen(a)} পর'),
                    (_BEFORE, lambda a: f'{_gen(a)} আগে'),
                    (_AT, _loc)):
        m = rx.match(s)
        if m:
            a = _atom(m.group(1))
            if a:
                return fmt(a)
    return None


def bn_segment(seg):
    """Bangla for one comma-separated part of a rubric name, or None."""
    s = seg.strip()
    if not s:
        return ''
    hit = SEG.get(s) or SEG.get(s.lower()) or SEG.get(s[:1].upper() + s[1:])
    if hit:
        return hit
    return bn_time(s)


def bn_rubric(name):
    """Compose a rubric's Bangla name. Returns (bangla, every_part_translated).

    Untranslated parts are kept verbatim in English so the name still points at
    the right rubric; `full` tells the caller whether anything was left over.
    """
    parts = [p.strip() for p in name.split(',')]
    out, missing = [], 0
    for p in parts:
        bn = bn_segment(p)
        if bn is None:
            out.append(p)
            missing += 1
        else:
            out.append(bn)
    return ', '.join(out), missing == 0


def bn_coverage(rubs):
    """(total segment occurrences, how many the glossary resolves)."""
    total = known = 0
    for r in rubs:
        for p in r.name.split(','):
            p = p.strip()
            if not p:
                continue
            total += 1
            if bn_segment(p) is not None:
                known += 1
    return total, known


if __name__ == '__main__':
    print('glossary terms:', len(SEG))
    for n in ['Pain, stitching, forehead, evening, walking, amel.',
              'Fear, night, waking, after', 'Thirst, morning, waking, on',
              'Eruptions, itching, 4 p.m.', 'Pain, drawing, thigh, 3 to 7 p.m.',
              'Delusions, imaginations, hallucinations, illusions']:
        bn, full = bn_rubric(n)
        print(f'  {"OK " if full else "part"} {n}\n       {bn}')
