# -*- coding: utf-8 -*-
"""Bangla for Kent's rubric vocabulary.

Kent's rubric names are compositional — 'Pain, stitching, forehead, evening,
walking, amel.' is six reusable terms — so the Bangla lives in a glossary of
terms rather than in 77,000 translated strings. The page composes a rubric's
Bangla name from this glossary at load time, which is also why the data file
carries no per-rubric Bangla for the generated rows.

A term that is not in SEG stays in English. That is deliberate: a wrong Bangla
rubric name is worse than an English one, because the practitioner would select
the wrong rubric and repertorise on it. Bengali homeopathic practice already
uses the English rubric words, so an untranslated term still reads naturally.
"""
import re, collections

# ---------------------------------------------------------------- chapter names
CHAPTER_BN = {
    'Mind': 'মন', 'Vertigo': 'মাথা ঘোরা', 'Head': 'মাথা', 'Eye': 'চোখ',
    'Vision': 'দৃষ্টি', 'Ear': 'কান', 'Hearing': 'শ্রবণ', 'Nose': 'নাক',
    'Face': 'মুখমণ্ডল', 'Mouth': 'মুখগহ্বর', 'Teeth': 'দাঁত', 'Throat': 'গলা',
    'External throat': 'বাইরের গলা', 'Stomach': 'পাকস্থলী', 'Abdomen': 'উদর',
    'Rectum': 'মলদ্বার', 'Stool': 'মল', 'Urinary organs': 'মূত্রতন্ত্র',
    'Bladder': 'মূত্রথলি', 'Kidneys': 'কিডনি', 'Prostate gland': 'প্রস্টেট',
    'Urethra': 'মূত্রনালি', 'Urine': 'প্রস্রাব', 'Genitalia male': 'পুরুষ জননাঙ্গ',
    'Genitalia female': 'নারী জননাঙ্গ', 'Larynx & trachea': 'কণ্ঠনালি',
    'Respiration': 'শ্বাস', 'Cough': 'কাশি', 'Expectoration': 'কফ',
    'Chest': 'বুক', 'Back': 'পিঠ', 'Extremities': 'হাত-পা', 'Sleep': 'ঘুম',
    'Chill': 'শীত', 'Fever': 'জ্বর', 'Perspiration': 'ঘাম', 'Skin': 'ত্বক',
    'Generalities': 'সাধারণ',
}

# ---------------------------------------------------------------- the glossary
# Ordered by theme so it stays auditable. Keys are matched case-insensitively.
SEG = {
    # ---- pain and sensation types
    'Pain': 'ব্যথা',
    'Pain (aching': 'ব্যথা (ভোঁতা',
    'Pain appear gradually': 'ব্যথা ধীরে ধীরে আসে',
    'pain': 'ব্যথা',
    'stitching': 'সূচিবিদ্ধ',
    'stitching (sticking': 'সূচিবিদ্ধ (খোঁচা',
    'stitching in': 'সূচিবিদ্ধ ব্যথা',
    'tearing': 'ছেঁড়া',
    'tearing in': 'ছেঁড়া ব্যথা',
    'drawing': 'টানা',
    'pressing': 'চাপা',
    'burning': 'জ্বালা',
    'sore': 'ঘা-ব্যথা',
    'sore bruised': 'ঘা-থেঁতলানো ব্যথা',
    'bruised': 'থেঁতলানো',
    'aching': 'ভোঁতা ব্যথা',
    'cutting': 'কাটা',
    'cutting (sudden sharp pain)': 'কাটা (হঠাৎ তীক্ষ্ণ ব্যথা)',
    'shooting': 'ছুটে যাওয়া',
    'boring': 'বিদ্ধকারী',
    'digging': 'খোঁড়া',
    'rending': 'ছিন্নকারী',
    'griping': 'মোচড়ানো',
    'cramping': 'খিঁচুনি-সদৃশ',
    'cramp-like': 'খিঁচুনি-সদৃশ',
    'gnawing': 'কুরে খাওয়া',
    'stinging': 'হুল ফোটানো',
    'biting': 'কাটাকাটা জ্বালা',
    'smarting': 'চিড়িক দেওয়া',
    'lancinating': 'তীক্ষ্ণ বিদ্ধকারী',
    'darting': 'ঝিলিক দেওয়া',
    'stabbing': 'ছুরিকাঘাতের মতো',
    'screwing': 'পাক দেওয়া',
    'pinching': 'চিমটি কাটা',
    'dragging': 'ভারী টান',
    'bursting': 'ফেটে যাওয়ার মতো',
    'beaten': 'পিটুনির মতো',
    'broken': 'ভেঙে যাওয়ার মতো',
    'sprained': 'মোচড় লাগার মতো',
    'rheumatic': 'বাতজনিত',
    'paralytic': 'পক্ষাঘাতসদৃশ',
    'constricting': 'সংকোচক',
    'jerking': 'ঝাঁকি দেওয়া',
    'Jerking': 'ঝাঁকি',
    'pulsating': 'স্পন্দনশীল',
    'Pulsating': 'স্পন্দনশীল',
    'Pulsation': 'স্পন্দন',
    'wandering': 'স্থান পরিবর্তনকারী',
    'paroxysmal': 'থেমে থেমে আসা',
    'sudden': 'হঠাৎ',
    'painful': 'ব্যথাযুক্ত',
    'tenderness': 'স্পর্শকাতরতা',
    'itching': 'চুলকানি',
    'Itching': 'চুলকানি',
    'sensation of': '-এর অনুভূতি',
    'as if': 'যেন',
    'as from': 'যেন কিছু থেকে',
    'like': '-এর মতো',

    # ---- complaints and states
    'Eruptions': 'উদ্ভেদ',
    'Eruption': 'উদ্ভেদ',
    'Discoloration': 'বিবর্ণতা',
    'Delusions': 'ভ্রান্ত ধারণা',
    'Delirium': 'প্রলাপ',
    'Weakness': 'দুর্বলতা',
    'Heat': 'উত্তাপ',
    'Coldness': 'শীতলতা',
    'Coldness (including Chill)': 'শীতলতা (কম্প সহ)',
    'Chilliness': 'শীত শীত ভাব',
    'Swelling': 'ফোলা',
    'Numbness': 'অবশতা',
    'Heaviness': 'ভারী বোধ',
    'Twitching': 'পেশির লাফানো',
    'Tension': 'টান',
    'Ulcers': 'ক্ষত',
    'Constriction': 'সংকোচন',
    'Eructations': 'ঢেঁকুর',
    'Vomiting': 'বমি',
    'Nausea': 'বমিবমি ভাব',
    'Dreams': 'স্বপ্ন',
    'Diarrhœa': 'উদরাময়',
    'Paralysis': 'পক্ষাঘাত',
    'Cramps': 'খিঁচুনি',
    'Convulsions': 'আক্ষেপ',
    'Perspiration': 'ঘাম',
    'perspiration': 'ঘাম',
    'Inflammation': 'প্রদাহ',
    'Congestion': 'রক্তসঞ্চয়',
    'Fear': 'ভয়',
    'Anxiety': 'উদ্বেগ',
    'Restlessness': 'অস্থিরতা',
    'Sadness': 'বিষণ্নতা',
    'Weeping': 'কান্না',
    'Excitement': 'উত্তেজনা',
    'Confusion of mind': 'মনের বিভ্রান্তি',
    'Unconsciousness': 'অচেতনতা',
    'Faintness': 'মূর্ছাভাব',
    'Dryness': 'শুষ্কতা',
    'Dry': 'শুষ্ক',
    'Sleepiness': 'তন্দ্রা',
    'Sleeplessness': 'অনিদ্রা',
    'Coryza': 'সর্দি',
    'Palpitation heart': 'হৃদস্পন্দন বেড়ে যাওয়া',
    'Oppression': 'চাপবোধ',
    'Fullness': 'পূর্ণতা বোধ',
    'Emptiness': 'খালি বোধ',
    'Distension': 'ফুলে ওঠা',
    'Formication': 'পিঁপড়ে হাঁটার অনুভূতি',
    'Tingling': 'ঝিনঝিন',
    'Shocks': 'ধাক্কা',
    'Stiffness': 'শক্ত হওয়া',
    'Trembling': 'কম্পন',
    'Lameness': 'খোঁড়ানো',
    'Tumors': 'টিউমার',
    'Sensitive': 'সংবেদনশীল',
    'sensitive to pressure': 'চাপে সংবেদনশীল',
    'Difficult': 'কষ্টকর',
    'difficult': 'কষ্টকর',
    'Discharge': 'স্রাব',
    'Sediment': 'তলানি',
    'Urination': 'মূত্রত্যাগ',
    'Urging to urinate (morbid desire)': 'মূত্রত্যাগের বেগ',
    'Menses': 'ঋতুস্রাব',
    'Metrorrhagia': 'অনিয়মিত রক্তস্রাব',
    'Epistaxis': 'নাক দিয়ে রক্ত পড়া',
    'Erections': 'লিঙ্গোত্থান',
    'Appetite': 'ক্ষুধা',
    'Taste': 'স্বাদ',
    'Voice': 'কণ্ঠস্বর',
    'Noises in': '-এ শব্দ',
    'Colors before the eyes': 'চোখের সামনে রঙ',
    'Contraction of muscles and tendons': 'পেশি ও রগের সংকোচন',
    'Asthmatic': 'হাঁপানিজনিত',
    'Desires alcoholic drinks': 'মদ্যপানের ইচ্ছা',
    'Aversion to acids': 'অম্লজাতীয় খাবারে অরুচি',
    'Dim': 'ঝাপসা',
    'headache': 'মাথাব্যথা',
    'sciatica': 'সায়াটিকা',
    'rash': 'র‍্যাশ',
    'pimples': 'ছোট ফুসকুড়ি',
    'vesicles': 'জলভরা ফুসকুড়ি',
    'pustules': 'পুঁজভরা ফুসকুড়ি',
    'tubercles': 'শক্ত দানা',
    'blotches': 'ছোপ',
    'spots': 'ছোপ',
    'boils': 'ফোড়া',
    'scabs': 'মামড়ি',
    'redness': 'লালচে ভাব',
    'offensive': 'দুর্গন্ধযুক্ত',
    'involuntary': 'অনিচ্ছাকৃত',
    'suppressed': 'রুদ্ধ',

    # ---- time
    'morning': 'সকাল',
    'Morning': 'সকাল',
    'forenoon': 'পূর্বাহ্ন',
    'Forenoon': 'পূর্বাহ্ন',
    'noon': 'দুপুর',
    'Noon': 'দুপুর',
    'afternoon': 'বিকাল',
    'Afternoon': 'বিকাল',
    'evening': 'সন্ধ্যা',
    'Evening': 'সন্ধ্যা',
    'night': 'রাত',
    'Night': 'রাত',
    'midnight': 'মধ্যরাত',
    'Midnight': 'মধ্যরাত',
    'daytime': 'দিনের বেলা',
    'Daytime': 'দিনের বেলা',
    'first': 'প্রথম',
    'second': 'দ্বিতীয়',
    'third': 'তৃতীয়',
    'fourth': 'চতুর্থ',
    'middle': 'মধ্যভাগ',

    # ---- grammar / connectives
    'after': 'পরে',
    'before': 'আগে',
    'during': 'সময়ে',
    'while': 'অবস্থায়',
    'when': 'যখন',
    'with': 'সহ',
    'from': 'থেকে',
    'in': '-এ',
    'on': '-এ',
    'to': '-এর দিকে',
    'of': '-এর',
    'under': 'নিচে',
    'above': 'উপরে',
    'between': 'মাঝে',
    'inside': 'ভিতরে',
    'externally': 'বাইরে',
    'lower': 'নিচের',
    'upward': 'উপরের দিকে',
    'outward': 'বাইরের দিকে',
    'right': 'ডান',
    'left': 'বাম',
    'side': 'পাশ',
    'sides': 'পাশ',
    'sides of': '-এর পাশ',
    'back of': '-এর পিছনে',
    'region of': '-এর অঞ্চল',
    'joints of': '-এর সন্ধি',
    'hollow of': '-এর গর্ত',
    'anterior part': 'সামনের অংশ',
    'etc.': 'ইত্যাদি',
    'etc.)': 'ইত্যাদি)',
    'amel.': 'উপশম',
    'agg.': 'বৃদ্ধি',

    # ---- modalities
    'motion': 'নড়াচড়া',
    'Motion': 'নড়াচড়া',
    'motion agg.': 'নড়াচড়ায় বৃদ্ধি',
    'motion amel.': 'নড়াচড়ায় উপশম',
    'touch': 'স্পর্শ',
    'pressure': 'চাপ',
    'pressure amel.': 'চাপে উপশম',
    'pressure agg.': 'চাপে বৃদ্ধি',
    'rubbing amel.': 'ঘষায় উপশম',
    'scratching': 'আঁচড়ানো',
    'walking': 'হাঁটা',
    'walking in open air': 'খোলা বাতাসে হাঁটা',
    'sitting': 'বসা',
    'standing': 'দাঁড়ানো',
    'lying': 'শোয়া',
    'lying down': 'শুয়ে পড়া',
    'rising': 'ওঠা',
    'rising from a seat': 'আসন থেকে ওঠা',
    'stooping': 'ঝুঁকা',
    'exertion': 'পরিশ্রম',
    'mental exertion': 'মানসিক পরিশ্রম',
    'eating': 'খাওয়া',
    'drinking': 'পান করা',
    'dinner': 'দুপুরের খাবার',
    'breakfast': 'সকালের নাশতা',
    'supper': 'রাতের খাবার',
    'food': 'খাদ্য',
    'water': 'জল',
    'coughing': 'কাশা',
    'cough': 'কাশি',
    'sneezing': 'হাঁচি',
    'yawning': 'হাই তোলা',
    'writing': 'লেখা',
    'reading': 'পড়া',
    'talking': 'কথা বলা',
    'swallowing': 'গেলা',
    'coition': 'সহবাস',
    'pregnancy': 'গর্ভাবস্থা',
    'urination': 'মূত্রত্যাগ',
    'urinating': 'মূত্রত্যাগ',
    'stool': 'মল',
    'sleep': 'ঘুম',
    'waking': 'জাগা',
    'on waking': 'জাগার পর',
    'on going to': '-এ যাওয়ার সময়',
    'bed': 'বিছানা',
    'in bed': 'বিছানায়',
    'air': 'বাতাস',
    'open': 'খোলা',
    'in open': 'খোলা জায়গায়',
    'in open air': 'খোলা বাতাসে',
    'cold': 'ঠান্ডা',
    'heat': 'উত্তাপ',
    'warm room': 'গরম ঘর',
    'room': 'ঘর',
    'chill': 'কম্প',
    'fever': 'জ্বর',
    'menses': 'ঋতুস্রাব',
    'sour': 'টক',
    'bitter': 'তেতো',

    # ---- colours
    'black': 'কালো',
    'red': 'লাল',
    'yellow': 'হলুদ',
    'white': 'সাদা',
    'brown': 'বাদামি',
    'pale': 'ফ্যাকাশে',
    'bluish': 'নীলচে',
    'green': 'সবুজ',

    # ---- anatomy
    'head': 'মাথা',
    'forehead': 'কপাল',
    'frontal': 'সম্মুখভাগ',
    'occiput': 'মাথার পেছন',
    'occiput and Forehead': 'মাথার পেছন ও কপাল',
    'temples': 'রগ',
    'vertex': 'মাথার চাঁদি',
    'eminence': 'উঁচু অংশ',
    'eyes': 'চোখ',
    'lids': 'চোখের পাতা',
    'canthi': 'চোখের কোণ',
    'nose': 'নাক',
    'lips': 'ঠোঁট',
    'tongue': 'জিহ্বা',
    'palate': 'তালু',
    'gums': 'মাড়ি',
    'neck': 'ঘাড়',
    'throat': 'গলা',
    'larynx': 'কণ্ঠনালি',
    'chest': 'বুক',
    'sternum': 'বক্ষাস্থি',
    'mammæ': 'স্তন',
    'heart': 'হৃদয়',
    'axilla': 'বগল',
    'clavicle': 'কণ্ঠাস্থি',
    'shoulder': 'কাঁধ',
    'scapulæ': 'কাঁধের হাড়',
    'upper arm': 'বাহুর উপরাংশ',
    'elbow': 'কনুই',
    'forearm': 'বাহুর নিচের অংশ',
    'wrist': 'কবজি',
    'hand': 'হাত',
    'hands': 'হাত',
    'palm': 'হাতের তালু',
    'fingers': 'আঙুল',
    'thumb': 'বুড়ো আঙুল',
    'upper limbs': 'ঊর্ধ্বাঙ্গ',
    'lower limbs': 'নিম্নাঙ্গ',
    'hip': 'নিতম্ব',
    'thigh': 'উরু',
    'knee': 'হাঁটু',
    'patella': 'হাঁটুর মালাইচাকি',
    'leg': 'জঙ্ঘা',
    'calf': 'পায়ের গোছা',
    'tibia': 'নলার হাড়',
    'ankle': 'গোড়ালির সন্ধি',
    'heel': 'গোড়ালি',
    'foot': 'পা',
    'sole': 'পায়ের তলা',
    'toes': 'পায়ের আঙুল',
    'joints': 'সন্ধি',
    'bones': 'অস্থি',
    'bone': 'অস্থি',
    'back': 'পিঠ',
    'spine': 'মেরুদণ্ড',
    'cervical region': 'গ্রীবাদেশ',
    'dorsal region': 'পৃষ্ঠদেশ',
    'lumbar region': 'কটিদেশ',
    'sacral region': 'ত্রিকাস্থি অঞ্চল',
    'coccyx': 'পুচ্ছাস্থি',
    'nates': 'পাছা',
    'abdomen': 'উদর',
    'umbilicus': 'নাভি',
    'hypochondria': 'পাঁজরের নিচের পার্শ্বদেশ',
    'hypogastrium': 'তলপেট',
    'inguinal region': 'কুঁচকি',
    'iliac region': 'শ্রোণী অঞ্চল',
    'liver': 'যকৃৎ',
    'uterus': 'জরায়ু',
    'ovaries': 'ডিম্বাশয়',
    'vagina': 'যোনি',
    'penis': 'পুরুষাঙ্গ',
    'testes': 'অণ্ডকোষ',
    'scrotum': 'অণ্ডথলি',
    'spermatic cords': 'শুক্রনালি',
    'meatus': 'মুখছিদ্র',
    'tip': 'ডগা',
    'bearing down': 'নিচের দিকে ঠেলা',
    'extending to abdomen': 'উদর পর্যন্ত বিস্তৃত',
    'extending to back': 'পিঠ পর্যন্ত বিস্তৃত',
    'extending to ear': 'কান পর্যন্ত বিস্তৃত',
    'extending to anus': 'পায়ু পর্যন্ত বিস্তৃত',
    'extending downward': 'নিচের দিকে বিস্তৃত',
    'extending across': 'আড়াআড়ি বিস্তৃত',
    'extending to': '-পর্যন্ত বিস্তৃত',
    'inspiration': 'শ্বাস নেওয়া',
}

# A second pass, authored against a frequency count of the terms the first pass
# left in English — main rubric catchwords first, since those are what a
# practitioner scans for.
SEG.update({
    # ---- main rubric catchwords
    'Vertigo': 'মাথা ঘোরা', 'Time': 'সময়', 'Shaking': 'কাঁপা',
    'Loss of vision (blindness)': 'দৃষ্টিহীনতা (অন্ধত্ব)',
    'Irritability': 'বিরক্তি', 'Membrane': 'ঝিল্লি', 'Speech': 'কথা বলা',
    'Weakness (tired feeling': 'দুর্বলতা (ক্লান্তি বোধ',
    'Urging': 'বেগ', 'Hæmorrhoids': 'অর্শ', 'Pulse abnormal': 'অস্বাভাবিক নাড়ি',
    'Rumbling': 'গড়গড় শব্দ', 'Perspiration scalp': 'মাথার ত্বকে ঘাম',
    'Impaired': 'ক্ষীণ', 'Convulsion': 'আক্ষেপ', 'Warts': 'আঁচিল',
    'Gestures': 'অঙ্গভঙ্গি', 'Profuse': 'প্রচুর',
    'Irritation in air passages': 'শ্বাসনালিতে উত্তেজনা',
    'Mucus': 'শ্লেষ্মা', 'Leucorrhœa': 'শ্বেতপ্রদর', 'Spasmodic': 'আক্ষেপিক',
    'Heartburn': 'বুকজ্বালা', 'Gurgling': 'গড়গড় আওয়াজ',
    'Trembling externally': 'বাইরে কম্পন', 'Indifference': 'উদাসীনতা',
    'Falling asleep morning': 'সকালে ঘুম আসা', 'Obstruction': 'বাধা',
    'Motions': 'নড়াচড়া', 'Emaciation': 'শীর্ণতা', 'Odors': 'গন্ধ', 'Odor': 'গন্ধ',
    'Thirst': 'তৃষ্ণা', 'Bloody': 'রক্তমিশ্রিত', 'Swollen': 'ফোলা',
    'Deep': 'গভীর', 'Abscess': 'ফোড়া', 'Dullness': 'জড়তা',
    'Crawling': 'পোকা হাঁটার অনুভূতি', 'Contraction': 'সংকোচন', 'Lump': 'দলা',
    'Color': 'রঙ', 'Retching': 'বমির চেষ্টা', 'Mucous': 'শ্লেষ্মাযুক্ত',
    'Hiccough': 'হিক্কা', 'Copious (increased)': 'প্রচুর (বর্ধিত)',
    'Itching in': '-এ চুলকানি', 'Suicidal disposition': 'আত্মহত্যার প্রবণতা',
    'Seminal emissions (nightly)': 'রাতে শুক্রক্ষয়', 'Cracks skin': 'ত্বকে ফাটা',
    'Short': 'ছোট', 'Hair baldness': 'টাক', 'Saliva': 'লালা',
    'Choking': 'শ্বাসরোধ', 'Cracking': 'কড়কড় শব্দ', 'Lying agg.': 'শোয়ায় বৃদ্ধি',
    'Weak': 'দুর্বল', 'Shivering': 'শীতে কাঁপা', 'Cancer': 'ক্যান্সার',
    'Erysipelas': 'বিসর্প', 'Condylomata': 'আঁচিল-জাতীয় বৃদ্ধি',
    'Laughing': 'হাসা', 'Stupefaction': 'মূঢ়তা', 'Lachrymation': 'চোখে জল',
    'Hæmorrhage': 'রক্তস্রাব', 'Foggy': 'কুয়াশাচ্ছন্ন',
    'Catarrh': 'প্রদাহজনিত স্রাব', 'Continued fever': 'একটানা জ্বর',
    'Discharges': 'স্রাব', 'Hacking': 'খুকখুক', 'Ulceration': 'ক্ষত হওয়া',
    'Tickling': 'সুড়সুড়ি', 'Stretching': 'টানটান করা', 'Starting': 'চমকে ওঠা',
    'Gangrene': 'পচন', 'Prickling': 'সূচ ফোটার মতো', 'Hard': 'শক্ত',
    'Rattling': 'ঘড়ঘড় শব্দ', 'Flatus': 'বায়ু', 'Cheerful': 'প্রফুল্ল',
    'Violent': 'প্রচণ্ড', 'Sighing': 'দীর্ঘশ্বাস', 'Shuddering': 'শিউরে ওঠা',
    'Roughness': 'খসখসে ভাব', 'Flickering': 'ঝিলমিল',
    'Flatulence': 'পেটে বায়ু', 'Chorea': 'নৃত্যরোগ', 'Wind': 'বাতাস',
    'Shrieking': 'চিৎকার', 'Constipation': 'কোষ্ঠকাঠিন্য', 'Scraping': 'খচখচ',
    'Salivation': 'লালাক্ষরণ', 'Lassitude': 'শ্রান্তি', 'Irritation': 'উত্তেজনা',
    'Chilblains': 'শীতে ফোলা', 'Anger': 'রাগ', 'Insanity': 'উন্মত্ততা',
    'Retention of urine': 'মূত্ররোধ', 'Excrescences': 'অতিরিক্ত বৃদ্ধি',
    'Empty': 'খালি', 'Acute': 'তীব্র', 'Turning': 'ঘোরা',
    'Quarrelsome': 'কলহপ্রিয়', 'Photophobia': 'আলোভীতি', 'Loose': 'আলগা',
    'Excoriation': 'চামড়া ছিলে যাওয়া', 'Distention': 'ফুলে ওঠা',
    'Compression': 'চাপ', 'Stiffness': 'শক্ত হওয়া', 'Chilliness': 'শীত শীত ভাব',
    'Thoughts of death': 'মৃত্যুচিন্তা', 'Nodosities': 'গাঁট',
    'Moisture': 'আর্দ্রতা', 'Frothy': 'ফেনাযুক্ত', 'Cramp': 'খিঁচুনি',
    'Watery': 'জলীয়', 'Viscid': 'আঠালো', 'Thick': 'ঘন', 'Thin': 'পাতলা',
    'Scanty': 'অল্প', 'Dark': 'গাঢ়', 'Grief': 'শোক', 'Frequent': 'ঘন ঘন',
    'Whistling': 'শিস দেওয়া', 'Snoring': 'নাক ডাকা', 'Staring': 'একদৃষ্টে তাকানো',
    'Suppuration': 'পুঁজ হওয়া', 'Freckles': 'তিল-ছোপ', 'Moles': 'তিল',
    'Yellowness': 'হলদে ভাব', 'Insensibility': 'অনুভূতিহীনতা',
    'Suspicious': 'সন্দেহপ্রবণ', 'Sulky': 'গোমড়ামুখো', 'Sensitiveness': 'সংবেদনশীলতা',
    'Hardness': 'কাঠিন্য', 'Quivering': 'থরথর কম্পন', 'Sticky': 'আঠালো',
    'Tough': 'শক্ত-আঠালো', 'Clammy': 'ঠান্ডা-আঠালো', 'Chapped': 'ফাটা',
    'Cracks': 'ফাটা', 'Wrinkled': 'কুঞ্চিত', 'Ascending': 'উপরে ওঠা',
    'Descending': 'নিচে নামা', 'Slow': 'ধীর', 'Loss of fluids': 'তরল ক্ষয়',
    'Twisting': 'মোচড়ানো', 'Splitting': 'ফেটে যাওয়া', 'Spasms of': '-এর আক্ষেপ',
    'Spasm': 'আক্ষেপ', 'Uneasiness': 'অস্বস্তি', 'Thirstless': 'তৃষ্ণাহীন',
    'Rough': 'খসখসে', 'Acrid': 'ঝাঁঝালো', 'Albuminous': 'অ্যালবুমিনযুক্ত',
    'Aphthæ': 'মুখের ঘা', 'Polypus': 'পলিপ', 'Tumor': 'টিউমার',
    'Varicose veins': 'ফোলা শিরা', 'Whooping': 'হুপিং কাশি',
    'Singing': 'গান গাওয়া', 'Dancing': 'নাচা', 'Winking': 'চোখ পিটপিট',
    'Torticollis': 'ঘাড় বেঁকে যাওয়া', 'Vaginismus': 'যোনি-আক্ষেপ',
    'Purpura': 'ত্বকে রক্তছোপ',

    # ---- frequent sub-rubric segments
    'sees': 'দেখে', 'root': 'গোড়া', 'nails': 'নখ', 'nail': 'নখ',
    'extending to arms': 'বাহু পর্যন্ত বিস্তৃত', 'extending to arm': 'বাহু পর্যন্ত বিস্তৃত',
    'œsophagus': 'খাদ্যনালি', 'vexation': 'মনঃক্ষোভ', 'sticking': 'খোঁচা',
    'crusts': 'মামড়ি', 'crusty': 'মামড়িযুক্ত', 'upper': 'উপরের',
    'riding': 'গাড়িতে চড়া', 'riding in a carriage': 'গাড়িতে চড়া',
    'downward': 'নিচের দিকে', 'urticaria': 'আমবাত', 'hard': 'শক্ত',
    'bend of': '-এর ভাঁজ', 'sacrum': 'ত্রিকাস্থি', 'smoking': 'ধূমপান',
    'right side': 'ডান দিক', 'left side': 'বাম দিক', 'wine': 'মদ',
    'herpes': 'হারপিস', 'extending': 'বিস্তৃত', 'over': 'উপরে',
    'moist': 'আর্দ্র', 'brain': 'মস্তিষ্ক', 'tips': 'ডগা', 'tips of': '-এর ডগা',
    'of the': '-এর', 'dark': 'গাঢ়', 'cold air': 'ঠান্ডা বাতাস',
    'trachea': 'শ্বাসনালি', 'noise': 'শব্দ', 'frequent': 'ঘন ঘন',
    'coffee': 'কফি', 'at': '-এ', 'touch agg.': 'স্পর্শে বৃদ্ধি',
    'into': '-এর ভিতরে', 'extending to chest': 'বুক পর্যন্ত বিস্তৃত',
    'deep': 'গভীর', 'periodical': 'পর্যায়ক্রমিক', 'periodic': 'পর্যায়ক্রমিক',
    'lying agg.': 'শোয়ায় বৃদ্ধি', 'lying amel.': 'শোয়ায় উপশম',
    'copious': 'প্রচুর', 'ulcerative': 'ক্ষতকারী', 'stepping': 'পা ফেলা',
    'intermittent': 'থেমে থেমে', 'drawing in': 'টানা ব্যথা',
    'lower jaw': 'নিচের চোয়াল', 'jaw': 'চোয়াল', 'glands': 'গ্রন্থি',
    'feet': 'পা', 'extending backward': 'পিছনের দিকে বিস্তৃত',
    'extending down back': 'পিঠ বেয়ে নিচে বিস্তৃত',
    'walking amel.': 'হাঁটায় উপশম', 'walking agg.': 'হাঁটায় বৃদ্ধি',
    'putrid': 'পচা', 'empty': 'খালি', 'convulsive': 'আক্ষেপিক',
    'as from a': 'যেন কিছু থেকে', 'anger': 'রাগ', 'tenesmus': 'কোঁথ',
    'posterior part': 'পিছনের অংশ', 'forward': 'সামনের দিকে',
    'cracking': 'কড়কড়', 'milk': 'দুধ', 'blowing nose': 'নাক ঝাড়া',
    'sensation as if': 'অনুভূতি যেন', 'retarded': 'বিলম্বিত',
    'one-sided': 'একপাশে', 'ankles': 'গোড়ালি', 'about': '-এর চারপাশে',
    'moving': 'নড়া', 'rumbling': 'গড়গড়', 'rest': 'বিশ্রাম', 'lost': 'হারানো',
    'hoarseness': 'স্বরভঙ্গ', 'wings': 'নাকের পাখা', 'open air': 'খোলা বাতাস',
    'glans': 'শিশ্নমুণ্ড', 'prepuce': 'লিঙ্গত্বক', 'violent': 'প্রচণ্ড',
    'vesicular': 'জলভরা', 'upwards': 'উপরের দিকে', 'dull pain': 'ভোঁতা ব্যথা',
    'children': 'শিশু', 'blue': 'নীল', 'thighs': 'উরু', 'roaring': 'গর্জন',
    'respiration': 'শ্বাস', 'epilepsy': 'মৃগী', 'chin': 'চিবুক',
    'inner side': 'ভিতরের দিক', 'ascending steps': 'সিঁড়ি ওঠা',
    'soreness': 'ঘা-ব্যথা', 'blood': 'রক্ত', 'behind the ear': 'কানের পিছনে',
    'warm': 'গরম', 'warmth agg.': 'উষ্ণতায় বৃদ্ধি', 'tonsils': 'টনসিল',
    'scratching agg.': 'আঁচড়ানোয় বৃদ্ধি', 'ringing': 'ঝনঝন',
    'around': 'চারপাশে', 'spasmodic': 'আক্ষেপিক', 'eczema': 'একজিমা',
    'in the': '-এ', 'fright': 'ভয় পাওয়া', 'flatus': 'বায়ু', 'beer': 'বিয়ার',
    'wrists': 'কবজি', 'washing': 'ধোয়া', 'parotid gland': 'কর্ণমূল গ্রন্থি',
    'mouth': 'মুখ', 'breathing': 'শ্বাস নেওয়া', 'below': 'নিচে',
    'becoming': 'হয়ে যাওয়া', 'lying on back': 'চিৎ হয়ে শোয়া',
    'and region of': 'এবং -এর অঞ্চল', 'painless': 'ব্যথাহীন', 'must': 'অবশ্যই',
    'music': 'সঙ্গীত', 'ilium': 'শ্রোণীচক্রের হাড়', 'by': '-এর দ্বারা',
    'sole of': '-এর তলা', 'hot': 'গরম', 'ball of': '-এর মাংসল অংশ',
    'singing': 'গান গাওয়া', 'sitting agg.': 'বসায় বৃদ্ধি',
    'standing agg.': 'দাঁড়ানোয় বৃদ্ধি', 'drinking agg.': 'পানে বৃদ্ধি',
    'swallowing agg.': 'গেলায় বৃদ্ধি', 'uncovering agg.': 'অনাবৃত করায় বৃদ্ধি',
    'stool, during': 'মলত্যাগের সময়', 'urination, during': 'মূত্রত্যাগের সময়',
    'covered parts': 'আবৃত অংশ', 'affected parts': 'আক্রান্ত অংশ',
    'single parts': 'একক অংশ', 'upper part of body': 'শরীরের উপরের অংশ',
})

# ---------------------------------------------------------------- clock times
BN_DIGITS = str.maketrans('0123456789', '০১২৩৪৫৬৭৮৯')
_AM = re.compile(r'^(\d{1,2})(?::(\d{2}))?\s*a\.?\s*m\.?$', re.I)
_PM = re.compile(r'^(\d{1,2})(?::(\d{2}))?\s*p\.?\s*m\.?$', re.I)
_RANGE = re.compile(r'^(\d{1,2})\s*to\s*(\d{1,2})\s*([ap])\.?\s*m\.?$', re.I)


def _clock(hour, minute, meridiem):
    h = int(hour)
    part = ('ভোর' if h < 6 else 'সকাল') if meridiem == 'a' else \
           ('দুপুর' if h < 3 else ('বিকাল' if h < 6 else 'রাত'))
    t = str(h) + (f':{minute}' if minute else '')
    return f'{part} {t.translate(BN_DIGITS)}টা'


def bn_segment(seg):
    """Bangla for one comma-separated part of a rubric name, or None."""
    s = seg.strip()
    if not s:
        return ''
    hit = SEG.get(s) or SEG.get(s.lower()) or SEG.get(s[:1].upper() + s[1:])
    if hit:
        return hit
    m = _AM.match(s) or _PM.match(s)
    if m:
        return _clock(m.group(1), m.group(2), 'a' if _AM.match(s) else 'p')
    m = _RANGE.match(s)
    if m:
        a = _clock(m.group(1), None, m.group(3).lower())
        b = _clock(m.group(2), None, m.group(3).lower())
        return f'{a} থেকে {b}'
    return None


def bn_rubric(name):
    """Compose a rubric's Bangla name. Returns (bangla, every_part_translated).

    Untranslated parts are kept verbatim in English so the name still points at
    the right rubric; `full` tells the caller whether anything was left over.
    """
    parts = [p.strip() for p in name.split(',')]
    out, missing = [], 0
    for p in parts:
        bn = bn_segment(p)
        if bn is None:
            out.append(p)
            missing += 1
        else:
            out.append(bn)
    return ', '.join(out), missing == 0


def bn_coverage(rubs):
    """(total segment occurrences, how many the glossary resolves)."""
    total = known = 0
    for r in rubs:
        for p in r.name.split(','):
            p = p.strip()
            if not p:
                continue
            total += 1
            if bn_segment(p) is not None:
                known += 1
    return total, known


if __name__ == '__main__':
    print('glossary terms:', len(SEG))
    for n in ['Pain, stitching, forehead, evening, walking, amel.',
              'Fear, night, waking, after', 'Thirst, morning, waking, on',
              'Eruptions, itching, 4 p.m.', 'Pain, drawing, thigh, 3 to 7 p.m.',
              'Delusions, imaginations, hallucinations, illusions']:
        bn, full = bn_rubric(n)
        print(f'  {"OK " if full else "part"} {n}\n       {bn}')
