# -*- coding: utf-8 -*-
"""Kent's Repertory — chapters 11-20 (Teeth, Throat, External throat, Stomach,
   Abdomen, Rectum, Stool, Bladder, Kidneys, Prostate gland)."""

K2 = [
(11, 'Teeth - দাঁত', {
 'Toothache': ('দাঁতের ব্যথা', [('cham',3),('mag-p',3),('merc',3),('bell',2),('coff',2),('staph',2),('plan',2),('hep',2),('puls',2),('spig',2)]),
 'Toothache worse at night': ('রাতে দাঁতের ব্যথা বৃদ্ধি', [('merc',3),('cham',2),('mag-p',2),('bell',2),('puls',2),('sil',2)]),
 'Toothache worse from cold drinks': ('ঠান্ডা পানীয়ে দাঁতের ব্যথা', [('calc',3),('sep',2),('sil',2),('nux-v',2),('merc',2),('staph',2)]),
 'Toothache better from cold': ('ঠান্ডায় দাঁতের ব্যথা উপশম', [('coff',3),('puls',3),('bry',2),('bism',2),('ferr-p',2)]),
 'Toothache better from warmth': ('গরমে দাঁতের ব্যথা উপশম', [('mag-p',3),('nux-v',2),('ars',2),('rhus-t',2),('sil',2),('cham',1)]),
 'Toothache during menses': ('ঋতুস্রাবের সময় দাঁতের ব্যথা', [('sep',2),('staph',2),('cham',2),('lach',2),('mag-c',2)]),
 'Teeth decay rapidly': ('দাঁত দ্রুত ক্ষয়', [('staph',3),('kreos',3),('merc',2),('calc',2),('sil',2),('fl-ac',2),('thuj',2)]),
 'Teeth, dentition difficult': ('দাঁত ওঠায় কষ্ট', [('cham',3),('calc-p',3),('calc',2),('bell',2),('podo',2),('kreos',2),('mag-p',2),('sil',2)]),
 'Teeth, grinding': ('দাঁত কিড়মিড়', [('cina',3),('tub',3),('bell',2),('podo',2),('hyos',2),('stram',2),('ars',2)]),
 'Teeth sensitive to touch': ('দাঁত স্পর্শে সংবেদনশীল', [('merc',3),('staph',2),('cham',2),('hep',2),('nux-v',2),('bry',1)]),
 'Teeth, looseness of': ('দাঁত আলগা হওয়া', [('merc',3),('carb-v',2),('nit-ac',2),('phos',2),('lach',2),('staph',2)]),
 'Gums, abscess of (gumboil)': ('দাঁতের মাংসে ফোড়া', [('hep',3),('merc',3),('sil',2),('bell',2),('staph',2),('caust',1)]),
 'Toothache after tooth extraction': ('দাঁত তোলার পর ব্যথা', [('arn',3),('hyper',3),('staph',2),('phos',2),('ham',1)]),
 'Teeth, discoloured': ('দাঁতের রং বদলে যাওয়া', [('kreos',2),('staph',2),('merc',2),('thuj',2),('fl-ac',2)]),
}),

(12, 'Throat - গলা', {
 'Sore throat': ('গলা ব্যথা', [('bell',3),('merc',3),('phyt',3),('lach',3),('apis',2),('hep',2),('lyc',2),('bar-c',2),('acon',2),('nit-ac',2)]),
 'Sore throat, right side': ('গলার ডান দিকে ব্যথা', [('lyc',3),('bell',2),('phyt',2),('bar-c',2),('merc',2)]),
 'Sore throat, left side': ('গলার বাঁ দিকে ব্যথা', [('lach',3),('sabad',2),('mur-ac',2),('nit-ac',1)]),
 'Sore throat, side to side': ('গলার ব্যথা পাশ বদলায়', [('lac-c',3),('lach',2),('phyt',1),('merc',1)]),
 'Tonsils, enlarged': ('টনসিল বড় হওয়া', [('bar-c',3),('bar-m',3),('calc',2),('lyc',2),('merc',2),('psor',2),('tub',2),('phyt',2)]),
 'Tonsils, suppurating': ('টনসিলে পুঁজ', [('hep',3),('merc',3),('sil',2),('lach',2),('bell',2),('phyt',2),('bar-m',2)]),
 'Pain on swallowing': ('গিলতে ব্যথা', [('bell',3),('merc',2),('phyt',2),('apis',2),('lach',2),('hep',2),('nit-ac',2),('bar-c',2)]),
 'Pain on empty swallowing': ('খালি গিলতে ব্যথা', [('lach',3),('bry',2),('ign',3),('caps',2),('merc',1)]),
 'Better from warm drinks (throat)': ('গরম পানীয়ে গলা আরাম', [('lyc',3),('rhus-t',2),('ars',2),('nux-m',1),('sabad',2)]),
 'Better from cold drinks (throat)': ('ঠান্ডা পানীয়ে গলা আরাম', [('apis',3),('lach',2),('phyt',2),('sulph',2),('bell',1)]),
 'Lump sensation in throat': ('গলায় দলা পাকানো অনুভূতি', [('ign',3),('lach',2),('nat-m',2),('kali-c',2),('sep',2),('asaf',2),('nux-v',1)]),
 'Dryness of throat': ('গলা শুকনো', [('bell',3),('bry',2),('lach',2),('nux-m',2),('nat-m',2),('phos',2),('apis',2)]),
 'Choking in throat': ('গলায় দমবন্ধ ভাব', [('lach',3),('ign',2),('mosch',2),('apis',2),('stram',2),('cann-i',1)]),
 'Constriction of throat': ('গলার সংকোচন', [('lach',3),('bell',2),('stram',2),('canth',2),('ign',2),('hyos',2)]),
 'Hawking of mucus': ('গলা খাঁকারি দিয়ে শ্লেষ্মা তোলা', [('hydr',3),('kali-bi',3),('nat-c',2),('sep',2),('lyc',2),('phos',2),('sil',2)]),
 'Diphtheritic membrane': ('গলায় সাদা পর্দা', [('merc-c',3),('kali-bi',2),('lach',2),('lyc',2),('phyt',2),('apis',2)]),
 'Swelling of throat, uvula': ('আলজিভ ফোলা', [('apis',3),('merc',2),('phyt',2),('kali-bi',2),('lach',2),('nux-v',1)]),
 'Elongated uvula': ('আলজিভ লম্বা হওয়া', [('hyos',2),('merc',2),('kali-bi',2),('alum',1),('coff',1)]),
}),

(13, 'External throat - বাইরের গলা', {
 'Glands of neck swollen': ('ঘাড়ের গ্রন্থি ফোলা', [('bar-c',3),('calc',3),('merc',2),('sil',2),('tub',2),('phyt',2),('con',2),('brom',2),('cist',2)]),
 'Glands, indurated': ('গ্রন্থি শক্ত হওয়া', [('con',3),('calc-f',3),('bar-c',2),('sil',2),('carb-an',2),('lap-a',2),('scroph',2)]),
 'Goitre': ('গলগণ্ড', [('iod',3),('spong',3),('calc',2),('thyr',2),('lyc',2),('brom',2),('nat-m',1)]),
 'Stiffness of neck': ('ঘাড় শক্ত', [('rhus-t',3),('cimic',3),('bry',2),('lach',2),('nux-v',2),('caust',2),('dulc',2)]),
 'Pain in neck': ('ঘাড়ে ব্যথা', [('cimic',3),('rhus-t',2),('bry',2),('nux-v',2),('lach',2),('sang',2),('gels',2)]),
 'Cannot bear anything tight around neck': ('গলায় আঁটসাঁট কিছু অসহ্য', [('lach',3),('crot-h',2),('apis',2),('spong',1),('sep',1)]),
 'Pulsation in neck vessels': ('ঘাড়ের শিরায় স্পন্দন', [('bell',3),('glon',2),('acon',2),('ferr-p',2),('sang',1)]),
 'Eruptions on neck': ('ঘাড়ে ফুসকুড়ি', [('nat-m',2),('sulph',2),('graph',2),('psor',2),('hep',2),('sil',1)]),
}),

(14, 'Stomach - পাকস্থলী', {
 'Appetite increased': ('ক্ষুধা বৃদ্ধি', [('iod',3),('lyc',2),('sulph',2),('cina',2),('calc',2),('phos',2),('chin',2),('tub',2),('nat-m',1)]),
 'Appetite diminished': ('ক্ষুধা হ্রাস', [('ars',3),('nux-v',2),('puls',2),('sep',2),('chin',2),('ferr',2),('sil',2),('carc',2),('ph-ac',2)]),
 'Appetite, easy satiety': ('অল্পতেই পেট ভরা', [('lyc',3),('carb-v',2),('chin',2),('sulph',2),('nux-v',2),('sep',1)]),
 'Appetite, ravenous yet emaciates': ('প্রচুর ক্ষুধা তবু শুকিয়ে যায়', [('iod',3),('nat-m',3),('tub',2),('cina',2),('abrot',2),('calc',1)]),
 'Thirst, extreme': ('তীব্র তৃষ্ণা', [('bry',3),('ars',3),('phos',3),('nat-m',2),('verat',2),('acon',2),('chin',2),('merc',2),('eup-per',2)]),
 'Thirstless': ('তৃষ্ণাহীনতা', [('puls',3),('apis',3),('gels',2),('ant-t',2),('cham',2),('ign',2),('sabad',2),('nux-m',2)]),
 'Cravings for salt': ('লবণের আকাঙ্ক্ষা', [('nat-m',3),('phos',2),('calc',2),('carb-v',2),('med',2),('verat',1)]),
 'Cravings for sweets': ('মিষ্টির আকাঙ্ক্ষা', [('lyc',3),('sulph',3),('arg-n',3),('calc',2),('kali-c',2),('med',2),('carb-v',2),('chin',1)]),
 'Cravings for sour': ('অম্লের আকাঙ্ক্ষা', [('hep',3),('sep',2),('verat',2),('puls',2),('sul-ac',2),('ars',2),('ign',2),('nat-m',1)]),
 'Cravings for fat': ('চর্বির আকাঙ্ক্ষা', [('nux-v',3),('sulph',2),('ars',2),('hep',2),('nit-ac',2),('tub',2)]),
 'Cravings for cold drinks': ('ঠান্ডা পানীয়ের আকাঙ্ক্ষা', [('phos',3),('verat',3),('bry',2),('acon',2),('merc',2),('med',2),('sulph',2)]),
 'Cravings for warm drinks': ('গরম পানীয়ের আকাঙ্ক্ষা', [('lyc',3),('ars',3),('chel',2),('sabad',2),('rhus-t',1)]),
 'Cravings for indigestible things': ('অখাদ্য বস্তুর আকাঙ্ক্ষা', [('calc',3),('alum',3),('nit-ac',2),('nux-v',2),('sil',1)]),
 'Aversion to meat': ('মাংসে অরুচি', [('sulph',3),('puls',2),('nit-ac',2),('merc',2),('graph',2),('calc',2),('sil',2),('carb-v',1)]),
 'Aversion to milk': ('দুধে অরুচি', [('nat-c',3),('sep',2),('calc',2),('sil',2),('lac-d',2),('sulph',2),('bry',2),('ign',1)]),
 'Aversion to sweets': ('মিষ্টিতে অরুচি', [('graph',3),('caust',2),('merc',2),('nit-ac',2),('sulph',1),('zinc',1)]),
 'Aversion to fat': ('চর্বিতে অরুচি', [('puls',3),('petr',2),('sep',2),('hep',2),('china',0),('bell',1)]),
 'Aversion to warm food': ('গরম খাবারে অরুচি', [('phos',3),('puls',2),('graph',1),('lyc',1)]),
 'Nausea': ('বমি ভাব', [('ip',3),('nux-v',3),('cocc',3),('tab',3),('ars',2),('sep',2),('puls',2),('sang',2),('colch',2),('bry',2)]),
 'Nausea in the morning': ('সকালে বমি ভাব', [('nux-v',3),('sep',3),('lyc',2),('carb-v',2),('puls',2),('kreos',2)]),
 'Nausea during pregnancy': ('গর্ভাবস্থার বমি ভাব', [('ip',3),('sep',3),('nux-v',3),('puls',2),('tab',2),('cocc',2),('lac-d',2),('kreos',2)]),
 'Vomiting': ('বমি', [('ip',3),('ars',3),('verat',3),('nux-v',2),('phos',2),('puls',2),('bry',2),('sang',2),('tab',2),('cupr',2)]),
 'Vomiting of bile': ('পিত্ত বমি', [('chel',3),('nux-v',2),('bry',2),('ip',2),('puls',2),('ars',2),('sang',2)]),
 'Vomiting of blood': ('রক্ত বমি', [('phos',3),('ip',2),('arn',2),('ham',2),('ars',2),('nux-v',1),('mill',2)]),
 'Vomiting, sour': ('টক বমি', [('nux-v',3),('nat-p',2),('sul-ac',2),('calc',2),('lyc',2),('cham',2)]),
 'Eructation': ('ঢেকুর', [('carb-v',3),('lyc',3),('nux-v',2),('chin',2),('sep',2),('kali-c',2),('nat-p',2),('sul-ac',2)]),
 'Heartburn': ('বুক জ্বালা', [('nux-v',3),('nat-p',3),('sul-ac',2),('carb-v',2),('phos',2),('ars',2),('lyc',2),('iris',2)]),
 'Pain in stomach': ('পাকস্থলীর ব্যথা', [('nux-v',3),('bry',3),('ars',3),('kali-bi',2),('lyc',2),('phos',2),('puls',2),('chel',2),('coloc',2)]),
 'Burning in stomach': ('পাকস্থলীতে জ্বালা', [('ars',3),('phos',3),('sulph',2),('nux-v',2),('carb-v',2),('iris',2),('sul-ac',2),('nat-p',2),('canth',2)]),
 'Cramping in stomach': ('পাকস্থলীর খিঁচুনি', [('coloc',3),('mag-p',3),('nux-v',2),('cupr',2),('plb',2),('bell',2),('cham',2)]),
 'Fullness after eating': ('খাওয়ার পর পেট ভরা ভাব', [('lyc',3),('carb-v',3),('nux-v',2),('chin',2),('kali-c',2),('sep',2),('graph',2)]),
 'Emptiness in stomach': ('পাকস্থলীতে ফাঁকা ভাব', [('sulph',3),('sep',2),('phos',2),('cocc',2),('ign',2),('chin',2),('carc',1)]),
 'Gastric ulcer': ('পাকস্থলীর ঘা', [('kali-bi',3),('arg-n',2),('ars',2),('phos',2),('nux-v',2),('lyc',2),('hydr',2)]),
 'Hiccough': ('হেঁচকি', [('ign',3),('nux-v',2),('mag-p',2),('cic',2),('hyos',2),('teucr',1)]),
 'Regurgitation of food': ('খাবার উঠে আসা', [('phos',3),('nux-v',2),('carb-v',2),('lyc',2),('kali-c',2),('sul-ac',2),('brom',1)]),
}),

(15, 'Abdomen - উদর', {
 'Pain in abdomen, colic': ('পেটের ব্যথা (কোলিক)', [('coloc',3),('mag-p',3),('cham',3),('bell',2),('nux-v',2),('plb',2),('dios',2),('lyc',2),('chin',2)]),
 'Colic better bending double': ('কুঁকড়ে গেলে পেটের ব্যথা উপশম', [('coloc',3),('mag-p',2),('chin',2),('nux-v',2),('bell',1)]),
 'Colic better bending backward': ('পিছনে হেলে পেটের ব্যথা উপশম', [('dios',3),('bell',2),('plb',1),('sec',1)]),
 'Flatulence, distension': ('পেট ফাঁপা', [('lyc',3),('carb-v',3),('chin',3),('nux-v',2),('sulph',2),('mag-p',2),('kali-c',2),('raph',2),('arg-n',2)]),
 'Rumbling in abdomen': ('পেটে গুড়গুড় শব্দ', [('lyc',3),('podo',2),('nat-s',2),('carb-v',2),('chin',2),('aloe',2),('sulph',2)]),
 'Liver, pain in region of': ('লিভার অঞ্চলে ব্যথা', [('chel',3),('lyc',3),('nat-s',3),('bry',2),('card-m',2),('nux-v',2),('mag-m',2),('sep',2)]),
 'Liver, enlarged': ('লিভার বড় হওয়া', [('card-m',3),('chel',2),('nat-s',2),('lyc',2),('sulph',2),('mag-m',2),('lept',2)]),
 'Jaundice': ('জন্ডিস', [('chel',3),('chin',2),('nat-s',2),('card-m',2),('lyc',2),('merc',2),('lept',2),('phos',2)]),
 'Gall stone colic': ('পিত্তথলির পাথরের ব্যথা', [('chel',3),('berb',3),('coloc',2),('mag-p',2),('lyc',2),('card-m',2),('nux-v',2)]),
 'Spleen, pain in': ('প্লীহায় ব্যথা', [('chin',3),('cean',3),('nat-m',2),('sulph',2),('ars',2),('agar',1)]),
 'Umbilical pain': ('নাভির চারপাশে ব্যথা', [('coloc',2),('plb',2),('nux-v',2),('cocc',2),('spig',2),('cina',2)]),
 'Hernia, inguinal': ('কুঁচকির হার্নিয়া', [('nux-v',3),('lyc',2),('calc',2),('sil',2),('aur',2),('cocc',2)]),
 'Abdomen, hardness of': ('পেট শক্ত', [('bry',2),('plb',2),('calc',2),('sulph',2),('lyc',2),('chin',1)]),
 'Abdomen, distended in children': ('শিশুর পেট ফোলা', [('calc',3),('sulph',2),('bar-c',2),('sil',2),('cina',2),('lyc',2)]),
 'Ascites': ('উদরে পানি', [('apis',2),('ars',2),('chin',2),('dig',2),('lyc',2),('sulph',2),('ter',1)]),
 'Pain worse after eating': ('খাওয়ার পর পেটে ব্যথা বৃদ্ধি', [('nux-v',3),('bry',2),('chin',2),('carb-v',2),('lyc',2),('kali-c',2),('puls',2)]),
 'Pain better after stool': ('মলত্যাগের পর পেটে ব্যথা উপশম', [('nat-s',2),('nux-v',2),('coloc',2),('aloe',2),('gamb',2)]),
 'Pain worse before stool': ('মলত্যাগের আগে পেটে ব্যথা', [('coloc',2),('merc',2),('aloe',2),('sulph',2),('nux-v',2),('rheum',2)]),
 'Worms, ailments from': ('কৃমির উপদ্রব', [('cina',3),('sabad',3),('santin',3),('teucr',2),('sulph',2),('nat-p',2),('spig',2)]),
 'Appendicitis pain': ('অ্যাপেন্ডিক্সের ব্যথা', [('bell',3),('bry',2),('rhus-t',2),('merc',2),('lach',2),('plb',1),('ars',1)]),
 'Coldness in abdomen': ('পেটে শীতলতা', [('camph',2),('verat',2),('carb-v',2),('colch',2),('ars',1)]),
 'Weight, sensation of in abdomen': ('পেটে ভারী ভাব', [('nux-v',2),('lyc',2),('sep',2),('sulph',2),('aloe',2),('bry',1)]),
 'Pulsation in abdomen': ('পেটে স্পন্দন', [('bell',2),('glon',2),('sulph',2),('calc',2),('nat-m',1)]),
 'Tenderness of abdomen': ('পেটে স্পর্শকাতরতা', [('bell',3),('bry',2),('merc',2),('apis',2),('lach',2),('ars',2)]),
 'Emaciation of abdomen in children': ('শিশুর পেট শুকিয়ে যাওয়া', [('abrot',3),('nat-m',2),('iod',2),('sanic',2),('tub',2),('sulph',1)]),
}),

(16, 'Rectum - মলদ্বার', {
 'Constipation': ('কোষ্ঠকাঠিন্য', [('nux-v',3),('bry',3),('alum',3),('op',2),('sulph',2),('lyc',2),('sep',2),('sil',2),('graph',2),('plb',2),('nat-m',2)]),
 'Constipation, ineffectual urging': ('মলত্যাগের বৃথা চাপ', [('nux-v',3),('anac',2),('lyc',2),('merc',2),('sep',2),('sil',2),('carc',1)]),
 'Constipation with no urge': ('মলত্যাগের ইচ্ছাই না হওয়া', [('alum',3),('op',3),('sulph',2),('sanic',2),('bry',2),('hydr',2)]),
 'Diarrhoea': ('পাতলা পায়খানা', [('podo',3),('ars',3),('verat',3),('sulph',2),('cham',2),('chin',2),('aloe',2),('merc',2),('gels',2),('nat-s',2)]),
 'Diarrhoea, painless': ('ব্যথাহীন পাতলা পায়খানা', [('chin',3),('phos',3),('podo',2),('ph-ac',2),('hydr',2),('apis',2)]),
 'Diarrhoea from fright': ('ভয়ের পর ডায়রিয়া', [('gels',3),('arg-n',3),('op',2),('acon',2),('phos',2),('puls',1)]),
 'Diarrhoea after eating': ('খাওয়ার পর ডায়রিয়া', [('aloe',3),('chin',2),('ferr',2),('nat-s',2),('sulph',2),('podo',2),('trom',1)]),
 'Dysentery': ('আমাশয়', [('merc-c',3),('merc',2),('nux-v',2),('colch',2),('canth',2),('aloe',2),('capsicum',0),('caps',2)]),
 'Haemorrhoids': ('অর্শ', [('aesc',3),('nux-v',3),('sulph',3),('ham',2),('coll',2),('aloe',2),('mur-ac',2),('lyc',2),('rat',2),('paeon',2)]),
 'Haemorrhoids, bleeding': ('অর্শে রক্তপাত', [('ham',3),('mur-ac',2),('sulph',2),('nux-v',2),('nit-ac',2),('phos',2),('coll',2)]),
 'Fissure of anus': ('মলদ্বারে ফাটল', [('nit-ac',3),('rat',3),('graph',2),('paeon',2),('sil',2),('sulph',2),('thuj',2)]),
 'Pain in rectum, burning': ('মলদ্বারে জ্বালা', [('sulph',3),('ars',2),('nit-ac',2),('merc',2),('aloe',2),('canth',1)]),
 'Pain in rectum, stitching': ('মলদ্বারে সেলাইয়ের মতো ব্যথা', [('nit-ac',3),('aesc',2),('rat',2),('coll',2),('sil',2),('sulph',1)]),
 'Sensation of stick in rectum': ('মলদ্বারে কাঠি ভরার অনুভূতি', [('aesc',3),('coll',2),('nit-ac',1),('sulph',1)]),
 'Prolapsus of rectum': ('মলদ্বার বেরিয়ে আসা', [('podo',3),('ign',3),('rut',0),('ruta',2),('merc',2),('nux-v',2),('sulph',2),('sep',2)]),
 'Itching of anus': ('মলদ্বারে চুলকানি', [('sulph',3),('cina',2),('teucr',2),('nit-ac',2),('ign',2),('petr',2),('nat-p',2)]),
 'Worms in rectum': ('মলদ্বারে কৃমি', [('cina',3),('teucr',3),('sabad',2),('santin',2),('nat-p',2),('sulph',2)]),
 'Urging, sudden': ('হঠাৎ মলত্যাগের চাপ', [('aloe',3),('sulph',3),('merc',2),('nux-v',2),('podo',2),('gamb',2)]),
 'Constriction of rectum': ('মলদ্বারের সংকোচন', [('nux-v',3),('nit-ac',2),('lach',2),('caust',2),('op',2),('plb',2)]),
 'Involuntary stool': ('অনিচ্ছাকৃত মলত্যাগ', [('aloe',3),('op',2),('ars',2),('phos',2),('hyos',2),('sec',2),('mur-ac',2)]),
 'Flatus, offensive': ('দুর্গন্ধযুক্ত বাতকর্ম', [('carb-v',3),('psor',2),('ars',2),('sulph',2),('graph',2),('asaf',2)]),
 'Moisture at anus': ('মলদ্বারে ভেজা ভাব', [('carb-v',2),('sulph',2),('petr',2),('thuj',2),('sil',2),('ant-c',1)]),
}),

(17, 'Stool - মল', {
 'Stool, hard': ('শক্ত মল', [('bry',3),('alum',3),('nat-m',2),('sulph',2),('sil',2),('plb',2),('op',2),('lyc',2)]),
 'Stool, large': ('বড় আকারের মল', [('bry',3),('sulph',2),('calc',2),('nat-m',2),('graph',2),('mag-m',2)]),
 'Stool, thin, narrow': ('সরু মল', [('phos',3),('caust',2),('lach',2),('chel',1),('plb',1)]),
 'Stool, sheep dung like': ('ভেড়ার নাদির মতো মল', [('plb',3),('op',2),('mag-m',2),('chel',2),('nat-m',1)]),
 'Stool, loose': ('নরম মল', [('podo',2),('sulph',2),('chin',2),('aloe',2),('nat-s',2),('puls',2),('merc',2)]),
 'Stool, watery': ('পানির মতো মল', [('podo',3),('verat',3),('ars',2),('chin',2),('phos',2),('gamb',2),('croc',0)]),
 'Stool, mucous': ('শ্লেষ্মাযুক্ত মল', [('merc',3),('nux-v',2),('sulph',2),('aloe',2),('colch',2),('kali-bi',2),('puls',2)]),
 'Stool, bloody': ('রক্তমিশ্রিত মল', [('merc-c',3),('nit-ac',2),('sulph',2),('ham',2),('nux-v',2),('phos',2),('ars',2),('alum',1)]),
 'Stool, undigested': ('অপাচ্য খাবারযুক্ত মল', [('chin',3),('ferr',3),('graph',2),('ars',2),('podo',2),('calc',2),('nat-c',1)]),
 'Stool, green': ('সবুজ মল', [('cham',3),('merc',2),('podo',2),('ip',2),('mag-c',2),('puls',2),('calc',1)]),
 'Stool, black': ('কালো মল', [('lept',3),('op',2),('ars',2),('chin',2),('merc',1),('bry',1)]),
 'Stool, yellow': ('হলুদ মল', [('chel',3),('podo',2),('puls',2),('merc',2),('gels',2),('lept',2)]),
 'Stool, white': ('সাদা মল', [('chel',2),('calc',2),('podo',2),('dig',2),('phos',1)]),
 'Stool, offensive': ('দুর্গন্ধযুক্ত মল', [('psor',3),('carb-v',3),('ars',2),('merc',2),('sulph',2),('pyrog',2),('bapt',2),('graph',1)]),
 'Stool, sour smelling': ('টক গন্ধযুক্ত মল', [('calc',3),('rheum',3),('mag-c',2),('hep',2),('sulph',1)]),
 'Stool, in the morning': ('সকালে মলত্যাগ', [('sulph',3),('podo',3),('nat-s',2),('nux-v',2),('rumx',2),('bry',1)]),
 'Stool, at night': ('রাতে মলত্যাগ', [('ars',3),('chin',2),('merc',2),('podo',2),('phos',2),('sulph',1)]),
 'Stool, painful': ('মলত্যাগে ব্যথা', [('nux-v',3),('nit-ac',3),('merc',2),('sulph',2),('rat',2),('aesc',2),('sil',2)]),
 'Stool, incomplete': ('অসম্পূর্ণ মলত্যাগ', [('nux-v',3),('sulph',2),('merc',2),('lyc',2),('sep',2),('carb-v',2),('aloe',2)]),
 'Stool, alternating constipation and diarrhoea': ('কোষ্ঠকাঠিন্য ও ডায়রিয়া পালা করে', [('nux-v',3),('sulph',2),('ant-c',2),('podo',2),('bry',2),('psor',2),('chel',1)]),
}),

(18, 'Bladder - মূত্রথলি', {
 'Cystitis, inflammation of bladder': ('মূত্রথলির প্রদাহ', [('canth',3),('apis',3),('merc-c',2),('staph',2),('sars',2),('berb',2),('acon',2),('equis',2)]),
 'Pain in bladder': ('মূত্রথলিতে ব্যথা', [('canth',3),('apis',2),('nux-v',2),('staph',2),('merc-c',2),('sars',2),('equis',2)]),
 'Urging to urinate, frequent': ('ঘন ঘন প্রস্রাবের চাপ', [('canth',3),('apis',2),('puls',2),('nux-v',2),('merc-c',2),('sulph',2),('staph',2),('equis',2)]),
 'Urging, ineffectual': ('প্রস্রাবের বৃথা চাপ', [('canth',3),('nux-v',2),('op',2),('apis',2),('caust',2),('stram',2)]),
 'Retention of urine': ('প্রস্রাব বন্ধ', [('acon',3),('canth',2),('apis',2),('op',2),('nux-v',2),('caust',2),('stram',2)]),
 'Incontinence of urine': ('প্রস্রাব ধরে রাখতে না পারা', [('caust',3),('puls',3),('sep',2),('bell',2),('kreos',2),('rhus-t',2),('nat-m',2),('equis',2)]),
 'Urination involuntary while coughing': ('কাশলে প্রস্রাব বেরিয়ে যাওয়া', [('caust',3),('nat-m',2),('puls',2),('sep',2),('squil',2),('zinc',2)]),
 'Bed wetting in children': ('শিশুর বিছানায় প্রস্রাব', [('caust',3),('kreos',3),('equis',2),('puls',2),('bell',2),('sep',2),('rhus-t',2),('sil',2)]),
 'Urination, must hurry': ('প্রস্রাব চেপে রাখতে না পারা', [('canth',2),('apis',2),('puls',2),('sulph',2),('petr',2),('staph',1)]),
 'Bladder, weakness of': ('মূত্রথলির দুর্বলতা', [('caust',3),('sep',2),('con',2),('sil',2),('staph',2),('lyc',1)]),
 'Bladder, fullness sensation': ('মূত্রথলি ভরা অনুভূতি', [('canth',2),('lyc',2),('sars',2),('berb',2),('equis',2)]),
 'Urination worse standing': ('দাঁড়িয়ে প্রস্রাবে কষ্ট', [('sars',3),('zinc',2),('nat-m',1),('caust',1)]),
 'Tenesmus of bladder': ('মূত্রথলির টান', [('canth',3),('merc-c',2),('nux-v',2),('apis',2),('caps',1)]),
 'Urination, dribbling': ('ফোঁটা ফোঁটা প্রস্রাব', [('canth',2),('sel',2),('thuj',2),('con',2),('caust',2),('sars',2)]),
 'Bladder, stones in': ('মূত্রথলিতে পাথর', [('berb',3),('lyc',2),('sars',2),('canth',2),('calc',2),('pareir',2),('uva',2)]),
}),

(19, 'Kidneys - কিডনি', {
 'Pain in kidney region': ('কিডনি অঞ্চলে ব্যথা', [('berb',3),('lyc',3),('ter',2),('canth',2),('sars',2),('nux-v',2),('coloc',2),('pareir',2)]),
 'Renal colic': ('কিডনির পাথরের ব্যথা', [('berb',3),('lyc',3),('pareir',3),('coloc',2),('canth',2),('sars',2),('mag-p',2),('ocim',2)]),
 'Nephritis': ('কিডনির প্রদাহ', [('apis',3),('canth',3),('ter',3),('merc-c',2),('ars',2),('phos',2),('dig',2)]),
 'Kidney pain extending down ureter': ('কিডনি থেকে নিচে ছড়ানো ব্যথা', [('berb',3),('lyc',2),('pareir',2),('sars',2),('canth',2),('ocim',2)]),
 'Suppression of urine': ('প্রস্রাব তৈরি বন্ধ', [('apis',3),('canth',2),('ars',2),('ter',2),('dig',2),('hell',2)]),
 'Albuminuria': ('প্রস্রাবে অ্যালবুমিন', [('apis',3),('ars',2),('phos',2),('merc-c',2),('ter',2),('kali-c',2)]),
 'Kidney pain worse motion': ('নড়াচড়ায় কিডনির ব্যথা বৃদ্ধি', [('berb',3),('bry',2),('canth',2),('lyc',1)]),
 'Kidney pain with nausea': ('বমি ভাবসহ কিডনির ব্যথা', [('berb',2),('ocim',2),('tab',2),('lyc',2),('canth',1)]),
}),

(20, 'Prostate gland - প্রস্টেট', {
 'Prostate, enlarged': ('প্রস্টেট বড় হওয়া', [('thuj',3),('con',3),('sabal',3),('puls',2),('sel',2),('lyc',2),('bar-c',2),('sil',2),('caust',2)]),
 'Prostate, inflammation of': ('প্রস্টেটের প্রদাহ', [('puls',3),('thuj',2),('caust',2),('sel',2),('merc',2),('sabal',2),('chim',0)]),
 'Prostate, pain in': ('প্রস্টেটে ব্যথা', [('thuj',2),('con',2),('puls',2),('sel',2),('lyc',2),('staph',2),('sabal',2)]),
 'Prostatic discharge': ('প্রস্টেট থেকে স্রাব', [('sel',3),('con',2),('thuj',2),('sabal',2),('nat-m',1),('sulph',1)]),
 'Prostate, urging with dribbling': ('প্রস্টেটজনিত ফোঁটা প্রস্রাব', [('sabal',3),('thuj',2),('con',2),('sel',2),('caust',2),('dig',2)]),
 'Prostate complaints in old age': ('বার্ধক্যে প্রস্টেটের সমস্যা', [('bar-c',3),('con',2),('sabal',2),('thuj',2),('sel',2),('lyc',2),('sulph',1)]),
}),
]
