# -*- coding: utf-8 -*-
"""Kent's Repertory — chapters 21-30 (Urethra, Urine, Genitalia male,
   Genitalia female, Larynx & trachea, Respiration, Cough, Expectoration,
   Chest, Back)."""

K3 = [
(21, 'Urethra - মূত্রনালি', {
 'Burning during urination': ('প্রস্রাবে জ্বালা', [('canth',3),('apis',3),('merc-c',3),('sars',2),('nit-ac',2),('sulph',2),('staph',2),('berb',2)]),
 'Burning at beginning of urination': ('প্রস্রাবের শুরুতে জ্বালা', [('canth',3),('thuj',2),('nat-m',2),('caust',2),('clem',2)]),
 'Burning at end of urination': ('প্রস্রাবের শেষে জ্বালা', [('sars',3),('canth',2),('equis',2),('thuj',2),('berb',2),('med',2)]),
 'Burning after urination': ('প্রস্রাবের পর জ্বালা', [('staph',3),('canth',2),('sars',2),('nit-ac',2),('berb',2),('equis',2)]),
 'Discharge from urethra': ('মূত্রনালি থেকে স্রাব', [('merc',3),('thuj',3),('cann-s',2),('nit-ac',2),('puls',2),('med',2),('cop',2),('cub',2)]),
 'Gonorrhoeal discharge': ('গনোরিয়ার স্রাব', [('med',3),('thuj',3),('cann-s',3),('merc',2),('cop',2),('cub',2),('nat-s',2),('puls',2)]),
 'Stricture of urethra': ('মূত্রনালি সংকীর্ণ হওয়া', [('clem',3),('thuj',2),('petr',2),('sulph',2),('arg-n',2),('caust',2)]),
 'Pain in urethra, cutting': ('মূত্রনালিতে কাটার মতো ব্যথা', [('canth',3),('merc-c',2),('nit-ac',2),('sars',2),('thuj',2),('cann-s',2)]),
 'Itching in urethra': ('মূত্রনালিতে চুলকানি', [('petr',2),('thuj',2),('sulph',2),('calad',2),('nit-ac',1)]),
 'Urethra, sensation of drop remaining': ('মূত্রনালিতে ফোঁটা রয়ে যাওয়ার অনুভূতি', [('kali-bi',2),('thuj',2),('sel',2),('caust',2),('petr',1)]),
}),

(22, 'Urine - প্রস্রাব', {
 'Urine, copious': ('প্রচুর প্রস্রাব', [('ph-ac',3),('acon',2),('apis',2),('gels',2),('sil',2),('mur-ac',2),('syzyg',2)]),
 'Urine, scanty': ('অল্প প্রস্রাব', [('apis',3),('canth',2),('ars',2),('bell',2),('dig',2),('ter',2),('colch',2)]),
 'Urine, frequent': ('ঘন ঘন প্রস্রাব', [('puls',3),('sulph',2),('lyc',2),('sep',2),('nat-m',2),('thuj',2),('ph-ac',2),('bell',2)]),
 'Urine, dark': ('গাঢ় প্রস্রাব', [('benz-ac',3),('bry',2),('chel',2),('ars',2),('lach',2),('nux-v',2)]),
 'Urine, cloudy': ('ঘোলা প্রস্রাব', [('sep',3),('phos',2),('berb',2),('chin',2),('graph',2),('sulph',2)]),
 'Urine, offensive': ('দুর্গন্ধযুক্ত প্রস্রাব', [('benz-ac',3),('nit-ac',3),('sep',2),('psor',2),('merc',2),('sulph',1)]),
 'Urine, bloody': ('প্রস্রাবে রক্ত', [('canth',3),('ter',3),('ham',2),('phos',2),('merc-c',2),('berb',2),('sec',2),('mill',2)]),
 'Urine, sediment, red': ('প্রস্রাবে লালচে তলানি', [('berb',3),('lyc',3),('sars',2),('sep',2),('phos',2),('nit-ac',2)]),
 'Urine, sediment, white': ('প্রস্রাবে সাদা তলানি', [('sep',3),('phos',2),('graph',2),('calc',2),('berb',2),('chin',1)]),
 'Urine, albuminous': ('প্রস্রাবে অ্যালবুমিন', [('apis',3),('ars',2),('phos',2),('merc-c',2),('ter',2),('kali-c',2)]),
 'Urine, sugar in (diabetes)': ('প্রস্রাবে চিনি', [('syzyg',3),('ph-ac',3),('uran-n',3),('lyc',2),('nat-s',2),('ars',2),('gymn',2)]),
 'Urine, milky': ('দুধের মতো প্রস্রাব', [('phos',2),('sep',2),('chin',2),('cina',2),('sil',1)]),
 'Urine, greasy pellicle on': ('প্রস্রাবের উপর তেলের মতো স্তর', [('phos',3),('sep',2),('sulph',1),('chin',1)]),
 'Urine, brick-dust sediment': ('ইটের গুঁড়োর মতো তলানি', [('berb',3),('lyc',3),('sars',2),('nit-ac',2),('sep',2)]),
 'Urine, burning while flowing': ('প্রস্রাব বেরোনোর সময় জ্বালা', [('canth',3),('merc-c',2),('apis',2),('sars',2),('nit-ac',2)]),
 'Urine, involuntary at night': ('রাতে অনিচ্ছাকৃত প্রস্রাব', [('caust',3),('kreos',3),('sep',2),('bell',2),('equis',2),('rhus-t',2),('sil',2)]),
 'Urine, retained, must wait': ('প্রস্রাব শুরু হতে দেরি', [('caust',3),('op',2),('hep',2),('mur-ac',2),('arn',2),('sabal',2)]),
 'Urine, odour of horse urine': ('ঘোড়ার প্রস্রাবের মতো গন্ধ', [('nit-ac',3),('benz-ac',2)]),
}),

(23, 'Genitalia male - পুরুষ জননাঙ্গ', {
 'Impotence': ('পুরুষত্বহীনতা', [('lyc',3),('agn',3),('sel',2),('sep',2),('nux-v',2),('phos',2),('con',2),('graph',2),('caust',1)]),
 'Erections, wanting': ('লিঙ্গোত্থান না হওয়া', [('agn',3),('lyc',3),('sel',2),('graph',2),('con',2),('nux-v',2),('phos',2)]),
 'Erections, troublesome, persistent': ('অতিরিক্ত লিঙ্গোত্থান', [('canth',3),('phos',2),('picric',0),('pic-ac',3),('nux-v',2),('plat',2),('lach',2)]),
 'Seminal emissions, nocturnal': ('রাতের স্বপ্নদোষ', [('sel',3),('phos',2),('staph',2),('con',2),('nat-m',2),('nux-v',2),('sulph',2),('thuj',2)]),
 'Sexual desire, increased': ('যৌন আকাঙ্ক্ষা বৃদ্ধি', [('plat',3),('staph',2),('canth',2),('phos',2),('lach',2),('nux-v',2),('med',2),('pic-ac',2)]),
 'Sexual desire, diminished': ('যৌন আকাঙ্ক্ষা হ্রাস', [('agn',3),('sep',2),('graph',2),('lyc',2),('con',2),('nat-m',2),('sel',2),('caust',1)]),
 'Ejaculation, premature': ('দ্রুত বীর্যপাত', [('sel',2),('nux-v',2),('lyc',2),('phos',2),('agn',2),('staph',2),('con',1)]),
 'Ejaculation, retarded': ('বিলম্বিত বীর্যপাত', [('sel',2),('agn',2),('graph',2),('lyc',1),('con',1)]),
 'Pain in testes': ('অণ্ডকোষে ব্যথা', [('puls',3),('clem',3),('rhod',2),('spong',2),('ham',2),('aur',2),('nux-v',1)]),
 'Swelling of testes': ('অণ্ডকোষ ফোলা', [('puls',3),('rhod',2),('clem',2),('apis',2),('merc',2),('aur',2),('ham',2)]),
 'Orchitis': ('অণ্ডকোষের প্রদাহ', [('puls',3),('clem',2),('rhod',2),('ham',2),('apis',2),('merc',2),('aur',2)]),
 'Hydrocele': ('হাইড্রোসিল', [('puls',3),('rhod',2),('graph',2),('sil',2),('apis',2),('sulph',1)]),
 'Varicocele': ('ভেরিকোসিল', [('ham',3),('puls',2),('calc-f',2),('nux-v',2),('lyc',1),('carb-v',1)]),
 'Condylomata, warts on genitals': ('জননাঙ্গে আঁচিল', [('thuj',3),('nit-ac',3),('med',2),('staph',2),('sabin',2),('caust',2),('lyc',1)]),
 'Itching of genitals': ('জননাঙ্গে চুলকানি', [('calad',3),('thuj',2),('merc',2),('sulph',2),('rhus-t',2),('nit-ac',2),('sep',2)]),
 'Perspiration of genitals, offensive': ('জননাঙ্গে দুর্গন্ধযুক্ত ঘাম', [('thuj',2),('sel',2),('sulph',2),('psor',2),('merc',1)]),
 'Prepuce, inflammation of': ('লিঙ্গত্বকের প্রদাহ', [('merc',3),('nit-ac',2),('sulph',2),('thuj',2),('cann-s',2),('apis',2)]),
 'Phimosis': ('লিঙ্গত্বক আটকে যাওয়া', [('merc',2),('sulph',2),('thuj',2),('nit-ac',2),('cann-s',2)]),
 'Coldness of genitals': ('জননাঙ্গ ঠান্ডা', [('agn',2),('sep',2),('sulph',2),('camph',2),('carb-v',1)]),
 'Atrophy of testes': ('অণ্ডকোষ ছোট হয়ে যাওয়া', [('agn',2),('aur',2),('iod',2),('sel',2),('con',1)]),
}),

(24, 'Genitalia female - নারী জননাঙ্গ', {
 'Menses too early': ('ঋতুস্রাব আগে হওয়া', [('calc',3),('nux-v',3),('ip',2),('sabin',2),('bell',2),('bry',2),('cham',2),('phos',2),('lach',2)]),
 'Menses too late': ('ঋতুস্রাব দেরিতে হওয়া', [('puls',3),('sep',3),('graph',2),('kali-c',2),('nat-m',2),('sulph',2),('con',2),('senec',2)]),
 'Menses, profuse': ('অতিরিক্ত ঋতুস্রাব', [('sabin',3),('calc',3),('chin',2),('ip',2),('phos',2),('bell',2),('nux-v',2),('trill',2),('ust',2)]),
 'Menses, scanty': ('অল্প ঋতুস্রাব', [('puls',3),('sep',2),('graph',2),('nat-m',2),('con',2),('sulph',2),('kali-c',2)]),
 'Menses, suppressed': ('ঋতুস্রাব বন্ধ', [('puls',3),('sep',2),('senec',2),('nat-m',2),('graph',2),('acon',2),('sulph',2),('kali-c',2)]),
 'Dysmenorrhoea, painful menses': ('কষ্টকর ঋতুস্রাব', [('mag-p',3),('cham',3),('coloc',3),('cimic',3),('puls',2),('sep',2),('vib',2),('sabin',2),('bell',2),('lach',2)]),
 'Menses, clotted': ('জমাট বাঁধা ঋতুস্রাব', [('sabin',3),('cham',2),('puls',2),('croc',2),('ust',2),('trill',2),('bell',1)]),
 'Metrorrhagia, uterine haemorrhage': ('জরায়ু থেকে রক্তপাত', [('sabin',3),('ip',3),('chin',2),('phos',2),('trill',2),('ust',2),('sec',2),('bell',2),('mill',2)]),
 'Leucorrhoea': ('লিউকোরিয়া', [('sep',3),('calc',3),('puls',2),('kreos',2),('alum',2),('graph',2),('nat-m',2),('sulph',2),('borx',2),('med',2)]),
 'Leucorrhoea, excoriating': ('জ্বালাযুক্ত লিউকোরিয়া', [('kreos',3),('nit-ac',2),('sulph',2),('sep',2),('ars',2),('merc',2)]),
 'Pruritus vulvae, itching': ('যোনিদ্বারে চুলকানি', [('kreos',3),('sep',2),('calad',2),('sulph',2),('con',2),('ambr',2),('nit-ac',2)]),
 'Prolapsus uteri': ('জরায়ু নেমে যাওয়া', [('sep',3),('lil-t',3),('murx',2),('nat-m',2),('calc',2),('puls',2),('lyc',2),('aesc',2)]),
 'Bearing down sensation': ('নিচের দিকে চাপ অনুভূতি', [('sep',3),('lil-t',3),('murx',2),('bell',2),('nat-m',2),('puls',2),('kreos',2)]),
 'Uterine fibroid': ('জরায়ুর ফাইব্রয়েড', [('calc',2),('lach',2),('thuj',2),('aur-m',2),('phos',2),('sep',2),('trill',2)]),
 'Ovarian pain': ('ডিম্বাশয়ে ব্যথা', [('apis',3),('lach',3),('coloc',2),('lil-t',2),('staph',2),('sep',2),('puls',2),('bell',2)]),
 'Ovarian cyst': ('ডিম্বাশয়ে সিস্ট', [('apis',3),('lach',2),('thuj',2),('lyc',2),('med',2),('sep',2),('calc',1)]),
 'Menopause, hot flushes': ('মেনোপজে গরম ঝলকানি', [('lach',3),('sulph',2),('sang',2),('sul-ac',2),('sep',2),('glon',2),('aml-ns',2),('cimic',2)]),
 'Sterility, infertility': ('বন্ধ্যাত্ব', [('sep',2),('nat-m',2),('puls',2),('borx',2),('calc',2),('med',2),('agn',2),('phos',1)]),
 'Morning sickness of pregnancy': ('গর্ভাবস্থার সকালের বমি ভাব', [('sep',3),('ip',3),('nux-v',3),('puls',2),('tab',2),('cocc',2),('kreos',2),('lac-d',2)]),
 'Complaints during pregnancy': ('গর্ভাবস্থার সমস্যা', [('sep',3),('puls',2),('nux-v',2),('ip',2),('kreos',2),('cimic',2),('bell',1)]),
 'Backache during pregnancy': ('গর্ভাবস্থায় পিঠে ব্যথা', [('kali-c',3),('cimic',2),('sep',2),('puls',2),('nux-v',2),('bell',1)]),
 'Anxiety during pregnancy': ('গর্ভাবস্থায় উদ্বেগ', [('acon',3),('ars',2),('puls',2),('sep',2),('kali-c',2),('arg-n',2),('gels',2)]),
 'Depression during pregnancy': ('গর্ভাবস্থায় বিষণ্নতা', [('sep',3),('nat-m',2),('puls',2),('cimic',2),('aur',2),('ign',2)]),
 'Threatened abortion': ('গর্ভপাতের আশঙ্কা', [('sabin',3),('sep',2),('vib',3),('caul',2),('cimic',2),('helon',2),('puls',2)]),
 'Labour pains, weak': ('দুর্বল প্রসববেদনা', [('caul',3),('puls',3),('cimic',2),('sec',2),('kali-c',2),('gels',2)]),
 'Labour pains, violent': ('অতি তীব্র প্রসববেদনা', [('cham',3),('coff',2),('bell',2),('cimic',2),('nux-v',2)]),
 'Lactation, milk scanty': ('বুকের দুধ কম', [('puls',3),('calc',2),('lac-d',2),('agn',2),('sil',2),('phyt',2),('urt-u',2)]),
 'Mastitis, breast inflammation': ('স্তনের প্রদাহ', [('bell',3),('phyt',3),('bry',2),('hep',2),('sil',2),('merc',2),('apis',2)]),
}),

(25, 'Larynx & trachea - কণ্ঠনালি', {
 'Hoarseness': ('গলা ভাঙা', [('caust',3),('phos',3),('spong',2),('arg-n',2),('carb-v',2),('arum-t',3),('rumx',2),('mang',2)]),
 'Voice, loss of': ('স্বর হারানো', [('caust',3),('phos',2),('spong',2),('arum-t',2),('arg-n',2),('gels',2),('carb-v',2)]),
 'Laryngitis': ('কণ্ঠনালির প্রদাহ', [('acon',3),('spong',2),('phos',2),('caust',2),('hep',2),('kali-bi',2),('arg-n',2),('iod',2)]),
 'Croup': ('ক্রুপ', [('acon',3),('spong',3),('hep',3),('kali-bi',2),('iod',2),('brom',2),('samb',2),('drosera',0)]),
 'Tickling in larynx': ('কণ্ঠনালিতে সুড়সুড়ি', [('rumx',3),('con',2),('dros',2),('phos',2),('bell',2),('hyos',2),('caust',2)]),
 'Dryness of larynx': ('কণ্ঠনালি শুকনো', [('bell',2),('spong',2),('caust',2),('phos',2),('kali-bi',2),('arum-t',2)]),
 'Pain in larynx': ('কণ্ঠনালিতে ব্যথা', [('phos',2),('caust',2),('spong',2),('hep',2),('arg-n',2),('bell',2)]),
 'Constriction of larynx': ('কণ্ঠনালির সংকোচন', [('spong',3),('lach',2),('brom',2),('iod',2),('cupr',2),('mosch',2)]),
 'Mucus in larynx': ('কণ্ঠনালিতে শ্লেষ্মা', [('kali-bi',3),('hydr',2),('phos',2),('caust',2),('stann',2),('sep',2)]),
 'Voice weak from overuse': ('অতিরিক্ত ব্যবহারে স্বর দুর্বল', [('arg-m',3),('arg-n',2),('caust',2),('phos',2),('rhus-t',2),('stann',2)]),
 'Larynx, sensitive to touch': ('কণ্ঠনালি স্পর্শে সংবেদনশীল', [('lach',3),('spong',2),('phos',2),('iod',1)]),
 'Whooping cough, laryngeal spasm': ('হুপিং কাশির খিঁচুনি', [('dros',3),('cupr',3),('coral',3),('mag-p',2),('ip',2),('bell',2)]),
}),

(26, 'Respiration - শ্বাস', {
 'Asthma': ('হাঁপানি', [('ars',3),('kali-c',3),('nat-s',3),('ip',2),('spong',2),('ant-t',2),('lach',2),('med',2),('tub',2),('sulph',2),('carb-v',2),('cupr',2)]),
 'Asthma worse night': ('রাতে হাঁপানি বৃদ্ধি', [('ars',3),('kali-c',3),('lach',2),('samb',2),('nat-s',2),('ant-t',2)]),
 'Asthma in damp weather': ('ভেজা আবহাওয়ায় হাঁপানি', [('nat-s',3),('med',2),('dulc',2),('ars',2),('thuj',2),('aran',2)]),
 'Asthma better bending forward': ('সামনে ঝুঁকে হাঁপানি উপশম', [('kali-c',3),('spong',2),('ars',2),('med',2),('lach',1)]),
 'Difficult breathing, dyspnoea': ('শ্বাসকষ্ট', [('ars',3),('carb-v',3),('lach',3),('ant-t',2),('kali-c',2),('phos',2),('ip',2),('spong',2),('sulph',2)]),
 'Shortness of breath on exertion': ('পরিশ্রমে দম ফুরিয়ে যাওয়া', [('carb-v',3),('ars',3),('calc',2),('kali-c',2),('lach',2),('crat',2),('dig',2),('phos',2)]),
 'Wheezing': ('শ্বাসে সাঁই সাঁই শব্দ', [('ars',3),('ip',3),('ant-t',2),('spong',2),('nat-s',2),('kali-c',2),('brom',2),('lach',2)]),
 'Rattling respiration': ('বুকে ঘড়ঘড় শব্দ', [('ant-t',3),('ip',2),('kali-s',2),('carb-v',2),('lyc',2),('hep',2),('bar-c',2)]),
 'Suffocation, must have air': ('দমবন্ধ ভাব, বাতাস চায়', [('carb-v',3),('lach',3),('ars',2),('apis',2),('sulph',2),('mosch',2),('samb',2)]),
 'Respiration, rapid': ('দ্রুত শ্বাস', [('acon',3),('bell',2),('phos',2),('ant-t',2),('ars',2),('ferr-p',2)]),
 'Respiration, slow': ('ধীর শ্বাস', [('op',3),('hell',2),('dig',2),('lach',2),('camph',1)]),
 'Respiration, sighing': ('দীর্ঘশ্বাস', [('ign',3),('op',2),('lach',2),('bry',2),('carb-v',2),('cimic',2)]),
 'Breathing worse lying down': ('শুলে শ্বাসকষ্ট বৃদ্ধি', [('ars',3),('lach',3),('ant-t',2),('cact',2),('spong',2),('phos',2),('kali-c',2),('samb',2)]),
 'Breathing better sitting up': ('বসলে শ্বাস আরাম', [('ars',3),('ant-t',3),('kali-c',2),('cact',2),('spong',2),('lach',2),('dig',2)]),
 'Breathing worse in cold air': ('ঠান্ডা বাতাসে শ্বাসকষ্ট', [('hep',3),('rumx',3),('sil',2),('nux-v',2),('spong',2),('ars',2),('phos',2)]),
 'Breathing worse in warm room': ('গরম ঘরে শ্বাসকষ্ট', [('puls',3),('apis',2),('sulph',2),('lach',2),('iod',2),('kali-s',2)]),
 'Breathing worse talking': ('কথা বললে শ্বাসকষ্ট', [('stann',3),('phos',2),('rumx',2),('spong',1),('calc',1)]),
 'Breathing worse walking': ('হাঁটলে শ্বাসকষ্ট', [('carb-v',3),('calc',2),('kali-c',2),('lyc',2),('phos',2),('crat',2)]),
 'Breathing, arrested during sleep': ('ঘুমে শ্বাস আটকে যাওয়া', [('op',3),('lach',3),('samb',2),('ant-t',2),('bar-c',2),('spong',1)]),
 'Breathing, asthma of children': ('শিশুর হাঁপানি', [('samb',3),('nat-s',2),('ant-t',2),('ip',2),('cham',2),('med',2),('tub',2)]),
}),

(27, 'Cough - কাশি', {
 'Cough, dry': ('শুকনো কাশি', [('bry',3),('rumx',3),('spong',3),('phos',2),('hyos',2),('acon',2),('dros',2),('con',2),('lach',2),('stict',2)]),
 'Cough, loose': ('আলগা কাশি', [('ant-t',3),('puls',3),('kali-s',2),('hep',2),('sil',2),('stann',2),('kali-bi',2),('sulph',2)]),
 'Cough, barking': ('ঘেউ ঘেউ কাশি', [('spong',3),('acon',2),('hep',2),('drosera',0),('dros',2),('bell',2),('verb',2)]),
 'Cough, spasmodic, paroxysmal': ('খিঁচুনিমূলক কাশি', [('dros',3),('cupr',3),('coral',3),('ip',2),('bell',2),('mag-p',2),('hyos',2),('stann',2)]),
 'Whooping cough': ('হুপিং কাশি', [('dros',3),('cupr',3),('coral',2),('ip',2),('mag-p',2),('bell',2),('ant-t',2),('kali-bi',2)]),
 'Cough worse lying down': ('শুলে কাশি বৃদ্ধি', [('dros',3),('hyos',3),('puls',2),('rumx',2),('con',2),('lach',2),('phos',2),('samb',2)]),
 'Cough worse in warm room': ('গরম ঘরে কাশি বৃদ্ধি', [('puls',3),('bry',2),('iod',2),('kali-s',2),('carb-v',2),('sulph',1)]),
 'Cough worse in cold air': ('ঠান্ডা বাতাসে কাশি বৃদ্ধি', [('rumx',3),('hep',3),('phos',2),('nux-v',2),('spong',2),('ars',2),('sil',2)]),
 'Cough from tickling in throat': ('গলায় সুড়সুড়ি থেকে কাশি', [('rumx',3),('con',2),('dros',2),('phos',2),('bell',2),('nux-v',2),('caust',2)]),
 'Cough, ends in vomiting': ('কাশতে গিয়ে বমি', [('dros',3),('ip',3),('kali-c',2),('bry',2),('ant-t',2),('nux-v',2),('carb-v',2)]),
 'Cough, night, wakes patient': ('রাতে কাশিতে ঘুম ভাঙা', [('hyos',3),('dros',2),('puls',2),('samb',2),('kali-c',2),('con',2),('ars',2)]),
 'Cough, morning': ('সকালের কাশি', [('nat-s',3),('nux-v',2),('kali-bi',2),('phos',2),('sulph',2),('stann',2)]),
 'Cough with pain in chest': ('কাশিতে বুকে ব্যথা', [('bry',3),('phos',2),('kali-c',2),('rumx',2),('squil',2),('nux-v',1)]),
 'Cough, must hold chest': ('কাশতে গিয়ে বুক চেপে ধরা', [('bry',3),('phos',2),('nat-s',2),('dros',2),('eup-per',2)]),
 'Cough with involuntary urination': ('কাশলে প্রস্রাব বেরিয়ে যাওয়া', [('caust',3),('squil',3),('puls',2),('nat-m',2),('sep',2),('zinc',2)]),
 'Cough from talking': ('কথা বললে কাশি', [('stann',2),('phos',2),('rumx',2),('dros',2),('hyos',1)]),
 'Cough, croupy': ('ক্রুপ ধরনের কাশি', [('spong',3),('acon',3),('hep',3),('kali-bi',2),('brom',2),('iod',2),('samb',2)]),
 'Cough, suffocative': ('দমবন্ধ করা কাশি', [('ip',3),('cupr',2),('ant-t',2),('lach',2),('samb',2),('dros',2)]),
 'Cough, short, hacking': ('ছোট খাঁকারি কাশি', [('phos',2),('bell',2),('ign',2),('sang',2),('sulph',2),('nux-v',1)]),
 'Cough after measles': ('হামের পরের কাশি', [('dros',2),('puls',2),('sulph',2),('hyos',2),('carb-v',2),('bry',1)]),
 'Cough, chronic in old people': ('বয়স্কদের দীর্ঘস্থায়ী কাশি', [('ant-t',3),('carb-v',2),('bar-c',2),('kali-c',2),('sen',2),('hydr',2)]),
 'Cough with expectoration difficult': ('কফ তুলতে কষ্ট', [('ant-t',3),('caust',2),('kali-bi',2),('sil',2),('hep',2),('stann',2),('phos',1)]),
}),

(28, 'Expectoration - কফ', {
 'Expectoration, thick': ('ঘন কফ', [('kali-bi',3),('puls',2),('hep',2),('sil',2),('stann',2),('hydr',2),('sulph',2)]),
 'Expectoration, yellow-green': ('হলদে-সবুজ কফ', [('puls',3),('kali-s',3),('kali-bi',2),('sil',2),('stann',2),('lyc',2),('nat-s',2)]),
 'Expectoration, viscid, stringy': ('আঠালো দড়ির মতো কফ', [('kali-bi',3),('hydr',2),('coc-c',0),('phos',1),('sang',2)]),
 'Expectoration, bloody': ('রক্তমিশ্রিত কফ', [('phos',3),('ip',3),('acon',2),('mill',2),('ferr-p',2),('dros',2),('puls',2),('nit-ac',1)]),
 'Expectoration, purulent': ('পুঁজযুক্ত কফ', [('hep',3),('sil',3),('puls',2),('stann',2),('kali-c',2),('phos',2),('bals',0)]),
 'Expectoration, offensive': ('দুর্গন্ধযুক্ত কফ', [('psor',3),('kali-c',2),('sil',2),('sang',2),('sulph',2),('stann',2),('carb-v',2)]),
 'Expectoration, salty': ('নোনতা কফ', [('phos',3),('sep',2),('sulph',2),('lyc',2),('ambr',2)]),
 'Expectoration, sweetish': ('মিষ্টি স্বাদের কফ', [('phos',2),('stann',3),('kali-bi',1),('sang',1)]),
 'Expectoration, difficult': ('কফ তুলতে কষ্ট', [('ant-t',3),('caust',2),('kali-bi',2),('sil',2),('hep',2),('stann',2),('phos',1)]),
 'Expectoration, scanty': ('অল্প কফ', [('bry',2),('spong',2),('rumx',2),('phos',2),('hyos',2),('con',1)]),
 'Expectoration, copious': ('প্রচুর কফ', [('ant-t',3),('kali-s',2),('sil',2),('stann',2),('sulph',2),('sen',2)]),
 'Expectoration, tasting of old catarrh': ('বাসি স্বাদের কফ', [('psor',2),('sulph',2),('hep',1),('sil',1)]),
 'Expectoration, in morning only': ('শুধু সকালে কফ', [('nat-s',3),('kali-bi',2),('stann',2),('phos',2),('sulph',2)]),
 'Expectoration, must be swallowed': ('কফ গিলে ফেলতে হয়', [('caust',3),('kali-c',2),('arn',2),('ant-t',2),('sep',1)]),
}),

(29, 'Chest - বুক', {
 'Pain in chest': ('বুকে ব্যথা', [('bry',3),('kali-c',3),('phos',2),('ran-b',2),('spig',2),('acon',2),('arn',2),('cact',2),('squil',2)]),
 'Pain in chest on deep breathing': ('গভীর শ্বাসে বুকে ব্যথা', [('bry',3),('ran-b',2),('acon',2),('kali-c',2),('squil',2),('spig',2)]),
 'Palpitation of heart': ('হৃদস্পন্দন দ্রুত', [('acon',3),('cact',3),('spig',3),('dig',2),('nat-m',2),('lach',2),('puls',2),('kali-c',2),('lyc',2),('crat',2)]),
 'Palpitation from emotion': ('আবেগে হৃদস্পন্দন বৃদ্ধি', [('acon',3),('nat-m',2),('ign',2),('gels',2),('puls',2),('phos',2),('cimic',2)]),
 'Oppression of chest': ('বুকে চাপ', [('lach',3),('ars',3),('cact',2),('phos',2),('kali-c',2),('sulph',2),('spong',2),('ip',2)]),
 'Constriction of chest': ('বুকের সংকোচন', [('cact',3),('lach',3),('spong',2),('ars',2),('ip',2),('phos',2),('cupr',2)]),
 'Pain in heart region': ('হৃদযন্ত্র অঞ্চলে ব্যথা', [('cact',3),('spig',3),('naja',3),('acon',2),('lach',2),('kalm',2),('dig',2),('arn',2)]),
 'Angina pectoris': ('অ্যানজাইনা', [('cact',3),('naja',3),('spig',2),('arn',2),('aml-ns',2),('lach',2),('kalm',2),('aur',2)]),
 'Pneumonia': ('নিউমোনিয়া', [('bry',3),('phos',3),('ant-t',2),('sulph',2),('lyc',2),('chel',2),('ip',2),('hep',2)]),
 'Pleurisy': ('প্লুরিসি', [('bry',3),('acon',2),('kali-c',2),('ran-b',2),('sulph',2),('squil',2),('apis',2)]),
 'Bronchitis': ('ব্রঙ্কাইটিস', [('ant-t',3),('bry',2),('phos',2),('kali-bi',2),('hep',2),('puls',2),('kali-s',2),('sulph',2)]),
 'Pain in mammae': ('স্তনে ব্যথা', [('phyt',3),('con',3),('bry',2),('bell',2),('lac-c',2),('murx',2),('puls',2)]),
 'Mammae, tumours of': ('স্তনে গুটি', [('con',3),('phyt',2),('carb-an',2),('calc-f',2),('scroph',2),('aster',2),('carc',2)]),
 'Milk in breast, complaints': ('স্তনদুধের সমস্যা', [('puls',3),('phyt',2),('lac-d',2),('bry',2),('bell',2),('calc',2),('urt-u',2)]),
 'Chest, tightness': ('বুকে টান', [('cact',3),('lach',2),('spong',2),('ars',2),('cupr',2),('ip',2)]),
 'Chest, heaviness': ('বুকে ভারী ভাব', [('ant-t',3),('carb-v',2),('phos',2),('kali-c',2),('sulph',2),('lach',2)]),
 'Chest, weakness in': ('বুকের দুর্বলতা', [('stann',3),('phos',2),('calc',2),('carb-v',2),('kali-c',2),('sil',2)]),
 'Chest, coldness in': ('বুকে শীতলতা', [('carb-v',2),('ars',2),('camph',2),('verat',2),('sec',1)]),
 'Chest, burning in': ('বুকে জ্বালা', [('phos',3),('sulph',2),('ars',2),('bell',2),('acon',2),('carb-v',2)]),
 'Chest, pain extending to left arm': ('বুক থেকে বাঁ হাতে ব্যথা', [('cact',3),('naja',2),('spig',2),('kalm',2),('aml-ns',1),('lach',1)]),
 'Chest pain worse motion': ('নড়াচড়ায় বুকে ব্যথা', [('bry',3),('ran-b',2),('rhus-t',2),('arn',2),('spig',2)]),
 'Chest pain with anxiety': ('উদ্বেগসহ বুকে ব্যথা', [('acon',3),('ars',3),('cact',2),('lach',2),('phos',2),('nat-m',2),('arg-n',2)]),
 'Haemoptysis, spitting blood': ('কফে রক্ত', [('phos',3),('ip',3),('acon',2),('mill',2),('ferr-p',2),('dros',2),('ham',2)]),
 'Tuberculosis of lungs': ('ফুসফুসের যক্ষ্মা', [('phos',3),('tub',3),('calc',2),('sil',2),('stann',2),('dros',2),('ars-i',2),('psor',2)]),
}),

(30, 'Back - পিঠ', {
 'Pain in back': ('পিঠে ব্যথা', [('rhus-t',3),('kali-c',3),('nux-v',3),('bry',2),('sep',2),('calc-f',2),('aesc',2),('sulph',2),('cimic',2),('arn',2)]),
 'Pain in lumbar region': ('কোমরে ব্যথা', [('kali-c',3),('rhus-t',3),('nux-v',2),('aesc',2),('sep',2),('berb',2),('bry',2),('calc-f',2)]),
 'Pain in cervical region': ('ঘাড়ে ব্যথা', [('cimic',3),('rhus-t',2),('bry',2),('nux-v',2),('lach',2),('gels',2),('sang',2)]),
 'Pain in sacrum': ('কোমরের নিচে (স্যাক্রাম) ব্যথা', [('aesc',3),('kali-c',2),('sabin',2),('cimic',2),('sep',2),('nux-v',2),('phos',2)]),
 'Pain in coccyx': ('কোকিক্সে ব্যথা', [('hyper',3),('sil',2),('carb-an',2),('caust',2),('kali-bi',2),('graph',1)]),
 'Sciatica': ('সায়াটিকা', [('coloc',3),('rhus-t',3),('gnaph',3),('mag-p',2),('bry',2),('lyc',2),('phyt',2),('kali-c',2)]),
 'Stiffness of back': ('পিঠ শক্ত', [('rhus-t',3),('bry',2),('nux-v',2),('cimic',2),('calc-f',2),('sulph',2),('lyc',1)]),
 'Weakness of back': ('পিঠের দুর্বলতা', [('kali-c',3),('calc-p',3),('sep',2),('nat-m',2),('sil',2),('ph-ac',2),('nux-v',2)]),
 'Back pain after exertion': ('পরিশ্রমের পর পিঠে ব্যথা', [('rhus-t',3),('arn',3),('calc',2),('kali-c',2),('nux-v',2),('ruta',2)]),
 'Back pain during menses': ('ঋতুস্রাবের সময় পিঠে ব্যথা', [('cimic',3),('sep',2),('kali-c',2),('sabin',2),('puls',2),('nux-v',2),('vib',2)]),
 'Back pain worse sitting': ('বসলে পিঠে ব্যথা বৃদ্ধি', [('rhus-t',3),('kali-c',2),('sep',2),('cocc',2),('valer',1)]),
 'Back pain worse standing': ('দাঁড়ালে পিঠে ব্যথা বৃদ্ধি', [('sulph',3),('sep',2),('aesc',2),('nat-c',2),('calc',2),('lyc',1)]),
 'Back pain worse walking': ('হাঁটলে পিঠে ব্যথা বৃদ্ধি', [('aesc',3),('sep',2),('calc',2),('nat-m',2),('con',2),('bry',2)]),
 'Back pain better lying': ('শুলে পিঠে ব্যথা উপশম', [('bry',3),('nux-v',2),('arn',2),('sep',2),('kali-c',2),('rhus-t',1)]),
 'Back pain worse morning': ('সকালে পিঠে ব্যথা বৃদ্ধি', [('rhus-t',3),('nux-v',3),('staph',2),('sulph',2),('lach',1)]),
 'Back pain must move continually': ('পিঠের ব্যথায় বারবার নড়তে হয়', [('rhus-t',3),('tarent',2),('med',2),('caust',1)]),
 'Curvature of spine': ('মেরুদণ্ডের বক্রতা', [('calc',3),('calc-p',3),('sil',2),('sulph',2),('phos',2),('tub',2),('lyc',1)]),
 'Spasm of back muscles': ('পিঠের পেশির খিঁচুনি', [('mag-p',3),('cimic',2),('nux-v',2),('cupr',2),('rhus-t',2),('bell',2)]),
 'Twitching of back muscles': ('পিঠের পেশিতে ঝাঁকুনি', [('agar',3),('zinc',2),('cimic',2),('nux-v',2),('ign',2)]),
 'Coldness in back': ('পিঠে শীতলতা', [('gels',2),('ars',2),('camph',2),('sep',2),('verat',2),('calc',1)]),
 'Burning in spine': ('মেরুদণ্ডে জ্বালা', [('phos',3),('pic-ac',2),('sulph',2),('zinc',2),('agar',2),('sec',1)]),
 'Sensitiveness of spine to touch': ('মেরুদণ্ড স্পর্শে সংবেদনশীল', [('chin-s',3),('agar',2),('phos',2),('ther',0),('theri',2),('lach',2),('zinc',2)]),
}),
]
