# -*- coding: utf-8 -*-
"""Kent's Repertory — chapters 31-37 (Extremities, Sleep, Chill, Fever,
   Perspiration, Skin, Generalities)."""

K4 = [
(31, 'Extremities - হাত-পা', {
 'Pain in joints': ('সন্ধিতে ব্যথা', [('rhus-t',3),('bry',3),('colch',3),('caust',2),('kalm',2),('led',2),('guai',2),('calc-f',2),('sulph',2),('ruta',2)]),
 'Pain in limbs': ('হাত-পায়ে ব্যথা', [('rhus-t',3),('bry',2),('arn',2),('eup-per',2),('phyt',2),('caust',2),('kali-c',2)]),
 'Rheumatic pain, wandering': ('বাতের ঘুরে বেড়ানো ব্যথা', [('puls',3),('kali-s',2),('kalm',2),('lac-c',2),('mang',2),('phyt',2)]),
 'Gout': ('গেঁটে বাত', [('colch',3),('led',3),('benz-ac',2),('guai',2),('urt-u',2),('lyc',2),('sulph',2),('nux-v',2)]),
 'Swelling of joints': ('সন্ধি ফোলা', [('apis',3),('bry',3),('rhus-t',2),('led',2),('colch',2),('merc',2),('sulph',2),('calc-f',2)]),
 'Cracking in joints': ('সন্ধিতে শব্দ', [('caust',2),('calc-f',2),('nit-ac',2),('petr',2),('sulph',2),('thuj',1)]),
 'Cramps in calves': ('পায়ের ডলা', [('cupr',3),('mag-p',3),('cham',2),('sulph',2),('nux-v',2),('calc',2),('rhus-t',2),('sec',2)]),
 'Cramp in feet': ('পায়ের পাতায় খিঁচুনি', [('cupr',3),('sulph',2),('mag-p',2),('calc',2),('nux-v',2),('zinc',2)]),
 'Cramp in hands': ('হাতে খিঁচুনি', [('cupr',3),('mag-p',2),('sec',2),('plb',2),('stann',1)]),
 'Swelling of feet, oedema': ('পায়ের ফোলা', [('apis',3),('ars',3),('dig',2),('lyc',2),('sulph',2),('merc',2),('thyr',2),('sil',2)]),
 'Swelling of hands': ('হাতের ফোলা', [('apis',3),('ars',2),('merc',2),('rhus-t',2),('thyr',2),('lyc',1)]),
 'Coldness of feet': ('পা ঠান্ডা', [('sil',3),('calc',3),('sep',2),('sulph',2),('carb-v',2),('nat-m',2),('lyc',2),('verat',2)]),
 'Coldness of hands': ('হাত ঠান্ডা', [('calc',3),('sil',2),('sep',2),('verat',2),('carb-v',2),('nat-m',2)]),
 'Burning of soles': ('পায়ের তলায় জ্বালা', [('sulph',3),('calc',2),('med',3),('lach',2),('graph',2),('sanic',2),('puls',2)]),
 'Weakness of legs': ('পায়ের দুর্বলতা', [('ph-ac',3),('gels',3),('con',2),('plb',2),('nux-v',2),('kali-c',2),('sil',2),('caust',2)]),
 'Weakness of arms': ('হাতের দুর্বলতা', [('caust',3),('plb',2),('con',2),('stann',2),('gels',2),('kali-c',1)]),
 'Trembling of hands': ('হাত কাঁপা', [('agar',3),('gels',3),('zinc',2),('merc',2),('lach',2),('phos',2),('plb',2),('sulph',2)]),
 'Trembling of legs': ('পা কাঁপা', [('gels',3),('agar',2),('zinc',2),('merc',2),('phos',2),('sil',1)]),
 'Numbness of hands': ('হাতে অসাড়তা', [('graph',3),('coloc',2),('plb',2),('cocc',2),('nux-v',2),('calc',2),('phos',2)]),
 'Numbness of feet': ('পায়ে অসাড়তা', [('graph',2),('coloc',2),('plb',2),('sec',2),('phos',2),('nux-v',2),('sil',1)]),
 'Varicose veins of legs': ('পায়ে ভেরিকোজ শিরা', [('ham',3),('calc-f',3),('puls',3),('carb-v',2),('lach',2),('fl-ac',2),('sep',2),('mill',2)]),
 'Restlessness of legs': ('পা ছটফট করা', [('zinc',3),('tarent',3),('rhus-t',2),('ars',2),('sulph',2),('med',2),('caust',2)]),
 'Heaviness of legs': ('পা ভারী লাগা', [('gels',3),('ph-ac',2),('con',2),('nux-v',2),('kali-c',2),('sep',2)]),
 'Paralysis of limbs': ('হাত-পা অবশ', [('caust',3),('plb',2),('gels',2),('con',2),('nux-v',2),('lath',2),('cocc',2),('phos',2)]),
 'Sprains': ('মোচকানো', [('arn',3),('rhus-t',3),('ruta',3),('bry',2),('led',2),('calc-f',2)]),
 'Panaritium, whitlow': ('আঙুলের ডলা/ফোড়া', [('hep',3),('sil',3),('myric',0),('apis',2),('lach',2),('nat-s',2),('fl-ac',2)]),
 'Nails, brittle': ('নখ ভঙ্গুর', [('sil',3),('ant-c',2),('graph',2),('thuj',2),('alum',2),('fl-ac',2)]),
 'Nails, deformed or thick': ('নখ বিকৃত বা পুরু', [('graph',3),('ant-c',2),('sil',2),('thuj',2),('sep',2),('sulph',1)]),
 'Ingrowing toenail': ('নখ মাংসে ঢুকে যাওয়া', [('mag-p',2),('sil',2),('graph',2),('teucr',2),('caust',1)]),
 'Corns on feet': ('পায়ে কড়া', [('ant-c',3),('sil',2),('sulph',2),('graph',2),('hep',1)]),
 'Perspiration of feet, offensive': ('পায়ে দুর্গন্ধযুক্ত ঘাম', [('sil',3),('psor',3),('graph',2),('sanic',2),('thuj',2),('bar-c',2),('sulph',2)]),
 'Perspiration of hands': ('হাতে ঘাম', [('calc',3),('sil',2),('sulph',2),('nat-m',2),('sep',2),('fl-ac',2)]),
 'Growing pains in children': ('শিশুর বৃদ্ধির ব্যথা', [('calc-p',3),('phos',2),('guai',2),('ruta',2),('mang',2),('calc',2)]),
 'Stiffness of joints in morning': ('সকালে সন্ধি শক্ত', [('rhus-t',3),('caust',2),('calc-f',2),('sulph',2),('lyc',2),('bry',1)]),
 'Pain in heels': ('গোড়ালিতে ব্যথা', [('valer',3),('ambr',2),('caust',2),('graph',2),('phyt',2),('mang',2),('ruta',2)]),
}),

(32, 'Sleep - ঘুম', {
 'Sleeplessness, insomnia': ('অনিদ্রা', [('coff',3),('nux-v',3),('ars',3),('sulph',2),('puls',2),('kali-p',2),('cocc',2),('op',2),('valer',2),('passi',2),('lyc',2)]),
 'Sleeplessness from thoughts': ('চিন্তার ভিড়ে ঘুম না আসা', [('coff',3),('nux-v',2),('puls',2),('kali-p',2),('sulph',2),('lyc',2),('op',1)]),
 'Sleeplessness before midnight': ('মাঝরাতের আগে ঘুম না আসা', [('puls',2),('coff',2),('nux-v',2),('rhus-t',2),('sulph',2)]),
 'Sleeplessness after 3 a.m.': ('ভোর ৩টার পর ঘুম না আসা', [('nux-v',3),('kali-c',3),('sulph',2),('ars',2),('sep',2),('lyc',2),('nat-m',2)]),
 'Sleepiness, drowsiness': ('ঘুমঘুম ভাব', [('op',3),('nux-m',3),('ant-t',2),('gels',2),('phos',2),('hell',2),('sulph',2),('puls',2)]),
 'Sleep, restless': ('অস্থির ঘুম', [('ars',3),('rhus-t',3),('acon',2),('bell',2),('cham',2),('sulph',2),('nux-v',2),('kali-c',2),('tarent',2)]),
 'Sleep, unrefreshing': ('ঘুমে সতেজ না হওয়া', [('bry',3),('lach',3),('nux-v',2),('sulph',2),('op',2),('lyc',2),('carc',2),('ph-ac',2)]),
 'Waking too early': ('খুব ভোরে জেগে ওঠা', [('nux-v',3),('kali-c',3),('sulph',2),('ars',2),('sep',2),('lyc',2),('nat-m',2)]),
 'Waking frequently': ('বারবার ঘুম ভাঙা', [('ars',3),('nux-v',2),('sulph',2),('kali-c',2),('acon',2),('merc',2),('sil',2)]),
 'Sleep, position on back': ('চিৎ হয়ে ঘুম', [('am-c',2),('nux-v',2),('rhus-t',2),('sulph',2),('op',1),('phos',1)]),
 'Sleep, position on abdomen': ('উপুড় হয়ে ঘুম', [('med',3),('am-c',2),('calc',2),('cina',2),('stram',1)]),
 'Sleep with limbs drawn up': ('হাত-পা গুটিয়ে ঘুম', [('med',2),('sep',2),('coloc',2),('mag-p',2),('nux-v',1)]),
 'Sleep with arms over head': ('হাত মাথার উপরে রেখে ঘুম', [('puls',3),('nux-v',2),('ars',2),('bell',2),('carb-v',1)]),
 'Sleep with one leg out of bed': ('এক পা বের করে ঘুম', [('sulph',3),('puls',2),('med',2),('cham',2),('lyc',1)]),
 'Sleep with mouth open': ('হাঁ করে ঘুমানো', [('op',3),('samb',2),('lyc',2),('rhus-t',2),('cham',2),('bar-c',1)]),
 'Sleep, head uncovered': ('মাথা খোলা রেখে ঘুম', [('sulph',3),('lyc',2),('iod',2),('puls',2),('med',1)]),
 'Sleep, must be covered completely': ('পুরো ঢেকে ঘুম', [('psor',3),('sil',3),('hep',2),('ars',2),('nux-v',2),('kali-c',2),('camph',2)]),
 'Talking in sleep': ('ঘুমের মধ্যে কথা', [('bell',3),('bry',3),('hyos',2),('lach',2),('nux-v',2),('rhus-t',2),('sulph',2)]),
 'Walking in sleep, somnambulism': ('ঘুমের মধ্যে হাঁটা', [('kali-br',3),('nat-m',2),('phos',2),('sil',2),('op',2),('bry',2),('stram',2)]),
 'Starting in sleep': ('ঘুমে চমকে ওঠা', [('bell',3),('borx',3),('nat-m',2),('sulph',2),('kali-c',2),('sil',2),('hyos',2)]),
 'Grinding teeth in sleep': ('ঘুমে দাঁত কিড়মিড়', [('cina',3),('tub',3),('bell',2),('podo',2),('hyos',2),('stram',2),('ars',2)]),
 'Snoring in sleep': ('নাক ডাকা', [('op',3),('ant-t',2),('bell',2),('nux-v',2),('bar-c',2),('lach',1)]),
 'Dreams, anxious': ('উদ্বেগের স্বপ্ন', [('ars',3),('nat-m',2),('sulph',2),('acon',2),('kali-c',2),('lyc',2),('carc',2)]),
 'Dreams of death': ('মৃত্যুর স্বপ্ন', [('acon',3),('ars',3),('mag-c',2),('calc',2),('nat-m',2),('thuj',2),('aur',2),('lach',2)]),
 'Dreams of dead people': ('মৃত মানুষের স্বপ্ন', [('thuj',3),('mag-c',2),('ars',2),('nat-m',2),('calc',2),('kali-c',1)]),
 'Dreams of falling': ('পড়ে যাওয়ার স্বপ্ন', [('bell',3),('thuj',3),('kali-c',2),('sulph',2),('borx',2),('gels',2),('sanic',2)]),
 'Dreams of water': ('পানির স্বপ্ন', [('mag-c',3),('nat-m',2),('verat',2),('phos',2),('sulph',2),('lac-c',1)]),
 'Dreams of fire': ('আগুনের স্বপ্ন', [('phos',3),('ars',2),('sulph',2),('hep',2),('lach',2),('mag-c',2),('bell',1)]),
 'Dreams of robbers': ('চোর-ডাকাতের স্বপ্ন', [('nat-m',3),('mag-m',2),('ars',2),('con',2),('sil',2),('alum',2)]),
 'Dreams of animals, snakes': ('পশু ও সাপের স্বপ্ন', [('lyss',3),('lac-c',3),('bell',2),('stram',2),('tub',2),('arg-n',2)]),
 'Dreams, vivid': ('জীবন্ত স্বপ্ন', [('op',3),('phos',2),('ars',2),('sulph',2),('nat-m',2),('med',2),('cann-i',2)]),
 'Dreams, prophetic': ('ভবিষ্যদ্বাণীমূলক স্বপ্ন', [('acon',3),('calc',2),('sil',2),('med',2),('sulph',1)]),
}),

(33, 'Chill - শীত', {
 'Chill in general': ('শীত লাগা', [('nux-v',3),('eup-per',3),('chin',3),('gels',2),('ars',2),('rhus-t',2),('puls',2),('sabad',2),('caps',2)]),
 'Chill, shaking': ('কাঁপুনিসহ শীত', [('eup-per',3),('nux-v',2),('gels',2),('chin',2),('ars',2),('caps',2),('pyrog',2)]),
 'Chill begins in back': ('পিঠ থেকে শীত শুরু', [('gels',3),('eup-per',2),('nux-v',2),('caps',2),('lach',2),('sep',2)]),
 'Chill, external, with internal heat': ('বাইরে শীত ভেতরে গরম', [('ars',3),('nux-v',2),('chin',2),('camph',2),('caps',2)]),
 'Chill not relieved by warmth': ('গরমেও শীত না কমা', [('nux-v',3),('caps',2),('chin',2),('ars',2),('pyrog',2)]),
 'Chill at a definite hour': ('নির্দিষ্ট সময়ে শীত', [('chin',3),('chin-s',3),('cedr',2),('ars',2),('eup-per',2),('nat-m',2)]),
 'Chill, one-sided': ('একদিকে শীত', [('puls',2),('chin',2),('nux-v',2),('lyc',1),('sep',1)]),
 'Chill from least draft': ('সামান্য হাওয়ায় শীত', [('nux-v',3),('hep',3),('sil',2),('calc',2),('kali-c',2),('cham',2)]),
 'Chill with thirst': ('তৃষ্ণাসহ শীত', [('eup-per',3),('nat-m',2),('ars',2),('chin',2),('nux-v',2),('bry',2)]),
 'Chill without thirst': ('তৃষ্ণা ছাড়া শীত', [('gels',3),('puls',2),('apis',2),('cina',2),('sabad',2)]),
 'Chill in the evening': ('সন্ধ্যায় শীত', [('puls',2),('sep',2),('rhus-t',2),('lyc',2),('nux-v',2),('sulph',1)]),
 'Chill in bed, cannot get warm': ('বিছানায় গরম হতে না পারা', [('nux-v',3),('ars',2),('sil',2),('psor',2),('camph',2),('calc',2)]),
}),

(34, 'Fever - জ্বর', {
 'Fever, high': ('উচ্চ জ্বর', [('bell',3),('acon',3),('ferr-p',3),('bry',2),('gels',2),('pyrog',2),('ars',2),('verat-v',2),('stram',2)]),
 'Fever, continued': ('অবিরাম জ্বর', [('bry',3),('bapt',3),('rhus-t',2),('ars',2),('pyrog',2),('phos',2),('gels',2)]),
 'Fever, intermittent': ('পর্যায়ক্রমিক জ্বর', [('chin',3),('ars',3),('chin-s',3),('nat-m',2),('eup-per',2),('nux-v',2),('cedr',2),('ip',2)]),
 'Fever, remittent': ('প্রশমনশীল জ্বর', [('bry',3),('rhus-t',2),('puls',2),('ars',2),('nux-v',2),('bell',2)]),
 'Fever, septic': ('সেপটিক জ্বর', [('pyrog',3),('bapt',3),('ars',2),('lach',2),('crot-h',2),('anthr',2),('echinacea',0)]),
 'Fever, typhoid type': ('টাইফয়েড ধরনের জ্বর', [('bapt',3),('bry',2),('rhus-t',2),('ars',2),('phos',2),('mur-ac',2),('lach',2)]),
 'Fever with chill and sweat': ('শীত ও ঘামসহ জ্বর', [('chin',3),('eup-per',2),('nux-v',2),('ars',2),('merc',2),('rhus-t',2)]),
 'Fever, burning heat': ('জ্বলন্ত জ্বর', [('acon',3),('bell',3),('ars',2),('sulph',2),('phos',2),('stram',2)]),
 'Fever, dry heat': ('শুকনো গরম জ্বর', [('bell',3),('acon',3),('bry',2),('nux-v',2),('phos',2),('stram',2)]),
 'Fever with delirium': ('প্রলাপসহ জ্বর', [('bell',3),('hyos',2),('stram',2),('bapt',2),('ars',2),('lach',2),('op',2)]),
 'Fever with headache': ('মাথাব্যথাসহ জ্বর', [('bell',3),('bry',3),('gels',3),('eup-per',2),('ferr-p',2),('acon',2),('nat-m',1)]),
 'Fever with restlessness': ('অস্থিরতাসহ জ্বর', [('acon',3),('ars',3),('rhus-t',3),('bell',2),('pyrog',2),('bry',1)]),
 'Fever with weakness': ('দুর্বলতাসহ জ্বর', [('gels',3),('bapt',3),('ars',2),('chin',2),('phos',2),('pyrog',2),('carb-v',2)]),
 'Fever with thirst': ('তৃষ্ণাসহ জ্বর', [('bry',3),('ars',3),('acon',2),('eup-per',2),('nat-m',2),('phos',2),('chin',2)]),
 'Fever, thirstless': ('তৃষ্ণাহীন জ্বর', [('gels',3),('puls',2),('apis',2),('ant-t',2),('sabad',2),('cina',2)]),
 'Fever with bone pains': ('হাড়ব্যথাসহ জ্বর', [('eup-per',3),('bry',2),('rhus-t',2),('gels',2),('nux-v',2),('phyt',2)]),
 'Fever after vaccination': ('টিকার পর জ্বর', [('thuj',3),('sil',3),('sulph',2),('ars',2),('vac',2),('bell',1)]),
 'Fever with joint pain': ('সন্ধিব্যথাসহ জ্বর', [('bry',3),('rhus-t',3),('eup-per',3),('acon',2),('ferr-p',2),('colch',2),('kalm',2)]),
}),

(35, 'Perspiration - ঘাম', {
 'Perspiration, profuse': ('প্রচুর ঘাম', [('merc',3),('chin',3),('calc',2),('sil',2),('sulph',2),('psor',2),('samb',2),('verat',2)]),
 'Perspiration, absent (dry skin)': ('ঘাম না হওয়া', [('acon',3),('bell',2),('nux-m',2),('alum',2),('lyc',2),('sulph',1)]),
 'Perspiration, offensive': ('দুর্গন্ধযুক্ত ঘাম', [('psor',3),('merc',2),('sil',2),('sulph',2),('bapt',2),('nit-ac',2),('thuj',2),('graph',1)]),
 'Perspiration, sour smelling': ('টক গন্ধযুক্ত ঘাম', [('calc',3),('hep',2),('merc',2),('sulph',2),('nat-p',1)]),
 'Perspiration, sweetish': ('মিষ্টি গন্ধযুক্ত ঘাম', [('thuj',3),('calc',2),('sulph',1),('graph',1)]),
 'Perspiration, cold': ('ঠান্ডা ঘাম', [('verat',3),('camph',2),('carb-v',2),('ars',2),('tab',2),('sec',2),('cina',2)]),
 'Perspiration, one-sided': ('একদিকে ঘাম', [('puls',2),('nux-v',2),('bar-c',2),('rhus-t',1),('chin',1)]),
 'Perspiration on head': ('মাথায় ঘাম', [('calc',3),('sil',2),('sanic',2),('merc',2),('sulph',2),('psor',2)]),
 'Perspiration on palms': ('হাতের তালুতে ঘাম', [('calc',3),('sil',2),('sulph',2),('nat-m',2),('fl-ac',2),('sep',2)]),
 'Perspiration on feet, offensive': ('পায়ে দুর্গন্ধযুক্ত ঘাম', [('sil',3),('psor',3),('graph',2),('sanic',2),('thuj',2),('bar-c',2),('sulph',2)]),
 'Perspiration during sleep': ('ঘুমে ঘাম', [('calc',3),('chin',2),('merc',2),('sulph',2),('tub',2),('sil',2),('psor',2)]),
 'Perspiration does not relieve': ('ঘামেও আরাম না হওয়া', [('merc',3),('psor',2),('stram',2),('chin',2),('ars',1)]),
 'Perspiration relieves': ('ঘামে আরাম', [('acon',3),('nat-m',2),('psor',2),('bell',1),('cham',1)]),
 'Perspiration, staining linen yellow': ('ঘামে কাপড়ে হলদে দাগ', [('merc',2),('lach',2),('carb-an',2),('sel',2),('graph',1)]),
}),

(36, 'Skin - ত্বক', {
 'Dryness of skin': ('শুষ্ক ত্বক', [('sulph',3),('alum',3),('graph',2),('petr',2),('ars',2),('calc',2),('sil',2),('nat-m',2),('psor',2)]),
 'Itching of skin': ('ত্বকে চুলকানি', [('sulph',3),('psor',3),('rhus-t',2),('mez',2),('ars',2),('urt-u',2),('graph',2),('alum',2),('staph',2),('dulc',2)]),
 'Itching worse from warmth of bed': ('বিছানার গরমে চুলকানি বৃদ্ধি', [('sulph',3),('psor',3),('merc',2),('puls',2),('mez',2),('graph',1)]),
 'Itching worse after scratching': ('আঁচড়ানোর পর জ্বালা', [('sulph',3),('mez',2),('rhus-t',2),('ars',2),('psor',2),('caust',1)]),
 'Burning of skin': ('ত্বকে জ্বালা', [('ars',3),('sulph',3),('apis',2),('urt-u',2),('canth',2),('rhus-t',2),('mez',2)]),
 'Eruptions, dry': ('শুকনো ফুসকুড়ি', [('sulph',3),('alum',2),('ars',2),('psor',2),('lyc',2),('nat-m',2)]),
 'Eruptions, moist': ('রসযুক্ত ফুসকুড়ি', [('graph',3),('rhus-t',2),('mez',2),('hep',2),('merc',2),('psor',2),('petr',2)]),
 'Eruptions, vesicular': ('ফোস্কাযুক্ত ফুসকুড়ি', [('rhus-t',3),('mez',2),('nat-m',2),('ran-b',2),('caust',2),('cantharis',0),('canth',2)]),
 'Eruptions, pustular': ('পুঁজযুক্ত ফুসকুড়ি', [('hep',3),('merc',2),('sil',2),('sulph',2),('ant-c',2),('kali-br',2),('thuj',2)]),
 'Eruptions, scaly': ('আঁশযুক্ত ফুসকুড়ি', [('ars',3),('sulph',2),('kali-s',2),('graph',2),('sep',2),('petr',2),('thuj',2)]),
 'Eczema': ('একজিমা', [('graph',3),('sulph',3),('psor',3),('petr',3),('mez',2),('rhus-t',2),('ars',2),('calc',2),('hep',2),('kali-s',2),('sep',2)]),
 'Psoriasis': ('সোরিয়াসিস', [('ars',3),('sulph',3),('kali-s',2),('graph',2),('petr',2),('sep',2),('thuj',2),('ars-i',2),('phyt',1)]),
 'Urticaria, hives': ('আমবাত', [('apis',3),('urt-u',3),('rhus-t',2),('nat-m',2),('sulph',2),('ars',2),('puls',2),('dulc',2),('med',2)]),
 'Herpes zoster': ('হার্পিস জোস্টার', [('mez',3),('rhus-t',3),('ran-b',3),('ars',2),('lach',2),('hyper',2),('graph',1)]),
 'Warts': ('আঁচিল', [('thuj',3),('nit-ac',3),('caust',3),('dulc',2),('ant-c',2),('med',2),('calc',2),('sep',2)]),
 'Ulcers, indolent': ('শুকাতে না চাওয়া ঘা', [('sil',3),('ars',2),('lach',2),('carb-v',2),('hep',2),('merc',2),('nit-ac',2),('psor',2)]),
 'Ulcers with offensive discharge': ('দুর্গন্ধযুক্ত ঘা', [('psor',3),('nit-ac',2),('merc',2),('ars',2),('sil',2),('carb-v',2),('pyrog',2)]),
 'Boils, furuncles': ('ফোড়া', [('hep',3),('sil',3),('bell',2),('merc',2),('sulph',2),('arn',2),('lach',2),('anthr',2)]),
 'Abscess': ('অ্যাবসেস', [('hep',3),('sil',3),('merc',3),('lach',2),('bell',2),('phos',2),('calc-s',2),('pyrog',2)]),
 'Cracks in skin': ('ত্বক ফাটা', [('graph',3),('petr',3),('nit-ac',2),('sulph',2),('sil',2),('calc',2),('sars',2),('hep',2)]),
 'Fungal infection, ringworm': ('ছত্রাক ও দাদ', [('sep',3),('tell',3),('bacil',2),('sulph',2),('graph',2),('thuj',2),('psor',2),('dulc',2)]),
 'Scabies': ('খোস-পাঁচড়া', [('sulph',3),('psor',3),('merc',2),('sep',2),('staph',2),('hep',2),('carb-v',2)]),
 'Acne': ('ব্রণ', [('sulph',3),('kali-br',3),('hep',2),('sil',2),('nat-m',2),('bell',2),('ant-c',2),('psor',2),('thuj',2)]),
 'Suppressed eruptions, ailments after': ('চর্মরোগ চাপা পড়ার কুফল', [('sulph',3),('psor',3),('zinc',2),('caust',2),('graph',2),('sep',2)]),
 'Discolouration, brown spots': ('ত্বকে বাদামি ছোপ', [('sep',3),('lyc',2),('nit-ac',2),('thuj',2),('caul',2),('carc',1)]),
 'Skin, unhealthy, every injury suppurates': ('সামান্য আঘাতেই পুঁজ', [('hep',3),('sil',3),('borx',2),('graph',2),('merc',2),('sulph',2),('calc-s',2)]),
}),

(37, 'Generalities - সাধারণ', {
 'Weakness, general': ('সাধারণ দুর্বলতা', [('ars',3),('chin',3),('ph-ac',3),('carb-v',3),('gels',2),('sep',2),('calc',2),('nat-m',2),('kali-c',2),('sulph',2),('verat',2),('psor',2),('stann',2)]),
 'Faintness, fainting': ('মূর্ছা', [('nux-v',3),('acon',2),('cham',2),('chin',2),('verat',2),('carb-v',2),('ign',2),('mosch',2),('sep',2)]),
 'Emaciation': ('শুকিয়ে যাওয়া', [('nat-m',3),('iod',3),('abrot',3),('tub',2),('ars',2),('calc',2),('sulph',2),('lyc',2),('sil',2)]),
 'Obesity': ('স্থূলতা', [('calc',3),('graph',2),('thyr',2),('kali-c',2),('ferr',2),('am-c',2),('caps',2)]),
 'Anaemia': ('রক্তশূন্যতা', [('ferr',3),('chin',3),('nat-m',2),('calc-p',2),('ars',2),('puls',2),('phos',2),('cean',2)]),
 'Convulsions': ('খিঁচুনি', [('bell',3),('cupr',3),('cic',3),('hyos',2),('stram',2),('op',2),('ign',2),('mag-p',2),('oena',2)]),
 'Oedema, dropsy': ('শোথ', [('apis',3),('ars',3),('dig',2),('lyc',2),('sulph',2),('ter',2),('thyr',2),('merc',2)]),
 'Haemorrhage, tendency to': ('রক্তপাতের প্রবণতা', [('phos',3),('ip',2),('chin',2),('lach',2),('crot-h',2),('sec',2),('mill',2),('ham',2)]),
 'Pain, burning': ('জ্বালাযুক্ত ব্যথা', [('ars',3),('sulph',3),('canth',3),('phos',2),('apis',2),('caps',2),('carb-v',2),('sec',2),('bell',1)]),
 'Pain, stitching': ('সেলাইয়ের মতো ব্যথা', [('bry',3),('kali-c',3),('apis',2),('nit-ac',2),('berb',2),('spig',2),('squil',2),('merc',1)]),
 'Pain, cramping': ('খিঁচুনি ব্যথা', [('coloc',3),('mag-p',3),('cupr',2),('plb',2),('nux-v',2),('cham',2),('bell',2)]),
 'Pain, shooting, lightning-like': ('বিদ্যুৎচমকের মতো ব্যথা', [('mag-p',3),('bell',2),('cimic',2),('phyt',2),('kalm',2),('coloc',2)]),
 'Pain, wandering': ('ঘুরে বেড়ানো ব্যথা', [('puls',3),('kali-s',2),('kalm',2),('lac-c',2),('mang',2),('phyt',2)]),
 'Pain appears suddenly, ceases gradually': ('হঠাৎ শুরু ধীরে শেষ', [('puls',2),('sulph',2),('nux-v',1),('bell',1)]),
 'Pain appears and ceases gradually': ('ধীরে শুরু ধীরে শেষ', [('plat',3),('stann',3),('sulph',2),('puls',1)]),
 'Coldness, general': ('সাধারণ শীতলতা', [('camph',3),('verat',3),('carb-v',3),('sec',2),('ars',2),('calc',2),('sil',2),('sep',2),('helon',1)]),
 'Heat, general': ('সাধারণ উষ্ণতা', [('sulph',3),('bell',3),('acon',2),('lach',2),('puls',2),('apis',2),('iod',2),('med',2),('fl-ac',2)]),
 'Worse from motion': ('নড়াচড়ায় বৃদ্ধি', [('bry',3),('colch',3),('nux-v',2),('gels',2),('cocc',2),('dig',2),('bell',2),('spig',2)]),
 'Better from motion': ('নড়াচড়ায় উপশম', [('rhus-t',3),('ferr',2),('puls',2),('tarent',2),('zinc',2),('med',2),('caps',1)]),
 'Worse from rest': ('বিশ্রামে বৃদ্ধি', [('rhus-t',3),('ferr',2),('puls',2),('tarent',2),('zinc',2),('med',2)]),
 'Worse from cold': ('ঠান্ডায় বৃদ্ধি', [('ars',3),('hep',3),('sil',3),('nux-v',3),('calc',2),('sep',2),('kali-c',2),('rhus-t',2),('mag-p',2),('psor',2)]),
 'Worse from heat': ('গরমে বৃদ্ধি', [('puls',3),('sulph',3),('apis',3),('lach',2),('iod',2),('nat-m',2),('bry',2),('med',2),('guai',2)]),
 'Worse from damp weather': ('আর্দ্রতায় বৃদ্ধি', [('nat-s',3),('dulc',3),('rhus-t',3),('calc',2),('med',2),('thuj',2),('ars',2),('merc',2),('aran',2),('colch',2)]),
 'Worse before a storm': ('ঝড়ের আগে বৃদ্ধি', [('phos',3),('rhod',3),('nat-c',2),('sil',2),('sep',2),('psor',2),('gels',1)]),
 'Worse at seashore': ('সমুদ্রতীরে বৃদ্ধি', [('nat-m',3),('ars',2),('syph',2),('sep',2),('mag-m',2)]),
 'Better at seashore': ('সমুদ্রতীরে উপশম', [('med',3),('brom',2),('nat-s',1),('carc',2)]),
 'Worse periodically': ('নির্দিষ্ট সময় পরপর বৃদ্ধি', [('chin',3),('ars',2),('cedr',2),('nat-m',2),('chin-s',2),('sabad',1)]),
 'Worse from suppressed discharges': ('স্রাব চাপা পড়লে বৃদ্ধি', [('lach',3),('zinc',2),('sulph',2),('asaf',2),('puls',2),('sil',1)]),
 'Ailments from loss of fluids': ('তরল হারানোর কুফল', [('chin',3),('carb-v',2),('ph-ac',2),('calc',2),('cocc',2),('phos',2)]),
 'Ailments from loss of sleep': ('ঘুম না হওয়ার কুফল', [('cocc',3),('nux-v',2),('coff',2),('ph-ac',2),('sulph',2),('caust',1)]),
 'Ailments from overlifting': ('ভারী তোলার কুফল', [('rhus-t',3),('arn',2),('calc',2),('nux-v',2),('bry',2),('mill',2),('ruta',2)]),
 'Ailments from vaccination': ('টিকার কুফল', [('thuj',3),('sil',3),('sulph',2),('ant-t',2),('vac',2),('mez',2)]),
 'Ailments from suppressed eruptions': ('চর্মরোগ চাপা পড়ার কুফল', [('sulph',3),('psor',3),('zinc',2),('caust',2),('graph',2),('sep',2)]),
 'Convalescence, slow': ('আরোগ্যে দেরি', [('psor',3),('carb-v',2),('sulph',2),('chin',2),('calc',2),('ph-ac',2),('sil',2)]),
 'Worse in the morning': ('সকালে বৃদ্ধি', [('nux-v',3),('sulph',3),('lach',2),('nat-m',2),('carc',2),('podo',2),('phos',2),('bry',2)]),
 'Worse in the evening': ('সন্ধ্যায় বৃদ্ধি', [('puls',3),('sep',3),('lyc',2),('phos',2),('rhus-t',2),('bell',2),('sulph',2),('kali-s',2)]),
 'Worse at night': ('রাতে বৃদ্ধি', [('merc',3),('ars',3),('syph',3),('cham',2),('hyos',2),('rhus-t',2),('nit-ac',2),('mez',2),('aur',2),('phos',2)]),
 'Worse after midnight': ('মাঝরাতের পর বৃদ্ধি', [('ars',3),('drosera',0),('dros',2),('kali-bi',2),('nux-v',2),('rhus-t',2),('phos',2)]),
 'Worse from eating': ('খাওয়ার পর বৃদ্ধি', [('nux-v',3),('bry',3),('chin',2),('carb-v',2),('lyc',2),('kali-c',2),('puls',2),('ars',2),('sep',1)]),
 'Worse from drinking': ('পান করার পর বৃদ্ধি', [('ars',3),('bry',2),('nux-v',2),('phos',2),('verat',2),('canth',2),('eup-per',2)]),
 'Worse from draft of air': ('ঠান্ডা হাওয়ার ঝাপটায় বৃদ্ধি', [('hep',3),('sil',3),('nux-v',3),('bell',2),('acon',2),('kali-c',2),('cham',2),('calc',2)]),
 'Worse during menses': ('ঋতুস্রাবের সময় বৃদ্ধি', [('cimic',3),('mag-p',3),('sep',2),('lach',2),('nat-m',2),('puls',2),('bell',2),('cham',2),('sabin',2)]),
 'Worse from standing': ('দাঁড়িয়ে থাকলে বৃদ্ধি', [('sulph',3),('sep',3),('aesc',2),('nat-c',2),('valer',2),('calc',2),('lyc',1)]),
 'Worse from walking': ('হাঁটলে বৃদ্ধি', [('bry',3),('aesc',2),('sep',2),('calc',2),('nat-c',2),('lyc',2),('con',2)]),
 'Worse from talking': ('কথা বললে বৃদ্ধি', [('stann',3),('sulph',2),('calc',2),('phos',2),('cocc',2),('ambr',2),('rumx',2)]),
 'Worse after sleep': ('ঘুমের পর বৃদ্ধি', [('lach',3),('apis',2),('spong',2),('sulph',2),('nux-v',2),('op',2),('kali-c',1)]),
 'Better after sleep': ('ঘুমের পর উপশম', [('phos',3),('sep',2),('sulph',2),('calc',2),('nux-v',2),('ph-ac',2)]),
 'Better in open air': ('খোলা বাতাসে উপশম', [('puls',3),('apis',2),('kali-s',2),('sulph',2),('lyc',2),('all-c',2),('iod',2),('arg-n',2)]),
 'Better in a warm room': ('গরম ঘরে উপশম', [('ars',3),('hep',2),('sil',2),('nux-v',2),('kali-c',2),('mag-p',2),('rhus-t',2),('caps',1)]),
 'Better lying down': ('শুয়ে থাকলে উপশম', [('bry',3),('nux-v',2),('colch',2),('arn',2),('phos',2),('stann',2),('mang',2)]),
 'Better from pressure': ('চাপে উপশম', [('bry',3),('mag-p',2),('coloc',2),('puls',2),('nat-m',2),('arg-n',2),('chin',2)]),
 'Better from warm applications': ('গরম প্রয়োগে উপশম', [('mag-p',3),('ars',3),('rhus-t',2),('nux-v',2),('sil',2),('hep',2),('caps',2)]),
 'Better from cold applications': ('ঠান্ডা প্রয়োগে উপশম', [('apis',3),('puls',2),('led',2),('lach',2),('sulph',2),('guai',2),('bry',1)]),
 'Better from open door, wants windows open': ('জানালা খোলা রাখতে চায়', [('carb-v',3),('lach',3),('sulph',2),('apis',2),('puls',2),('iod',2)]),
 'Side, right': ('ডান দিকের রোগ', [('lyc',3),('bell',2),('chel',2),('apis',2),('sang',2),('bry',2),('kali-c',2)]),
 'Side, left': ('বাঁ দিকের রোগ', [('lach',3),('spig',2),('phos',2),('sep',2),('arg-n',2),('thuj',2),('cimic',2)]),
 'Symptoms go right to left': ('ডান থেকে বাঁয়ে যায়', [('lyc',3),('chel',2),('sang',1)]),
 'Symptoms go left to right': ('বাঁ থেকে ডানে যায়', [('lach',3),('rhus-t',2),('sil',1)]),
}),
]
