# -*- coding: utf-8 -*-
"""Kent's Repertory — chapters 1-10 (Mind, Vertigo, Head, Eye, Vision, Ear,
   Hearing, Nose, Face, Mouth).

   Format:  'English rubric': ('বাংলা', [(remedy key, grade 1-3), ...])
"""

K1 = [
(1, 'Mind - মন', {
 'Anxiety': ('উদ্বেগ', [('acon',3),('ars',3),('arg-n',3),('aur',3),('phos',2),('calc',2),('kali-c',2),('puls',2),('nat-m',2),('lyc',2),('gels',2),('caust',1),('sep',1),('carc',2)]),
 'Anxiety of conscience': ('অপরাধবোধের উদ্বেগ', [('aur',3),('ars',2),('cocc',2),('dig',2),('puls',2),('sulph',2),('carc',2)]),
 'Anticipation, ailments from': ('আগাম দুশ্চিন্তার কুফল', [('arg-n',3),('gels',3),('lyc',3),('carc',2),('ars',2),('sil',2),('phos',2),('anac',2)]),
 'Fear': ('ভয়', [('acon',3),('ars',3),('stram',3),('calc',2),('phos',2),('lyc',2),('bell',2),('gels',2),('puls',2),('bar-c',2),('kali-c',2),('op',2)]),
 'Fear of death': ('মৃত্যুভয়', [('acon',3),('ars',3),('aur',2),('calc',2),('nit-ac',2),('phos',2),('gels',2),('lach',1)]),
 'Fear of being alone': ('একা থাকার ভয়', [('ars',3),('phos',3),('stram',3),('kali-c',2),('lyc',2),('puls',2),('bism',2),('hyos',1)]),
 'Fear of crowds': ('ভিড়ের ভয়', [('acon',3),('arg-n',3),('gels',2),('nat-m',2),('puls',2),('lyc',2),('bar-c',2)]),
 'Fear of height': ('উচ্চতার ভয়', [('arg-n',3),('gels',2),('sulph',2),('calc',2),('staph',1)]),
 'Fear of water': ('পানির ভয়', [('lyss',3),('stram',3),('hyos',2),('bell',2),('sanic',2),('ars',1)]),
 'Fear of thunderstorm': ('বজ্রপাতের ভয়', [('phos',3),('rhod',3),('nat-c',3),('sil',2),('sep',2),('borx',2),('gels',1),('nit-ac',1)]),
 'Fear of animals': ('পশুর ভয়', [('bell',3),('stram',2),('tub',2),('calc',2),('hyos',1),('cupr',1)]),
 'Fear of narrow places': ('সংকীর্ণ জায়গার ভয়', [('arg-n',3),('acon',2),('puls',2),('lyc',2),('valer',1)]),
 'Fear of poverty': ('দারিদ্র্যের ভয়', [('calc',3),('bry',3),('sep',2),('psor',2),('ars',2),('nux-v',1)]),
 'Fear of insanity': ('পাগল হওয়ার ভয়', [('calc',3),('cann-i',2),('lil-t',2),('nat-m',2),('puls',2),('lach',2)]),
 'Restlessness': ('অস্থিরতা', [('ars',3),('rhus-t',3),('acon',3),('tarent',3),('med',2),('ferr',2),('puls',2),('sulph',2),('cham',2),('zinc',2)]),
 'Irritability': ('বিরক্তি ও খিটখিটে মেজাজ', [('nux-v',3),('cham',3),('hep',3),('bry',3),('sep',3),('lyc',2),('staph',2),('nat-m',2),('sulph',2),('ars',2),('ign',2),('cina',2),('kali-c',2)]),
 'Anger': ('রাগ', [('cham',3),('nux-v',3),('hep',3),('staph',3),('bry',2),('lyc',2),('ign',2),('anac',2),('tarent',2),('aur',2)]),
 'Anger, suppressed': ('চাপা রাগ', [('staph',3),('ign',3),('nat-m',2),('carc',2),('aur',2),('lyc',1)]),
 'Impatience': ('অধৈর্য', [('nux-v',3),('ign',2),('sulph',2),('cham',2),('arg-n',2),('med',2),('sep',2)]),
 'Hurry': ('তাড়াহুড়ো', [('arg-n',3),('merc',3),('med',3),('sul-ac',3),('nux-v',2),('lil-t',2),('tarent',2)]),
 'Grief': ('শোক', [('ign',3),('nat-m',3),('ph-ac',3),('aur',2),('staph',2),('puls',2),('carc',2),('cimic',2),('lach',1)]),
 'Sadness': ('বিষণ্নতা', [('aur',3),('nat-m',3),('ign',3),('puls',2),('sep',2),('ars',2),('lach',2),('calc',2),('graph',2),('ph-ac',2),('carc',2)]),
 'Weeping': ('কান্না', [('puls',3),('ign',3),('nat-m',3),('sep',2),('lyc',2),('cimic',2),('graph',2),('apis',2),('coff',1),('carc',2)]),
 'Weeping, involuntary': ('অনিচ্ছাকৃত কান্না', [('sep',3),('nat-m',2),('lyc',2),('graph',2),('puls',2),('cimic',2)]),
 'Consolation aggravates': ('সান্ত্বনায় বৃদ্ধি', [('nat-m',3),('ign',3),('sep',2),('sil',2),('lil-t',2),('helon',2),('calc-p',2)]),
 'Forsaken feeling': ('পরিত্যক্ত অনুভূতি', [('puls',3),('carc',2),('nat-m',2),('psor',2),('ars',2),('lach',1)]),
 'Loquacity': ('বাচালতা', [('lach',3),('hyos',3),('stram',3),('cann-i',2),('coff',2),('bell',2),('verat',2),('tarent',2),('op',1)]),
 'Taciturn': ('স্বল্পভাষী', [('ign',3),('nat-m',2),('sep',2),('bry',2),('phos-ac',0),('ph-ac',2),('verat',1)]),
 'Memory, weakness of': ('স্মৃতিশক্তির দুর্বলতা', [('anac',3),('lyc',3),('bar-c',3),('nat-m',2),('sep',2),('alum',2),('phos',2),('kali-p',2),('sulph',2),('con',2),('agar',2),('plb',1)]),
 'Concentration difficult': ('মনোযোগের অভাব', [('lyc',3),('nat-m',2),('sulph',2),('kali-p',2),('sep',2),('phos',2),('nux-v',2),('cann-i',2),('anac',2)]),
 'Confusion of mind': ('বিভ্রান্তি', [('nux-m',3),('bapt',3),('op',3),('lach',2),('phos',2),('sulph',2),('hell',2),('cann-i',2),('alum',2),('gels',2)]),
 'Delirium': ('প্রলাপ', [('bell',3),('hyos',3),('stram',3),('op',2),('bapt',2),('lach',2),('ars',2),('acon',2),('verat',2),('verat-v',2)]),
 'Delusions': ('ভ্রান্ত ধারণা', [('bell',3),('hyos',3),('stram',3),('thuj',3),('lach',2),('cann-i',2),('anac',2),('sulph',2),('bapt',2)]),
 'Mania': ('উন্মাদনা', [('bell',3),('hyos',3),('stram',3),('verat',3),('lach',2),('aur',2),('op',2),('cupr',1),('agar',1)]),
 'Suicidal disposition': ('আত্মহত্যার প্রবণতা', [('aur',3),('nat-s',3),('psor',2),('lach',2),('ars',2),('hep',2),('nux-v',2),('carc',2),('chin',1),('sep',1)]),
 'Hysteria': ('হিস্টিরিয়া', [('ign',3),('mosch',3),('valer',3),('tarent',2),('plat',2),('croc',2),('asaf',2),('nux-m',2),('lil-t',1)]),
 'Jealousy': ('ঈর্ষা', [('lach',3),('apis',3),('hyos',3),('nux-v',2),('puls',1),('staph',1)]),
 'Suspiciousness': ('সন্দেহপ্রবণতা', [('lach',3),('ars',3),('hyos',2),('merc',2),('rhus-t',2),('thuj',2),('puls',1),('bry',1),('nux-v',1)]),
 'Indifference, apathy': ('উদাসীনতা', [('sep',3),('ph-ac',3),('nat-m',2),('puls',2),('apis',2),('hell',2),('op',2),('carc',2),('chin',2)]),
 'Laughing, immoderate': ('অট্টহাসি', [('hyos',3),('croc',3),('cann-i',2),('stram',2),('ign',2),('nat-m',1),('plat',1)]),
 'Fastidious': ('অতি পরিচ্ছন্নতাপ্রিয়', [('ars',3),('nux-v',3),('carc',3),('anac',2),('sil',2),('graph',2),('sulph',1)]),
 'Obstinate': ('একগুঁয়ে', [('calc',3),('nux-v',2),('sil',2),('tub',2),('cham',2),('bell',2),('anac',2)]),
 'Timidity': ('ভীরুতা', [('bar-c',3),('sil',3),('puls',2),('gels',2),('lyc',2),('nat-m',2),('carc',2)]),
 'Starting from noise': ('শব্দে চমকে ওঠা', [('bor',0),('borx',3),('nat-m',2),('nux-v',2),('sil',2),('phos',2),('kali-c',2),('lyc',2)]),
 'Sensitive to noise': ('শব্দে অতি সংবেদনশীল', [('nux-v',3),('coff',3),('bell',2),('sil',2),('nat-m',2),('spig',2),('theri',2),('acon',2)]),
 'Sensitive to music': ('সংগীতে সংবেদনশীল', [('nat-c',3),('nat-m',2),('sabin',2),('acon',2),('tarent',2),('graph',2)]),
 'Company, desire for': ('সঙ্গের আকাঙ্ক্ষা', [('ars',3),('phos',3),('stram',3),('lyc',2),('puls',2),('kali-c',2),('bism',2),('hyos',1)]),
 'Company, aversion to': ('সঙ্গে অরুচি', [('nat-m',3),('sep',3),('ign',3),('bry',2),('gels',2),('aur',2),('cham',2),('lyc',2),('thuj',1)]),
 'Desire to be alone': ('একা থাকার ইচ্ছা', [('nat-m',3),('ign',3),('sep',3),('bry',2),('gels',2),('aur',2),('thuj',2),('arn',2)]),
 'Fright, ailments from': ('ভয়ের কুফল', [('op',3),('acon',3),('gels',2),('ign',2),('stram',2),('lyc',2),('puls',1)]),
 'Mortification, ailments from': ('অপমানের কুফল', [('staph',3),('ign',3),('nat-m',2),('lyc',2),('aur',2),('colch',2)]),
}),

(2, 'Vertigo - মাথা ঘোরা', {
 'Vertigo in general': ('মাথা ঘোরা', [('cocc',3),('con',3),('gels',3),('bell',2),('phos',2),('nat-m',2),('bry',2),('puls',2),('sil',2),('calc',2),('tab',2),('arg-n',2)]),
 'Vertigo on rising': ('উঠতে গেলে মাথা ঘোরা', [('bry',3),('phos',2),('nux-v',2),('op',2),('rhus-t',2),('acon',2),('chin',2)]),
 'Vertigo on lying down': ('শুলে মাথা ঘোরা', [('con',3),('rhus-t',2),('apis',2),('bry',1),('nux-v',1)]),
 'Vertigo on closing eyes': ('চোখ বন্ধ করলে মাথা ঘোরা', [('lach',3),('tab',2),('arg-n',2),('thuj',2),('sep',1)]),
 'Vertigo looking upward': ('উপরে তাকালে মাথা ঘোরা', [('puls',3),('calc',2),('sil',2),('nux-v',1)]),
 'Vertigo looking downward': ('নিচে তাকালে মাথা ঘোরা', [('kalm',3),('spig',2),('phos',2),('sulph',2),('sil',1)]),
 'Vertigo with nausea': ('বমি ভাবসহ মাথা ঘোরা', [('cocc',3),('tab',3),('nux-v',2),('ip',2),('petr',2),('sep',2),('bry',2)]),
 'Vertigo while walking': ('হাঁটতে গেলে মাথা ঘোরা', [('agar',3),('nux-v',2),('phos',2),('gels',2),('bell',2),('lach',1)]),
 'Vertigo in open air': ('খোলা বাতাসে মাথা ঘোরা', [('cycl',2),('nux-v',2),('sil',2),('sep',2),('sulph',1)]),
 'Vertigo from riding in a carriage': ('যানবাহনে মাথা ঘোরা', [('cocc',3),('petr',3),('tab',2),('sep',2),('nux-v',1)]),
 'Vertigo with tendency to fall': ('মাথা ঘুরে পড়ে যাওয়ার প্রবণতা', [('gels',3),('bell',2),('nux-v',2),('phos',2),('cocc',2),('agar',2),('con',2)]),
 'Vertigo with headache': ('মাথাব্যথাসহ মাথা ঘোরা', [('cocc',3),('gels',3),('bell',2),('nux-v',2),('phos',2),('bry',2),('sil',1)]),
}),

(3, 'Head - মাথা', {
 'Headache in general': ('মাথাব্যথা', [('bell',3),('bry',3),('nat-m',3),('nux-v',3),('sang',3),('glon',2),('spig',2),('sep',2),('sil',2),('gels',2),('iris',2),('lac-c',2)]),
 'Headache, burning': ('জ্বালাযুক্ত মাথাব্যথা', [('ars',3),('sulph',2),('phos',2),('bell',2),('sang',2),('glon',2)]),
 'Headache, bursting': ('মাথা ফেটে যাওয়ার মতো ব্যথা', [('bell',3),('glon',3),('bry',2),('nux-v',2),('nat-m',2),('meli',2),('cham',1)]),
 'Headache, pressing': ('চাপযুক্ত মাথাব্যথা', [('nat-m',3),('gels',3),('nux-v',2),('bry',2),('sep',2),('cimic',2),('chel',2),('sulph',2)]),
 'Headache, throbbing': ('স্পন্দনশীল মাথাব্যথা', [('bell',3),('glon',3),('sang',2),('ferr-p',2),('lach',2),('nat-m',2),('meli',2),('puls',2)]),
 'Headache, stitching': ('সেলাইয়ের মতো মাথাব্যথা', [('bry',3),('kali-c',2),('spig',2),('nit-ac',2),('sil',2),('apis',1)]),
 'Headache as if nail driven in': ('পেরেক ঠোকার মতো মাথাব্যথা', [('ign',3),('coff',2),('thuj',2),('nux-v',1),('hep',1)]),
 'Headache, one-sided': ('একদিকের মাথাব্যথা', [('sang',3),('spig',3),('nux-v',2),('chel',2),('sep',2),('lac-c',2),('sil',2),('iris',2)]),
 'Headache, occipital': ('মাথার পিছনে ব্যথা', [('gels',3),('cocc',2),('nat-m',2),('sil',2),('cimic',2),('carb-v',2),('petr',2)]),
 'Headache, forehead': ('কপালে ব্যথা', [('bry',3),('nux-v',3),('nat-m',2),('bell',2),('sep',2),('kali-bi',2),('gels',2),('sulph',2)]),
 'Headache, temples': ('রগে ব্যথা', [('bell',3),('nat-m',2),('sep',2),('chin',2),('lach',2),('sulph',2),('spig',2)]),
 'Headache, vertex': ('মাথার তালুতে ব্যথা', [('sulph',3),('cimic',2),('lach',2),('sep',2),('sil',2),('phos',1)]),
 'Headache from sun': ('রোদে মাথাব্যথা', [('glon',3),('bell',3),('nat-m',3),('lach',2),('sang',2),('cact',1),('ars',1)]),
 'Headache from noise': ('শব্দে মাথাব্যথা', [('bell',3),('nux-v',3),('spig',2),('coff',2),('sil',2),('nat-m',2),('sep',1)]),
 'Headache from light': ('আলোয় মাথাব্যথা', [('bell',3),('sil',2),('nat-m',2),('spig',2),('phos',2),('sang',2),('gels',2)]),
 'Headache from reading': ('পড়াশোনায় মাথাব্যথা', [('nat-m',3),('calc-p',2),('ruta',2),('sep',2),('cimic',2),('phos',2),('nux-v',2)]),
 'Headache from mental exertion': ('মানসিক পরিশ্রমে মাথাব্যথা', [('nat-m',3),('nux-v',3),('calc-p',2),('sil',2),('cimic',2),('kali-p',2),('anac',2)]),
 'Headache after eating': ('খাওয়ার পর মাথাব্যথা', [('nux-v',3),('bry',2),('lyc',2),('carb-v',2),('puls',2),('chin',1)]),
 'Headache during menses': ('ঋতুস্রাবের সময় মাথাব্যথা', [('nat-m',3),('sep',3),('cimic',3),('lach',2),('puls',2),('bell',2),('sang',2),('lac-c',2)]),
 'Headache from grief': ('শোকের পর মাথাব্যথা', [('ign',3),('nat-m',3),('ph-ac',2),('staph',2),('aur',1)]),
 'Headache from suppressed coryza': ('সর্দি চাপা পড়ে মাথাব্যথা', [('kali-bi',3),('sil',2),('lach',2),('nux-v',2),('bell',1)]),
 'Headache worse morning': ('সকালে মাথাব্যথা বৃদ্ধি', [('nux-v',3),('nat-m',3),('sang',2),('lach',2),('sulph',2),('bry',2),('carc',2)]),
 'Headache worse evening': ('সন্ধ্যায় মাথাব্যথা বৃদ্ধি', [('puls',3),('sep',2),('lyc',2),('phos',2),('bell',2),('rhus-t',1)]),
 'Headache better motion': ('নড়াচড়ায় মাথাব্যথা উপশম', [('rhus-t',3),('sep',2),('puls',2),('mag-p',1),('cycl',1)]),
 'Headache better rest': ('বিশ্রামে মাথাব্যথা উপশম', [('bry',3),('bell',3),('gels',2),('nux-v',2),('sil',2),('spig',2)]),
 'Headache better pressure': ('চাপ দিলে মাথাব্যথা উপশম', [('bry',3),('puls',2),('mag-p',2),('nat-m',2),('sil',2),('arg-n',2)]),
 'Headache with nausea': ('বমি ভাবযুক্ত মাথাব্যথা', [('nux-v',3),('sang',3),('iris',3),('bry',2),('sep',2),('cocc',2),('ip',2),('puls',2)]),
 'Headache with vomiting': ('বমিসহ মাথাব্যথা', [('sang',3),('iris',3),('nux-v',2),('bry',2),('sep',2),('ip',2),('lac-c',2),('nat-m',2)]),
 'Headache with vertigo': ('মাথা ঘোরাসহ মাথাব্যথা', [('cocc',3),('gels',3),('con',2),('bell',2),('nux-v',2),('phos',2),('bry',2)]),
 'Headache with visual disturbance': ('দৃষ্টি সমস্যাসহ মাথাব্যথা', [('nat-m',3),('gels',3),('lac-c',2),('psor',2),('iris',2),('cycl',2),('sil',2)]),
 'Headache with fever': ('জ্বরের সাথে মাথাব্যথা', [('bell',3),('bry',3),('gels',3),('eup-per',2),('ferr-p',2),('acon',2),('nat-m',1)]),
 'Perspiration of scalp': ('মাথার তালুতে ঘাম', [('calc',3),('sil',2),('sanic',2),('merc',2),('sulph',2),('psor',2)]),
 'Hair falling': ('চুল পড়া', [('ph-ac',3),('nat-m',3),('sep',2),('lyc',2),('sil',2),('calc',2),('fl-ac',2),('thuj',2),('graph',2)]),
 'Dandruff': ('খুশকি', [('graph',3),('sulph',2),('nat-m',2),('sep',2),('thuj',2),('kali-s',2),('psor',2)]),
 'Head, coldness of': ('মাথা ঠান্ডা', [('calc',3),('verat',2),('sep',2),('camph',2),('sil',1)]),
}),

(4, 'Eye - চোখ', {
 'Inflammation of eyes': ('চোখের প্রদাহ', [('euphr',3),('apis',3),('bell',3),('merc',2),('puls',2),('ars',2),('rhus-t',2),('hep',2),('sulph',2),('arg-n',2)]),
 'Lachrymation': ('চোখে পানি ঝরা', [('euphr',3),('all-c',3),('nat-m',2),('puls',2),('rhus-t',2),('sabad',2),('apis',2),('graph',2)]),
 'Discharge from eyes, purulent': ('চোখে পুঁজ', [('arg-n',3),('puls',3),('merc',2),('hep',2),('sil',2),('sulph',2),('graph',2),('apis',2)]),
 'Photophobia': ('আলোয় অসহ্য', [('bell',3),('euphr',2),('con',3),('graph',2),('merc',2),('nux-v',2),('sil',2),('sulph',2),('acon',2)]),
 'Burning in eyes': ('চোখে জ্বালা', [('euphr',3),('ars',2),('sulph',2),('bell',2),('apis',2),('nat-m',2),('rhus-t',2),('merc',2)]),
 'Dryness of eyes': ('চোখ শুকনো', [('nat-m',3),('bell',2),('sulph',2),('puls',2),('lyc',2),('alum',2)]),
 'Sensation of sand in eyes': ('চোখে বালি পড়ার অনুভূতি', [('euphr',3),('sulph',3),('nat-m',2),('zinc',2),('calc',2),('puls',2)]),
 'Styes': ('অঞ্জনি', [('puls',3),('staph',3),('graph',2),('sulph',2),('sil',2),('hep',2),('lyc',2)]),
 'Swelling of lids': ('চোখের পাতা ফোলা', [('apis',3),('kali-c',3),('ars',2),('merc',2),('rhus-t',2),('phos',2),('graph',2)]),
 'Agglutination of lids in morning': ('সকালে চোখের পাতা আটকে থাকা', [('graph',3),('puls',2),('merc',2),('sulph',2),('hep',2),('calc',2)]),
 'Twitching of lids': ('চোখের পাতা কাঁপা', [('agar',3),('nat-m',2),('sulph',2),('bell',2),('mag-p',2),('phos',1)]),
 'Ptosis, drooping of lids': ('চোখের পাতা ঝুলে পড়া', [('gels',3),('caust',2),('sep',2),('nat-m',2),('con',2),('plb',2)]),
 'Pain in eyes': ('চোখে ব্যথা', [('bell',3),('spig',3),('bry',2),('rhus-t',2),('merc',2),('nat-m',2),('con',2),('ruta',2)]),
 'Pain in eyes from use': ('চোখ ব্যবহারে ব্যথা', [('ruta',3),('nat-m',3),('calc-p',2),('sep',2),('phos',2),('con',2),('cimic',2)]),
 'Injuries of eye': ('চোখে আঘাত', [('symph',3),('arn',3),('ham',2),('euphr',2),('ledum',0),('led',2),('acon',2)]),
 'Redness of eyes': ('চোখ লাল', [('bell',3),('euphr',2),('apis',2),('nux-v',2),('sulph',2),('merc',2),('acon',2)]),
 'Cataract': ('চোখের ছানি', [('calc',2),('sil',2),('phos',2),('caust',3),('nat-m',2),('sulph',2),('con',2)]),
 'Glaucoma': ('গ্লুকোমা', [('phos',2),('bell',2),('gels',2),('spig',2),('bry',1),('osm',1)]),
 'Eye strain from close work': ('সূক্ষ্ম কাজে চোখের ক্লান্তি', [('ruta',3),('nat-m',2),('sep',2),('calc-p',2),('phos',2),('cimic',1)]),
 'Ulceration of cornea': ('কর্নিয়ার ঘা', [('merc',3),('hep',2),('sil',2),('ars',2),('con',2),('kali-bi',2)]),
}),

(5, 'Vision - দৃষ্টি', {
 'Dim vision': ('ঝাপসা দৃষ্টি', [('phos',3),('gels',3),('nat-m',2),('sep',2),('sil',2),('caust',2),('con',2),('cycl',2)]),
 'Loss of vision': ('দৃষ্টি হারানো', [('phos',3),('gels',2),('bell',2),('sulph',2),('caust',2),('plb',2),('tab',2)]),
 'Diplopia, double vision': ('দ্বৈত দৃষ্টি', [('gels',3),('nat-m',2),('bell',2),('agar',2),('stram',2),('hyos',2),('cic',2)]),
 'Flickering before eyes': ('চোখের সামনে ঝিলিক', [('nat-m',3),('sep',2),('cycl',2),('graph',2),('psor',2),('sulph',2)]),
 'Zigzag lines before eyes': ('আঁকাবাঁকা রেখা দেখা', [('nat-m',3),('sep',2),('psor',2),('graph',2),('lac-c',2),('iris',2)]),
 'Spots before eyes': ('চোখের সামনে বিন্দু', [('nat-m',2),('sulph',2),('phos',2),('sep',2),('lyc',2),('caust',2)]),
 'Halo around light': ('আলোর চারপাশে বৃত্ত', [('bell',3),('phos',2),('sulph',2),('cycl',1),('osm',1)]),
 'Photopsia, sparks': ('স্ফুলিঙ্গ দেখা', [('bell',2),('phos',2),('nat-m',2),('bar-c',2),('cycl',2)]),
 'Vision blurred before headache': ('মাথাব্যথার আগে ঝাপসা দৃষ্টি', [('nat-m',3),('gels',2),('psor',2),('lac-c',2),('iris',2),('cycl',2)]),
 'Myopia, short-sightedness': ('ক্ষীণদৃষ্টি', [('phos',3),('puls',2),('sulph',2),('calc',2),('sep',2),('lyc',1)]),
 'Presbyopia, far-sightedness': ('দূরদৃষ্টি', [('carb-an',2),('lyc',2),('sil',2),('nat-m',1),('sulph',1)]),
 'Colours before eyes': ('রঙিন দৃষ্টিভ্রম', [('bell',2),('phos',2),('sant',0),('santin',2),('cycl',2),('digitalis',0),('dig',2)]),
}),

(6, 'Ear - কান', {
 'Earache': ('কানে ব্যথা', [('cham',3),('bell',3),('puls',3),('merc',2),('hep',2),('acon',2),('sil',2),('mag-p',2),('verb',2),('caps',2)]),
 'Otitis, inflammation of ear': ('কানের প্রদাহ', [('bell',3),('puls',3),('cham',2),('merc',2),('hep',2),('ferr-p',2),('sil',2),('kali-m',2)]),
 'Discharge from ear, purulent': ('কান পাকা', [('merc',3),('hep',3),('sil',3),('puls',2),('calc',2),('graph',2),('kali-bi',2),('tell',2),('psor',2)]),
 'Discharge from ear, offensive': ('দুর্গন্ধযুক্ত কানের স্রাব', [('psor',3),('tell',3),('merc',2),('hep',2),('sil',2),('kali-p',2),('graph',1)]),
 'Noises in ear': ('কানে শব্দ', [('chin',3),('chin-s',3),('sil',2),('phos',2),('kali-c',2),('caust',2),('graph',2),('petr',2),('nat-s',2)]),
 'Stopped sensation in ear': ('কান বন্ধ লাগা', [('sil',3),('merc',2),('lyc',2),('kali-m',2),('mang',2),('puls',2),('graph',2)]),
 'Itching in ear': ('কানে চুলকানি', [('sulph',2),('sil',2),('psor',2),('nat-c',2),('mez',2),('graph',2)]),
 'Swelling behind ear': ('কানের পিছনে ফোলা', [('bell',2),('merc',2),('sil',2),('hep',2),('calc',2),('graph',2)]),
 'Eruptions behind ear': ('কানের পিছনে ফুসকুড়ি', [('graph',3),('petr',2),('psor',2),('sulph',2),('rhus-t',2),('lyc',2)]),
 'Sensitive to noise (ear)': ('কানে শব্দ সহ্য না হওয়া', [('bell',3),('nux-v',2),('coff',2),('theri',2),('sil',2),('spig',2)]),
 'Mastoid pain': ('কানের পিছনের হাড়ে ব্যথা', [('caps',3),('sil',2),('hep',2),('merc',2),('bell',2),('aur',2)]),
 'Wax, increased': ('কানের খৈল বৃদ্ধি', [('con',2),('lach',2),('puls',2),('elaps',2),('calc',1)]),
 'Wax, deficient (dry ear)': ('কানের খৈল কমে যাওয়া', [('lach',2),('elaps',2),('psor',1),('sil',1)]),
 'Pain extending to throat': ('কান থেকে গলায় ব্যথা', [('phyt',3),('hep',2),('merc',2),('nux-v',1),('caps',2)]),
 'Boils in ear canal': ('কানের নালিতে ফোড়া', [('hep',3),('sil',2),('merc',2),('bell',2),('picric',0),('pic-ac',2)]),
 'Cracking in ear on swallowing': ('গিলতে গেলে কানে শব্দ', [('bar-c',2),('merc',2),('nit-ac',2),('graph',2),('sil',1)]),
 'Deafness after suppressed eruption': ('চর্মরোগ চাপা পড়ে বধিরতা', [('sulph',2),('psor',2),('graph',2),('sil',2),('caust',1)]),
 'Eustachian tube, catarrh of': ('ইউস্টেশিয়ান নালির প্রদাহ', [('kali-m',3),('merc',2),('sil',2),('puls',2),('lyc',2),('mang',2),('hydr',2)]),
}),

(7, 'Hearing - শ্রবণ', {
 'Hearing impaired': ('শ্রবণশক্তি কমে যাওয়া', [('sil',3),('chin',2),('kali-c',2),('caust',2),('graph',2),('petr',2),('phos',2),('lyc',2),('merc',2)]),
 'Hearing acute, over-sensitive': ('অতি তীক্ষ্ণ শ্রবণ', [('bell',3),('coff',3),('nux-v',2),('sil',2),('theri',2),('acon',2),('opium',0),('op',1)]),
 'Hearing lost for human voice': ('মানুষের কণ্ঠ শুনতে না পাওয়া', [('phos',3),('ign',2),('nux-m',1),('sil',1)]),
 'Hearing better in noise': ('শব্দের মধ্যে ভালো শোনা', [('graph',3),('nit-ac',2),('caust',1)]),
 'Hearing worse when swallowing': ('গিলতে গেলে শ্রবণে সমস্যা', [('bar-c',2),('merc',2),('graph',2),('nit-ac',1)]),
 'Hearing worse in damp weather': ('ভেজা আবহাওয়ায় শ্রবণে সমস্যা', [('dulc',2),('nat-s',2),('merc',2),('kali-m',2),('calc',1)]),
 'Deafness with tinnitus': ('কানে শব্দসহ বধিরতা', [('chin-s',3),('chin',2),('sil',2),('caust',2),('phos',2),('kali-c',2)]),
 'Deafness with dryness of ear': ('কান শুকনোসহ বধিরতা', [('lach',2),('elaps',2),('sil',2),('psor',1)]),
}),

(8, 'Nose - নাক', {
 'Coryza, cold in nose': ('সর্দি', [('all-c',3),('nux-v',3),('ars',2),('puls',2),('nat-m',2),('sabad',2),('euphr',2),('kali-bi',2),('sil',2),('dulc',2)]),
 'Coryza, fluent': ('ঝরঝরে সর্দি', [('all-c',3),('nat-m',3),('ars',2),('euphr',2),('sabad',2),('merc',2),('gels',2)]),
 'Coryza, dry': ('শুকনো সর্দি (নাক বন্ধ)', [('nux-v',3),('sambucus',0),('samb',3),('sticta',0),('stict',2),('kali-bi',2),('lyc',2),('am-c',2),('sil',2)]),
 'Discharge, excoriating': ('জ্বালাযুক্ত নাকের স্রাব', [('ars',3),('all-c',3),('merc',2),('nat-m',2),('kali-bi',2),('sulph',2)]),
 'Discharge, thick yellow-green': ('ঘন হলুদ-সবুজ স্রাব', [('puls',3),('kali-bi',3),('hydr',2),('merc',2),('sil',2),('kali-s',2),('nat-s',2)]),
 'Discharge, offensive': ('দুর্গন্ধযুক্ত স্রাব', [('kali-bi',3),('psor',3),('aur',2),('merc',2),('sil',2),('nit-ac',2),('hep',2)]),
 'Discharge, bloody': ('রক্তমিশ্রিত স্রাব', [('phos',2),('kali-bi',2),('merc',2),('lach',2),('sulph',1),('nit-ac',1)]),
 'Obstruction of nose': ('নাক বন্ধ', [('samb',3),('nux-v',3),('kali-bi',2),('lyc',2),('sil',2),('am-c',2),('stict',2),('sang',2)]),
 'Epistaxis, nosebleed': ('নাক দিয়ে রক্ত', [('phos',3),('ferr-p',3),('ham',2),('bry',2),('bell',2),('croc',2),('mill',2),('trill',2),('sec',1)]),
 'Sneezing': ('হাঁচি', [('sabad',3),('all-c',3),('nux-v',2),('ars',2),('nat-m',2),('sil',2),('carb-v',2),('euphr',2)]),
 'Sneezing, violent, paroxysmal': ('একটানা প্রচণ্ড হাঁচি', [('sabad',3),('all-c',2),('nat-m',2),('ars',2),('sil',1),('carb-v',1)]),
 'Loss of smell': ('ঘ্রাণশক্তি হারানো', [('puls',3),('nat-m',2),('sil',2),('sep',2),('kali-bi',2),('mag-m',2),('alum',2)]),
 'Smell, over-sensitive': ('অতি তীক্ষ্ণ ঘ্রাণ', [('nux-v',3),('cham',2),('acon',2),('colch',3),('lyc',2),('phos',2),('sep',2)]),
 'Smell, imaginary offensive': ('কাল্পনিক দুর্গন্ধ পাওয়া', [('anac',2),('aur',2),('graph',2),('puls',2),('nux-v',1)]),
 'Dryness of nose': ('নাক শুকনো', [('sticta',0),('stict',2),('nat-m',2),('am-c',2),('lyc',2),('sil',2),('kali-bi',2)]),
 'Post-nasal drip': ('নাক থেকে গলায় স্রাব', [('hydr',3),('kali-bi',3),('nat-c',2),('sep',2),('sil',2),('lyc',2)]),
 'Polypus of nose': ('নাকের পলিপ', [('thuj',3),('calc',2),('sang',2),('teucr',3),('lem-m',2),('kali-bi',2),('sil',1)]),
 'Pain in nasal bones': ('নাকের হাড়ে ব্যথা', [('aur',3),('kali-bi',2),('merc',2),('hep',2),('sil',2),('asaf',2)]),
 'Coldness of nose': ('নাক ঠান্ডা', [('verat',2),('camph',2),('carb-v',2),('ars',1),('calc',1)]),
 'Redness of nose': ('নাক লাল', [('lach',2),('sulph',2),('carb-an',2),('rhus-t',2),('bell',2),('nux-v',2)]),
 'Ulceration in nose': ('নাকে ঘা', [('kali-bi',3),('nit-ac',2),('merc',2),('sil',2),('hep',2),('ars',2),('aur',2)]),
 'Coryza worse in warm room': ('গরম ঘরে সর্দি বৃদ্ধি', [('all-c',3),('puls',2),('kali-s',2),('apis',1),('iod',2)]),
}),

(9, 'Face - মুখমণ্ডল', {
 'Pale face': ('ফ্যাকাশে মুখ', [('ferr',3),('chin',2),('calc',2),('ars',2),('verat',2),('sep',2),('puls',2),('nat-m',2)]),
 'Red face': ('লাল মুখ', [('bell',3),('acon',2),('op',2),('glon',2),('ferr-p',2),('sulph',2),('stram',2)]),
 'Circumscribed red cheeks': ('গালে গোল লাল দাগ', [('phos',3),('sang',2),('tub',2),('sulph',2),('ars',1)]),
 'One-sided redness of face': ('মুখের একদিক লাল', [('cham',3),('acon',2),('bell',2),('ip',2),('nux-v',1)]),
 'Yellow face, jaundiced': ('হলদে মুখ', [('chel',3),('chin',2),('nat-s',2),('lyc',2),('sep',2),('card-m',2),('lept',2)]),
 'Sickly face': ('রুগ্ণ চেহারা', [('ars',3),('carb-v',2),('psor',2),('tub',2),('sil',2),('nat-m',2),('phos',2)]),
 'Swelling of face': ('মুখ ফোলা', [('apis',3),('ars',3),('merc',2),('rhus-t',2),('bell',2),('kali-c',2),('phos',2)]),
 'Neuralgia of face': ('মুখের স্নায়ুশূল', [('spig',3),('mag-p',3),('bell',2),('acon',2),('verb',2),('chin',2),('coloc',2),('kalm',2)]),
 'Eruptions on face': ('মুখে ফুসকুড়ি', [('sulph',3),('kali-br',2),('hep',2),('sil',2),('nat-m',2),('ant-c',2),('psor',2),('rhus-t',2)]),
 'Acne of face': ('মুখে ব্রণ', [('sulph',3),('kali-br',3),('hep',2),('sil',2),('nat-m',2),('bell',2),('ant-c',2),('thuj',2)]),
 'Cracked lips': ('ঠোঁট ফাটা', [('nat-m',3),('bry',2),('graph',2),('sulph',2),('petr',2),('hep',2)]),
 'Herpes on lips': ('ঠোঁটে জ্বরঠোসা', [('nat-m',3),('rhus-t',3),('hep',2),('sep',2),('mez',2),('graph',1)]),
 'Chloasma, liver spots on face': ('মুখে বাদামি ছোপ', [('sep',3),('lyc',2),('caul',2),('nat-m',2),('thuj',2),('carc',1)]),
 'Hair on face in women': ('নারীর মুখে লোম', [('thuj',3),('sep',2),('nat-m',2),('med',2),('sulph',1)]),
 'Perspiration of face': ('মুখে ঘাম', [('cham',2),('calc',2),('merc',2),('sulph',2),('acon',2),('verat',2)]),
}),

(10, 'Mouth - মুখগহ্বর', {
 'Aphthae, mouth ulcers': ('মুখে ঘা', [('borx',3),('merc',3),('nit-ac',3),('nat-m',2),('sulph',2),('kali-bi',2),('bapt',2),('hydr',2),('ars',2)]),
 'Dryness of mouth': ('মুখ শুকনো', [('bry',3),('nux-m',3),('nat-m',2),('ars',2),('phos',2),('bell',2),('lach',2)]),
 'Salivation increased': ('অতিরিক্ত লালা', [('merc',3),('ip',2),('lach',2),('nit-ac',2),('bapt',2),('lyss',2),('iod',2)]),
 'Taste, bitter': ('তেতো স্বাদ', [('bry',3),('chin',2),('nux-v',2),('puls',2),('chel',2),('ars',2),('merc',2)]),
 'Taste, sour': ('টক স্বাদ', [('nux-v',3),('sulph',2),('calc',2),('lyc',2),('nat-p',2),('cham',2)]),
 'Taste, metallic': ('ধাতব স্বাদ', [('merc',3),('cupr',2),('rhus-t',2),('nat-c',2),('kali-bi',1)]),
 'Taste, putrid': ('পচা স্বাদ', [('merc',3),('nux-v',2),('bapt',2),('psor',2),('kali-p',2),('carb-v',2)]),
 'Taste, lost': ('স্বাদ হারানো', [('puls',3),('nat-m',2),('sil',2),('sep',2),('mag-m',2),('sulph',1)]),
 'Tongue, white coated': ('জিভে সাদা প্রলেপ', [('ant-c',3),('bry',2),('kali-m',2),('merc',2),('nux-v',2),('puls',2)]),
 'Tongue, yellow coated': ('জিভে হলদে প্রলেপ', [('chel',3),('merc',2),('nux-v',2),('kali-bi',2),('lept',2),('hydr',2)]),
 'Tongue, brown or black': ('জিভে বাদামি-কালচে প্রলেপ', [('bapt',3),('ars',2),('phos',2),('bry',2),('merc',1),('lach',2)]),
 'Tongue, clean with nausea': ('বমি ভাবের সাথেও জিভ পরিষ্কার', [('ip',3),('cina',2),('dig',1),('puls',1)]),
 'Tongue, red streak in middle': ('জিভের মাঝে লাল রেখা', [('verat-v',3),('bapt',2),('phyt',1),('rhus-t',1)]),
 'Tongue, mapped': ('জিভে ছাপ ছাপ দাগ', [('nat-m',2),('taraxacum',0),('tarax',2),('nit-ac',2),('rhus-t',1)]),
 'Tongue, trembling': ('জিভ কাঁপা', [('lach',3),('merc',2),('gels',2),('plb',2),('stram',2),('apis',1)]),
 'Burning in mouth': ('মুখে জ্বালা', [('ars',3),('capsicum',0),('caps',3),('merc',2),('sulph',2),('phos',2),('iris',2)]),
 'Gums bleeding': ('মশারিতে রক্ত (দাঁতের মাংসে)', [('merc',3),('phos',2),('carb-v',2),('kreos',2),('nit-ac',2),('lach',2),('sul-ac',2)]),
 'Gums swollen': ('দাঁতের মাংস ফোলা', [('merc',3),('hep',2),('sil',2),('bell',2),('nit-ac',2),('staph',2),('phos',2)]),
 'Odour from mouth, offensive': ('মুখে দুর্গন্ধ', [('merc',3),('kali-p',2),('nux-v',2),('puls',2),('psor',2),('carb-v',2),('aur',2),('nit-ac',2)]),
 'Speech, difficult': ('কথা বলতে কষ্ট', [('caust',2),('lach',2),('stram',2),('gels',2),('bell',2),('hyos',2),('plb',1)]),
}),
]
