# -*- coding: utf-8 -*-
"""Bangla names for the Kent remedies our curated roster (r_remedies.py) misses.

Kent's abbreviation key lists 650 remedies; the curated roster covers 387 of
them, because those are the ones that also carry materia medica text. The rest
still show up in the repertorisation grid, so they need a Bangla name — keyed by
the Latin name as it appears in the book's own key page.

These are transliterations in the spelling Bengali homeopathic literature uses,
authored by hand. They are ordered by how often the remedy appears in the
repertory, so the entries that matter most are also the ones most easily
checked. A remedy absent from here keeps its Latin name in the UI rather than
getting a guessed spelling.
"""
BN = {
    'Ammonium Muriaticum': 'অ্যামোনিয়াম মিউরিয়েটিকাম',
    'Carboneum Sulphuratum': 'কার্বোনিয়াম সালফিউরেটাম',
    'Borax': 'বোরাক্স',
    'Coccus Cacti': 'ককাস ক্যাক্টাই',
    'Natrum Arsenicatum': 'নেট্রাম আর্সেনিকেটাম',
    'Senega': 'সেনেগা',
    'Strontium': 'স্ট্রনসিয়াম',
    'Oxalicum Acidum': 'অক্সালিকাম অ্যাসিডাম',
    'Niccolum': 'নিকোলাম',
    'Cinnabaris': 'সিনাবেরিস',
    'Chininum Arsenicosum': 'চিনিনাম আর্সেনিকোসাম',
    'Alumen': 'অ্যালুমেন',
    'Euphorbium': 'ইউফোরবিয়াম',
    'Oleum Animale': 'ওলিয়াম অ্যানিমেল',
    'Angustura Vera': 'অ্যাঙ্গুস্টুরা ভেরা',
    'Physostigma': 'ফাইসোস্টিগমা',
    'Ranunculus Sceleratus': 'র‍্যানানকুলাস স্কেলেরেটাস',
    'Indigo': 'ইন্ডিগো',
    'Rhus Venenata': 'রাস ভেনেনাটা',
    'Anantherum Muricatum': 'অ্যানানথেরাম মিউরিকেটাম',
    'Palladium': 'প্যালেডিয়াম',
    'Theridion': 'থেরিডিয়ন',
    'Prunus Spinosa': 'প্রুনাস স্পাইনোসা',
    'Lactic Acid': 'ল্যাকটিক অ্যাসিড',
    'Mercurialis': 'মার্কিউরিয়ালিস',
    'Lithium Carbonicum': 'লিথিয়াম কার্বনিকাম',
    'Hydrocyanicum Acidum': 'হাইড্রোসায়ানিকাম অ্যাসিডাম',
    'Apocynum Cannabinum': 'অ্যাপোসাইনাম ক্যানাবিনাম',
    'Carlsbad': 'কার্লসব্যাড',
    'Vipera': 'ভাইপেরা',
    'Lachnanthes Tinctoria': 'ল্যাকন্যান্থিস টিংক্টোরিয়া',
    'Corallium Rubrum': 'কোরালিয়াম রুব্রাম',
    'Cadmium Sulphuratum': 'ক্যাডমিয়াম সালফিউরেটাম',
    'Acetic Acid': 'অ্যাসিটিক অ্যাসিড',
    'Aurum Muriaticum Natronatum': 'অরাম মিউরিয়েটিকাম ন্যাট্রোনেটাম',
    'Arundo Mauritanica': 'অ্যারুন্ডো মরিটানিকা',
    'Asclepias Tuberosa': 'অ্যাসক্লেপিয়াস টিউবেরোসা',
    'Cimex': 'সাইমেক্স',
    'Lycopus Virginicus': 'লাইকোপাস ভার্জিনিকাস',
    'Atropinium': 'অ্যাট্রোপিনাম',
    'Morphinum': 'মরফিনাম',
    'Arsenicum Hydrogenisatum': 'আর্সেনিকাম হাইড্রোজেনিসেটাম',
    'Teplitz': 'টেপ্লিটজ',
    'Ginseng': 'জিনসেং',
    'Xanthoxylum Fraxineum': 'জ্যানথক্সিলাম ফ্র্যাক্সিনিয়াম',
    'Cahinca': 'কাহিনকা',
    'Allium Sativum': 'অ্যালিয়াম সাটিভাম',
    'Sarracenia Purpurea': 'সারাসেনিয়া পারপিউরিয়া',
    'Chloralum': 'ক্লোরালাম',
    'Eugenia Jambos': 'ইউজেনিয়া জাম্বোস',
    'Juglans Cinerea': 'জাগল্যান্স সিনেরিয়া',
    'Ammoniacum Gummi': 'অ্যামোনিয়াকাম গামি',
    'Piper Methysticum': 'পাইপার মেথিস্টিকাম',
    'Asparagus Officinalis': 'অ্যাসপ্যারাগাস অফিসিনালিস',
    'Juglans Regia': 'জাগল্যান্স রেজিয়া',
    'Ferrum Muriaticum': 'ফেরাম মিউরিয়েটিকাম',
    'Brachyglottis Repens': 'ব্র্যাকিগ্লটিস রেপেন্স',
    'Oleum Jecoris Aselli': 'ওলিয়াম জেকোরিস অ্যাসেলি',
    'Guarea': 'গুয়ারিয়া',
    'Elaterium': 'ইলাটেরিয়াম',
    'Echinacea Angustifolia': 'ইকিনেসিয়া অ্যাঙ্গুস্টিফোলিয়া',
    'Stillingia Sylvatica': 'স্টিলিনজিয়া সিলভাটিকা',
    'Anagallis Arvensis': 'অ্যানাগ্যালিস আরভেনসিস',
    'Actæa Spicata': 'অ্যাক্টিয়া স্পাইকাটা',
    'Cenchris Contortrix': 'সেনক্রিস কনটরট্রিক্স',
    'Solanum Tuberosum Ægrotans': 'সোলানাম টিউবেরোসাম ইগ্রোট্যান্স',
    'Chimaphila Umbellata': 'কিমাফিলা আম্বেলাটা',
    'Ferrum Magneticum': 'ফেরাম ম্যাগনেটিকাম',
    'Arsenicum Metallicum': 'আর্সেনিকাম মেটালিকাম',
    'Boletus Laricis': 'বোলেটাস ল্যারিসিস',
    'Hippozænium': 'হিপোজিনিয়াম',
    'Dirca Palustris': 'ডার্কা প্যালাস্ট্রিস',
    'Amyl Nitrite': 'অ্যামাইল নাইট্রাইট',
    'Mercurius Sulphuricus': 'মার্কিউরিয়াস সালফিউরিকাস',
    'Carboneum Oxygenisatum': 'কার্বোনিয়াম অক্সিজেনিসেটাম',
    'Taxus Baccata': 'ট্যাক্সাস ব্যাকাটা',
    'Eryngium Aquaticum': 'ইরিনজিয়াম অ্যাকোয়াটিকাম',
    'Mercurius Cyanatus': 'মার্কিউরিয়াস সায়ানেটাস',
    'Rhus Radicans': 'রাস র‍্যাডিক্যান্স',
    'Uranium Nitricum': 'ইউরেনিয়াম নাইট্রিকাম',
    'Salicylicum Acidum': 'স্যালিসাইলিকাম অ্যাসিডাম',
    'Trillium Pendulum': 'ট্রিলিয়াম পেন্ডুলাম',
    'Castor Equi': 'ক্যাস্টর ইকুই',
    'Aurum Sulphuratum': 'অরাম সালফিউরেটাম',
    'Doryphora': 'ডরিফোরা',
    'Euonymus Europæus': 'ইউওনিমাস ইউরোপিয়াস',
    'Jacaranda Caroba': 'জ্যাকারান্ডা ক্যারোবা',
    'Aphis Chenopodii glauci': 'অ্যাফিস কিনোপোডাই গ্লসাই',
    'Gentiana Cruciata': 'জেনসিয়ানা ক্রুসিয়াটা',
    'Ammonium Bromatum': 'অ্যামোনিয়াম ব্রোমেটাম',
    'Sulphur Iodatum': 'সালফার আয়োডেটাম',
    'Natrum Hypochlorosum': 'নেট্রাম হাইপোক্লোরোসাম',
    'Petroselinum': 'পেট্রোসেলিনাম',
    'Cuprum Sulphuricum': 'কুপ্রাম সালফিউরিকাম',
    'Artemisia Vulgaris': 'আর্টেমিসিয়া ভালগারিস',
    'Mygale Lasiodora': 'মাইগেল ল্যাসিওডোরা',
    'Polygonum Hydropiperoides': 'পলিগোনাম হাইড্রোপাইপারয়ডিস',
    'Zizia Aurea': 'জিজিয়া অরিয়া',
    'Inula Helenium': 'ইনুলা হেলেনিয়াম',
    'Baryta Iodata': 'ব্যারাইটা আয়োডেটা',
    'Santoninum': 'স্যান্টোনিনাম',
    'Cajuputum': 'ক্যাজুপুটাম',
    'Chloroformium': 'ক্লোরোফরমিয়াম',
    'Cascarilla': 'ক্যাসকারিলা',
    'Dolichos Pruriens': 'ডোলিকস প্রুরিয়েন্স',
    'Jacaranda Gualandai': 'জ্যাকারান্ডা গুয়ালান্দাই',
    'Derris Pinnata': 'ডেরিস পিনাটা',
    'Carboneum Hydrogenisatum': 'কার্বোনিয়াম হাইড্রোজেনিসেটাম',
    'Citrus Vulgaris': 'সাইট্রাস ভালগারিস',
    'Amygdalæ Amaræ Aqua': 'অ্যামিগডালি আমারি অ্যাকোয়া',
    'Convallaria Majalis': 'কনভ্যালেরিয়া মাজালিস',
    'Arum Dracontium': 'অ্যারাম ড্র্যাকনসিয়াম',
    'Cochlearia Armoracia': 'কক্লিয়ারিয়া আরমোরাসিয়া',
    'Aralia Racemosa': 'অ্যারালিয়া রেসিমোসা',
    'Cuprum Aceticum': 'কুপ্রাম অ্যাসিটিকাম',
    'Chionanthus Virginica': 'কিওন্যান্থাস ভার্জিনিকা',
    'Saccharum Album': 'স্যাকারাম অ্যালবাম',
    'Pothos Fœtidus': 'পোথোস ফিটিডাস',
    'Antimonium Sulph. Auratum': 'অ্যান্টিমোনিয়াম সালফ. অরেটাম',
    'Ammonium Causticum': 'অ্যামোনিয়াম কষ্টিকাম',
    'Codeinum': 'কোডেইনাম',
    'Anthemis Nobilis': 'অ্যান্থেমিস নোবিলিস',
    'Gossypium Herbaceum': 'গসিপিয়াম হারবেসিয়াম',
    'Abies Nigra': 'অ্যাবিস নাইগ্রা',
    'Sinapis Alba': 'সাইনাপিস অ্যালবা',
    'Chenopodium Anthelminticum': 'কিনোপোডিয়াম অ্যান্থেলমিন্টিকাম',
    'Lepidium Bonariense': 'লেপিডিয়াম বোনারিয়েন্স',
    'Calcarea Caustica': 'ক্যালকেরিয়া কষ্টিকা',
    'Abies Canadensis': 'অ্যাবিস ক্যানাডেনসিস',
    'Latrodectus Mactans': 'ল্যাট্রোডেক্টাস ম্যাক্ট্যান্স',
    'Kali Manganicum': 'কেলি ম্যাঙ্গানিকাম',
    'Heloderma': 'হেলোডার্মা',
    'Gentiana Lutea': 'জেনসিয়ানা লুটিয়া',
    'Bufo Sahytiensis': 'বুফো সাহিটিয়েনসিস',
    'Lobelia Syphilitica': 'লোবেলিয়া সিফিলিটিকা',
    'Iris Fœtidissima': 'আইরিস ফিটিডিসিমা',
    'Pyrus Americana': 'পাইরাস আমেরিকানা',
    'Arum Maculatum': 'অ্যারাম ম্যাকুলেটাম',
    'Variolinum': 'ভ্যারিওলিনাম',
    'Natrum Nitricum': 'নেট্রাম নাইট্রিকাম',
    'Grindelia Robusta': 'গ্রিন্ডেলিয়া রোবাস্টা',
    'Asclepias Cornuti (Syriaca)': 'অ্যাসক্লেপিয়াস কর্নুটি (সিরিয়াকা)',
    'Illicium Anisatum': 'ইলিসিয়াম অ্যানিসেটাম',
    'Petiveria': 'পেটিভেরিয়া',
    'Ocimum Canum': 'ওসিমাম ক্যানাম',
    'Magnetis Polus Arcticus': 'ম্যাগনেটিস পোলাস আর্কটিকাস',
    'Calcarea Acetica': 'ক্যালকেরিয়া অ্যাসিটিকা',
    'Eucalyptus Globulus': 'ইউক্যালিপটাস গ্লোবুলাস',
    'Plectranthus': 'প্লেকট্রান্থাস',
    'Lamium Album': 'ল্যামিয়াম অ্যালবাম',
    'Calendula Officinalis': 'ক্যালেন্ডুলা অফিসিনালিস',
    'Genista Tinctoria': 'জেনিস্টা টিংক্টোরিয়া',
    'Asimina Triloba': 'অ্যাসিমিনা ট্রাইলোবা',
    'Manganum Muriaticum': 'ম্যাঙ্গানাম মিউরিয়েটিকাম',
    'Anthrokokali': 'অ্যানথ্রোকোকালি',
    'Zincum Sulphuricum': 'জিঙ্কাম সালফিউরিকাম',
    'Lac Felinum': 'ল্যাক ফেলাইনাম',
    'Iberis Amara': 'আইবেরিস আমারা',
    'Benzinum Nitricum': 'বেঞ্জিনাম নাইট্রিকাম',
    'Baryta Acetica': 'ব্যারাইটা অ্যাসিটিকা',
    'Arsenicum Sulphuratum Flavum': 'আর্সেনিকাম সালফিউরেটাম ফ্লেভাম',
    'Zincum Muriaticum': 'জিঙ্কাম মিউরিয়েটিকাম',
    'Myrtus Communis': 'মার্টাস কমিউনিস',
    'Calcarea Silicata': 'ক্যালকেরিয়া সিলিকাটা',
    'Castanea Vesca': 'ক্যাস্টেনিয়া ভেসকা',
    'Spiranthes': 'স্পাইর‍্যান্থিস',
    'Ether': 'ইথার',
    'Aconitum Cammarum': 'অ্যাকোনাইটাম ক্যামারাম',
    'Tussilago Petasites': 'টুসিলাগো পেটাসাইটিস',
    'Magnetis Polus Australis': 'ম্যাগনেটিস পোলাস অস্ট্রালিস',
    'Kali Ferrocyanicum': 'কেলি ফেরোসায়ানিকাম',
    'Aconitum Ferox': 'অ্যাকোনাইটাম ফেরক্স',
    'Stellaria Media': 'স্টেলেরিয়া মিডিয়া',
    'Kali Aceticum': 'কেলি অ্যাসিটিকাম',
    'Cereus Bonplandii': 'সেরিয়াস বনপ্লান্ডাই',
    'Arsenicum Sulphuratum Rubrum': 'আর্সেনিকাম সালফিউরেটাম রুব্রাম',
    'Antimonium Oxydatum': 'অ্যান্টিমোনিয়াম অক্সিডেটাম',
    'Natrum Aceticum': 'নেট্রাম অ্যাসিটিকাম',
    'Guarana': 'গুয়ারানা',
    'Serpentaria': 'সার্পেন্টেরিয়া',
    'Mercurius Nitrosus': 'মার্কিউরিয়াস নাইট্রোসাস',
    'Ferrum Picricum': 'ফেরাম পিক্রিকাম',
    'Coccinella Septempunctata': 'ককসিনেলা সেপ্টেমপাংক্টাটা',
    'Bartfelder (acid spring)': 'বার্টফেল্ডার (অম্ল জলের ঝর্না)',
    'Oxytropis Lamberti': 'অক্সিট্রপিস ল্যাম্বার্টি',
    'Ferrum Sulphuricum': 'ফেরাম সালফিউরিকাম',
    'Chenopodium Glauci Aphis': 'কিনোপোডিয়াম গ্লসাই অ্যাফিস',
    'Cypripedium Pubescens': 'সিপ্রিপিডিয়াম পিউবেসেন্স',
    'Blatta Orientalis': 'ব্ল্যাটা ওরিয়েন্টালিস',
    'Argentum Muriaticum': 'আর্জেন্টাম মিউরিয়েটিকাম',
    'Wiesbaden': 'ভিসবাডেন',
    'Juncus Effusus': 'জাঙ্কাস এফিউসাস',
    'Gallicum Acidum': 'গ্যালিকাম অ্যাসিডাম',
    'Calotropis Gigantea': 'ক্যালোট্রপিস জাইগ্যানসিয়া',
    'Alstonia Constricta': 'অ্যালস্টোনিয়া কনস্ট্রিক্টা',
    'Myristica Sebifera': 'মিরিস্টিকা সেবিফেরা',
    'Lobelia Cardinalis': 'লোবেলিয়া কার্ডিনালিস',
    'Kaolin': 'কেওলিন',
    'Coriaria Ruscifolia': 'কোরিয়ারিয়া রাসকিফোলিয়া',
    'Coffea Tosta': 'কফিয়া টোস্টা',
    'Cundurango': 'কুন্ডুরাঙ্গো',
}
