# -*- coding: utf-8 -*-
"""Remedy roster.  key -> (Latin name, Bangla name, family/source, thermal, miasm)
   thermal: chilly | hot | mixed | ''      (blank = not confidently known)
   Only genuine homoeopathic remedies. Nothing invented.
"""

R = {
 # ---------------- polychrests & common remedies ----------------
 'acon':   ('Aconitum Napellus', 'অ্যাকোনাইট ন্যাপেলাস', 'Ranunculaceae', 'hot', 'Acute'),
 'aeth':   ('Aethusa Cynapium', 'ইথুসা সাইনাপিয়াম', 'Umbelliferae', 'chilly', ''),
 'agar':   ('Agaricus Muscarius', 'অ্যাগারিকাস মাসকেরিয়াস', 'Fungi', 'chilly', ''),
 'all-c':  ('Allium Cepa', 'অ্যালিয়াম সিপা', 'Liliaceae', 'hot', ''),
 'aloe':   ('Aloe Socotrina', 'অ্যালো সোকোট্রিনা', 'Liliaceae', 'hot', ''),
 'alum':   ('Alumina', 'অ্যালুমিনা', 'Mineral', 'chilly', 'Syphilitic'),
 'am-c':   ('Ammonium Carbonicum', 'অ্যামোনিয়াম কার্বনিকাম', 'Mineral', 'chilly', ''),
 'ambr':   ('Ambra Grisea', 'অ্যাম্ব্রা গ্রিসিয়া', 'Animal', 'chilly', ''),
 'anac':   ('Anacardium Orientale', 'অ্যানাকার্ডিয়াম ওরিয়েন্টেল', 'Anacardiaceae', 'chilly', ''),
 'ant-c':  ('Antimonium Crudum', 'অ্যান্টিমোনিয়াম ক্রুডাম', 'Mineral', 'chilly', ''),
 'ant-t':  ('Antimonium Tartaricum', 'অ্যান্টিমোনিয়াম টার্টারিকাম', 'Mineral', 'chilly', 'Tubercular'),
 'apis':   ('Apis Mellifica', 'এপিস মেলিফিকা', 'Insecta', 'hot', ''),
 'arg-n':  ('Argentum Nitricum', 'আর্জেন্টাম নাইট্রিকাম', 'Mineral', 'hot', 'Syphilitic'),
 'arn':    ('Arnica Montana', 'আর্নিকা মন্টানা', 'Compositae', 'chilly', ''),
 'ars':    ('Arsenicum Album', 'আর্সেনিকাম অ্যালবাম', 'Mineral', 'chilly', 'Syphilitic'),
 'ars-i':  ('Arsenicum Iodatum', 'আর্সেনিকাম আয়োডেটাম', 'Mineral', 'hot', 'Tubercular'),
 'asaf':   ('Asafoetida', 'অ্যাসাফিটিডা', 'Umbelliferae', 'chilly', ''),
 'aur':    ('Aurum Metallicum', 'অরাম মেটালিকাম', 'Mineral', 'chilly', 'Syphilitic'),
 'bapt':   ('Baptisia Tinctoria', 'ব্যাপ্টিশিয়া টিংক্টোরিয়া', 'Leguminosae', 'hot', ''),
 'bar-c':  ('Baryta Carbonica', 'ব্যারাইটা কার্বনিকা', 'Mineral', 'chilly', 'Scrofulous'),
 'bell':   ('Belladonna', 'বেলাডোনা', 'Solanaceae', 'hot', 'Acute'),
 'bell-p': ('Bellis Perennis', 'বেলিস পেরেনিস', 'Compositae', '', ''),
 'benz-ac':('Benzoicum Acidum', 'বেঞ্জোয়িকাম অ্যাসিডাম', 'Acid', 'chilly', ''),
 'berb':   ('Berberis Vulgaris', 'বার্বেরিস ভালগারিস', 'Berberidaceae', '', ''),
 'bism':   ('Bismuthum', 'বিসমাথাম', 'Mineral', '', ''),
 'borx':   ('Borax', 'বোরাক্স', 'Mineral', 'chilly', ''),
 'both':   ('Bothrops Lanceolatus', 'বোথ্রপস ল্যান্সিওলেটাস', 'Serpentes', '', ''),
 'bov':    ('Bovista Lycoperdon', 'বোভিস্টা লাইকোপার্ডন', 'Fungi', '', ''),
 'brom':   ('Bromium', 'ব্রোমিয়াম', 'Mineral', 'hot', ''),
 'bry':    ('Bryonia Alba', 'ব্রায়োনিয়া অ্যালবা', 'Cucurbitaceae', 'hot', ''),
 'bufo':   ('Bufo Rana', 'বুফো রানা', 'Amphibia', '', ''),
 'cact':   ('Cactus Grandiflorus', 'ক্যাক্টাস গ্র্যান্ডিফ্লোরাস', 'Cactaceae', '', ''),
 'calad':  ('Caladium Seguinum', 'ক্যালেডিয়াম সেগুইনাম', 'Araceae', '', ''),
 'calc':   ('Calcarea Carbonica', 'ক্যালকেরিয়া কার্বনিকা', 'Mineral', 'chilly', 'Psoric'),
 'calc-f': ('Calcarea Fluorica', 'ক্যালকেরিয়া ফ্লুরিকা', 'Mineral', 'chilly', 'Syphilitic'),
 'calc-p': ('Calcarea Phosphorica', 'ক্যালকেরিয়া ফসফরিকা', 'Mineral', 'chilly', 'Tubercular'),
 'calc-s': ('Calcarea Sulphurica', 'ক্যালকেরিয়া সালফিউরিকা', 'Mineral', 'hot', ''),
 'camph':  ('Camphora', 'ক্যাম্ফোরা', 'Lauraceae', 'chilly', ''),
 'canth':  ('Cantharis Vesicatoria', 'ক্যান্থারিস ভেসিকেটোরিয়া', 'Insecta', '', ''),
 'caps':   ('Capsicum Annuum', 'ক্যাপসিকাম অ্যানুয়াম', 'Solanaceae', 'chilly', ''),
 'carb-an':('Carbo Animalis', 'কার্বো অ্যানিমেলিস', 'Carbon', 'chilly', ''),
 'carb-v': ('Carbo Vegetabilis', 'কার্বো ভেজিটেবিলিস', 'Carbon', 'chilly', ''),
 'carc':   ('Carcinosinum', 'কার্সিনোসিনাম', 'Nosode', 'mixed', 'Cancer'),
 'caul':   ('Caulophyllum Thalictroides', 'কলোফাইলাম থ্যালিকট্রয়ডিস', 'Berberidaceae', '', ''),
 'caust':  ('Causticum', 'কষ্টিকাম', 'Mineral', 'chilly', 'Psoric'),
 'cham':   ('Chamomilla', 'ক্যামোমিলা', 'Compositae', 'hot', ''),
 'chel':   ('Chelidonium Majus', 'চেলিডোনিয়াম মেজাস', 'Papaveraceae', 'chilly', ''),
 'chin':   ('China Officinalis', 'চায়না অফিসিনালিস', 'Rubiaceae', 'chilly', ''),
 'cic':    ('Cicuta Virosa', 'সিকুটা ভিরোসা', 'Umbelliferae', '', ''),
 'cimic':  ('Cimicifuga Racemosa', 'সিমিসিফিউগা রেসিমোসা', 'Ranunculaceae', 'chilly', ''),
 'cina':   ('Cina Maritima', 'সিনা ম্যারিটিমা', 'Compositae', 'chilly', ''),
 'cocc':   ('Cocculus Indicus', 'কক্কুলাস ইন্ডিকাস', 'Menispermaceae', 'chilly', ''),
 'coff':   ('Coffea Cruda', 'কফিয়া ক্রুডা', 'Rubiaceae', 'hot', ''),
 'colch':  ('Colchicum Autumnale', 'কলচিকাম অটামনেল', 'Liliaceae', 'chilly', ''),
 'coloc':  ('Colocynthis', 'কলোসিন্থিস', 'Cucurbitaceae', 'chilly', ''),
 'con':    ('Conium Maculatum', 'কোনিয়াম ম্যাকুলেটাম', 'Umbelliferae', 'chilly', 'Cancer'),
 'croc':   ('Crocus Sativus', 'ক্রোকাস স্যাটিভাস', 'Iridaceae', '', ''),
 'crot-h': ('Crotalus Horridus', 'ক্রোটেলাস হরিডাস', 'Serpentes', 'hot', ''),
 'cupr':   ('Cuprum Metallicum', 'কুপ্রাম মেটালিকাম', 'Mineral', 'chilly', ''),
 'cycl':   ('Cyclamen Europaeum', 'সাইক্লামেন ইউরোপিয়াম', 'Primulaceae', 'chilly', ''),
 'dig':    ('Digitalis Purpurea', 'ডিজিটালিস পারপিউরিয়া', 'Scrophulariaceae', '', ''),
 'dros':   ('Drosera Rotundifolia', 'ড্রসেরা রোটান্ডিফোলিয়া', 'Droseraceae', '', 'Tubercular'),
 'dulc':   ('Dulcamara', 'ডালকামারা', 'Solanaceae', 'chilly', ''),
 'eup-per':('Eupatorium Perfoliatum', 'ইউপেটোরিয়াম পারফোলিয়েটাম', 'Compositae', 'chilly', ''),
 'euphr':  ('Euphrasia Officinalis', 'ইউফ্রেশিয়া অফিসিনালিস', 'Scrophulariaceae', '', ''),
 'ferr':   ('Ferrum Metallicum', 'ফেরাম মেটালিকাম', 'Mineral', 'chilly', ''),
 'ferr-p': ('Ferrum Phosphoricum', 'ফেরাম ফসফরিকাম', 'Mineral', 'mixed', ''),
 'fl-ac':  ('Fluoricum Acidum', 'ফ্লুরিকাম অ্যাসিডাম', 'Acid', 'hot', 'Syphilitic'),
 'gels':   ('Gelsemium Sempervirens', 'জেলসেমিয়াম সেম্পারভাইরেন্স', 'Loganiaceae', 'chilly', ''),
 'glon':   ('Glonoinum', 'গ্লোনোইনাম', 'Mineral', 'hot', ''),
 'graph':  ('Graphites', 'গ্রাফাইটিস', 'Carbon', 'chilly', 'Psoric'),
 'ham':    ('Hamamelis Virginiana', 'হ্যামামেলিস ভার্জিনিয়ানা', 'Hamamelidaceae', '', ''),
 'hell':   ('Helleborus Niger', 'হেলেবোরাস নাইজার', 'Ranunculaceae', '', ''),
 'hep':    ('Hepar Sulphuris Calcareum', 'হিপার সালফার', 'Mineral', 'chilly', 'Psoric'),
 'hyos':   ('Hyoscyamus Niger', 'হায়োসায়ামাস নাইজার', 'Solanaceae', 'hot', ''),
 'hyper':  ('Hypericum Perforatum', 'হাইপেরিকাম পারফোরেটাম', 'Hypericaceae', 'chilly', ''),
 'ign':    ('Ignatia Amara', 'ইগ্নেশিয়া আমারা', 'Loganiaceae', 'chilly', ''),
 'iod':    ('Iodum', 'আয়োডাম', 'Mineral', 'hot', 'Tubercular'),
 'ip':     ('Ipecacuanha', 'ইপিকাক', 'Rubiaceae', 'mixed', ''),
 'kali-ar':('Kali Arsenicosum', 'কেলি আর্সেনিকোসাম', 'Mineral', 'chilly', ''),
 'kali-bi':('Kali Bichromicum', 'কেলি বাইক্রোমিকাম', 'Mineral', 'chilly', 'Syphilitic'),
 'kali-br':('Kali Bromatum', 'কেলি ব্রোমেটাম', 'Mineral', '', ''),
 'kali-c': ('Kali Carbonicum', 'কেলি কার্বনিকাম', 'Mineral', 'chilly', 'Tubercular'),
 'kali-p': ('Kali Phosphoricum', 'কেলি ফসফরিকাম', 'Mineral', 'chilly', ''),
 'kali-s': ('Kali Sulphuricum', 'কেলি সালফিউরিকাম', 'Mineral', 'hot', ''),
 'kreos':  ('Kreosotum', 'ক্রিয়োসোটাম', 'Distillate', 'chilly', 'Cancer'),
 'lach':   ('Lachesis Muta', 'ল্যাকেসিস মিউটা', 'Serpentes', 'hot', 'Syphilitic'),
 'lac-c':  ('Lac Caninum', 'ল্যাক ক্যানাইনাম', 'Milk', 'chilly', ''),
 'laur':   ('Laurocerasus', 'লরোসেরাসাস', 'Rosaceae', '', ''),
 'led':    ('Ledum Palustre', 'লেডাম প্যালাস্ট্রে', 'Ericaceae', 'chilly', ''),
 'lil-t':  ('Lilium Tigrinum', 'লিলিয়াম টাইগ্রিনাম', 'Liliaceae', 'hot', ''),
 'lyc':    ('Lycopodium Clavatum', 'লাইকোপোডিয়াম ক্লাভেটাম', 'Lycopodiaceae', 'chilly', 'Psoric'),
 'mag-c':  ('Magnesia Carbonica', 'ম্যাগ্নেশিয়া কার্বনিকা', 'Mineral', 'chilly', ''),
 'mag-p':  ('Magnesia Phosphorica', 'ম্যাগ্নেশিয়া ফসফরিকা', 'Mineral', 'chilly', ''),
 'med':    ('Medorrhinum', 'মেডোরিনাম', 'Nosode', 'hot', 'Sycotic'),
 'merc':   ('Mercurius Solubilis', 'মার্কিউরিয়াস সলুবিলিস', 'Mineral', 'mixed', 'Syphilitic'),
 'merc-c': ('Mercurius Corrosivus', 'মার্কিউরিয়াস করোসিভাস', 'Mineral', 'mixed', 'Syphilitic'),
 'mez':    ('Mezereum', 'মেজেরিয়াম', 'Thymelaeaceae', 'chilly', 'Syphilitic'),
 'mosch':  ('Moschus', 'মস্কাস', 'Animal', 'chilly', ''),
 'mur-ac': ('Muriaticum Acidum', 'মিউরিয়াটিকাম অ্যাসিডাম', 'Acid', '', ''),
 'murx':   ('Murex Purpurea', 'মিউরেক্স পারপিউরিয়া', 'Mollusca', '', ''),
 'nat-c':  ('Natrum Carbonicum', 'নেট্রাম কার্বনিকাম', 'Mineral', 'chilly', ''),
 'nat-m':  ('Natrum Muriaticum', 'নেট্রাম মিউরিয়েটিকাম', 'Mineral', 'hot', 'Psoric'),
 'nat-p':  ('Natrum Phosphoricum', 'নেট্রাম ফসফরিকাম', 'Mineral', '', ''),
 'nat-s':  ('Natrum Sulphuricum', 'নেট্রাম সালফিউরিকাম', 'Mineral', 'hot', 'Sycotic'),
 'nit-ac': ('Nitricum Acidum', 'নাইট্রিকাম অ্যাসিডাম', 'Acid', 'chilly', 'Syphilitic'),
 'nux-m':  ('Nux Moschata', 'নাক্স মসকেটা', 'Myristicaceae', 'chilly', ''),
 'nux-v':  ('Nux Vomica', 'নাক্স ভমিকা', 'Loganiaceae', 'chilly', 'Psoric'),
 'op':     ('Opium', 'ওপিয়াম', 'Papaveraceae', 'hot', ''),
 'petr':   ('Petroleum', 'পেট্রোলিয়াম', 'Mineral', 'chilly', 'Psoric'),
 'ph-ac':  ('Phosphoricum Acidum', 'ফসফরিকাম অ্যাসিডাম', 'Acid', 'chilly', ''),
 'phos':   ('Phosphorus', 'ফসফরাস', 'Mineral', 'chilly', 'Tubercular'),
 'phyt':   ('Phytolacca Decandra', 'ফাইটোল্যাকা ডেকান্ড্রা', 'Phytolaccaceae', 'chilly', ''),
 'plat':   ('Platinum Metallicum', 'প্ল্যাটিনাম মেটালিকাম', 'Mineral', 'hot', ''),
 'plb':    ('Plumbum Metallicum', 'প্লাম্বাম মেটালিকাম', 'Mineral', 'chilly', ''),
 'podo':   ('Podophyllum Peltatum', 'পোডোফাইলাম পেলটেটাম', 'Berberidaceae', 'hot', ''),
 'psor':   ('Psorinum', 'সোরিনাম', 'Nosode', 'chilly', 'Psoric'),
 'puls':   ('Pulsatilla Nigricans', 'পালসেটিলা নাইগ্রিকান্স', 'Ranunculaceae', 'hot', ''),
 'pyrog':  ('Pyrogenium', 'পাইরোজেনিয়াম', 'Nosode', 'chilly', ''),
 'ran-b':  ('Ranunculus Bulbosus', 'র‍্যানানকুলাস বালবোসাস', 'Ranunculaceae', '', ''),
 'rat':    ('Ratanhia', 'র‍্যাটানহিয়া', 'Krameriaceae', '', ''),
 'rhod':   ('Rhododendron', 'রোডোডেনড্রন', 'Ericaceae', 'chilly', ''),
 'rhus-t': ('Rhus Toxicodendron', 'রাস টক্সিকোডেনড্রন', 'Anacardiaceae', 'chilly', ''),
 'rumx':   ('Rumex Crispus', 'রুমেক্স ক্রিসপাস', 'Polygonaceae', 'chilly', ''),
 'ruta':   ('Ruta Graveolens', 'রুটা গ্রেভিওলেন্স', 'Rutaceae', 'chilly', ''),
 'sabad':  ('Sabadilla', 'সাবাডিলা', 'Liliaceae', 'chilly', ''),
 'sabin':  ('Sabina', 'সাবিনা', 'Coniferae', 'hot', ''),
 'samb':   ('Sambucus Nigra', 'স্যাম্বুকাস নাইগ্রা', 'Caprifoliaceae', '', ''),
 'sang':   ('Sanguinaria Canadensis', 'স্যাঙ্গুইনেরিয়া ক্যানাডেনসিস', 'Papaveraceae', 'hot', ''),
 'sanic':  ('Sanicula Aqua', 'স্যানিকুলা অ্যাকোয়া', 'Water', 'chilly', 'Tubercular'),
 'sars':   ('Sarsaparilla', 'সার্সাপারিলা', 'Liliaceae', 'chilly', ''),
 'sec':    ('Secale Cornutum', 'সিকেলি কর্নুটাম', 'Fungi', 'hot', ''),
 'sel':    ('Selenium Metallicum', 'সেলেনিয়াম মেটালিকাম', 'Mineral', 'hot', ''),
 'sep':    ('Sepia Officinalis', 'সিপিয়া অফিসিনালিস', 'Mollusca', 'chilly', 'Psoric'),
 'sil':    ('Silicea Terra', 'সিলিসিয়া টেরা', 'Mineral', 'chilly', 'Scrofulous'),
 'spig':   ('Spigelia Anthelmia', 'স্পাইজেলিয়া অ্যান্থেলমিয়া', 'Loganiaceae', 'chilly', ''),
 'spong':  ('Spongia Tosta', 'স্পঞ্জিয়া টোস্টা', 'Porifera', 'chilly', ''),
 'squil':  ('Squilla Maritima', 'স্কুইলা ম্যারিটিমা', 'Liliaceae', '', ''),
 'stann':  ('Stannum Metallicum', 'স্ট্যানাম মেটালিকাম', 'Mineral', 'chilly', ''),
 'staph':  ('Staphysagria', 'স্ট্যাফিসেগ্রিয়া', 'Ranunculaceae', 'chilly', ''),
 'stram':  ('Stramonium', 'স্ট্র্যামোনিয়াম', 'Solanaceae', 'hot', ''),
 'sul-ac': ('Sulphuricum Acidum', 'সালফিউরিকাম অ্যাসিডাম', 'Acid', 'chilly', ''),
 'sulph':  ('Sulphur', 'সালফার', 'Mineral', 'hot', 'Psoric'),
 'syph':   ('Syphilinum', 'সিফিলিনাম', 'Nosode', 'chilly', 'Syphilitic'),
 'tab':    ('Tabacum', 'ট্যাবাকাম', 'Solanaceae', 'chilly', ''),
 'tarent': ('Tarentula Hispanica', 'ট্যারেন্টুলা হিসপানিকা', 'Arachnida', 'hot', ''),
 'ter':    ('Terebinthina', 'টেরিবিন্থিনা', 'Coniferae', '', ''),
 'thuj':   ('Thuja Occidentalis', 'থুজা অক্সিডেন্টালিস', 'Coniferae', 'chilly', 'Sycotic'),
 'tub':    ('Tuberculinum Bovinum', 'টিউবারকুলিনাম বোভিনাম', 'Nosode', 'chilly', 'Tubercular'),
 'urt-u':  ('Urtica Urens', 'আর্টিকা ইউরেন্স', 'Urticaceae', '', ''),
 'valer':  ('Valeriana Officinalis', 'ভ্যালেরিয়ানা অফিসিনালিস', 'Valerianaceae', 'hot', ''),
 'verat':  ('Veratrum Album', 'ভেরাট্রাম অ্যালবাম', 'Liliaceae', 'chilly', ''),
 'verb':   ('Verbascum Thapsus', 'ভার্বাস্কাম থ্যাপসাস', 'Scrophulariaceae', '', ''),
 'viol-t': ('Viola Tricolor', 'ভায়োলা ট্রাইকলর', 'Violaceae', '', ''),
 'zinc':   ('Zincum Metallicum', 'জিঙ্কাম মেটালিকাম', 'Mineral', 'chilly', ''),
 # ---------------- further genuine remedies (roster completion) ----------------
 'abrot':  ('Abrotanum', 'অ্যাব্রোটেনাম', 'Compositae', 'chilly', 'Tubercular'),
 'absin':  ('Absinthium', 'অ্যাবসিন্থিয়াম', 'Compositae', '', ''),
 'acal':   ('Acalypha Indica', 'অ্যাকালিফা ইন্ডিকা', 'Euphorbiaceae', '', ''),
 'adon':   ('Adonis Vernalis', 'অ্যাডোনিস ভার্নালিস', 'Ranunculaceae', '', ''),
 'aesc':   ('Aesculus Hippocastanum', 'ইস্কুলাস হিপোক্যাস্টেনাম', 'Sapindaceae', '', ''),
 'agn':    ('Agnus Castus', 'অ্যাগনাস ক্যাস্টাস', 'Verbenaceae', '', ''),
 'ail':    ('Ailanthus Glandulosa', 'আইলান্থাস গ্ল্যান্ডুলোসা', 'Simaroubaceae', '', ''),
 'alet':   ('Aletris Farinosa', 'অ্যালেট্রিস ফ্যারিনোসা', 'Liliaceae', '', ''),
 'aml-ns': ('Amylenum Nitrosum', 'অ্যামাইলেনাম নাইট্রোসাম', 'Chemical', 'hot', ''),
 'anthr':  ('Anthracinum', 'অ্যানথ্রাসিনাম', 'Nosode', '', ''),
 'aran':   ('Aranea Diadema', 'অ্যারেনিয়া ডায়াডেমা', 'Arachnida', 'chilly', ''),
 'arg-m':  ('Argentum Metallicum', 'আর্জেন্টাম মেটালিকাম', 'Mineral', '', ''),
 'arum-t': ('Arum Triphyllum', 'অ্যারাম ট্রাইফাইলাম', 'Araceae', '', ''),
 'asar':   ('Asarum Europaeum', 'অ্যাসারাম ইউরোপিয়াম', 'Aristolochiaceae', '', ''),
 'astac':  ('Astacus Fluviatilis', 'অ্যাস্টেকাস ফ্লুভিয়াটিলিস', 'Crustacea', '', ''),
 'aster':  ('Asterias Rubens', 'অ্যাস্টেরিয়াস রুবেন্স', 'Echinodermata', '', 'Cancer'),
 'aur-m':  ('Aurum Muriaticum', 'অরাম মিউরিয়েটিকাম', 'Mineral', '', ''),
 'bad':    ('Badiaga', 'ব্যাডিয়াগা', 'Porifera', '', ''),
 'bapt-c': ('Baptisia Confusa', 'ব্যাপ্টিশিয়া কনফিউসা', 'Leguminosae', '', ''),
 'bar-m':  ('Baryta Muriatica', 'ব্যারাইটা মিউরিয়েটিকা', 'Mineral', '', ''),
 'bell-d': ('Belladonna Digitalis', 'বেলাডোনা ডিজিটালিস', 'Combination', '', ''),
 'benz':   ('Benzinum', 'বেঞ্জিনাম', 'Chemical', '', ''),
 'bor-ac': ('Boricum Acidum', 'বোরিকাম অ্যাসিডাম', 'Acid', '', ''),
 'calc-ar':('Calcarea Arsenicosa', 'ক্যালকেরিয়া আর্সেনিকোসা', 'Mineral', 'chilly', ''),
 'calc-i': ('Calcarea Iodata', 'ক্যালকেরিয়া আয়োডেটা', 'Mineral', '', ''),
 'calc-si':('Calcarea Silicata', 'ক্যালকেরিয়া সিলিকেটা', 'Mineral', 'chilly', ''),
 'cann-i': ('Cannabis Indica', 'ক্যানাবিস ইন্ডিকা', 'Cannabaceae', '', ''),
 'cann-s': ('Cannabis Sativa', 'ক্যানাবিস স্যাটিভা', 'Cannabaceae', '', ''),
 'carb-ac':('Carbolicum Acidum', 'কার্বলিকাম অ্যাসিডাম', 'Acid', '', ''),
 'card-m': ('Carduus Marianus', 'কার্ডুয়াস ম্যারিয়েনাস', 'Compositae', '', ''),
 'cast':   ('Castoreum', 'ক্যাস্টোরিয়াম', 'Animal', '', ''),
 'caust-s':('Causticum Sulphuricum', 'কষ্টিকাম সালফিউরিকাম', 'Mineral', '', ''),
 'cean':   ('Ceanothus Americanus', 'সিনোথাস আমেরিকেনাস', 'Rhamnaceae', '', ''),
 'cedr':   ('Cedron', 'সেড্রন', 'Simaroubaceae', '', ''),
 'cham-v': ('Chamomilla Vulgaris', 'ক্যামোমিলা ভালগারিস', 'Compositae', '', ''),
 'chin-ar':('China Arsenicosa', 'চায়না আর্সেনিকোসা', 'Combination', '', ''),
 'chin-s': ('Chininum Sulphuricum', 'কুইনিনাম সালফিউরিকাম', 'Alkaloid', '', ''),
 'chlor':  ('Chloralum', 'ক্লোরালাম', 'Chemical', '', ''),
 'chr-ac': ('Chromicum Acidum', 'ক্রোমিকাম অ্যাসিডাম', 'Acid', '', ''),
 'cina-m': ('Cinnabaris', 'সিনাবারিস', 'Mineral', '', 'Syphilitic'),
 'cinnam': ('Cinnamomum', 'সিনামোমাম', 'Lauraceae', '', ''),
 'cist':   ('Cistus Canadensis', 'সিস্টাস ক্যানাডেনসিস', 'Cistaceae', 'chilly', 'Scrofulous'),
 'clem':   ('Clematis Erecta', 'ক্লেমাটিস ইরেক্টা', 'Ranunculaceae', '', ''),
 'cob':    ('Cobaltum Metallicum', 'কোবাল্টাম মেটালিকাম', 'Mineral', '', ''),
 'coca':   ('Coca', 'কোকা', 'Erythroxylaceae', '', ''),
 'colchi': ('Colchicinum', 'কলচিসিনাম', 'Alkaloid', '', ''),
 'coll':   ('Collinsonia Canadensis', 'কলিনসোনিয়া ক্যানাডেনসিস', 'Lamiaceae', '', ''),
 'com':    ('Comocladia Dentata', 'কোমোক্ল্যাডিয়া ডেনটাটা', 'Anacardiaceae', '', ''),
 'convo':  ('Convolvulus Duartinus', 'কনভলভুলাস', 'Convolvulaceae', '', ''),
 'cop':    ('Copaiva Officinalis', 'কোপাইভা অফিসিনালিস', 'Leguminosae', '', ''),
 'coral':  ('Corallium Rubrum', 'কোরালিয়াম রুব্রাম', 'Anthozoa', '', ''),
 'corn':   ('Cornus Circinata', 'কর্নাস সার্সিনাটা', 'Cornaceae', '', ''),
 'crat':   ('Crataegus Oxyacantha', 'ক্রেটেগাস অক্সিয়াকান্থা', 'Rosaceae', '', ''),
 'crot-c': ('Crotalus Cascavella', 'ক্রোটেলাস ক্যাসকাভেলা', 'Serpentes', '', ''),
 'crot-t': ('Croton Tiglium', 'ক্রোটন টিগ্লিয়াম', 'Euphorbiaceae', '', ''),
 'cub':    ('Cubeba Officinalis', 'কিউবেবা অফিসিনালিস', 'Piperaceae', '', ''),
 'cund':   ('Cundurango', 'কুন্ডুরাঙ্গো', 'Asclepiadaceae', '', 'Cancer'),
 'cupr-ar':('Cuprum Arsenicosum', 'কুপ্রাম আর্সেনিকোসাম', 'Mineral', '', ''),
 'cur':    ('Curare', 'কিউরারে', 'Plant poison', '', ''),
 'daph':   ('Daphne Indica', 'ড্যাফনি ইন্ডিকা', 'Thymelaeaceae', '', ''),
 'dios':   ('Dioscorea Villosa', 'ডায়োস্কোরিয়া ভিলোসা', 'Dioscoreaceae', '', ''),
 'dros-r': ('Drosera Ramentacea', 'ড্রসেরা র‍্যামেন্টেসিয়া', 'Droseraceae', '', ''),
 'elaps':  ('Elaps Corallinus', 'ইল্যাপস কোরালিনাস', 'Serpentes', 'chilly', ''),
 'equis':  ('Equisetum Hyemale', 'ইকুইজেটাম হাইমেল', 'Equisetaceae', '', ''),
 'erig':   ('Erigeron Canadensis', 'ইরিজেরন ক্যানাডেনসিস', 'Compositae', '', ''),
 'eup-pur':('Eupatorium Purpureum', 'ইউপেটোরিয়াম পারপিউরিয়াম', 'Compositae', '', ''),
 'euph':   ('Euphorbium Officinarum', 'ইউফরবিয়াম', 'Euphorbiaceae', '', ''),
 'eupi':   ('Eupionum', 'ইউপায়োনাম', 'Distillate', '', ''),
 'fago':   ('Fagopyrum Esculentum', 'ফ্যাগোপাইরাম', 'Polygonaceae', '', ''),
 'ferr-ar':('Ferrum Arsenicosum', 'ফেরাম আর্সেনিকোসাম', 'Mineral', '', ''),
 'ferr-i': ('Ferrum Iodatum', 'ফেরাম আয়োডেটাম', 'Mineral', 'hot', ''),
 'fic':    ('Ficus Religiosa', 'ফাইকাস রেলিজিওসা', 'Moraceae', '', ''),
 'form':   ('Formica Rufa', 'ফরমিকা রুফা', 'Insecta', '', ''),
 'gamb':   ('Gambogia', 'গ্যাম্বোজিয়া', 'Clusiaceae', '', ''),
 'gink':   ('Ginkgo Biloba', 'জিঙ্কো বিলোবা', 'Ginkgoaceae', '', ''),
 'gnaph':  ('Gnaphalium Polycephalum', 'ন্যাফালিয়াম', 'Compositae', '', ''),
 'gran':   ('Granatum', 'গ্রানেটাম', 'Punicaceae', '', ''),
 'grat':   ('Gratiola Officinalis', 'গ্র্যাশিওলা অফিসিনালিস', 'Scrophulariaceae', '', ''),
 'guai':   ('Guaiacum Officinale', 'গুয়াইকাম অফিসিনেল', 'Zygophyllaceae', 'hot', ''),
 'gymn':   ('Gymnema Sylvestre', 'জিমনেমা সিলভেস্ট্রে', 'Apocynaceae', '', ''),
 'haem':   ('Haematoxylum Campechianum', 'হিমাটক্সাইলাম', 'Leguminosae', '', ''),
 'hecla':  ('Hecla Lava', 'হেকলা লাভা', 'Mineral', '', ''),
 'helon':  ('Helonias Dioica', 'হেলোনিয়াস ডায়োইকা', 'Liliaceae', '', ''),
 'hipp':   ('Hippozaeninum', 'হিপোজিনিনাম', 'Nosode', '', ''),
 'hist':   ('Histaminum Muriaticum', 'হিস্টামিনাম', 'Chemical', '', ''),
 'hura':   ('Hura Brasiliensis', 'হুরা ব্রাসিলিয়েনসিস', 'Euphorbiaceae', '', ''),
 'hydr':   ('Hydrastis Canadensis', 'হাইড্রাস্টিস ক্যানাডেনসিস', 'Ranunculaceae', '', 'Cancer'),
 'hydrc':  ('Hydrocotyle Asiatica', 'হাইড্রোকোটাইল এশিয়াটিকা', 'Umbelliferae', '', ''),
 'ictod':  ('Ictodes Foetida', 'ইক্টোডিস ফিটিডা', 'Araceae', '', ''),
 'ind':    ('Indigo Tinctoria', 'ইন্ডিগো টিংক্টোরিয়া', 'Leguminosae', '', ''),
 'iodof':  ('Iodoformum', 'আয়োডোফর্মাম', 'Chemical', '', ''),
 'ipom':   ('Ipomoea Purpurea', 'ইপোমিয়া', 'Convolvulaceae', '', ''),
 'iris':   ('Iris Versicolor', 'আইরিস ভার্সিকলর', 'Iridaceae', '', ''),
 'jab':    ('Jaborandi', 'জ্যাবোরান্ডি', 'Rutaceae', '', ''),
 'jal':    ('Jalapa', 'জালাপা', 'Convolvulaceae', '', ''),
 'jatr':   ('Jatropha Curcas', 'জ্যাট্রোফা কার্কাস', 'Euphorbiaceae', '', ''),
 'jugl-c': ('Juglans Cinerea', 'জুগ্ল্যান্স সিনেরিয়া', 'Juglandaceae', '', ''),
 'jun':    ('Juniperus Communis', 'জুনিপেরাস কমিউনিস', 'Coniferae', '', ''),
 'kali-bic':('Kali Bichromicum', 'কেলি বাইক্রোমিকাম', 'Mineral', 'chilly', ''),
 'kali-chl':('Kali Chloricum', 'কেলি ক্লোরিকাম', 'Mineral', '', ''),
 'kali-cy': ('Kali Cyanatum', 'কেলি সায়ানেটাম', 'Mineral', '', ''),
 'kali-i':  ('Kali Iodatum', 'কেলি আয়োডেটাম', 'Mineral', 'hot', 'Syphilitic'),
 'kali-m':  ('Kali Muriaticum', 'কেলি মিউরিয়েটিকাম', 'Mineral', '', ''),
 'kali-n':  ('Kali Nitricum', 'কেলি নাইট্রিকাম', 'Mineral', '', ''),
 'kalm':    ('Kalmia Latifolia', 'কালমিয়া ল্যাটিফোলিয়া', 'Ericaceae', '', ''),
 'lac-d':   ('Lac Defloratum', 'ল্যাক ডিফ্লোরেটাম', 'Milk', '', ''),
 'lact':    ('Lactuca Virosa', 'ল্যাকটুকা ভিরোসা', 'Compositae', '', ''),
 'lap-a':   ('Lapis Albus', 'ল্যাপিস অ্যালবাস', 'Mineral', '', 'Cancer'),
 'lath':    ('Lathyrus Sativus', 'ল্যাথাইরাস স্যাটিভাস', 'Leguminosae', '', ''),
 'lec':     ('Lecithinum', 'লেসিথিনাম', 'Animal', '', ''),
 'lem-m':   ('Lemna Minor', 'লেমনা মাইনর', 'Araceae', '', ''),
 'lept':    ('Leptandra Virginica', 'লেপ্টান্ড্রা ভার্জিনিকা', 'Scrophulariaceae', '', ''),
 'lil-alb': ('Lilium Album', 'লিলিয়াম অ্যালবাম', 'Liliaceae', '', ''),
 'lith-c':  ('Lithium Carbonicum', 'লিথিয়াম কার্বনিকাম', 'Mineral', '', ''),
 'lob':     ('Lobelia Inflata', 'লোবেলিয়া ইনফ্লাটা', 'Campanulaceae', '', ''),
 'lup':     ('Lupulus Humulus', 'লুপুলাস', 'Cannabaceae', '', ''),
 'lyss':    ('Lyssinum', 'লিসিনাম', 'Nosode', '', ''),
 'mag-m':   ('Magnesia Muriatica', 'ম্যাগ্নেশিয়া মিউরিয়েটিকা', 'Mineral', 'chilly', ''),
 'mag-s':   ('Magnesia Sulphurica', 'ম্যাগ্নেশিয়া সালফিউরিকা', 'Mineral', '', ''),
 'manc':    ('Mancinella', 'ম্যানসিনেলা', 'Euphorbiaceae', '', ''),
 'mang':    ('Manganum Aceticum', 'ম্যাঙ্গানাম অ্যাসেটিকাম', 'Mineral', 'chilly', ''),
 'meli':    ('Melilotus Officinalis', 'মেলিলোটাস', 'Leguminosae', '', ''),
 'meny':    ('Menyanthes Trifoliata', 'মেনিয়ানথিস', 'Menyanthaceae', '', ''),
 'meph':    ('Mephitis Putorius', 'মেফাইটিস', 'Animal', '', ''),
 'merc-d':  ('Mercurius Dulcis', 'মার্কিউরিয়াস ডালসিস', 'Mineral', '', ''),
 'merc-i-f':('Mercurius Iodatus Flavus', 'মার্কিউরিয়াস আয়োডেটাস ফ্লেভাস', 'Mineral', '', ''),
 'merc-i-r':('Mercurius Iodatus Ruber', 'মার্কিউরিয়াস আয়োডেটাস রুবার', 'Mineral', '', ''),
 'mill':    ('Millefolium', 'মিলিফোলিয়াম', 'Compositae', '', ''),
 'morg':    ('Morgan Bach', 'মরগান ব্যাক', 'Bowel nosode', '', ''),
 'myric':   ('Myrica Cerifera', 'মাইরিকা সেরিফেরা', 'Myricaceae', '', ''),
 'naja':    ('Naja Tripudians', 'নাজা ট্রাইপুডিয়ান্স', 'Serpentes', '', ''),
 'naphtin': ('Naphtalinum', 'ন্যাপথালিনাম', 'Chemical', '', ''),
 'nat-ar':  ('Natrum Arsenicosum', 'নেট্রাম আর্সেনিকোসাম', 'Mineral', '', ''),
 'nat-sil': ('Natrum Silicatum', 'নেট্রাম সিলিকেটাম', 'Mineral', '', ''),
 'niccol':  ('Niccolum Metallicum', 'নিকোলাম মেটালিকাম', 'Mineral', '', ''),
 'nuph':    ('Nuphar Luteum', 'নুফার লুটিয়াম', 'Nymphaeaceae', '', ''),
 'ocim':    ('Ocimum Canum', 'ওসিমাম ক্যানাম', 'Lamiaceae', '', ''),
 'oena':    ('Oenanthe Crocata', 'ইনান্থি ক্রোকাটা', 'Umbelliferae', '', ''),
 'olnd':    ('Oleander', 'ওলিয়েন্ডার', 'Apocynaceae', '', ''),
 'onos':    ('Onosmodium Virginianum', 'ওনোসমোডিয়াম', 'Boraginaceae', '', ''),
 'op-ac':   ('Oxalicum Acidum', 'অক্সালিকাম অ্যাসিডাম', 'Acid', '', ''),
 'orig':    ('Origanum Majorana', 'অরিগেনাম মেজোরানা', 'Lamiaceae', '', ''),
 'osm':     ('Osmium Metallicum', 'অসমিয়াম', 'Mineral', '', ''),
 'ova':     ('Ovi Gallinae Pellicula', 'ওভা টেস্টা', 'Animal', '', ''),
 'paeon':   ('Paeonia Officinalis', 'পিওনিয়া অফিসিনালিস', 'Paeoniaceae', '', ''),
 'palla':   ('Palladium Metallicum', 'প্যালাডিয়াম', 'Mineral', '', ''),
 'par':     ('Paris Quadrifolia', 'প্যারিস কোয়াড্রিফোলিয়া', 'Liliaceae', '', ''),
 'pareir':  ('Pareira Brava', 'পেরেইরা ব্রাভা', 'Menispermaceae', '', ''),
 'passi':   ('Passiflora Incarnata', 'প্যাসিফ্লোরা ইনকার্নাটা', 'Passifloraceae', '', ''),
 'penic':   ('Penicillinum', 'পেনিসিলিনাম', 'Nosode', '', ''),
 'phel':    ('Phellandrium Aquaticum', 'ফেলান্ড্রিয়াম', 'Umbelliferae', '', ''),
 'physal':  ('Physalis Alkekengi', 'ফাইসেলিস', 'Solanaceae', '', ''),
 'physos':  ('Physostigma Venenosum', 'ফাইসোস্টিগমা', 'Leguminosae', '', ''),
 'phyt-d':  ('Phytolacca Berry', 'ফাইটোল্যাকা বেরি', 'Phytolaccaceae', '', ''),
 'pic-ac':  ('Picricum Acidum', 'পিক্রিকাম অ্যাসিডাম', 'Acid', '', ''),
 'pilo':    ('Pilocarpinum', 'পাইলোকার্পিনাম', 'Alkaloid', '', ''),
 'pin-s':   ('Pinus Sylvestris', 'পাইনাস সিলভেস্ট্রিস', 'Coniferae', '', ''),
 'piper':   ('Piper Nigrum', 'পাইপার নাইগ্রাম', 'Piperaceae', '', ''),
 'plan':    ('Plantago Major', 'প্ল্যান্টেগো মেজর', 'Plantaginaceae', '', ''),
 'plat-m':  ('Platinum Muriaticum', 'প্ল্যাটিনাম মিউরিয়েটিকাম', 'Mineral', '', ''),
 'polyg':   ('Polygonum Punctatum', 'পলিগোনাম', 'Polygonaceae', '', ''),
 'pop':     ('Populus Tremuloides', 'পপুলাস ট্রেমুলয়ডিস', 'Salicaceae', '', ''),
 'primu':   ('Primula Obconica', 'প্রিমুলা অবকোনিকা', 'Primulaceae', '', ''),
 'prun':    ('Prunus Spinosa', 'প্রুনাস স্পাইনোসা', 'Rosaceae', '', ''),
 'ptel':    ('Ptelea Trifoliata', 'টেলিয়া ট্রাইফোলিয়াটা', 'Rutaceae', '', ''),
 'puls-n':  ('Pulsatilla Nuttalliana', 'পালসেটিলা নাটালিয়ানা', 'Ranunculaceae', '', ''),
 'quer':    ('Quercus Robur', 'কোয়ার্কাস', 'Fagaceae', '', ''),
 'radm':    ('Radium Bromatum', 'রেডিয়াম ব্রোমেটাম', 'Mineral', '', ''),
 'raph':    ('Raphanus Sativus', 'র‍্যাফানাস স্যাটিভাস', 'Brassicaceae', '', ''),
 'rheum':   ('Rheum Officinale', 'রিউম অফিসিনেল', 'Polygonaceae', '', ''),
 'rhus-g':  ('Rhus Glabra', 'রাস গ্ল্যাব্রা', 'Anacardiaceae', '', ''),
 'rob':     ('Robinia Pseudacacia', 'রবিনিয়া', 'Leguminosae', '', ''),
 'rosm':    ('Rosmarinus Officinalis', 'রোজমেরিনাস', 'Lamiaceae', '', ''),
 'rubi':    ('Rubia Tinctorum', 'রুবিয়া টিংক্টোরাম', 'Rubiaceae', '', ''),
 'sabal':   ('Sabal Serrulata', 'সাবাল সেরুলাটা', 'Palmae', '', ''),
 'senec':   ('Senecio Aureus', 'সেনেসিও অরিয়াস', 'Compositae', '', ''),
 'bacil':   ('Bacillinum', 'ব্যাসিলিনাম', 'Nosode', 'chilly', 'Tubercular'),
 'sac-alb': ('Saccharum Album', 'স্যাকারাম অ্যালবাম', 'Sugar', '', ''),
 'salv':    ('Salvia Officinalis', 'সালভিয়া অফিসিনালিস', 'Lamiaceae', '', ''),
 'sang-n':  ('Sanguinarinum Nitricum', 'স্যাঙ্গুইনেরিনাম নাইট্রিকাম', 'Alkaloid', '', ''),
 'santin':  ('Santoninum', 'স্যান্টোনিনাম', 'Chemical', '', ''),
 'saponin': ('Saponinum', 'স্যাপোনিনাম', 'Chemical', '', ''),
 'scroph':  ('Scrophularia Nodosa', 'স্ক্রোফুলারিয়া নোডোসা', 'Scrophulariaceae', '', 'Cancer'),
 'scut':    ('Scutellaria Lateriflora', 'স্কুটেলারিয়া', 'Lamiaceae', '', ''),
 'sen':     ('Senega Officinalis', 'সেনেগা অফিসিনালিস', 'Polygalaceae', '', ''),
 'senn':    ('Senna', 'সেনা', 'Leguminosae', '', ''),
 'ser-ang': ('Serum Anguillae', 'সেরাম অ্যাঙ্গুইলি', 'Animal', '', ''),
 'sil-m':   ('Silica Marina', 'সিলিকা মেরিনা', 'Mineral', '', ''),
 'sin-n':   ('Sinapis Nigra', 'সিনাপিস নাইগ্রা', 'Brassicaceae', '', ''),
 'sol-n':   ('Solanum Nigrum', 'সোলানাম নাইগ্রাম', 'Solanaceae', '', ''),
 'spirae':  ('Spiraea Ulmaria', 'স্পাইরিয়া', 'Rosaceae', '', ''),
 'stach':   ('Stachys Betonica', 'স্ট্যাকিস', 'Lamiaceae', '', ''),
 'stict':   ('Sticta Pulmonaria', 'স্টিক্টা পালমোনারিয়া', 'Lichenes', '', ''),
 'stroph':  ('Strophanthus Hispidus', 'স্ট্রোফ্যান্থাস', 'Apocynaceae', '', ''),
 'stront-c':('Strontium Carbonicum', 'স্ট্রনশিয়াম কার্বনিকাম', 'Mineral', 'chilly', ''),
 'stry':    ('Strychninum', 'স্ট্রিকনিনাম', 'Alkaloid', '', ''),
 'sumb':    ('Sumbulus Moschatus', 'সুম্বুলাস', 'Umbelliferae', '', ''),
 'symph':   ('Symphytum Officinale', 'সিম্ফাইটাম অফিসিনেল', 'Boraginaceae', '', ''),
 'syzyg':   ('Syzygium Jambolanum', 'সিজিজিয়াম জাম্বোলানাম', 'Myrtaceae', '', ''),
 'tanac':   ('Tanacetum Vulgare', 'ট্যানাসেটাম', 'Compositae', '', ''),
 'tarax':   ('Taraxacum Officinale', 'ট্যারাক্সেকাম', 'Compositae', '', ''),
 'tarent-c':('Tarentula Cubensis', 'ট্যারেন্টুলা কিউবেনসিস', 'Arachnida', '', ''),
 'tell':    ('Tellurium Metallicum', 'টেলুরিয়াম', 'Mineral', '', ''),
 'teucr':   ('Teucrium Marum Verum', 'টিউক্রিয়াম মেরাম', 'Lamiaceae', '', ''),
 'thal':    ('Thallium Metallicum', 'থ্যালিয়াম', 'Mineral', '', ''),
 'thea':    ('Thea Chinensis', 'থিয়া চাইনেনসিস', 'Theaceae', '', ''),
 'theri':   ('Theridion Curassavicum', 'থেরিডিয়ন', 'Arachnida', '', 'Tubercular'),
 'thlaspi': ('Thlaspi Bursa Pastoris', 'থ্ল্যাসপি', 'Brassicaceae', '', ''),
 'thyr':    ('Thyroidinum', 'থাইরয়েডিনাম', 'Sarcode', '', ''),
 'til':     ('Tilia Europaea', 'টিলিয়া', 'Malvaceae', '', ''),
 'trill':   ('Trillium Pendulum', 'ট্রিলিয়াম পেন্ডুলাম', 'Liliaceae', '', ''),
 'trom':    ('Trombidium', 'ট্রম্বিডিয়াম', 'Arachnida', '', ''),
 'tussil':  ('Tussilago Farfara', 'টুসিলেগো', 'Compositae', '', ''),
 'upa':     ('Upas Tieute', 'উপাস টিউটে', 'Loganiaceae', '', ''),
 'uran-n':  ('Uranium Nitricum', 'ইউরেনিয়াম নাইট্রিকাম', 'Mineral', '', ''),
 'ust':     ('Ustilago Maydis', 'উস্টিলেগো মেইডিস', 'Fungi', '', ''),
 'uva':     ('Uva Ursi', 'উভা উরসি', 'Ericaceae', '', ''),
 'vac':     ('Vaccininum', 'ভ্যাকসিনিনাম', 'Nosode', '', ''),
 'vanad':   ('Vanadium Metallicum', 'ভ্যানাডিয়াম', 'Mineral', '', ''),
 'verat-v': ('Veratrum Viride', 'ভেরাট্রাম ভিরিডি', 'Liliaceae', '', ''),
 'verbe':   ('Verbena Officinalis', 'ভার্বেনা অফিসিনালিস', 'Verbenaceae', '', ''),
 'vesp':    ('Vespa Crabro', 'ভেসপা ক্র্যাব্রো', 'Insecta', '', ''),
 'vib':     ('Viburnum Opulus', 'ভাইবার্নাম ওপুলাস', 'Adoxaceae', '', ''),
 'vinc':    ('Vinca Minor', 'ভিঙ্কা মাইনর', 'Apocynaceae', '', ''),
 'viol-o':  ('Viola Odorata', 'ভায়োলা ওডোরাটা', 'Violaceae', '', ''),
 'visc':    ('Viscum Album', 'ভিস্কাম অ্যালবাম', 'Santalaceae', '', ''),
 'wye':     ('Wyethia Helenoides', 'ওয়াইথিয়া', 'Compositae', '', ''),
 'xanth':   ('Xanthoxylum Fraxineum', 'জ্যান্থক্সাইলাম', 'Rutaceae', '', ''),
 'yohim':   ('Yohimbinum', 'ইয়োহিম্বিনাম', 'Alkaloid', '', ''),
 'zinc-p':  ('Zincum Phosphoricum', 'জিঙ্কাম ফসফরিকাম', 'Mineral', '', ''),
 'zing':    ('Zingiber Officinale', 'জিঞ্জিবার অফিসিনেল', 'Zingiberaceae', '', ''),
 'zizia':   ('Zizia Aurea', 'জিজিয়া', 'Umbelliferae', '', ''),
}
