# -*- coding: utf-8 -*-
"""Rubrics, chapters 9-16."""

RUB2 = {

'Respiration - শ্বাস': {
 'Asthma': ('হাঁপানি', [('ars',3),('kali-c',3),('nat-s',3),('ip',2),('spong',2),('ant-t',2),('lach',2),('med',2),('tub',2),('sulph',2),('carb-v',2),('cupr',2)]),
 'Cough dry': ('শুকনো কাশি', [('bry',3),('rumx',3),('spong',3),('phos',2),('hyos',2),('acon',2),('dros',2),('sticta',0),('con',2),('lach',2)]),
 'Cough with expectoration': ('কফসহ কাশি', [('ant-t',3),('puls',3),('kali-s',2),('hep',2),('sil',2),('stann',2),('kali-bi',2),('sulph',2),('phos',2)]),
 'Wheezing': ('শ্বাসে সাঁই সাঁই শব্দ', [('ars',3),('ip',3),('ant-t',2),('spong',2),('nat-s',2),('kali-c',2),('brom',2),('lach',2)]),
 'Difficult breathing': ('শ্বাসকষ্ট', [('ars',3),('carb-v',3),('lach',3),('ant-t',2),('kali-c',2),('phos',2),('ip',2),('spong',2),('sulph',2)]),
 'Shortness of breath': ('দম ফুরিয়ে যাওয়া', [('carb-v',3),('ars',3),('phos',2),('calc',2),('kali-c',2),('lach',2),('crat',2),('dig',2)]),
 'Rapid breathing': ('দ্রুত শ্বাস', [('acon',3),('bell',2),('phos',2),('ant-t',2),('ars',2),('ferr-p',2)]),
 'Slow breathing': ('ধীর শ্বাস', [('op',3),('hell',2),('dig',2),('lach',2),('camph',1)]),
 'Noisy breathing': ('শব্দযুক্ত শ্বাস', [('ant-t',3),('op',2),('hep',2),('spong',2),('samb',2),('lach',1)]),
 'Painful breathing': ('শ্বাসে ব্যথা', [('bry',3),('kali-c',3),('acon',2),('ran-b',2),('squil',2),('phos',2),('spig',2)]),
 'Breathing worse lying': ('শুলে শ্বাসকষ্ট বৃদ্ধি', [('ars',3),('lach',3),('ant-t',2),('cact',2),('spong',2),('phos',2),('kali-c',2),('samb',2)]),
 'Breathing better sitting': ('বসলে শ্বাস আরাম', [('ars',3),('ant-t',3),('kali-c',2),('cact',2),('spong',2),('lach',2),('dig',2)]),
 'Breathing worse cold air': ('ঠান্ডা বাতাসে শ্বাসকষ্ট', [('hep',3),('sil',2),('rumx',3),('nux-v',2),('spong',2),('ars',2),('phos',2)]),
 'Breathing worse warm room': ('গরম ঘরে শ্বাসকষ্ট', [('puls',3),('apis',2),('sulph',2),('lach',2),('iod',2),('kali-s',2)]),
 'Breathing worse talking': ('কথা বললে শ্বাসকষ্ট', [('stann',3),('phos',2),('rumx',2),('spong',1),('calc',1)]),
 'Breathing better walking': ('হাঁটলে শ্বাস আরাম', [('ferr',2),('rhus-t',2),('puls',2),('med',2),('tarent',1)]),
 'Breathing worse walking': ('হাঁটলে শ্বাসকষ্ট', [('carb-v',3),('calc',2),('kali-c',2),('lyc',2),('phos',2),('crat',2)]),
 'Breathing worse night': ('রাতে শ্বাসকষ্ট', [('ars',3),('lach',2),('kali-c',3),('ant-t',2),('samb',2),('spong',2),('nat-s',2)]),
 'Breathing worse morning': ('সকালে শ্বাসকষ্ট', [('nat-s',3),('nux-v',2),('sulph',2),('kali-bi',2),('phos',2)]),
 'Breathing during sleep': ('ঘুমের মধ্যে শ্বাসের সমস্যা', [('op',3),('lach',3),('samb',2),('ant-t',2),('bar-c',2),('spong',1)]),
},

'Chest - বুক': {
 'Pain in chest': ('বুকে ব্যথা', [('bry',3),('kali-c',3),('phos',2),('ran-b',2),('spig',2),('acon',2),('arn',2),('cact',2),('squil',2)]),
 'Palpitation': ('হৃদস্পন্দন দ্রুত হওয়া', [('acon',3),('cact',3),('spig',3),('dig',2),('nat-m',2),('lach',2),('puls',2),('kali-c',2),('lyc',2),('crat',2)]),
 'Oppression of chest': ('বুকে চাপ', [('lach',3),('ars',3),('cact',2),('phos',2),('kali-c',2),('sulph',2),('spong',2),('ip',2)]),
 'Constriction of chest': ('বুকের সংকোচন', [('cact',3),('lach',3),('spong',2),('ars',2),('ip',2),('phos',2),('cupr',2)]),
 'Heartburn': ('বুক জ্বালা', [('nux-v',3),('nat-p',3),('sul-ac',2),('phos',2),('carb-v',2),('lyc',2),('iris',2)]),
 'Pain in heart region': ('হৃদযন্ত্র অঞ্চলে ব্যথা', [('cact',3),('spig',3),('acon',2),('naja',2),('lach',2),('kalm',2),('dig',2),('arn',2)]),
 'Pain in ribs': ('পাঁজরে ব্যথা', [('bry',3),('ran-b',3),('arn',2),('kali-c',2),('rhus-t',2),('chel',2)]),
 'Tightness in chest': ('বুকে আঁটসাঁট ভাব', [('lach',3),('cact',2),('ars',2),('spong',2),('phos',2),('ip',2)]),
 'Pain on deep breathing': ('গভীর শ্বাসে ব্যথা', [('bry',3),('ran-b',2),('acon',2),('kali-c',2),('squil',2),('spig',2)]),
 'Cough with chest pain': ('কাশিতে বুকে ব্যথা', [('bry',3),('phos',2),('kali-c',2),('rumx',2),('squil',2),('nux-v',1)]),
 'Chest pain during movement': ('নড়াচড়ায় বুকে ব্যথা', [('bry',3),('ran-b',2),('rhus-t',2),('arn',2),('spig',2)]),
 'Chest pain at rest': ('বিশ্রামে বুকে ব্যথা', [('rhus-t',2),('cact',2),('kali-c',2),('naja',2),('spig',1)]),
 'Chest pain with anxiety': ('উদ্বেগসহ বুকে ব্যথা', [('acon',3),('ars',3),('cact',2),('lach',2),('phos',2),('nat-m',2),('arg-n',2)]),
 'Chest pain with nausea': ('বমি ভাবসহ বুকে ব্যথা', [('ip',2),('nux-v',2),('dig',2),('cact',1),('ars',2)]),
 'Chest pain with dizziness': ('মাথা ঘোরাসহ বুকে ব্যথা', [('dig',2),('cocc',2),('nat-m',2),('phos',2),('cact',1)]),
 'Chest tightness': ('বুকে টান', [('cact',3),('lach',2),('spong',2),('ars',2),('cupr',2),('ip',2)]),
 'Chest heaviness': ('বুকে ভারী ভাব', [('ant-t',3),('carb-v',2),('phos',2),('kali-c',2),('sulph',2),('lach',2)]),
 'Chest weakness': ('বুকের দুর্বলতা', [('stann',3),('phos',2),('calc',2),('carb-v',2),('kali-c',2),('sil',2)]),
 'Chest coldness': ('বুকে শীতলতা', [('carb-v',2),('ars',2),('camph',2),('verat',2),('sec',1)]),
 'Chest heat': ('বুকে উষ্ণতা', [('phos',2),('sulph',2),('bell',2),('lach',2),('acon',1)]),
},

'Back - পিঠ': {
 'Back pain': ('পিঠে ব্যথা', [('rhus-t',3),('kali-c',3),('nux-v',3),('bry',2),('sep',2),('calc-f',2),('aesc',2),('sulph',2),('cimic',2),('arn',2)]),
 'Back stiffness': ('পিঠের শক্ততা', [('rhus-t',3),('bry',2),('nux-v',2),('cimic',2),('calc-f',2),('sulph',2),('lyc',1)]),
 'Back weakness': ('পিঠের দুর্বলতা', [('kali-c',3),('calc-p',3),('sep',2),('nat-m',2),('sil',2),('ph-ac',2),('nux-v',2)]),
 'Back aching after exertion': ('পরিশ্রমের পর পিঠে ব্যথা', [('rhus-t',3),('arn',3),('calc',2),('kali-c',2),('nux-v',2),('ruta',2)]),
 'Back pain during menses': ('ঋতুস্রাবের সময় পিঠে ব্যথা', [('cimic',3),('sep',2),('kali-c',2),('sabin',2),('puls',2),('nux-v',2),('vib',2)]),
 'Back pain worse sitting': ('বসলে পিঠে ব্যথা বৃদ্ধি', [('rhus-t',3),('kali-c',2),('sep',2),('cocc',2),('valer',1)]),
 'Back pain worse standing': ('দাঁড়ালে পিঠে ব্যথা বৃদ্ধি', [('sulph',3),('sep',2),('aesc',2),('nat-c',2),('calc',2),('lyc',1)]),
 'Back pain worse walking': ('হাঁটলে পিঠে ব্যথা বৃদ্ধি', [('aesc',3),('sep',2),('calc',2),('nat-m',2),('con',2),('bry',2)]),
 'Back pain better lying': ('শুলে পিঠে ব্যথা উপশম', [('bry',3),('nux-v',2),('arn',2),('sep',2),('rhus-t',1),('kali-c',2)]),
 'Back pain worse morning': ('সকালে পিঠে ব্যথা বৃদ্ধি', [('rhus-t',3),('nux-v',3),('staph',2),('sulph',2),('lach',1)]),
 'Back pain worse evening': ('সন্ধ্যায় পিঠে ব্যথা বৃদ্ধি', [('sep',2),('puls',2),('lyc',2),('phos',2),('rhus-t',1)]),
 'Back pain with fever': ('জ্বরসহ পিঠে ব্যথা', [('eup-per',3),('bry',2),('rhus-t',2),('gels',2),('bapt',2),('acon',2)]),
 'Back pain with chill': ('শীতসহ পিঠে ব্যথা', [('gels',3),('eup-per',2),('nux-v',2),('caps',2),('rhus-t',2)]),
 'Back pain with weakness': ('দুর্বলতাসহ পিঠে ব্যথা', [('kali-c',3),('calc-p',2),('ph-ac',2),('sep',2),('nat-m',2),('sil',2)]),
 'Back pain with numbness': ('অসাড়তাসহ পিঠে ব্যথা', [('coloc',2),('hyper',2),('graph',2),('plb',2),('nux-v',2),('cocc',2)]),
 'Back curvature': ('মেরুদণ্ডের বক্রতা', [('calc',3),('calc-p',3),('sil',2),('sulph',2),('phos',2),('tub',2),('lyc',1)]),
 'Back spasm': ('পিঠের খিঁচুনি', [('mag-p',3),('cimic',2),('nux-v',2),('cupr',2),('rhus-t',2),('bell',2)]),
 'Back twitching': ('পিঠে ঝাঁকুনি', [('agar',3),('zinc',2),('cimic',2),('nux-v',2),('ign',2)]),
 'Back coldness': ('পিঠে শীতলতা', [('gels',2),('ars',2),('camph',2),('sep',2),('verat',2),('calc',1)]),
 'Back heat': ('পিঠে উষ্ণতা', [('phos',2),('sulph',2),('bell',1),('lach',1)]),
},

'Extremities - অঙ্গ': {
 'Pain in joints': ('সন্ধিতে ব্যথা', [('rhus-t',3),('bry',3),('colch',3),('caust',2),('kalm',2),('led',2),('guai',2),('calc-f',2),('sulph',2),('ruta',2)]),
 'Pain in limbs': ('হাত-পায়ে ব্যথা', [('rhus-t',3),('bry',2),('arn',2),('eup-per',2),('phyt',2),('caust',2),('kali-c',2)]),
 'Cramp in legs': ('পায়ের ডলা/খিঁচুনি', [('cupr',3),('mag-p',3),('cham',2),('sulph',2),('nux-v',2),('calc',2),('rhus-t',2),('sec',2)]),
 'Cramp in feet': ('পায়ের পাতায় খিঁচুনি', [('cupr',3),('sulph',2),('mag-p',2),('calc',2),('nux-v',2),('zinc',2)]),
 'Cramp in hands': ('হাতে খিঁচুনি', [('cupr',3),('mag-p',2),('sec',2),('plb',2),('stann',1)]),
 'Swelling of feet': ('পায়ের ফোলা', [('apis',3),('ars',3),('dig',2),('lyc',2),('sulph',2),('merc',2),('thyr',2),('sil',2)]),
 'Swelling of hands': ('হাতের ফোলা', [('apis',3),('ars',2),('merc',2),('rhus-t',2),('lyc',1),('thyr',2)]),
 'Coldness of feet': ('পা ঠান্ডা', [('sil',3),('calc',3),('sep',2),('sulph',2),('carb-v',2),('nat-m',2),('lyc',2),('verat',2)]),
 'Coldness of hands': ('হাত ঠান্ডা', [('calc',3),('sil',2),('sep',2),('verat',2),('carb-v',2),('nat-m',2)]),
 'Weakness of legs': ('পায়ের দুর্বলতা', [('ph-ac',3),('gels',3),('con',2),('plb',2),('nux-v',2),('kali-c',2),('sil',2),('caust',2)]),
 'Weakness of arms': ('হাতের দুর্বলতা', [('caust',3),('plb',2),('con',2),('stann',2),('gels',2),('kali-c',1)]),
 'Trembling of hands': ('হাত কাঁপা', [('agar',3),('gels',3),('zinc',2),('merc',2),('lach',2),('phos',2),('plb',2),('sulph',2)]),
 'Trembling of legs': ('পা কাঁপা', [('gels',3),('agar',2),('zinc',2),('merc',2),('phos',2),('sil',1)]),
 'Numbness in hands': ('হাতে অসাড়তা', [('graph',3),('coloc',2),('plb',2),('cocc',2),('nux-v',2),('calc',2),('phos',2)]),
 'Numbness in feet': ('পায়ে অসাড়তা', [('graph',2),('coloc',2),('plb',2),('sec',2),('phos',2),('nux-v',2),('sil',1)]),
 'Varicose veins': ('ভেরিকোজ শিরা', [('ham',3),('calc-f',3),('puls',3),('carb-v',2),('lach',2),('fl-ac',2),('sep',2),('mill',2)]),
 'Restless legs': ('পা ছটফট করা', [('zinc',3),('tarent',3),('rhus-t',2),('ars',2),('sulph',2),('med',2),('caust',2)]),
 'Restless feet': ('পায়ের পাতা ছটফট করা', [('zinc',3),('tarent',2),('med',2),('sulph',2),('rhus-t',2)]),
 'Heavy legs': ('পা ভারী লাগা', [('gels',3),('ph-ac',2),('con',2),('nux-v',2),('kali-c',2),('sep',2)]),
 'Heavy feet': ('পায়ের পাতা ভারী লাগা', [('gels',2),('nux-v',2),('con',2),('kali-c',2),('ph-ac',2)]),
},

'Female - নারী': {
 'Menses too early': ('ঋতুস্রাব আগে হওয়া', [('calc',3),('nux-v',3),('ip',2),('sabin',2),('bell',2),('bry',2),('cham',2),('phos',2),('lach',2)]),
 'Menses late': ('ঋতুস্রাব দেরিতে হওয়া', [('puls',3),('sep',3),('graph',2),('kali-c',2),('nat-m',2),('sulph',2),('con',2),('senec',0)]),
 'Menses painful': ('কষ্টকর ঋতুস্রাব', [('mag-p',3),('cham',3),('coloc',3),('cimic',3),('puls',2),('sep',2),('lach',2),('vib',2),('sabin',2),('bell',2)]),
 'Leucorrhea': ('লিউকোরিয়া', [('sep',3),('calc',3),('puls',2),('kreos',2),('alum',2),('graph',2),('nat-m',2),('sulph',2),('borx',2),('med',2)]),
 'Menopause symptoms': ('মেনোপজের উপসর্গ', [('lach',3),('sep',3),('sulph',2),('sang',2),('sul-ac',2),('cimic',2),('graph',2),('puls',2),('amyl-ns',0)]),
 'Infertility': ('বন্ধ্যাত্ব', [('sep',2),('nat-m',2),('puls',2),('borx',2),('calc',2),('med',2),('phos',1),('agn',2)]),
 'Pregnancy complaints': ('গর্ভাবস্থার সমস্যা', [('sep',3),('puls',2),('nux-v',2),('ip',2),('kreos',2),('bell',1),('cimic',2)]),
 'Morning sickness': ('সকালের বমি ভাব', [('sep',3),('ip',3),('nux-v',3),('puls',2),('tab',2),('cocc',2),('kreos',2),('lac-d',2)]),
 'Cravings during pregnancy': ('গর্ভাবস্থার আকাঙ্ক্ষা', [('sep',2),('nat-m',2),('calc',2),('lyc',2),('alum',2),('nux-v',1)]),
 'Aversions during pregnancy': ('গর্ভাবস্থার অরুচি', [('sep',2),('puls',2),('nat-m',2),('nux-v',2),('ip',1)]),
 'Pain during pregnancy': ('গর্ভাবস্থায় ব্যথা', [('cimic',3),('sep',2),('puls',2),('bell',2),('kali-c',2),('vib',2)]),
 'Back pain during pregnancy': ('গর্ভাবস্থায় পিঠে ব্যথা', [('kali-c',3),('cimic',2),('sep',2),('puls',2),('nux-v',2),('bell',1)]),
 'Headache during pregnancy': ('গর্ভাবস্থায় মাথাব্যথা', [('sep',2),('nat-m',2),('bell',2),('puls',2),('gels',2),('nux-v',1)]),
 'Anxiety during pregnancy': ('গর্ভাবস্থায় উদ্বেগ', [('acon',3),('ars',2),('puls',2),('sep',2),('kali-c',2),('arg-n',2),('gels',2)]),
 'Depression during pregnancy': ('গর্ভাবস্থায় বিষণ্নতা', [('sep',3),('nat-m',2),('puls',2),('cimic',2),('aur',2),('ign',2)]),
 'Sleep problems during pregnancy': ('গর্ভাবস্থায় ঘুমের সমস্যা', [('coff',2),('puls',2),('sep',2),('nux-v',2),('kali-c',2),('ars',2)]),
 'Swelling during pregnancy': ('গর্ভাবস্থায় ফোলা', [('apis',3),('nat-m',2),('calc',2),('puls',2),('lyc',2),('thyr',1)]),
 'Varicose veins during pregnancy': ('গর্ভাবস্থায় ভেরিকোজ শিরা', [('ham',3),('puls',2),('calc-f',2),('lach',2),('carb-v',2),('sep',1)]),
 'Skin changes during pregnancy': ('গর্ভাবস্থায় ত্বকের পরিবর্তন', [('sep',3),('nat-m',2),('thuj',2),('calc-f',2),('sulph',1),('graph',1)]),
 'Hair changes during pregnancy': ('গর্ভাবস্থায় চুলের পরিবর্তন', [('nat-m',2),('sep',2),('lyc',2),('ph-ac',2),('sil',2),('calc',1)]),
},

'Male - পুরুষ': {
 'Impotence': ('পুরুষত্বহীনতা', [('lyc',3),('agn',3),('sel',2),('sep',2),('nux-v',2),('phos',2),('con',2),('graph',2),('caust',1)]),
 'Nocturnal emissions': ('রাতের স্বপ্নদোষ', [('sel',3),('phos',2),('staph',2),('con',2),('nat-m',2),('nux-v',2),('sulph',2),('thuj',2)]),
 'Prostate issues': ('প্রস্টেটের সমস্যা', [('thuj',3),('sabal',0),('con',3),('puls',2),('sel',2),('lyc',2),('sil',2),('bar-c',2),('caust',2)]),
 'Testicular pain': ('অণ্ডকোষে ব্যথা', [('puls',3),('clem',3),('rhod',2),('spong',2),('ham',2),('aur',2),('nux-v',1)]),
 'Erectile dysfunction': ('লিঙ্গোত্থানে সমস্যা', [('lyc',3),('agn',3),('sel',2),('nux-v',2),('sep',2),('con',2),('graph',2),('phos',2)]),
 'Low libido': ('যৌন আকাঙ্ক্ষা কম', [('agn',3),('sep',2),('graph',2),('lyc',2),('con',2),('nat-m',2),('sel',2),('caust',1)]),
 'High libido': ('যৌন আকাঙ্ক্ষা বেশি', [('plat',3),('staph',2),('canth',2),('phos',2),('lach',2),('nux-v',2),('med',2)]),
 'Premature ejaculation': ('দ্রুত বীর্যপাত', [('sel',2),('nux-v',2),('lyc',2),('phos',2),('agn',2),('staph',2),('con',1)]),
 'Delayed ejaculation': ('বিলম্বিত বীর্যপাত', [('sel',2),('agn',2),('graph',2),('lyc',1),('con',1)]),
 'Pain during intercourse': ('সহবাসে ব্যথা', [('staph',3),('sep',2),('nat-m',2),('thuj',2),('lyc',1),('kreos',2)]),
 'Pain in penis': ('লিঙ্গে ব্যথা', [('canth',2),('thuj',2),('merc',2),('nit-ac',2),('cann-s',2),('staph',2)]),
 'Swelling of penis': ('লিঙ্গের ফোলা', [('apis',2),('merc',2),('rhus-t',2),('thuj',2),('nit-ac',1)]),
 'Discharge from penis': ('লিঙ্গ থেকে স্রাব', [('merc',3),('thuj',3),('cann-s',2),('nit-ac',2),('puls',2),('sulph',2),('med',2),('cop',2)]),
 'Itching of penis': ('লিঙ্গে চুলকানি', [('calad',3),('thuj',2),('merc',2),('sulph',2),('rhus-t',2),('nit-ac',1)]),
 'Pain in testicles': ('অণ্ডকোষে ব্যথা', [('puls',3),('clem',2),('rhod',2),('aur',2),('ham',2),('spong',2)]),
 'Swelling of testicles': ('অণ্ডকোষের ফোলা', [('puls',3),('rhod',2),('clem',2),('apis',2),('merc',2),('aur',2)]),
 'Varicocele': ('ভেরিকোসিল', [('ham',3),('puls',2),('calc-f',2),('nux-v',2),('lyc',1),('carb-v',1)]),
 'Hydrocele': ('হাইড্রোসিল', [('puls',3),('rhod',2),('graph',2),('sil',2),('apis',2),('sulph',1)]),
 'Inguinal hernia': ('কুঁচকির হার্নিয়া', [('nux-v',3),('lyc',2),('calc',2),('sil',2),('aur',2),('cocc',2)]),
 'Inguinal pain': ('কুঁচকিতে ব্যথা', [('nux-v',2),('lyc',2),('aur',2),('coloc',2),('berb',2),('sil',1)]),
},

'Urine - প্রস্রাব': {
 'Burning during urination': ('প্রস্রাবে জ্বালা', [('canth',3),('apis',3),('merc-c',3),('sars',2),('nit-ac',2),('sulph',2),('staph',2),('berb',2)]),
 'Frequent urination': ('ঘন ঘন প্রস্রাব', [('puls',3),('phos-ac',0),('sulph',2),('lyc',2),('sep',2),('nat-m',2),('thuj',2),('ph-ac',2),('bell',2)]),
 'Scanty urine': ('অল্প প্রস্রাব', [('apis',3),('canth',2),('ars',2),('bell',2),('dig',2),('ter',2),('colch',2)]),
 'Dark urine': ('গাঢ় প্রস্রাব', [('bry',2),('chel',2),('ars',2),('benz-ac',3),('lach',2),('nux-v',2)]),
 'Cloudy urine': ('ঘোলা প্রস্রাব', [('sep',3),('phos',2),('berb',2),('chin',2),('graph',2),('sulph',2)]),
 'Foul smelling urine': ('দুর্গন্ধযুক্ত প্রস্রাব', [('benz-ac',3),('nit-ac',3),('sep',2),('psor',2),('merc',2),('sulph',1)]),
 'Blood in urine': ('প্রস্রাবে রক্ত', [('canth',3),('ter',3),('ham',2),('phos',2),('merc-c',2),('berb',2),('sec',2),('mill',2)]),
 'Pain during urination': ('প্রস্রাবে ব্যথা', [('canth',3),('merc-c',2),('nit-ac',2),('sars',2),('berb',2),('apis',2),('staph',2)]),
 'Involuntary urination': ('অনিচ্ছাকৃত প্রস্রাব', [('caust',3),('puls',3),('sep',2),('bell',2),('kreos',2),('rhus-t',2),('nat-m',2),('equis',2)]),
 'Retention of urine': ('প্রস্রাব বন্ধ', [('acon',3),('canth',2),('apis',2),('op',2),('nux-v',2),('caust',2),('stram',2)]),
 'Urgency of urination': ('প্রস্রাবের তীব্র চাপ', [('canth',3),('apis',2),('puls',2),('nux-v',2),('merc-c',2),('sulph',2),('staph',2)]),
 'Dribbling after urination': ('প্রস্রাবের পর ফোঁটা ফোঁটা', [('sel',2),('thuj',2),('con',2),('caust',2),('sars',2),('sulph',1)]),
 'Pain in bladder': ('মূত্রথলিতে ব্যথা', [('canth',3),('apis',2),('nux-v',2),('staph',2),('merc-c',2),('sars',2)]),
 'Pain in kidneys': ('কিডনিতে ব্যথা', [('berb',3),('canth',2),('lyc',2),('ter',2),('sars',2),('nux-v',2),('coloc',2)]),
 'Pain in urethra': ('মূত্রনালিতে ব্যথা', [('canth',3),('sars',2),('nit-ac',2),('cann-s',2),('merc-c',2),('thuj',2)]),
 'Pain in prostate': ('প্রস্টেটে ব্যথা', [('thuj',2),('con',2),('puls',2),('sel',2),('lyc',2),('staph',2)]),
 'Pain in bladder region': ('মূত্রথলির অঞ্চলে ব্যথা', [('canth',2),('apis',2),('sars',2),('staph',2),('nux-v',2),('berb',1)]),
 'Pain in kidney region': ('কিডনি অঞ্চলে ব্যথা', [('berb',3),('lyc',2),('ter',2),('canth',2),('sars',2),('nux-v',1)]),
 'Pain during full bladder': ('মূত্রথলি ভরা থাকলে ব্যথা', [('canth',2),('apis',2),('sars',2),('berb',1),('lyc',1)]),
 'Pain during empty bladder': ('মূত্রথলি খালি হলে ব্যথা', [('sars',3),('canth',2),('nit-ac',1),('berb',1)]),
},

'Stool - মল': {
 'Diarrhea': ('পাতলা পায়খানা', [('podo',3),('ars',3),('verat',3),('sulph',2),('cham',2),('chin',2),('aloe',2),('merc',2),('gels',2),('croc',0),('nat-s',2)]),
 'Constipation': ('কোষ্ঠকাঠিন্য', [('nux-v',3),('bry',3),('alum',3),('op',2),('sulph',2),('lyc',2),('sep',2),('sil',2),('graph',2),('plb',2)]),
 'Hard stool': ('শক্ত মল', [('bry',3),('alum',3),('nat-m',2),('sulph',2),('sil',2),('plb',2),('op',2),('lyc',2)]),
 'Loose stool': ('নরম মল', [('podo',2),('sulph',2),('chin',2),('aloe',2),('nat-s',2),('puls',2),('merc',2)]),
 'Mucus in stool': ('মলে শ্লেষ্মা', [('merc',3),('nux-v',2),('sulph',2),('aloe',2),('colch',2),('kali-bi',2),('puls',2)]),
 'Blood in stool': ('মলে রক্ত', [('merc-c',3),('nit-ac',2),('sulph',2),('ham',2),('nux-v',2),('phos',2),('ars',2),('alum',1)]),
 'Undigested food in stool': ('মলে অপাচ্য খাবার', [('chin',3),('ferr',3),('graph',2),('ars',2),('podo',2),('calc',2),('nat-c',1)]),
 'Green stool': ('সবুজ মল', [('cham',3),('merc',2),('podo',2),('ip',2),('mag-c',2),('puls',2),('calc',1)]),
 'Black stool': ('কালো মল', [('op',2),('lept',3),('ars',2),('chin',2),('merc',1),('bry',1)]),
 'Yellow stool': ('হলুদ মল', [('chel',3),('podo',2),('puls',2),('merc',2),('gels',2),('lept',2)]),
 'Foul smelling stool': ('দুর্গন্ধযুক্ত মল', [('psor',3),('carb-v',3),('ars',2),('merc',2),('sulph',2),('pyrog',2),('bapt',2),('graph',1)]),
 'Pain during stool': ('মলত্যাগে ব্যথা', [('nux-v',3),('nit-ac',3),('merc',2),('sulph',2),('rat',2),('aesc',2),('sil',2)]),
 'Burning during stool': ('মলত্যাগে জ্বালা', [('sulph',3),('ars',2),('nit-ac',2),('merc',2),('aloe',2),('canth',1)]),
 'Involuntary stool': ('অনিচ্ছাকৃত মলত্যাগ', [('aloe',3),('op',2),('ars',2),('phos',2),('hyos',2),('sec',2),('mur-ac',2)]),
 'Incomplete evacuation': ('অসম্পূর্ণ মলত্যাগ', [('nux-v',3),('sulph',2),('merc',2),('lyc',2),('sep',2),('carb-v',2),('aloe',2)]),
 'Urgency of stool': ('মলত্যাগের তীব্র চাপ', [('aloe',3),('sulph',3),('merc',2),('nux-v',2),('podo',2),('gamb',2)]),
 'Stool after eating': ('খাওয়ার পর মলত্যাগ', [('aloe',3),('chin',2),('ferr',2),('nat-s',2),('sulph',2),('podo',2),('trom',1)]),
 'Stool in morning': ('সকালে মলত্যাগ', [('sulph',3),('podo',3),('nat-s',2),('nux-v',2),('bry',1),('rumx',2)]),
 'Stool at night': ('রাতে মলত্যাগ', [('ars',3),('chin',2),('merc',2),('podo',2),('sulph',1),('phos',2)]),
 'Stool during travel': ('ভ্রমণে মলত্যাগের সমস্যা', [('arg-n',3),('gels',2),('lyc',2),('op',2),('nux-v',1),('carc',2)]),
},

}
