# -*- coding: utf-8 -*-
"""Rubrics, chapters 1-8.  'English name': ('বাংলা', [(remedy key, grade 1-3), ...])
   Grade 3 = most characteristic, 2 = important, 1 = also listed.
"""

RUB1 = {

'Mind - মন': {
 'Anxiety': ('উদ্বেগ', [('acon',3),('ars',3),('arg-n',3),('aur',3),('phos',2),('calc',2),('kali-c',2),('puls',2),('nat-m',2),('lyc',2),('gels',2),('caust',1),('sep',1),('carc',2)]),
 'Fear': ('ভয়', [('acon',3),('ars',3),('stram',3),('calc',2),('phos',2),('lyc',2),('bell',2),('gels',2),('puls',2),('bar-c',2),('kali-c',2),('nat-m',1),('op',2)]),
 'Restlessness': ('অস্থিরতা', [('ars',3),('rhus-t',3),('acon',3),('tarent',3),('med',2),('ferr',2),('puls',2),('sulph',2),('cham',2),('sep',1),('zinc',2)]),
 'Irritability': ('বিরক্তি ও খিটখিটে মেজাজ', [('nux-v',3),('cham',3),('hep',3),('bry',3),('sep',3),('lyc',2),('staph',2),('nat-m',2),('sulph',2),('ars',2),('ign',2),('cina',2),('kali-c',2)]),
 'Grief': ('শোক', [('ign',3),('nat-m',3),('ph-ac',3),('aur',2),('staph',2),('puls',2),('carc',2),('lach',1),('cimic',2)]),
 'Loquacity': ('বাচালতা', [('lach',3),('hyos',3),('stram',3),('cann-i',2),('coff',2),('bell',2),('verat',2),('tarent',2),('op',1)]),
 'Memory': ('স্মৃতিশক্তির দুর্বলতা', [('anac',3),('lyc',3),('bar-c',3),('nat-m',2),('sep',2),('alum',2),('phos',2),('kali-p',2),('sulph',2),('con',2),('plb',1),('agar',2)]),
 'Concentration': ('মনোযোগের অভাব', [('lyc',3),('nat-m',2),('sulph',2),('kali-p',2),('sep',2),('phos',2),('nux-v',2),('cann-i',2),('agar',1),('anac',2)]),
 'Confusion': ('বিভ্রান্তি', [('nux-m',3),('bapt',3),('op',3),('lach',2),('phos',2),('sulph',2),('hell',2),('cann-i',2),('alum',2),('gels',2)]),
 'Delirium': ('প্রলাপ', [('bell',3),('hyos',3),('stram',3),('op',2),('bapt',2),('lach',2),('ars',2),('acon',2),('verat',2),('verat-v',2)]),
 'Suicidal disposition': ('আত্মহত্যার প্রবণতা', [('aur',3),('nat-s',3),('psor',2),('lach',2),('ars',2),('hep',2),('nux-v',2),('chin',1),('sep',1),('carc',2)]),
 'Mania': ('উন্মাদনা', [('bell',3),('hyos',3),('stram',3),('verat',3),('lach',2),('aur',2),('op',2),('cupr',1),('agar',1)]),
 'Melancholy': ('বিষাদ', [('aur',3),('nat-m',3),('ign',3),('puls',2),('sep',2),('ars',2),('lach',2),('calc',2),('graph',2),('ph-ac',2),('carc',2),('cimic',2)]),
 'Hysteria': ('হিস্টিরিয়া', [('ign',3),('mosch',3),('valer',3),('tarent',2),('plat',2),('croc',2),('asaf',2),('nux-m',2),('lil-t',1)]),
 'Jealousy': ('ঈর্ষা', [('lach',3),('apis',3),('hyos',3),('nux-v',2),('puls',1),('staph',1)]),
 'Suspiciousness': ('সন্দেহপ্রবণতা', [('lach',3),('ars',3),('hyos',2),('merc',2),('rhus-t',2),('puls',1),('bry',1),('nux-v',1),('thuj',2)]),
 'Indifference': ('উদাসীনতা', [('sep',3),('ph-ac',3),('nat-m',2),('puls',2),('apis',2),('hell',2),('op',2),('carc',2),('chin',2)]),
 'Weeping': ('কান্না', [('puls',3),('ign',3),('nat-m',3),('sep',2),('lyc',2),('cimic',2),('graph',2),('apis',2),('coff',1),('carc',2)]),
 'Laughter': ('অট্টহাসি', [('hyos',3),('croc',3),('cann-i',2),('stram',2),('ign',2),('nat-m',1),('plat',1)]),
 'Anger': ('রাগ', [('cham',3),('nux-v',3),('hep',3),('staph',3),('bry',2),('lyc',2),('ign',2),('anac',2),('tarent',2),('aur',2)]),
 'Fear of being alone': ('একা থাকার ভয়', [('ars',3),('phos',3),('stram',3),('kali-c',2),('lyc',2),('puls',2),('hyos',1),('bism',2)]),
 'Fear of crowds': ('ভিড়ের ভয়', [('acon',3),('arg-n',3),('gels',2),('nat-m',2),('puls',2),('lyc',2),('bar-c',2)]),
 'Fear of height': ('উচ্চতার ভয়', [('arg-n',3),('gels',2),('sulph',2),('calc',2),('staph',1)]),
 'Fear of water': ('পানির ভয়', [('lyss',3),('stram',3),('hyos',2),('bell',2),('sanic',2),('ars',1)]),
 'Fear of thunder': ('বজ্রপাতের ভয়', [('phos',3),('rhod',3),('nat-c',3),('sil',2),('sep',2),('borx',2),('gels',1),('nit-ac',1)]),
 'Fear of animals': ('পশুর ভয়', [('bell',3),('stram',2),('tub',2),('calc',2),('hyos',1),('cupr',1)]),
 'Desire for company': ('সঙ্গের আকাঙ্ক্ষা', [('ars',3),('phos',3),('stram',3),('lyc',2),('puls',2),('kali-c',2),('bism',2),('hyos',1)]),
 'Aversion to company': ('সঙ্গে অরুচি', [('nat-m',3),('sep',3),('ign',3),('bry',2),('gels',2),('aur',2),('cham',2),('lyc',2),('thuj',1)]),
 'Desire to be alone': ('একা থাকার ইচ্ছা', [('nat-m',3),('ign',3),('sep',3),('bry',2),('gels',2),('aur',2),('thuj',2),('arn',2)]),
 'Aversion to being alone': ('একা থাকতে অনিচ্ছা', [('ars',3),('phos',2),('stram',2),('kali-c',2),('puls',2),('lyc',2),('bism',2)]),
},

'Generalities - সাধারণ': {
 'Weakness': ('দুর্বলতা', [('ars',3),('chin',3),('ph-ac',3),('carb-v',3),('gels',2),('sep',2),('calc',2),('nat-m',2),('kali-c',2),('sulph',2),('verat',2),('psor',2),('stann',2)]),
 'Fatigue': ('ক্লান্তি', [('ph-ac',3),('chin',3),('kali-p',3),('gels',2),('calc',2),('sep',2),('nat-m',2),('ars',2),('sulph',2),('carc',2),('pic-ac',2)]),
 'Burning pain': ('জ্বালাযুক্ত ব্যথা', [('ars',3),('sulph',3),('canth',3),('phos',2),('apis',2),('caps',2),('carb-v',2),('sec',2),('bell',1)]),
 'Stabbing pain': ('ছুরিকাঘাতের মতো ব্যথা', [('bry',3),('kali-c',3),('apis',2),('nit-ac',2),('berb',2),('spig',2),('squil',2),('merc',1)]),
 'Coldness': ('শীতলতা', [('camph',3),('verat',3),('carb-v',3),('sec',2),('ars',2),('calc',2),('sil',2),('sep',2),('helon',1)]),
 'Heat': ('উষ্ণতা', [('sulph',3),('bell',3),('acon',2),('lach',2),('puls',2),('apis',2),('iod',2),('med',2),('fl-ac',2)]),
 'Worse motion': ('নড়াচড়ায় বৃদ্ধি', [('bry',3),('colch',3),('nux-v',2),('gels',2),('cocc',2),('dig',2),('bell',2),('spig',2)]),
 'Worse rest': ('বিশ্রামে বৃদ্ধি', [('rhus-t',3),('ferr',2),('puls',2),('tarent',2),('zinc',2),('med',2),('caps',1)]),
 'Worse cold': ('ঠান্ডায় বৃদ্ধি', [('ars',3),('hep',3),('sil',3),('nux-v',3),('calc',2),('sep',2),('kali-c',2),('rhus-t',2),('mag-p',2),('psor',2)]),
 'Worse heat': ('গরমে বৃদ্ধি', [('puls',3),('sulph',3),('apis',3),('lach',2),('iod',2),('nat-m',2),('bry',2),('med',2),('guai',2)]),
 'Worse damp': ('আর্দ্রতায় বৃদ্ধি', [('nat-s',3),('dulc',3),('rhus-t',3),('calc',2),('med',2),('thuj',2),('ars',2),('merc',2),('aran',2),('colch',2)]),
 'Worse dry': ('শুকনো আবহাওয়ায় বৃদ্ধি', [('caust',3),('hep',2),('nux-m',2),('spong',2),('asar',1)]),
 'Worse eating': ('খাওয়ার পর বৃদ্ধি', [('nux-v',3),('bry',3),('chin',2),('carb-v',2),('lyc',2),('kali-c',2),('puls',2),('ars',2),('sep',1)]),
 'Worse drinking': ('পান করার পর বৃদ্ধি', [('ars',3),('bry',2),('nux-v',2),('phos',2),('verat',2),('canth',2),('eup-per',2)]),
 'Worse morning': ('সকালে বৃদ্ধি', [('nux-v',3),('sulph',3),('lach',2),('nat-m',2),('carc',2),('podo',2),('phos',2),('bry',2)]),
 'Worse evening': ('সন্ধ্যায় বৃদ্ধি', [('puls',3),('sep',3),('lyc',2),('phos',2),('rhus-t',2),('bell',2),('sulph',2),('kali-s',2)]),
 'Worse night': ('রাতে বৃদ্ধি', [('merc',3),('ars',3),('syph',3),('cham',2),('hyos',2),('rhus-t',2),('nit-ac',2),('mez',2),('aur',2),('phos',2)]),
 'Worse during menses': ('ঋতুস্রাবের সময় বৃদ্ধি', [('cimic',3),('mag-p',3),('sep',2),('lach',2),('nat-m',2),('puls',2),('bell',2),('cham',2),('sabin',2)]),
 'Worse during storm': ('ঝড়ের সময় বৃদ্ধি', [('phos',3),('rhod',3),('nat-c',2),('sil',2),('sep',2),('psor',2),('gels',1)]),
 'Worse from draft': ('ঠান্ডা হাওয়ার ঝাপটায় বৃদ্ধি', [('hep',3),('sil',3),('nux-v',3),('bell',2),('acon',2),('kali-c',2),('cham',2),('calc',2)]),
 'Better in open air': ('খোলা বাতাসে উপশম', [('puls',3),('apis',2),('kali-s',2),('sulph',2),('lyc',2),('all-c',2),('iod',2),('arg-n',2)]),
 'Better in warm room': ('গরম ঘরে উপশম', [('ars',3),('hep',2),('sil',2),('nux-v',2),('kali-c',2),('mag-p',2),('rhus-t',2),('caps',1)]),
 'Better lying down': ('শুয়ে থাকলে উপশম', [('bry',3),('nux-v',2),('colch',2),('arn',2),('phos',2),('stann',2),('mang',2)]),
 'Better walking': ('হাঁটলে উপশম', [('rhus-t',3),('puls',2),('ferr',2),('sep',2),('tarent',2),('med',2)]),
 'Better sitting': ('বসে থাকলে উপশম', [('bell',3),('ant-t',2),('spig',2),('nux-v',2),('kali-c',2),('puls',1)]),
 'Worse standing': ('দাঁড়িয়ে থাকলে বৃদ্ধি', [('sulph',3),('sep',3),('aesc',2),('nat-c',2),('valer',2),('lyc',1),('calc',2)]),
 'Worse walking': ('হাঁটলে বৃদ্ধি', [('bry',3),('aesc',2),('sep',2),('calc',2),('nat-c',2),('lyc',2),('con',2)]),
 'Worse talking': ('কথা বললে বৃদ্ধি', [('stann',3),('sulph',2),('calc',2),('phos',2),('cocc',2),('ambr',2),('rumx',2)]),
 'Better after sleep': ('ঘুমের পর উপশম', [('phos',3),('sep',2),('sulph',2),('calc',2),('nux-v',2),('ph-ac',2)]),
 'Worse after sleep': ('ঘুমের পর বৃদ্ধি', [('lach',3),('apis',2),('spong',2),('sulph',2),('nux-v',2),('op',2),('kali-c',1)]),
},

'Head - মাথা': {
 'Headache': ('মাথাব্যথা', [('bell',3),('bry',3),('nat-m',3),('nux-v',3),('sang',3),('glon',2),('spig',2),('sep',2),('sil',2),('gels',2),('iris',2),('lac-c',2)]),
 'Headache burning': ('জ্বালাযুক্ত মাথাব্যথা', [('ars',3),('sulph',2),('phos',2),('bell',2),('sang',2),('glon',2)]),
 'Headache pressing': ('চাপযুক্ত মাথাব্যথা', [('nat-m',3),('gels',3),('nux-v',2),('bry',2),('sep',2),('cimic',2),('chel',2),('sulph',2)]),
 'Headache throbbing': ('স্পন্দনশীল মাথাব্যথা', [('bell',3),('glon',3),('sang',2),('ferr-p',2),('lach',2),('nat-m',2),('meli',2),('puls',2)]),
 'Headache from sun': ('রোদে মাথাব্যথা', [('glon',3),('bell',3),('nat-m',3),('lach',2),('ars',1),('sang',2),('cact',1)]),
 'Headache from noise': ('শব্দে মাথাব্যথা', [('bell',3),('nux-v',3),('spig',2),('coff',2),('sil',2),('nat-m',2),('sep',1)]),
 'Headache from light': ('আলোয় মাথাব্যথা', [('bell',3),('sil',2),('nat-m',2),('spig',2),('phos',2),('sang',2),('gels',2)]),
 'Headache from reading': ('পড়াশোনায় মাথাব্যথা', [('nat-m',3),('calc-p',2),('ruta',2),('sep',2),('cimic',2),('phos',2),('nux-v',2)]),
 'Headache after eating': ('খাওয়ার পর মাথাব্যথা', [('nux-v',3),('bry',2),('lyc',2),('carb-v',2),('puls',2),('chin',1)]),
 'Headache during menses': ('ঋতুস্রাবের সময় মাথাব্যথা', [('nat-m',3),('sep',3),('cimic',3),('lach',2),('puls',2),('bell',2),('sang',2),('lac-c',2)]),
 'Headache from grief': ('শোকের পর মাথাব্যথা', [('ign',3),('nat-m',3),('ph-ac',2),('staph',2),('aur',1)]),
 'Headache worse morning': ('সকালে মাথাব্যথা বৃদ্ধি', [('nux-v',3),('nat-m',3),('sang',2),('lach',2),('sulph',2),('bry',2),('carc',2)]),
 'Headache worse evening': ('সন্ধ্যায় মাথাব্যথা বৃদ্ধি', [('puls',3),('sep',2),('lyc',2),('phos',2),('bell',2),('rhus-t',1)]),
 'Headache better motion': ('নড়াচড়ায় মাথাব্যথা উপশম', [('rhus-t',3),('sep',2),('puls',2),('mag-p',1),('cycl',1)]),
 'Headache better rest': ('বিশ্রামে মাথাব্যথা উপশম', [('bry',3),('bell',3),('gels',2),('nux-v',2),('sil',2),('spig',2)]),
 'Headache with nausea': ('বমি ভাবযুক্ত মাথাব্যথা', [('nux-v',3),('sang',3),('iris',3),('bry',2),('sep',2),('cocc',2),('ip',2),('puls',2)]),
 'Headache with vomiting': ('বমির সাথে মাথাব্যথা', [('sang',3),('iris',3),('nux-v',2),('bry',2),('sep',2),('ip',2),('lac-c',2),('nat-m',2)]),
 'Headache with dizziness': ('মাথা ঘোরার সাথে মাথাব্যথা', [('cocc',3),('gels',3),('con',2),('bell',2),('nux-v',2),('phos',2),('bry',2)]),
 'Headache with vision problems': ('দৃষ্টি সমস্যাসহ মাথাব্যথা', [('nat-m',3),('gels',3),('lac-c',2),('psor',2),('iris',2),('cycl',2),('sil',2)]),
 'Headache with fever': ('জ্বরের সাথে মাথাব্যথা', [('bell',3),('bry',3),('gels',3),('eup-per',2),('ferr-p',2),('acon',2),('nat-m',1)]),
},

'Stomach - পাকস্থলী': {
 'Nausea': ('বমি ভাব', [('ip',3),('nux-v',3),('cocc',3),('tab',3),('ars',2),('sep',2),('puls',2),('sang',2),('colch',2),('bry',2)]),
 'Vomiting': ('বমি', [('ip',3),('ars',3),('verat',3),('nux-v',2),('phos',2),('puls',2),('bry',2),('sang',2),('tab',2),('cupr',2)]),
 'Diarrhea': ('ডায়রিয়া', [('ars',3),('podo',3),('verat',3),('sulph',2),('cham',2),('chin',2),('merc',2),('aloe',2),('gels',2),('nat-s',2)]),
 'Constipation': ('কোষ্ঠকাঠিন্য', [('nux-v',3),('bry',3),('alum',3),('op',3),('sulph',2),('lyc',2),('sep',2),('sil',2),('graph',2),('plb',2),('nat-m',2)]),
 'Thirst': ('তৃষ্ণা', [('bry',3),('ars',3),('phos',3),('nat-m',2),('verat',2),('acon',2),('chin',2),('merc',2),('eup-per',2)]),
 'Appetite increased': ('ক্ষুধা বৃদ্ধি', [('iod',3),('lyc',2),('sulph',2),('cina',2),('calc',2),('phos',2),('chin',2),('nat-m',1),('tub',2)]),
 'Appetite decreased': ('ক্ষুধা হ্রাস', [('ars',3),('nux-v',2),('puls',2),('sep',2),('chin',2),('ferr',2),('sil',2),('carc',2),('ph-ac',2)]),
 'Cravings for salt': ('লবণের আকাঙ্ক্ষা', [('nat-m',3),('phos',2),('calc',2),('carb-v',2),('verat',1),('med',2)]),
 'Cravings for sweets': ('মিষ্টির আকাঙ্ক্ষা', [('lyc',3),('sulph',3),('arg-n',3),('calc',2),('kali-c',2),('med',2),('chin',1),('carb-v',2)]),
 'Cravings for sour': ('অম্লের আকাঙ্ক্ষা', [('hep',3),('sep',2),('verat',2),('puls',2),('sul-ac',2),('ars',2),('ign',2),('nat-m',1)]),
 'Cravings for fat': ('চর্বির আকাঙ্ক্ষা', [('nux-v',3),('sulph',2),('ars',2),('hep',2),('nit-ac',2),('tub',2)]),
 'Cravings for cold drinks': ('ঠান্ডা পানীয়ের আকাঙ্ক্ষা', [('phos',3),('verat',3),('bry',2),('acon',2),('merc',2),('med',2),('sulph',2)]),
 'Cravings for warm drinks': ('গরম পানীয়ের আকাঙ্ক্ষা', [('lyc',3),('ars',3),('chel',2),('sabad',2),('casts',0)]),
 'Aversion to meat': ('মাংসে অরুচি', [('sulph',3),('puls',2),('nit-ac',2),('merc',2),('graph',2),('calc',2),('sil',2),('carb-v',1)]),
 'Aversion to milk': ('দুধে অরুচি', [('nat-c',3),('sep',2),('calc',2),('sil',2),('lac-d',2),('sulph',2),('bry',2),('ign',1)]),
 'Aversion to sweets': ('মিষ্টিতে অরুচি', [('graph',3),('caust',2),('merc',2),('nit-ac',2),('sulph',1),('zinc',1)]),
 'Aversion to fat': ('চর্বিতে অরুচি', [('puls',3),('petr',2),('sep',2),('hep',2),('china',0),('bell',1)]),
 'Aversion to warm food': ('গরম খাবারে অরুচি', [('phos',3),('puls',2),('graph',1),('lyc',1)]),
 'Stomach pain': ('পাকস্থলীর ব্যথা', [('nux-v',3),('bry',3),('ars',3),('kali-bi',2),('lyc',2),('phos',2),('puls',2),('chel',2),('coloc',2)]),
 'Stomach burning': ('পাকস্থলীতে জ্বালা', [('ars',3),('phos',3),('sulph',2),('nux-v',2),('carb-v',2),('iris',2),('sul-ac',2),('nat-p',2),('canth',2)]),
 'Stomach cramping': ('পাকস্থলীর খিঁচুনি', [('coloc',3),('mag-p',3),('nux-v',2),('cupr',2),('plb',2),('bell',2),('cham',2)]),
 'Stomach fullness': ('পেট ভরা ভাব', [('lyc',3),('carb-v',3),('nux-v',2),('chin',2),('kali-c',2),('sep',2),('graph',2)]),
 'Stomach emptiness': ('পাকস্থলীতে ফাঁকা ভাব', [('sulph',3),('sep',2),('phos',2),('cocc',2),('ign',2),('chin',2),('carc',1)]),
 'Eructation': ('ঢেকুর', [('carb-v',3),('lyc',3),('nux-v',2),('chin',2),('sep',2),('kali-c',2),('nat-p',2),('sul-ac',2)]),
 'Flatulence': ('পেট ফাঁপা', [('lyc',3),('carb-v',3),('chin',3),('nux-v',2),('sulph',2),('mag-p',2),('kali-c',2),('raph',2)]),
 'Heartburn': ('বুক জ্বালা', [('nux-v',3),('nat-p',3),('sul-ac',2),('carb-v',2),('phos',2),('ars',2),('lyc',2),('iris',2)]),
 'Regurgitation': ('খাবার উঠে আসা', [('phos',3),('nux-v',2),('carb-v',2),('lyc',2),('kali-c',2),('sul-ac',2),('brom',1)]),
 'Nausea during pregnancy': ('গর্ভাবস্থার বমি ভাব', [('ip',3),('sep',3),('nux-v',3),('puls',2),('tab',2),('cocc',2),('lac-d',2),('kreos',2)]),
},

'Skin - ত্বক': {
 'Dry skin': ('শুষ্ক ত্বক', [('sulph',3),('alum',3),('graph',2),('petr',2),('ars',2),('calc',2),('sil',2),('nat-m',2),('psor',2)]),
 'Burning skin': ('ত্বকে জ্বালা', [('ars',3),('sulph',3),('apis',2),('urt-u',2),('canth',2),('rhus-t',2),('mez',2)]),
 'Itching skin': ('ত্বকে চুলকানি', [('sulph',3),('psor',3),('rhus-t',2),('mez',2),('ars',2),('urt-u',2),('graph',2),('alum',2),('staph',2),('dulc',2)]),
 'Eruptions': ('ফুসকুড়ি', [('sulph',3),('graph',3),('rhus-t',2),('mez',2),('psor',2),('hep',2),('ant-c',2),('dulc',2),('kali-s',2)]),
 'Eczema': ('একজিমা', [('graph',3),('sulph',3),('psor',3),('petr',3),('mez',2),('rhus-t',2),('ars',2),('calc',2),('hep',2),('kali-s',2),('sep',2)]),
 'Psoriasis': ('সোরিয়াসিস', [('ars',3),('sulph',3),('kali-s',2),('graph',2),('petr',2),('sep',2),('thuj',2),('ars-i',2),('phyt',1)]),
 'Urticaria': ('আমবাত', [('apis',3),('urt-u',3),('rhus-t',2),('nat-m',2),('sulph',2),('ars',2),('puls',2),('dulc',2),('med',2)]),
 'Cracks': ('ফাটা', [('graph',3),('petr',3),('nit-ac',2),('sulph',2),('sil',2),('calc',2),('sars',2),('hep',2)]),
 'Warts': ('আঁচিল', [('thuj',3),('nit-ac',3),('caust',3),('dulc',2),('ant-c',2),('med',2),('calc',2),('sep',2)]),
 'Fungal infections': ('ছত্রাক সংক্রমণ', [('sep',3),('tell',3),('bacillinum',0),('sulph',2),('graph',2),('thuj',2),('psor',2),('calc',2)]),
 'Boils': ('ফোড়া', [('hep',3),('sil',3),('bell',2),('merc',2),('sulph',2),('arn',2),('lach',2),('anthr',2)]),
 'Abscess': ('অ্যাবসেস', [('hep',3),('sil',3),('merc',3),('lach',2),('bell',2),('phos',2),('calc-s',2),('pyrog',2)]),
 'Herpes': ('হার্পিস', [('nat-m',3),('rhus-t',3),('mez',3),('graph',2),('sep',2),('ran-b',2),('ars',2),('hep',2)]),
 'Ringworm': ('দাদ', [('sep',3),('tell',3),('bacil',0),('sulph',2),('graph',2),('thuj',2),('psor',2),('dulc',2)]),
 'Scabies': ('খোস-পাঁচড়া', [('sulph',3),('psor',3),('merc',2),('sep',2),('staph',2),('hep',2),('carb-v',2)]),
 'Vitiligo': ('শ্বেতী', [('ars',2),('sulph',2),('sep',2),('nat-m',2),('sil',2),('thuj',1),('syph',1)]),
 'Acne': ('ব্রণ', [('sulph',3),('kali-br',3),('hep',2),('sil',2),('nat-m',2),('bell',2),('ant-c',2),('psor',2),('thuj',2)]),
 'Rosacea': ('রোজেসিয়া', [('lach',2),('sulph',2),('carb-an',2),('rhus-t',2),('bell',2),('nux-v',2),('psor',1)]),
 'Cold sores': ('জ্বরঠোসা', [('nat-m',3),('rhus-t',3),('hep',2),('sep',2),('mez',2),('ars',2),('graph',1)]),
 'Skin cancer': ('ত্বকের ক্যান্সার', [('ars',2),('con',2),('hydr',2),('lyc',2),('sep',1),('carc',2),('kreos',1)]),
 'Burns': ('পোড়া', [('canth',3),('urt-u',3),('caust',3),('ars',2),('apis',2),('hep',1)]),
 'Scars': ('ক্ষতচিহ্ন', [('sil',3),('graph',3),('thiosin',0),('calc-f',2),('fl-ac',2),('nit-ac',1)]),
 'Stretch marks': ('স্ট্রেচ মার্ক', [('calc-f',2),('sil',2),('graph',1),('sep',1),('fl-ac',1)]),
 'Varicose veins': ('ভেরিকোজ শিরা', [('ham',3),('puls',3),('calc-f',3),('carb-v',2),('lach',2),('sep',2),('fl-ac',2),('mill',2),('aesc',2)]),
},

'Sleep - ঘুম': {
 'Sleep restless': ('অস্থির ঘুম', [('ars',3),('rhus-t',3),('acon',2),('bell',2),('cham',2),('sulph',2),('nux-v',2),('kali-c',2),('tarent',2)]),
 'Insomnia': ('অনিদ্রা', [('coff',3),('nux-v',3),('ars',3),('sulph',2),('puls',2),('kali-p',2),('cocc',2),('op',2),('valer',2),('passi',2),('lyc',2)]),
 'Sleepiness': ('ঘুমঘুম ভাব', [('op',3),('nux-m',3),('ant-t',2),('gels',2),('phos',2),('hell',2),('sulph',2),('puls',2)]),
 'Sleep unrefreshing': ('ঘুমে সতেজ না হওয়া', [('bry',3),('lach',3),('nux-v',2),('sulph',2),('op',2),('lyc',2),('carc',2),('ph-ac',2)]),
 'Waking too early': ('খুব ভোরে জেগে ওঠা', [('nux-v',3),('kali-c',3),('sulph',2),('ars',2),('sep',2),('lyc',2),('nat-m',2)]),
 'Waking late': ('দেরিতে ঘুম ভাঙা', [('nux-v',3),('sulph',2),('lach',2),('op',2),('calc',2),('nat-m',1)]),
 'Nightmares': ('দুঃস্বপ্ন', [('acon',3),('stram',3),('kali-br',2),('nat-m',2),('sulph',2),('ars',2),('cina',2),('calc',2),('lyss',2)]),
 'Sleep walking': ('ঘুমের মধ্যে হাঁটা', [('kali-br',3),('nat-m',2),('phos',2),('sil',2),('op',2),('bry',2),('stram',2)]),
 'Sleep talking': ('ঘুমের মধ্যে কথা', [('bell',3),('bry',3),('hyos',2),('lach',2),('nux-v',2),('rhus-t',2),('sulph',2)]),
 'Grinding teeth': ('দাঁত কিড়মিড়', [('cina',3),('tub',3),('bell',2),('podo',2),('hyos',2),('stram',2),('ars',2)]),
 'Snoring': ('নাক ডাকা', [('op',3),('ant-t',2),('bell',2),('nux-v',2),('bar-c',2),('lach',1)]),
 'Sleep position preference': ('ঘুমের ভঙ্গির পছন্দ', [('puls',2),('med',3),('lyc',2),('sulph',2),('phos',2),('rhus-t',2),('ars',2)]),
 'Sleep with mouth open': ('হাঁ করে ঘুমানো', [('op',3),('samb',2),('lyc',2),('rhus-t',2),('cham',2),('bar-c',1)]),
 'Sleep with head uncovered': ('মাথা খোলা রেখে ঘুম', [('sulph',3),('lyc',2),('iod',2),('puls',2),('med',1)]),
 'Sleep covered completely': ('পুরো ঢেকে ঘুম', [('psor',3),('sil',3),('hep',2),('ars',2),('nux-v',2),('kali-c',2),('camph',2)]),
 'Sleep with one leg out': ('এক পা বের করে ঘুম', [('sulph',3),('puls',2),('med',2),('cham',2),('lyc',1)]),
 'Sleep on back': ('চিৎ হয়ে ঘুম', [('am-c',2),('nux-v',2),('rhus-t',2),('sulph',2),('op',1),('phos',1)]),
 'Sleep on side': ('কাত হয়ে ঘুম', [('phos',3),('bry',2),('spig',2),('puls',2),('lyc',2),('sep',1)]),
 'Sleep on stomach': ('উপুড় হয়ে ঘুম', [('med',3),('am-c',2),('acet-ac',0),('calc',2),('cina',2),('stram',1)]),
 'Sleep with arms over head': ('হাত মাথার উপরে রেখে ঘুম', [('puls',3),('nux-v',2),('ars',2),('bell',2),('carb-v',1)]),
},

'Dreams - স্বপ্ন': {
 'Dreams of death': ('মৃত্যুর স্বপ্ন', [('acon',3),('ars',3),('mag-c',2),('calc',2),('nat-m',2),('thuj',2),('aur',2),('lach',2)]),
 'Dreams of falling': ('পড়ে যাওয়ার স্বপ্ন', [('bell',3),('thuj',3),('kali-c',2),('sulph',2),('borx',2),('gels',2),('sanic',2)]),
 'Dreams of water': ('পানির স্বপ্ন', [('mag-c',3),('nat-m',2),('verat',2),('phos',2),('sulph',2),('lac-c',1)]),
 'Dreams of fire': ('আগুনের স্বপ্ন', [('phos',3),('ars',2),('sulph',2),('hep',2),('lach',2),('bell',1),('mag-c',2)]),
 'Dreams of flying': ('উড়ার স্বপ্ন', [('apis',2),('cann-i',2),('lac-c',2),('nat-m',1),('sanic',1)]),
 'Dreams of being chased': ('তাড়া খাওয়ার স্বপ্ন', [('lyc',2),('nat-m',2),('stram',2),('bell',2),('ars',2),('kali-br',2),('lyss',2)]),
 'Dreams of being lost': ('হারিয়ে যাওয়ার স্বপ্ন', [('nat-m',2),('anac',2),('lyc',2),('sil',2),('bar-c',1)]),
 'Dreams of being attacked': ('আক্রান্ত হওয়ার স্বপ্ন', [('ars',2),('stram',2),('lach',2),('nat-m',2),('bell',2),('rhus-t',2)]),
 'Dreams of being naked': ('নগ্ন থাকার স্বপ্ন', [('nat-m',2),('lyc',2),('staph',2),('hyos',1)]),
 'Dreams of being late': ('দেরি হয়ে যাওয়ার স্বপ্ন', [('arg-n',3),('lyc',2),('nat-m',2),('med',2),('carc',2)]),
 'Dreams of exams': ('পরীক্ষার স্বপ্ন', [('arg-n',3),('gels',3),('lyc',2),('anac',2),('sil',2),('carc',2)]),
 'Dreams of work': ('কাজের স্বপ্ন', [('bry',3),('nux-v',2),('rhus-t',2),('lach',2),('sulph',2),('staph',1)]),
 'Dreams of travel': ('ভ্রমণের স্বপ্ন', [('tub',3),('med',2),('calc-p',2),('lyc',1),('nat-m',1)]),
 'Dreams of home': ('বাড়ির স্বপ্ন', [('bry',3),('caps',3),('hom',0),('nat-m',2),('puls',2),('ign',2)]),
 'Dreams of friends': ('বন্ধুদের স্বপ্ন', [('nat-m',2),('puls',2),('phos',2),('ign',1)]),
 'Dreams of strangers': ('অপরিচিতদের স্বপ্ন', [('nat-m',2),('lach',2),('bar-c',2),('stram',1)]),
 'Dreams of dead relatives': ('মৃত আত্মীয়ের স্বপ্ন', [('thuj',3),('mag-c',2),('ars',2),('nat-m',2),('calc',2),('kali-c',1)]),
 'Dreams of animals': ('পশুর স্বপ্ন', [('lyss',3),('lac-c',3),('bell',2),('stram',2),('tub',2),('cupr',1)]),
 'Dreams of food': ('খাবারের স্বপ্ন', [('lyc',2),('calc',2),('sulph',2),('chin',1),('nux-v',1)]),
 'Dreams of money': ('টাকার স্বপ্ন', [('bry',2),('nux-v',2),('lyc',2),('sulph',2),('calc',1)]),
},

'Fever - জ্বর': {
 'Fever high': ('উচ্চ জ্বর', [('bell',3),('acon',3),('ferr-p',3),('bry',2),('gels',2),('pyrog',2),('ars',2),('verat-v',2),('stram',2)]),
 'Fever with chills': ('শীতসহ জ্বর', [('nux-v',3),('eup-per',3),('chin',3),('ars',2),('gels',2),('rhus-t',2),('puls',2),('sabad',2),('chin-s',2)]),
 'Fever with sweat': ('ঘামসহ জ্বর', [('merc',3),('chin',3),('ars',2),('puls',2),('sulph',2),('sil',2),('bry',2),('psor',2)]),
 'Fever intermittent': ('পর্যায়ক্রমিক জ্বর', [('chin',3),('ars',3),('chin-s',3),('nat-m',2),('eup-per',2),('nux-v',2),('cedr',2),('ip',2)]),
 'Fever remittent': ('প্রশমনশীল জ্বর', [('bry',3),('rhus-t',2),('puls',2),('ars',2),('nux-v',2),('bell',2)]),
 'Fever continuous': ('অবিরাম জ্বর', [('bry',3),('bapt',3),('rhus-t',2),('ars',2),('pyrog',2),('phos',2),('gels',2)]),
 'Fever with headache': ('মাথাব্যথাসহ জ্বর', [('bell',3),('bry',3),('gels',3),('eup-per',2),('nat-m',2),('ferr-p',2),('acon',2)]),
 'Fever with nausea': ('বমি ভাবসহ জ্বর', [('ip',3),('nux-v',2),('eup-per',2),('bry',2),('ars',2),('puls',2)]),
 'Fever with diarrhea': ('ডায়রিয়াসহ জ্বর', [('ars',3),('bapt',3),('podo',2),('gels',2),('merc',2),('phos',2),('pyrog',2)]),
 'Fever with vomiting': ('বমিসহ জ্বর', [('ars',3),('ip',2),('eup-per',2),('verat',2),('bry',2),('phos',2)]),
 'Fever with restlessness': ('অস্থিরতাসহ জ্বর', [('acon',3),('ars',3),('rhus-t',3),('bell',2),('bry',1),('pyrog',2)]),
 'Fever with weakness': ('দুর্বলতাসহ জ্বর', [('gels',3),('bapt',3),('ars',2),('chin',2),('phos',2),('pyrog',2),('carb-v',2)]),
 'Fever with thirst': ('তৃষ্ণাসহ জ্বর', [('bry',3),('ars',3),('acon',2),('eup-per',2),('nat-m',2),('phos',2),('chin',2)]),
 'Fever with burning': ('জ্বালাসহ জ্বর', [('ars',3),('sulph',2),('bell',2),('phos',2),('acon',2),('canth',1)]),
 'Fever with coldness': ('শীতলতাসহ জ্বর', [('camph',3),('verat',3),('carb-v',2),('ars',2),('sec',2),('chin',2)]),
 'Fever during menses': ('ঋতুস্রাবকালীন জ্বর', [('bell',2),('cham',2),('puls',2),('sep',2),('nat-m',2),('cimic',2)]),
 'Fever during pregnancy': ('গর্ভাবস্থায় জ্বর', [('acon',2),('bell',2),('puls',2),('ferr-p',2),('bry',1),('sep',1)]),
 'Fever after vaccination': ('টিকার পর জ্বর', [('thuj',3),('sil',3),('sulph',2),('ars',2),('vac',2),('bell',1)]),
 'Fever with rash': ('ফুসকুড়িসহ জ্বর', [('bell',3),('apis',2),('rhus-t',2),('sulph',2),('ail',2),('puls',2)]),
 'Fever with joint pain': ('সন্ধিব্যথাসহ জ্বর', [('bry',3),('rhus-t',3),('eup-per',3),('acon',2),('ferr-p',2),('colch',2),('kalm',2)]),
},

}
